### ISSUE TITLE
Allow log message as json object when serialize is true

### ISSUE THREAD

**Issue by af6140** [Delgan/loguru#10]
When message is a json object, serializer should parse the json and output it as an object other than a json string.

**Comment by Delgan** [comment]
Unfortunately, this is not possible, as that would break the contract that as long as a sink accept a string message it will work.

If `serialize` would pass a object, you could not do `logger.start("file.log"), serialize=True)`.

You should proceed of the deserialization in your custom sink.

```python
def sink(serialized_message):
    obj = json.loads(serialized_message)
```

Also, note that you can access the log values without even needing serialization, it is available through the [`.record`](https://loguru.readthedocs.io/en/stable/api/logger.html#record) attribute of each logged message.

```python
def sink(message):
    record = message.record  # This is just a dict
    print(record["time"])
```

**Comment by Delgan** [comment]
What's your use case exactly please?
I have trouble understanding why the proposed solutions would not work.
As `record["message"]` is just the string passed to `logger.debug("Message")`, I don't see how it could be parsed as a JSON object.

**Comment by af6140** [comment]
Oh, forgot to mention, I was talking about generating { in format string.

**Comment by af6140** [comment]
like i want to log like logger.debug("\"message\": { \"source\":  \"blabla\"}"). For example, the message can be an AWS sns message field, a json doc string generated by cloudwatch.

**Comment by Delgan** [comment]
I see, thanks. I think you should perform the deserialization in your custom sink function.

```python
def sink(message):
    record = message.record
    if "deserialize" in record["extra"]:
        obj = json.loads(record["message"])
        # Do whatever you want with the deserialized object
```

And call log function using [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) like this:

```python
logger.bind(deserialize=True).debug(aws_message)
```

That way, you can still log non-serialized message like `logger.debug("No JSON here")`, and others sinks using string can still continue to work.
