### ISSUE TITLE
How to add console output to log file

### ISSUE THREAD

**Issue by mujinbao** [Delgan/loguru#100]
![2019-05-28 10-08-03屏幕截图](https://user-images.githubusercontent.com/42856783/58445773-933a5e00-8130-11e9-8d61-861f5fdb32b6.png)
If your computer doesn't have a camera, errors will occur in this code --> 'VIDEOIO ERROR: V4L: can't open camera by index 0'  
It's an exception, but it's not caught by loguru, there should be many more examples like this. I want to record the output of the console and "logger. debug (" XXX ") in the same file. How can I operate it?

![2019-05-28 10-13-53屏幕截图](https://user-images.githubusercontent.com/42856783/58445946-51f67e00-8131-11e9-8090-60639063bc51.png)

**Comment by mujinbao** [comment]
Hi @Delgan , hope you can help me with this. Thank you.

**Comment by ms7m** [comment]
The documentation shows you how to send outputs to stderr. 
In your case simply do 
```logger.add(sys.stderr, format="{time} {level} {message}", filter="my_module", level="DEBUG")```
```logger.add("file.log", level="DEBUG")```

However this not your issue.
You need to either add```camera = cv2.VideoCapture(0)``` to a function and do a ```logger.catch`` decorator or do a try and except Exception as error and log the error.

**Comment by Delgan** [comment]
Hi @mujinbao.

Loguru does not automatically log exceptions. As @ms7m explained it (thanks!), you need to explicitly catch the error, the same way this is usually done in Python:

```python
try:
    camera = cv2.VideoCapture(0)
except Exception:
    # Using 'logger.exception()' automatically adds the traceback to your log message
    logger.exception("An error occurred while opening camera")
```

When you log information using the `logger` object, the messages are sent to the configured handlers. If you called `logger.add("info.log")`, you should see the error reported in your file.

The `VIDEOIO ERROR` you saw on the console was actually not logged, it's just the error message printed by Python on `stderr` when an exception interrupts your program.

**Comment by Delgan** [comment]
@mujinbao Did you manage to solve your issue?

**Comment by Delgan** [comment]
Closing this, if you encounter other problems, don't hesitate to ask me.
