### ISSUE TITLE
How to filter traceback with my modules?

### ISSUE THREAD

**Issue by CrazyMelody** [Delgan/loguru#1002]
When I use logger.exception(e), it prints the entire stack trace, including many framework stack frames. I only want to keep the stack frames from my own code. How can I do that?

**Comment by Delgan** [comment]
You can add your handler with `backtrace=False` to reduce the verbosity. If you want even less logs, you will need to implement an alternative exception formatter: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).

**Comment by CrazyMelody** [comment]
Thanks , it's work !
