### ISSUE TITLE
Logging with level number doesn't produce expected result

### ISSUE THREAD

**Issue by joejoinerr** [Delgan/loguru#1011]
When using the `Logger.log()` method with a level number, the log message is generated with `Level [number]` rather than the name of the severity level. This is different to the behaviour of the builtin logging library and not what I would expect from looking at the implementation.

![image](https://github.com/Delgan/loguru/assets/2454320/7e66be96-7d60-479c-af9f-ec16cdab4bc1)

```python
from loguru import logger

logger.log(10, 'Test message')
logger.log('DEBUG', 'Test message')
print(logger.level('DEBUG'))
```

I would expect the output of both log messages to show "DEBUG" as the log severity.

Python 3.10.2
Loguru 0.7.0

**Comment by Delgan** [comment]
Hi.

This is actually by design. When using an integer, the level will be treated as anonymous. This is because there is no way to uniquely identify a level by a integer, since two levels with different names can share the same severity.

See also https://github.com/Delgan/loguru/issues/599.

**Comment by joejoinerr** [comment]
Ah that makes a lot of sense. My issue was using this with the tenacity library, specifically the `tenacity.before_sleep_log` function. But I realised I can just provide the level name instead and it works just fine.

Apologies for the duplicate question. Thanks for your help, and for all your work on Loguru :)
