### ISSUE TITLE
loguru not working with a custom class inheriting logging.Handler

### ISSUE THREAD

**Issue by GuitaristForEver** [Delgan/loguru#1018]
Hi, first of all, I love using loguru.

recently I needed to add another logger to my code called Coralogix , here's the [documnetation](https://coralogix.com/docs/coralogix-python-integration/) and here's the [source code ](https://github.com/coralogix/python-coralogix-sdk/tree/master) when I try to use ```logger.add(coralogix_handler, level=logging.INFO, colorize=False)```

I hit an exception originating from the coralogix handler `Severity name is invalid!`

when I debug this, I see that it happens on this line (loguru) `elif hasattr(sink, "write") and callable(sink.write):` leading to [this line](https://github.com/coralogix/python-coralogix-sdk/blob/8ea995d02bd899a6f7b38e78aa19b32d5b35195d/coralogix/handlers/coralogix.py#L147C9-L147C9) (coralogix_handler) 
```
    def __getattr__(self, severity):
        """
        Send log with some severity by it name
        :param severity: Log record severity(level)
        :type severity: str
        :return: Log sending with severity procedure wrapper
        """
        severity = severity.upper()
        if hasattr(Coralogix.Severity, severity):
            def wrapper(message, category=None, classname='', methodname='', thread_id=''):
```

can you please advice what should I do ?

**Comment by Delgan** [comment]
Hi @GuitaristForEver. Glad you like Loguru. :+1: 

Thank you for your preliminary investigation of the bug.

I would say the `CoralogixLogger` handler is probably faulty for raising a `NotImplementedError` instead of `AttributeError` in `__getattr__()`, as it breaks usage with `hasattr()`.

As a workaround for now, I think you can inherit `CoralogixLogger` and fix the `__getattr__()` method:

```python
class FixedCoralogixLogger(CoralogixLogger):

    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except RuntimeError:
            raise AttributeError(f"Severity {name} is invalid!")

logger.add(FixedCoralogixLogger())
```

**Comment by GuitaristForEver** [comment]
Thank you for the quick response! @Delgan 

I would give it a go, and open an issue for Coralogix team for investigation 👍

**Comment by Delgan** [comment]
> I would give it a go, and open an issue for Coralogix team for investigation 👍

I opened https://github.com/coralogix/python-coralogix-sdk/pull/18 ;)

**Comment by GuitaristForEver** [comment]
Thanks! In the meanwhile I can confirm your  suggested workaround has worked.

Thank you, I appreciate your efforts

**Comment by Delgan** [comment]
Closing this ticket since it was fixed upstream. :+1:
