### ISSUE TITLE
How to inspect sinks?

### ISSUE THREAD

**Issue by antoine-gallix** [Delgan/loguru#1024]
# in which situation do I need this 

The loguru configuration of our project start to be complex, and programmatically configured. I arrive to the point where I need to inspect the configuration of all the sinks at a given point in the code, to see if the configuration values do produce the logging configuration I wish.

# example needs

- I want to get my hands on the list of currently active sink objects.
- I want to see the detailed configuration of a sink, including it's format or format function, it's destination or sink function, it's patches.
- Eventually see debug logging of the internals of loguru log flow, is there a logger I can unmute?

**Comment by Delgan** [comment]
It is not possible to inspect the configured handlers. To keep the Loguru API minimal, I do not plan to add such feature.



> * I want to get my hands on the list of currently active sink objects.
> 
> * I want to see the detailed configuration of a sink, including it's format or format function, it's destination or sink function, it's patches.

You could define the logging configuration as a `dict` and use `logger.configure()`. This way, you'll still have access to the list of installed handlers, in the form of the configuration `dict`.

If you're adding and removing handlers repeatedly in your application, then I would advise to create a small wrapper over these calls to update the handlers configuration state in a separate variable.

> * Eventually see debug logging of the internals of loguru log flow, is there a logger I can unmute?

Not really, Loguru isn't using `logging` internally. Is there a reason why you need to see this?

**Comment by antoine-gallix** [comment]
Ok so if I understand correctly, you suggest me to apply my logging configuration logic to a configuration dictionary instead of on the logger directly, and sync that configuration with `logger.configure()` after each operation, so I can keep a hand on that object to inspect it. I thought such an object would already exist in the `loguru` internals and that it would be easier to just access it instead of maintaining a proxy. But if you tell me this object is not easily build or accessed, I understand.

Regarding debugging, I was referring to trying to understand what happen in the internals of `loguru` between filters and sink functions, and formatting functions, in case the result logging behavior is not the one I intend and I want to understand what happens in the internal flow. Maybe `loguru` itself has an internal logger that I can activate?

**Comment by Delgan** [comment]
> Ok so if I understand correctly, you suggest me to apply my logging configuration logic to a configuration dictionary instead of on the logger directly, and sync that configuration with `logger.configure()` after each operation, so I can keep a hand on that object to inspect it. I thought such an object would already exist in the `loguru` internals and that it would be easier to just access it instead of maintaining a proxy. But if you tell me this object is not easily build or accessed, I understand.

Yes, this is what I'm suggesting. I agree this is not very convenient, but this use case isn't very common and consequently I would rather not expose an API for inspecting and manipulating the handlers.

> Regarding debugging, I was referring to trying to understand what happen in the internals of loguru between filters and sink functions, and formatting functions, in case the result logging behavior is not the one I intend and I want to understand what happens in the internal flow. Maybe loguru itself has an internal logger that I can activate?

No, Loguru does not have such thing. I don't think using logging internally is worth it, since it adds overhead while the internal flow is _relatively_ straightforward.

You'll need to draw out the debugger or inspect the code. However, if the description of Loguru's workflow is unclear in the documentation, let me know, and I can try to clarify it.

**Comment by antoine-gallix** [comment]
Ok thanks for the clarifications and the suggestions. Very much appreciated.
