### ISSUE TITLE
how to update _options depth attribute

### ISSUE THREAD

**Issue by reesezxf** [Delgan/loguru#1029]
Here is my question: 
I use a custom Class like MyLogger 
```
class MyLogger:
    @classmethod
    def log_msg(cls, msg:str):
        logger.info(msg)
        # this signal is a PyQt Signal, I want show msg to My PyQt app and record msg to log file  
        cls.__sigal.emit(msg)
````
I can use it in my project other module like 
`
MyLogger.log_msg("hello")
`
now in my log file like 
`
2023-11-28 10:32:41:332 | INFO   | Log.MyLog.log_msg:50  - hello
`
see the "Log.MyLog.log_msg:50 " is wrong

SO  I want to log the correct location, I read the source code in the Logger._log method I see `frame = get_frame(depth+2) `,
that's why I want to update  the **`depth`**

**Comment by Delgan** [comment]
I think you can use the `depth` argument from the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method:

```python
class MyLogger:
    @classmethod
    def log_msg(cls, msg:str):
        logger.opt(depth=1).info(msg)
        # this signal is a PyQt Signal, I want show msg to My PyQt app and record msg to log file  
        cls.__sigal.emit(msg)
```

**Comment by reesezxf** [comment]
> I think you can use the `depth` argument from the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method:
> 
> ```python
> class MyLogger:
>     @classmethod
>     def log_msg(cls, msg:str):
>         logger.opt(depth=1).info(msg)
>         # this signal is a PyQt Signal, I want show msg to My PyQt app and record msg to log file  
>         cls.__sigal.emit(msg)
> ```

Thanks man, it works !
