### ISSUE TITLE
How can I get the msg from logger.exception() 

### ISSUE THREAD

**Issue by reesezxf** [Delgan/loguru#1031]
In my project When I record exception msg to log file, I also need to send the exception msg to my email or telegram bot.

Here is the problem, I just use the code `logger.exception()`， then loguru will record the full exception stack to my log file **automatic**，like 
```
2023-11-29 11:22:11.796 | ERROR    | __main__:<module>:26 - division by zero
Traceback (most recent call last):

> File "/home/eric/workspace/PycharmProjects/py_redis_sample/test/test_loguru.py", line 24, in <module>
    main()
    └ <function main at 0x723a1f266050>

  File "/home/eric/workspace/PycharmProjects/py_redis_sample/test/test_loguru.py", line 13, in main
    a = division(10, 0)
        └ <function division at 0x723a1e88caf0>

  File "/home/eric/workspace/PycharmProjects/py_redis_sample/test/test_loguru.py", line 19, in division
    return x / y
           │   └ 0
           └ 10

ZeroDivisionError: division by zero

```
so I can't get the exception msg to send. My back up is sending the msg from `traceback.format_exc()` , but it isn't as good as loguru.

Is there a solution?

**Comment by mrkmcnamee** [comment]
Generally speaking, you need to add a second sink to the logger to send the message to another destination, e.g. a mailbox. You can use the 'filter' argument to select only exception messages.
https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add

**Comment by reesezxf** [comment]
@mrkmcnamee 
> Hi @mayanyax.
> 
> As suggested by @mrkmcnamee, I think you need to implement a custom sink to access the formatted exception before sending by e-mail.
> 
> Here is an example:
> 
> ```python
> from loguru import logger
> 
> 
> def send_error_by_mail(message):
>     # Fictive example. The `message` variable contain the formatted log message.
>     # In your case, since we'll add the sink with `format=lambda _: "{exception}"`,
>     # it will be composed of the formatted exception alone.
>     email.send("dest@mail.com", title="Error", content=message)
> 
> def error_only_logs(record):
>     if record["exception"] is None:
>         return False
>     return True
> 
> logger.add(send_error_by_mail, filter=error_only_logs, format=lambda _: "{exception}", diagnose=True, level="ERROR")
> ```
Thank you two for reply,  It's so kind of you , I will try this solution
