### ISSUE TITLE
ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by tarzanfan** [Delgan/loguru#1039]
```
-- Logging error in Loguru Handler #34 ---
Record was: {'elapsed': datetime.timedelta(seconds=149, microseconds=44090), 'exception': None, 'extra': {}, 'file': (name='public_global.py', path='/home/kylin/gpu_mass_production_tool/public/public_global.py'), 'function': 'exec_cmd', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 52, 'message': '命令执行结果：', 'module': 'public_global', 'name': 'public.public_global', 'process': (id=157495, name='MainProcess'), 'thread': (id=547807866896, name='MainThread'), 'time': datetime(2023, 12, 4, 15, 26, 57, 186796, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/loguru/_handler.py", line 197, in emit
    self._sink.write(str_record)
  File "/usr/local/lib/python3.8/dist-packages/loguru/_simple_sinks.py", line 16, in write
    self._stream.write(message)
ValueError: I/O operation on closed file.
--- End of logging error ---
```
loguru has been running stably for a long time, but recently when running the code, it prompted this error. This problem has been bothering me for a week. I don't use multi-threading or multi-processing in my code.
My loguru configuration: `logger.py`:
```
import sys
import os
import logging
from loguru import logger
project_path = os.path.dirname(__file__)
log_path = os.path.join(project_path, 'log/run_log.log')


class PropagateHandler(logging.Handler):
    def emit(self, record):
        logging.getLogger(record.name).handle(record)


def get_logger():
    logger.remove()
    logger.add(sys.stdout, level='INFO', format='{message}')
    logger.add(log_path, rotation='00:00')
    logger.add(PropagateHandler())
    return logger


if __name__ == '__main__':
    logger = get_logger()
    logger.info('runlog')

```
`other.py`:
```
from logger import get_logger
logger = get_logger()
logger.info('test')
```
It is ok when running a py file alone, but it will happen when the entire project is run.

**Comment by tarzanfan** [comment]
![123](https://github.com/Delgan/loguru/assets/43024508/3e09fc7a-a6ac-4bb3-b952-0f5bceae5da6)

loguru version 0.7.2  and 0.7.0

**Comment by Delgan** [comment]
Hi @tarzanfan.

I'm not sure of what is causing the error in your case, but I note your `get_logger()` function is probably an anti-pattern. One should usually configure the logger once, then import it from other modules by simply using `from loguru import logger`.
Here, it seems you're repeatedly removing and re-adding different handlers since you're calling `get_logger()` multiple times. Keep in mind that the `logger` imported from `loguru` is a global object, therefore it can be configured from one single file, and other files will automatically inherit the configuration.

For example, I would rewrite your code as follows:

```python
# main.py
import sys
import os
import logging
from loguru import logger
project_path = os.path.dirname(__file__)
log_path = os.path.join(project_path, 'log/run_log.log')


class PropagateHandler(logging.Handler):
    def emit(self, record):
        logging.getLogger(record.name).handle(record)

if __name__ == '__main__':
    logger.remove()
    logger.add(sys.stdout, level='INFO', format='{message}')
    logger.add(log_path, rotation='00:00')
    logger.add(PropagateHandler())

    logger.info('runlog')
```
```python
# other.py
from loguru import logger

logger.info('test')
```

Please, try the approach above and let me know if it solves your problem.

**Comment by tarzanfan** [comment]
> Hi @tarzanfan.
> 
> I'm not sure of what is causing the error in your case, but I note your `get_logger()` function is probably an anti-pattern. One should usually configure the logger once, then import it from other modules by simply using `from loguru import logger`. Here, it seems you're repeatedly removing and re-adding different handlers since you're calling `get_logger()` multiple times. Keep in mind that the `logger` imported from `loguru` is a global object, therefore it can be configured from one single file, and other files will automatically inherit the configuration.
> 
> For example, I would rewrite your code as follows:
> 
> ```python
> # main.py
> import sys
> import os
> import logging
> from loguru import logger
> project_path = os.path.dirname(__file__)
> log_path = os.path.join(project_path, 'log/run_log.log')
> 
> 
> class PropagateHandler(logging.Handler):
>     def emit(self, record):
>         logging.getLogger(record.name).handle(record)
> 
> if __name__ == '__main__':
>     logger.remove()
>     logger.add(sys.stdout, level='INFO', format='{message}')
>     logger.add(log_path, rotation='00:00')
>     logger.add(PropagateHandler())
> 
>     logger.info('runlog')
> ```
> 
> ```python
> # other.py
> from loguru import logger
> 
> logger.info('test')
> ```
> 
> Please, try the approach above and let me know if it solves your problem.

Thank you very much for your reply, loguru can work.
