### ISSUE TITLE
how to use retention?

### ISSUE THREAD

**Issue by panla** [Delgan/loguru#1051]
# QQQ

[TOC]

## question

Unable to automatically delete log files

How to use retention

## code

```python
import sys
from pathlib import Path

from loguru import logger

class LogConfig:
    LEVEL = "INFO"
    PATH = "./logs/x.log"
    ROTATION = "16KB"
    RETENTION = "10 minutes"
    STDOUT = True
    COMPRESSION = None

level = LogConfig.LEVEL.upper()
Path(LogConfig.PATH).parent.mkdir(exist_ok=True)

logger.remove()
logger.add(
    LogConfig.PATH, level=level, rotation=LogConfig.ROTATION, retention=LogConfig.RETENTION, backtrace=True,
    diagnose=True, enqueue=True, compression=LogConfig.COMPRESSION
)
if LogConfig.STDOUT:
    logger.add(sys.stdout, level=level, backtrace=True, diagnose=True, enqueue=True)
```

**Comment by Delgan** [comment]
Because your `rotation` configuration is not `None`, the `retention` process will only be triggered when the file is rotated. See [documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#file):

> The `retention` occurs at rotation or at sink stop if rotation is `None`. Files resulting from previous sessions or rotations are automatically collected from disk. A file is selected if it matches the pattern `"basename(.*).ext(.*)"` (possible time fields are beforehand replaced with `.*`) based on the configured sink. 

Therefore, when the file currently written will exceed 16 KB in your example, Loguru will list all other logs files and delete them if there were modified more than 10 minutes ago.

**Comment by panla** [comment]
@Delgan 
no, it`s not been deleted.
Even though I already have a lot of log files

**Comment by Delgan** [comment]
@panla Which OS are you using? What is the output of `ls --full-time`? Would you be able to produce a fully producible example? I tried to replicate your problem but it worked as expected in my case.

**Comment by panla** [comment]
@Delgan

it`s my error.
