### ISSUE TITLE
How to get file name?

### ISSUE THREAD

**Issue by spookymonster** [Delgan/loguru#106]
I'm using the following sink definition. How do I query the logger to get the file name?
{
                "sink":
                logdir + R"/" + name + "_{time:[D]YYYYMMDD_THHmmss}.log",
                "format":
                "{time:YYYY-MM-DD HH:mm:ss} |{level:1.1}| {message}",
                "retention":
                "180 days",
            },

**Comment by Delgan** [comment]
Hi @spookymonster.

Basically... You can't. I suggest you to define the file name by yourself, outside of the config, and don't let Loguru automatically generate it. What do you need the filename for?

**Comment by Delgan** [comment]
@spookymonster Is this workaround ok for you?

**Comment by spookymonster** [comment]
Not really, but I can live with it :).

**Comment by Delgan** [comment]
Could you give me an example of your use case? Maybe this can be achieved with a custom `rotation` or `compression` function.

**Comment by spookymonster** [comment]
I mainly use Python as a wrapper to vendor utilities. If I have to send the
logs to the vendor or a customer, having the first record be the log file
path makes it easier for me to find again if I have to dig through it on my
end. Sure, I can piece together the name and make an educated guess about
the date and time qualifiers based on the log timestamps, but that's extra
work :).

**Comment by Delgan** [comment]
Thanks for the example. Yet, I don't understand why you would have to guess the filename. Can you do something like the following?

```python
from datetime import datetime

filepath = logdir + R"/" + name + "_{:D%Y%m%d_T%H%M%S}.log".format(datetime.now())

config = {
    "sink": filepath,
    "format": "{time:YYYY-MM-DD HH:mm:ss} |{level:1.1}| {message}",
    "retention": "180 days",
}
```

I agree, this is a little cumbersome, but as `loguru` intentionally doesn't provide access to configured handlers, there are not really other ways.

**Comment by spookymonster** [comment]
That's fine.

**Comment by Delgan** [comment]
Thanks for your comprehension. I'm closing this issue then, as the `logger` doesn't allow accessing handlers and their attributes.

If you just want to make the filename part of the file content, a workaround is possible using the `compression` attribute. The provided function will be executed at the end of your program (or before rotating the file):

```python
def append_filepath(filepath):
    with open(filepath, "a") as file:
        file.write("### Log filepath: %r ###\n" % filepath)

logger.add("file_{time:[D]YYYYMMDD_THHmmss}.log", compression=append_filepath)
```

**Comment by AGeekInside** [comment]
I am commenting here because there is another use case that needs the display of file names. VSCode (in its terminal) allows clicking to source code locations, if the filename is fully displayed. I'd like to be able to specifically format a log message to have the file location so it would be clickable from the terminal output of VSCode. 

I am not sure the best approach to do this and any suggestions would be appreciated.

**Comment by Delgan** [comment]
@AGeekInside Do you want source file path to be fully displayed in the log messages? Maybe by using a custom `format`?

```python
import os
import sys


def custom_format(record):
    path = os.path.abspath(record["file"].path)
    record["extra"]["abspath"] = path
    return "{name} - {level} - {extra[abspath]} - {message}\n{exception}"

logger.add(sys.stderr, format=custom_format)
```

**Comment by AGeekInside** [comment]
Thanks so much! This is exactly what we needed.

**Comment by metaperl** [comment]
> What do you need the filename for?

We are sending an email with the log of execution attached. We wanted to leverage the `{time}` automatic timestamping that loguru provides. So we wanted something like:

```
filename = 'xyz{time}'
handler_id = logger.add(filename)

send_as_attachment(logger.handler(handler_id).filename)

```
but since loguru doesnt provide easy access, this is not possible/easy.

**Comment by Delgan** [comment]
@metaperl Maybe you can use a custom `rotation` or `compression` function which provides access to the file path. Otherwise, you can create the filename manually: `filename = 'xyz{time}'.format(time=datetime.now())`.

**Comment by metaperl** [comment]
It would really be simpler if you just exposed the internals. It's up to us as developers if we want to take the chance.

But since they are not exposed, here is how to get the filename from the handlers you have added:

```python

for _, handler in logger._core.handlers.items():
    if isinstance(handler._sink, FileSink):
        return handler._sink._file.name
```
