### ISSUE TITLE
Question duplicate the warning

### ISSUE THREAD

**Issue by xiki-tempula** [Delgan/loguru#1061]
Hi, I have some code that does warnings.warn.
I wonder if there is some setting in loguru that would detect warnings.warn raised in other part of the code and record it in the log file? Thanks.
Or I have to do both? Like
```
from loguru import logger
import warning
warning.warn('XXX')
logger.warn('XXX')
```

**Comment by Delgan** [comment]
Hi.

Does this recipe in the documentation answer your question: [Capturing standard `stdout`, `stderr` and `warnings`](https://loguru.readthedocs.io/en/stable/resources/recipes.html#capturing-standard-stdout-stderr-and-warnings)?

Basically, you need to replace [`warnings.showwarning`](https://docs.python.org/3/library/warnings.html#warnings.showwarning):

```python
import warnings
from loguru import logger

showwarning_ = warnings.showwarning

def showwarning(message, *args, **kwargs):
    logger.warning(message)
    showwarning_(message, *args, **kwargs)

warnings.showwarning = showwarning
```

**Comment by xiki-tempula** [comment]
I see. Sorry I didn't realise that that part addressed my question.
