### ISSUE TITLE
Difficulty in Configuring Loguru to Honor --log-cli-level=INFO in Pytest

### ISSUE THREAD

**Issue by Janus-Shiau** [Delgan/loguru#1062]
### Environment
- Python Version: 3.9
- Loguru Version: 0.7.2
- Pytest Version: 7.4.4

### Description
I am encountering an issue with configuring Loguru to work in tandem with Pytest's `--log-cli-level` flag. Recently I start to switch logging from python native logging to Loguru. It's indeed simple and coll. However, I found when it goes to pytest, it became somehow confusing. My goal is to run Pytest with the flag `--log-cli-level=INFO` or `--log-level=INFO` and ensure that `DEBUG` level messages are not shown in the test output. However, despite various attempts and configurations, `DEBUG` messages are still being displayed.

### Steps to Reproduce
1. Write a test function that includes `loguru` logger messages at various levels, including `DEBUG`.
2. Run Pytest with the command: `python -m pytest -s tests --log-cli-level=INFO`.
3. Observe that `DEBUG` messages are still appearing in the output.

### What I've Tried
- I've read through related GitHub issues (GH#59 and GH#474) and the official `loguru` documentation (https://loguru.readthedocs.io/en/stable/resources/migration.html#replacing-assertlogs-method-from-unittest-library).
- I've tried using a `caplog` fixture to integrate `loguru` logger with `pytest`'s logging mechanism as shown below:

    ```python
    @pytest.fixture
    def caplog(caplog: LogCaptureFixture):
        handler_id = logger.add(
            caplog.handler,
            format="{message}",
            level=0,
            filter=lambda record: record["level"].no >= caplog.handler.level,
            enqueue=False,
        )
        yield caplog
        logger.remove(handler_id)
    ```

- I've also tried adding a `reportlog` fixture to handle log messages:

    ```python
    @pytest.fixture
    def reportlog(pytestconfig):
        logging_plugin = pytestconfig.pluginmanager.getplugin("logging-plugin")
        handler_id = logger.add(logging_plugin.report_handler, format="{message}")
        yield
        logger.remove(handler_id)
    ```

- I've also try `pytest-loguru`, but also not getting what I want.

### Expected Behavior
I would expect that running Pytest with `--log-cli-level=INFO` would result in `DEBUG` level messages being filtered out from the test output.

### Actual Behavior
`DEBUG` level messages are still being displayed in the test output.

### Request
Could you please provide guidance or a solution on how to configure `loguru` to respect the `--log-cli-level=INFO` flag in Pytest? Any assistance or insights into this issue would be greatly appreciated.

Thank you for your time and help.

**Comment by Delgan** [comment]
Hi @Janus-Shiau.

The ` --log-cli-level` from `pytest` controls the logs emitted from the standard `logging` library.

I think you need to configure a [`PropagateHandler`](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging) for your logs to be captured by `pytest`, see notably:
* https://github.com/Delgan/loguru/issues/751#issuecomment-1320935865
* https://github.com/Delgan/loguru/issues/698#issuecomment-1228391037

For example, I think implementing the following fixture would solve your problem:

```python
@pytest.fixture(autouse=True)
def propagate_logs():

    class PropagateHandler(logging.Handler):
        def emit(self, record):
            if logging.getLogger(record.name).isEnabledFor(record.levelno):
                logging.getLogger(record.name).handle(record)

    logger.remove()
    logger.add(PropagateHandler(), format="{message}")
    yield
```

If you confirm that this is the case, I'll update the documentation.

**Comment by Janus-Shiau** [comment]
Hi,

Sorry for the late reply. Thanks for the solution with `PropagateHandler`; it's exactly what I needed to integrate loguru with pytest's logging levels. Appreciate your help and looking forward to seeing this update in the documentation.
