### ISSUE TITLE
Custom log handlers do not receive the original log message

### ISSUE THREAD

**Issue by sergeykad** [Delgan/loguru#1080]
Reading `Record.msg` in a custom `logging.Handler` implementation returns a formatted message instead of the original text. Since I need to use a different format for different handlers this is quite problematic. This is also different from the Python logging.

**Expected value:**
`"That's it, beautiful and simple logging!"`

**Actual value:**
`"2024-02-13 13:30:54.357 | DEBUG    | __main__:run_it:31 - That's it, beautiful and simple logging!"`

**Comment by Delgan** [comment]
> I managed to resolve it by adding format="{message}" like this: logger.add(custom_handler, format="{message}")

Yes, this is the correct solution.
