### ISSUE TITLE
Ability to pass Exception to logger.exception

### ISSUE THREAD

**Issue by mvanderlee** [Delgan/loguru#1087]
In asyncio callbacks, i.e.: a Starlette error handler, we have the exception but it's not part of the `sys.exc_info()`. Therefore I can't log the stacktrace via `logger.exception()`.

It'd be great if I could pass the exception in, i.e.: 
```python
def exception(__self, __message, *args, exception: BaseException | tuple | bool = True, **kwargs):  # noqa: N805
        r"""Convenience method for logging an ``'ERROR'`` with exception information."""
        options = (exception,) + __self._options[1:]
        __self._log("ERROR", False, options, __message, args, kwargs)
```

Right now the workaround is to use _private_ options and functions
```python
options = (error,) + logger._options[1:]
logger._log("ERROR", False, options, f'Server Error: {error}', [], {})
```

**Comment by Delgan** [comment]
You can do so using the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method:

```python
logger.opt(exception=error).error(f'Server Error: {error}')
```

**Comment by mvanderlee** [comment]
Ah, nice! thank you,I will close the ticket
