### ISSUE TITLE
Can I customize log format on top of loguru format

### ISSUE THREAD

**Issue by adithyasam** [Delgan/loguru#109]
I am trying to figure out if I could customize log message in addition to the log format provided by loguru.

For example: 
Log message from Loguru : 
```2019-07-01 16:21:16.733 | INFO     | __main__:run_server:50 - Tornado server starting on port 5000```

Can I change this format to include correlation ID as well like :point_down:
```[2019-06-28 09:51:59] [application_name] [correlationID] [INFO] - __main__:run_server:50 Tornado server starting on port 5000```

Thanks

**Comment by Delgan** [comment]
Hi @adithyasam.

You can use the `format` attribute of the [`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) function, can't you?

```
fmt = "[{time}] [application_name] [correlationId] [{level}] - {name}:{function}:{line} - {message}"
logger.add(sys.stderr, format=fmt)
```

Supposing `correlationID` is programmatically generated and varies across messages, you can use [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) to set it dynamically in [the record dict](https://loguru.readthedocs.io/en/stable/api/logger.html#record):

```
# Note that the format make use of the "extra" dict
fmt = "[{time}] [application_name] [{extra[correlationId]}] [{level}] - {name}:{function}:{line} - {message}"
logger.add(sys.stderr, format=fmt)
logger.bind(correlationId=123).info("First message")
logger.bind(correlationId=456).info("Another message")
```

**Comment by adithyasam** [comment]
But that's adding an extra line of the same log like this 
```2019-07-02 09:58:38.772 | INFO     | __main__:run_api_server:53 - Tornado server starting on port 5000```
```[2019-07-02T09:58:38.772510-0400] [application_name] [correlationId] [INFO] - __main__:run_api_server:53 - Tornado server starting on port 5000```

I would like to add extra parameters to the original log coming from loguru.

**Comment by Delgan** [comment]
I forgot to precise: you need first to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) the default handler, otherwise, logs will be printed twice as you saw!

The thing is that, for convenience, loguru add a pre-configured handler which sends messages to `stderr`. This is why you can do `from loguru import logger` then `logger.info("A message")` and it works out of the box.

If you want to customize the log format, you have to remove the default handler first.

```python
logger.remove()  # All configured handlers are removed
logger.add(sys.stderr, format=your_format)
logger.info("Logged message")
```

Note that the default format used by Loguru is as follow:

```
"<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
```

**Comment by AnesBenmerzoug** [comment]
Another way to do the same, which I use myself, is to directly [configure](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) the logger with the handler(s) you desire which also takes care of removing the default handler.

```python
import sys
from loguru import logger

fmt = "[{time}] [application_name] [correlationId] [{level}] - {name}:{function}:{line} - {message}"
config = {
    "handlers": [
        {"sink": sys.stderr, "format": fmt},
    ],
}
logger.configure(**config)

logger.info("Logged message")
```
Which would give you the desired output:
```bash
[2019-07-06T11:35:07.697112+0200] [application_name] [correlationId] [INFO] - __main__:<module>:14 - Logged message
```

**Comment by Delgan** [comment]
@adithyasam Did I answer your question and did you manage to configure the `logger` as expected?

**Comment by Delgan** [comment]
Feel free to ping me if you have any other question.

**Comment by gaillota** [comment]
> Another way to do the same, which I use myself, is to directly [configure](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) the logger with the handler(s) you desire which also takes care of removing the default handler.
> 
> ```python
> import sys
> from loguru import logger
> 
> fmt = "[{time}] [application_name] [correlationId] [{level}] - {name}:{function}:{line} - {message}"
> config = {
>     "handlers": [
>         {"sink": sys.stderr, "format": fmt},
>     ],
> }
> logger.configure(**config)
> 
> logger.info("Logged message")
> ```
> 
> Which would give you the desired output:
> 
> ```shell
> [2019-07-06T11:35:07.697112+0200] [application_name] [correlationId] [INFO] - __main__:<module>:14 - Logged message
> ```

How do you pass down the correlationId on each request with this setup ?

**Comment by leodotcloud** [comment]
@gaillota you have to use `logger.bind(correlationId="some-id")` in your code before using the related logging message.

**Comment by MonolithFoundation** [comment]
Hello, i have one more quesiton.

I want using customized logger just in one of my lib file, but not effect everyone else and anywhere else, they can call logger outside with default.

But now, all i see is that every time I customized it, whole logger style would change...

**Comment by MonolithFoundation** [comment]
Thanks, as I noticed from previous discuss, won't this casuse 2 line output? 

I am wondering if there a machism that use loguru in my lib (package) with my own style, while not effect others who use this lib, but logger in his logic code (for instance, I have a lib aa, users can pip install aa, they only saw my log style inside aa, but their own logger in their logic code not effected)

**Comment by Delgan** [comment]
@MonolithFoundation Maybe take a look at this section of the documentation: [Configuring Loguru to be used by a library or an application](https://loguru.readthedocs.io/en/stable/resources/recipes.html#configuring-loguru-to-be-used-by-a-library-or-an-application).

Using `logger.add()` from within your library could indeed cause logs duplication to your users, and therefore it's not recommended (except in a `__main__.py` file for example).

There is no way to configure the `logger` as a library author (like `aa` in your example). The thing is that your library should just be emitting log records and should not care about how they are formatted. This is the end user that should be responsible of arranging the logger based on its preferred format. This ensures consistent logs regardless of their source.

If your use case is more advanced than that, then you should expose an API to your users that allows them to use the format you have in mind.

**Comment by MonolithFoundation** [comment]
If am understanding correctly, one should using something like register `mylib` to inside logger, than let users to judge wether call `logger.disable('mylib')` or not?

**Comment by Delgan** [comment]
> does logger.enable() is logger.enable('somelib')? otherwise no clue to enable what.

Yes.

> the "register mylib to inside logger" means, since we can enable something, that must able to add new format into loguru? But currently it just prints twice.

When using `logger.enable("somelib")` or `logger.disable("somelib")`, the filtering of `"somelib"` is made based on the `"name"` attribute of the log record, which actually corresponds to the name of your Python module. Therefore, there is nothing to "register". Calling `logger.info("Some message")` from within `somelib` automatically set the record name to `"somelib"`. Combined with `logger.disable("somelib")`, that means end user wont see the logs from `somelib`. And `somelib` should not call `logger.add()` anyway.

---

@MonolithFoundation I'm worried that this discussion is getting off-topic and polluting this thread in regards to the original question for which was opened.

Please, create a new dedicated ticket if you need further explanations. It will be more appropriate to discuss your specific problem.
