### ISSUE TITLE
Log warning with their filename and line number

### ISSUE THREAD

**Issue by MarcBresson** [Delgan/loguru#1092]
Hello, the [code snippets in loguru's doc](https://loguru.readthedocs.io/en/0.3.1/resources/recipes.html#capturing-standard-stdout-stderr-and-warnings) show how to log warnings.

However, the snippet does not include the additional args of `showwarning` that are `filename` and `lineno`. I found no way of editing the log record to manually replace its `file` and `line` attribute.

Has anyone have an idea how to do such a thing without relying on extras? This would avoid me writing another formatter just to handle warnings

**Comment by Delgan** [comment]
It's generally not advised to try modifying record attributes like `file` and `line`, although I supposed you could technically update them using `logger.patch()`.

Maybe you can try using this updated snippet, which should display the correct file context thanks to `logger.opt()`:

```python
import warnings
from loguru import logger

showwarning_ = warnings.showwarning

def showwarning(message, *args, **kwargs):
    logger.opt(depth=2).warning(message)
    showwarning_(message, *args, **kwargs)

warnings.showwarning = showwarning
```

Note however that this only works well when `warn()` is used with `stacklevel=1`.

**Comment by nikosavola** [comment]
Hi, thanks for the snippet. Would there be a way to make this work with other `warnings.warn` stacklevels, somehow infer the used stacklevel in a nice way?

**Comment by MarcBresson** [comment]
Hey thank you very much for reaching back. I eventually switched back to the logging library to be able to use filters and multiple loggers with different capabilities. One of this filter allows the identification of the file that originally called a logging function.

**Comment by Delgan** [comment]
> Hi, thanks for the snippet. Would there be a way to make this work with other `warnings.warn` stacklevels, somehow infer the used stacklevel in a nice way?

Unfortunately, I'm unaware of any way to do this.

**Comment by nikosavola** [comment]
> > Hi, thanks for the snippet. Would there be a way to make this work with other `warnings.warn` stacklevels, somehow infer the used stacklevel in a nice way?
> 
> Unfortunately, I'm unaware of any way to do this.

I ended up going with a hacky way in https://github.com/gdsfactory/gdsfactory/pull/2656

**Comment by Delgan** [comment]
Thanks for the snippet @nikosavola.

As an alternatiev to stack iteration, one could also [patch](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) the Loguru's record using the `filename` and `lineno` values passed to `showwarning()`. Unfortunately, not all fields can be updated this way, the function name will remain invalid for example. The standard `logging` suffers from the same problem.

Just for reference, I'm linking here another ticket where the `stacklevel` issue is mentioned: https://github.com/Delgan/loguru/issues/1076
