### ISSUE TITLE
Update extras across all loggers

### ISSUE THREAD

**Issue by shaunpatterson** [Delgan/loguru#1097]
I have an http interceptor that I want to read a tracer header value.  I want to inject that header into the logger extras so I can print it out with every other request.    The only way I've found to do that is...

interceptor.py
```
from loguru import logger
...
trace_id = request.get_header('x-tracer')
logger._core.extra.update(dict(tracer=trace_id)) 
```

api.py
```
from loguru import logger
...
logger.debug("Test")
```

where Test should have the tracer in the logger "context"

I don't like the thought of accessing `_core`.    I tried 

```
logger = logger.bind(trace=tracer_id)
```

but that doesn't update the instance in `api.py`

Is there another way of doing this?  Essentially I'm trying to mimic MDC in Log4j

**Comment by shaunpatterson** [comment]
Maybe it's best to just use ContextVar?

**Comment by Delgan** [comment]
Yes, depending on your use case you can rely on [`logger.contextualize()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.contextualize) or simply use a `ContextVar` from standard library.
