### ISSUE TITLE
Changing format of handler

### ISSUE THREAD

**Issue by blueyed** [Delgan/loguru#11]
It appears that you cannot change the format (easily), but have to start a new logger/sink for it (and then stop the previous one), or am I missing something?

I think it would be good to have a method to update the format of a handler (which would take care of handling caches etc) maybe.

Currently I am using:
```python
log_format = loguru._defaults.LOGURU_FORMAT + ' ({extra[reqid]}:{extra[ip]}:{extra[user]})'
logger = loguru.logger
logger.start(sys.stderr, format=log_format)
logger = logger.bind(reqid='-', ip='-', user="-")
logger.stop(0)
```

And then later bind extra per request:
```python
def get_logger_for_request(request):
    global request_id
    request_id += 1
    ip = request.headers.get("x-real-ip", "?")
    return logger.bind(reqid=request_id, ip=ip, user="?")
```

Something like `logger._handlers[0].set_format(loguru._defaults.LOGURU_FORMAT + ' ({extra[reqid]}:{extra[ip]}:{extra[user]})')` could replace the first block here.

I've found that there is `Handler.update_format`, which looked promising, but then it is only about updating formats for color.

Another way would be to use `LOGURU_AUTOINIT=0`, but I wonder what you think about changing the format on the fly.

**Comment by Delgan** [comment]
Hi @blueyed, thanks for your interest on Loguru. 😉 

I don't think that updating the format of an handler is what you really need here.
It looks more like you would prefer the default handler to be started with another format.

Ideally, you could just do: `export LOGURU_FORMAT="... ({extra[reqid]}:{extra[ip]}:{extra[user]})"`

But if you want this just for one of yours scripts, I would suggest to use [`logger.configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure):

```python
logger.configure(
    handlers=[{"sink": sys.stderr, "format"=log_format}],
    extra={"reqid": "-", "ip": "-", user="-"}
)
```

Actually, depending on your program, you may **have to** use `.configure()` as for example, if you `from loguru import logger` in another module, it will not automatically "inherit" from the default values of your extra dict (`.configure()` adds extra to the root logger so it's ok).

As you talk about changing the format "on-the-fly", I just wan to say as a side note that this is possible by passing a function to the `format` argument, so the format can be dynamically modifed at run-time. But that would be of no use here.

Oh, please, don't use Loguru internals, one day it will break unexpectedly! 😛

**Comment by alkuzad** [comment]
@Delgan is LOGURU_FORMAT available also on Windows ?

Can configure be added into README ? I like this library as I like such helpers but I really have strong opinion about ISO8601 datetime everywhere (timezones are such help when debugging). 

I would like to add loguru as dependency but I have to configure it to have proper format and demanding LOGURU_FORMAT this way is not something I can easily do as dependency :)

**Comment by alkuzad** [comment]
@Delgan is LOGURU_FORMAT available also on Windows ?

Can configure be added into README ? I like this library as I like such helpers but I really have strong opinion about ISO8601 datetime everywhere (timezones are such help when debugging). 

I would like to add loguru as dependency but I have to configure it to have proper format and demanding LOGURU_FORMAT this way is not something I can easily do as dependency :)

Oh btw thanks to https://github.com/vitalets/github-trending-repos/issues/11 for pointing that repo :)

**Comment by Delgan** [comment]
Hey @alkuzad.

Yes, you can set the format as an environment variable on Windows too, for example:

```
setx LOGURU_FORMAT "<g>{time}</g> {name} <lvl>{message}</lvl>"
```

Also note that when using `"{time}"` for formatting without specifiers, the default is ISO8601 with timezone information.

In the end, if you want to share a program using `loguru`, you should indeed not rely on environment variables but properly use `.add()` or `.configure()` (which is already mentionned in the README, see: [Suitable for scripts and libraries](https://github.com/Delgan/loguru#suitable-for-scripts-and-libraries)).

Just set the format you prefer at the beginning of your script. 🙂

**Comment by jcmcken** [comment]
Should the default timestamp of messages include the timezone offset? I don't see that in the README animation. Or are you saying the underlying datetime object is timezone aware.

**Comment by Delgan** [comment]
@blueyed Are you satisfied with the proposed solution and did you manage to configure your logger correctly?

**Comment by blueyed** [comment]
@Delgan 
Thanks for your help, I am the following in a `log` module, where I import `logger` from across the app:
```python
import sys

import loguru

# log_format = '<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level> ({extra})'
log_format = loguru._defaults.LOGURU_FORMAT + ' ({extra[reqid]}:{extra[ip]}:{extra[user]})'

logger = loguru.logger

logger.configure(
    handlers=[
        {"sink": sys.stderr, "format": log_format},
    ],
    extra={"reqid": "-", "ip": "-", "user": "-"},
)
```
