### ISSUE TITLE
gevent not compatible

### ISSUE THREAD

**Issue by chenyuan53618** [Delgan/loguru#110]
multiprocess.queue block hangs gevent. is there any solution?

**Comment by Delgan** [comment]
Hi @chenyuan53618. I'm not very used to `gevent`, do you have any code sample I could run to reproduce the problem, please?

**Comment by Delgan** [comment]
@chenyuan53618 I don't know how to reproduce the problem.

Please, can you share the code snippet causing trouble so I can investigate this issue?

**Comment by Delgan** [comment]
I'm closing this as I'm unable to reproduce this error. Also, I'm not sure this is related to `loguru`. According to a quick Google search, it seems `gevent` does not work very well with `multiprocessing` out of the box.

**Comment by Delgan** [comment]
Actually this was probably related to `gevent.patch_all()`. One should not patch threads while using `gevent`. See #258.
