### ISSUE TITLE
Use substring

### ISSUE THREAD

**Issue by mmuraro** [Delgan/loguru#1109]
Hi, I would like to know if I can use a substring in the definition of the loguru log records format. For example for a format like:
"<green>{time:YYYY-MM-DD HH:mm:ss}</green> | {file.name:<20} | <cyan>{module:<15} - {function[0:14]: 15}:{line:<4}</cyan> | <level>{level.name:<8}</level> | <i>{message}</i>"

A thousand thanks

**Comment by changchiyou** [comment]
Yes you can:

- [loguru.logger - The record dict](https://loguru.readthedocs.io/en/stable/api/logger.html#sink:~:text=logger.critical()-,The%20record%20dict,-The%20record%20is)

  > Note that you can use any [formatting directives](https://docs.python.org/3/library/string.html#format-string-syntax) available in Python’s `str.format()` method (e.g. `"{key: >3}"` will right-align and pad to a width of 3 characters). This is particularly useful for time formatting (see below).

- [loguru.logger - The time formatting](https://loguru.readthedocs.io/en/stable/api/logger.html#sink:~:text=See%20datetime.datetime-,The%20time%20formatting,-To%20use%20your)

  > To use your favorite time representation, you can set it directly in the time formatter specifier of your handler format, like for example `format="{time:HH:mm:ss} {message}"`. Note that this datetime represents your local time, and it is also made timezone-aware, so you can display the UTC offset to avoid ambiguities.

**Comment by Delgan** [comment]
The `format` of the handlers follows the string syntax defined by Python here: [Format String Syntax](https://docs.python.org/3/library/string.html#format-string-syntax).

Unfortunately, there is no syntax for sub-stings / slices.

You can instead use a function to generate the string and store it under the `extra` key of the `record` dict, then use it within your format:

```python
from loguru import logger
import sys

def add_function_substring(record):
    record["extra"]["truncated_function"] = record["function"][0:14]

def my_super_long_function_name():
    logger.info("Log message")

if __name__ == "__main__":
    logger.configure(patcher=add_function_substring)
    logger.remove()
    logger.add(sys.stderr, format="{time:YYYY-MM-DD HH:mm:ss} | {file.name:<20} | {module:<15} - {extra[truncated_function]:<15}:{line:<4} | {level.name:<8} | {message}")

    logger.info("Start")
    my_super_long_function_name()
```
Output:
```
2024-03-30 18:17:19 | script.py            | script          - <module>       :15   | INFO     | Start
2024-03-30 18:17:19 | script.py            | script          - my_super_long_ :8    | INFO     | Log message
```

**Comment by mmuraro** [comment]
Hi, great solution.
Works perfectly, solved my problem.

Thank you so much

m.

Il giorno sab 30 mar 2024 alle ore 18:18 Delgan ***@***.***>
ha scritto:

**Comment by Delgan** [comment]
Great, closing then. :+1:
