### ISSUE TITLE
Two line logged for each statement? 

### ISSUE THREAD

**Issue by felixgao** [Delgan/loguru#112]
```python
from loguru import logger
logger.add(sys.stdout, colorize=True, backtrace=True, diagnose=True, format="<green>{time}</green> <level>{message}</level>")

if __name__ == "__main__":
    txt = "This is test text"
    logger.debug("{}", txt)
    logger.debug("End")
```

My terminal output looks like
![image](https://user-images.githubusercontent.com/1153820/60845331-ca207c80-a190-11e9-9eb4-b3a3c5f9aa34.png)

Not sure why it wants to output two rows per log

**Comment by Cosmin-Clucerescu** [comment]
That's working as expected as you have the default handler/sink active.
You need to call "logger.remove()" to remove the default handler/sink, alternatively the default handler/sink configuration can be disabled by setting the environment variable "LOGURU_AUTOINIT" to "False".

**Comment by Delgan** [comment]
Thanks @Cosmin-Clucerescu, I would not have said better. :pray: 

I realized the README was not mentioning the `remove()` function, so I added a sentence about removing the default handler. 

@felixgao Note that you can also use the `configure()` method which automatically remove all previously added handlers.

**Comment by jamesstidard** [comment]
Hi,

I'm having a similar issue with double logging when I use the redirect to `loguru` example. Though I'm not sure how to silence the original logging.

I tried `logger.remove(sys.stdout)` but that doesn't seem right.

I'm probably just being a little brain dead this morning and misunderstanding the comments/docs.

**Comment by Delgan** [comment]
Hi @jamesstidard.

The confusion is understandable, it is not explicitly written in the Readme how to use `logger.remove()`, and one may indeed expect this method to "symmetrically" behaves like `logger.add()` regarding the sink.
This is not the case, though, because calling `logger.add(sys.stderr)` twice is perfectly valid (it would result in logs being duplicated of course), so it would be impossible to identify which of the two handlers should be removed when calling `logger.remove(sys.stderr)`.
For this reason, the `add()` method returns an identifier. This identifier should be used when you wish to remove an handler, simply like this:

```python
i = logger.add(sys.stderr)
logger.remove(i)
```
If you don't know of care about the handler id, you can remove all existing handers by just calling `logger.remove()` without parameter, this will effectively remove the default `stderr` handler and resolve your problem with duplicated logs.

A little bit more information can be found in the documentation: [`logger.remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove). Anyway, I just updated the Readme to make the `remove()` behavior more explicit. :wink:

**Comment by Delgan** [comment]
Also, I will add a more explicit error message when trying to call `logger.remove()` with an identifier which is not a number. :)

**Comment by jamesstidard** [comment]
@Delgan ah, that makes a lot of sense. Sorry, I didn't think to check out the doc string on the function apparently.... probably should have figured that out.

Not to take advantage of your good will, but adding the remove call does indeed get rid of the duplicate lines, but not the ones I was hoping :)

```python
import logging

from loguru import logger

from sanic import Sanic
from sanic.response import json

# Redirect all logging to loguru
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Retrieve context where the logging call occurred, this happens to be in the 6th frame upward
        logger_opt = logger.opt(depth=6, exception=record.exc_info)
        logger_opt.log(record.levelno, record.getMessage())

# logger.remove()
logging.basicConfig(handlers=[InterceptHandler()], level=0)

app = Sanic()

@app.route('/')
async def test(request):
    return json({'hello': 'world'})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```

Without the remove line this outputs:

```console
[2019-07-26 10:44:35 +0100] [17811] [INFO] Goin' Fast @ http://0.0.0.0:8000
2019-07-26 10:44:35.242 | Level 20 | sanic.app:_helper:1383 - Goin' Fast @ http://0.0.0.0:8000
[2019-07-26 10:44:35 +0100] [17811] [INFO] Starting worker [17811]
2019-07-26 10:44:35.248 | Level 20 | sanic.server:serve:802 - Starting worker [17811]
```

With the remove line, it drops the pretty loguru ones in favor of the default. It's still the morning here so I'll continue to blame it on that :)

Thanks for the help.

**Comment by Delgan** [comment]
@jamesstidard The standard `logging` is not always straightforward to work with, I would blame that instead. :smile: 

It seems you need first to remove the Sanic's handler:

```python
logging.getLogger("sanic.root").handlers.clear()
```

For some libraries, this extra-step is not required. I'm not sure of why, I guess it depends on how these libraries configure `logging` internally. `Sanic` seems to attach their own `stderr` handler to `logging.getLogger("sanic.root")`. There is a bit of documentation there: [Sanic Logging](https://sanic.readthedocs.io/en/latest/sanic/logging.html)

**Comment by jamesstidard** [comment]
@Delgan Ah, ok. Feel a little better. Thank you for digging into that for me, very much appreciate it.

> The standard logging is not always straightforward

Yep, been using python for years, still quite baffled by it. Not normally the kinda thing you can get excited about learning either. So I appreciate the library; looks great.

**Comment by Delgan** [comment]
@felixgao Is it ok for you? Do you need more help?

**Comment by jamesstidard** [comment]
@Delgan I'm good, thanks again :+1:; you're welcome to close the ticket.

**Comment by zzxxiinn** [comment]
> @jamesstidard The standard `logging` is not always straightforward to work with, I would blame that instead. smile
> 
> It seems you need first to remove the Sanic's handler:
> 
> ```python
> logging.getLogger("sanic.root").handlers.clear()
> ```
> 
> For some libraries, this extra-step is not required. I'm not sure of why, I guess it depends on how these libraries configure `logging` internally. `Sanic` seems to attach their own `stderr` handler to `logging.getLogger("sanic.root")`. There is a bit of documentation there: [Sanic Logging](https://sanic.readthedocs.io/en/latest/sanic/logging.html)

It works like a charm!
