### ISSUE TITLE
catpure exception as extras?

### ISSUE THREAD

**Issue by trim21** [Delgan/loguru#1138]
currently I'm using `logger.exception` to capture a exception, but it generate a very long `{text}` message.

Is it possible I capture exception with save feature but stored as extra field, instead of part of `{text}`?

**Comment by Delgan** [comment]
Do you mean when `serialize=True`? 
I plan to simplify things a bit, but for now, you would have to [use a custom function](https://loguru.readthedocs.io/en/stable/resources/recipes.html#serializing-log-messages-using-a-custom-function).

**Comment by trim21** [comment]
Thanks, I just read the code and I find that I don't need to custom anythink. It I consider `record["message"]` as logging test and exception traceback is already stored in a seprated `text` field.

**Comment by trim21** [comment]
I re-open this becaust I find that `.record.message` doesn't support color....

**Comment by trim21** [comment]
Nevermind, this is not a big problem
