### ISSUE TITLE
Loguru suppresses an instance of logger from `logging.getLogger()`

### ISSUE THREAD

**Issue by Adversarian** [Delgan/loguru#1141]
Hi,
I would to begin by thanking you for the amount of work you've put into ~~making me not want to paint the walls in red whenever I decide to perform any form of logging~~ this tremendous library.

I've recently encountered an issue which I'm sure is happening by design and the answer to which I have unfortunately not been able to find in the past issues.

I'm currently using a library ([sentence-transformers](https://github.com/UKPLab/sentence-transformers) if it's of any consequence), which happens to be using the default logger from `logging` library.  In a script where I'm making use of this library I'm also logging my own events which is handled by `loguru`. However, it appears that whenever an event is logged in the external library (see [this file](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/evaluation/BinaryClassificationEvaluator.py) for reference), the log is suppressed by loguru and nothing is actually written to stdout. 

Is there anyway I can circumvent this without having to alter the external library? 

Thanks in advance!

**Comment by Delgan** [comment]
Hey @Adversarian.

Did you try to setup an `InterceptHandler` as explained here: [Entirely compatible with standard logging](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging)?

**Comment by Adversarian** [comment]
That would be exactly what I need. Thank you so much @Delgan!

**Comment by Delgan** [comment]
You're welcome, glad you like Loguru. :+1:
