### ISSUE TITLE
Add a "recipe" to change the icon for an existing log level

### ISSUE THREAD

**Issue by DeflateAwning** [Delgan/loguru#1148]
I want to change the warning icon because it renders weird in the Microsoft fonts.

How can I change this icon? I think this would be a valuable recipe.

Side note - I think it might be valuable to turn on GitHub Discussions for this repo for these sorts of Q&A questions, which don't necessarily merit a full GitHub Issue

**Comment by AlTosterino** [comment]
Hey,

There is already recipe how to change icon (and other stuff) for levels, see here: https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.level (`logger.level("WARNING", icon="CUSTOM ICON")`)

About Q&A questions -- This is very good idea, the majority of issues created are just questions and not real problems with the package itself.

**Comment by DeflateAwning** [comment]
That's what I was looking for, thanks a lot! 

Looking forward to seeing the Discussions feature turned on in this repo hopefully, @Delgan :)

**Comment by Delgan** [comment]
Thanks @AlTosterino for sharing the recipe.

Regarding the "Discussions" feature, I might enable it when I cleanup the existing tickets. But to be honest, I'm also fine with having everything in one place, and just labeling the tickets as "Question".

**Comment by DeflateAwning** [comment]
You can easily convert Issues to Discussions with a button-click. Discussions are nice because they work like Reddit/StackOverflow instead of like a Forum (that is, answers are ordered by Votes instead of chronologically, and chronology is represented by comment depth).

I was slow to hop on the Dicussions chain, but have ultimately decided they're nice for Q&A :)
