### ISSUE TITLE
Checking if level exists or not

### ISSUE THREAD

**Issue by sglbl** [Delgan/loguru#1150]
Is there a way to check if the level (I've added) exists or not?
I've added a new level:
```python
logger.level("TITLE", color = "<bold><fg 86>", no=21)
```
But if I don't restart the jupyter kernel, my second run gives me error that 
```python
TypeError: Level 'TITLE' already exists, you can't update its severity no
```
I don't want to restart my jupyter kernel every time, so what I am looking for is something like:
```python
if logger.levels.get("TITLE") is None:
    # check if level title exists, if not, add it
    logger.level("TITLE", color = "<bold><fg 86>", no=21)
```

**Comment by AlTosterino** [comment]
Hey,

What about simple try...except? 
```python
from loguru import logger

try:
    logger.level("TITLE")
except ValueError:
    logger.level("TITLE", color="<bold><fg 86>", no=21)

logger.log("TITLE", "Hello World")
```

**Comment by Delgan** [comment]
Hi.

As suggested by @AlTosterino, using `try / except` is the recommended way to check whether a Loguru level exist.

**Comment by sglbl** [comment]
Thank you. As a suggestion, I think if the new level is created with the same no, it should ignore instead of raising an error.

**Comment by Delgan** [comment]
> Thank you. As a suggestion, I think if the new level is created with the same no, it should ignore instead of raising an error.

I think it would be confusing for the users if the level they configuration of the level fails silently. Raising an exception explicitly warns about conflicts.
