### ISSUE TITLE
Support printf-style formatting?

### ISSUE THREAD

**Issue by NiklasRosenstein** [Delgan/loguru#1151]
I'm looking into migrating an existing project from Python's built-in `logging` facilities to `loguru`. The code base uses printf-style formatting quite extensively, e.g.

```
logger.info("Loading project %s", project.name)
```

Unfortunately loguru doesn't seem to be plug&play in this situation, unless I'm missing something. Is there a way to have loguru support percent-style formatting?

**Comment by AlTosterino** [comment]
Hey, did you check: https://loguru.readthedocs.io/en/stable/resources/migration.html#replacing-style-formatting-of-messages?

**Comment by NiklasRosenstein** [comment]
I did not manage to find this page 👉 👈 . Thank you, I'll check this out next week.

**Comment by Delgan** [comment]
Hi.

> Is there a way to have loguru support percent-style formatting?

Not really, you'll have to replace `%s` with `{}` in your logs. 

See also https://github.com/Delgan/loguru/issues/991.

**Comment by Dev-iL** [comment]
One of the reasons to support `%s`, is to avoid code analysis warnings (e.g. by flake8/ruff). A warning is raised in the case of `{}`-formatted strings since they're less efficient as they're evaluated eagerly, as opposed to `%s` strings: https://docs.astral.sh/ruff/rules/logging-f-string/

(P.S. I like `{}` better, but my preference is irrelevant to the discussion.)

**Comment by Delgan** [comment]
@Dev-iL Thanks for the additional input.

Note that `flake8` warns about usage of f-strings, but you can use `{}` formatting without them:

```python
logger.debug("Retrieved value: {}", value)
```

This does prevent the message to be formatted if not required, and therefore this should not trigger any linting warning.

**Comment by NiklasRosenstein** [comment]
Thanks @Delgan , the `InterceptHandler` was exactly what I was looking for. ❤️
