### ISSUE TITLE
Programmatic interface to color changes

### ISSUE THREAD

**Issue by kfsone** [Delgan/loguru#1159]
In theory:

```
import os
os.environ["LOGURU_DEBUG_COLOR"] = os.environ.get("LOGURU_DEBUG_COLOR", "<dim>")
from loguru import logger
```

works, up until someone else imports loguru first.

Is there an extant mechanism to that lets me cause a logger to rebuild its color table? Or if I'm desperate to control it, do I just play whackamole with logger._core.levels[x].color?

**Comment by Delgan** [comment]
Could you update the color using [`logger.level()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.level)?

```python
logger.level("DEBUG", color="<dim>")
```

**Comment by kfsone** [comment]
YES! Might be worth calling this out in the section on color customization, somehow my read thru of the documentation actually lead me *away* from that.
