### ISSUE TITLE
How to display taskName of async task in loguru?

### ISSUE THREAD

**Issue by truebit** [Delgan/loguru#1161]
as of Python 3.12, [logging module supports taskName](https://docs.python.org/3/library/logging.html#logrecord-attributes):
```
taskName
%(taskName)s
[asyncio.Task](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task) name (if available).
```
If Anyone know how to display `taskName` in loguru format?
Thanks a lot.

**Comment by Delgan** [comment]
That's not available as a built-in, but you can easily patch the logger to add the task's name to the `record`:

```python
def add_task_name(record):
    try:
        record["extra"]["task_name"] = asyncio.current_task().get_name()
    except Exception:
        pass

if __name__ == "__main__":
    logger.configure(patcher=add_task_name)
    logger.add("file.log", format="{extra[task_name]} {message}")
```

**Comment by truebit** [comment]
Thanks a lot. It works.
I added `record["extra"]["task_name"] = record['thread'].name` in except to make sure it displays something
