### ISSUE TITLE
Can `loguru` conditionally display the extra field if the data is non-empty only?

### ISSUE THREAD

**Issue by mainrs** [Delgan/loguru#1164]
My template contains `| {extra}` at the end. Is it possible to only print that part of any extra arguments are present? Right now all my logging lines without extra data end in `| {}`.

**Comment by Delgan** [comment]
You need to use a dynamic `format` function:

```python
def formatter(record):
    if record["extra"]:
        return "{time} {message} | {extra}\n{exception}"
    else:
        return "{time} {message}\n{exception}"    
```

**Comment by mainrs** [comment]
Thank you!
