### ISSUE TITLE
Supress bold while preserving colours

### ISSUE THREAD

**Issue by savchenko** [Delgan/loguru#1169]
I am quite happy with the default colours, however the bold text looks off.

Is there a way to preserve all decorations, but remove the bold?

**Comment by Delgan** [comment]
You can use [`logger.level()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.level) to edit the style of levels:

```python
logger.level("INFO", color="<white>")
```

You can also configure it through environment variables:

```python
export LOGURU_INFO_COLOR="<white>"
```

**Comment by Delgan** [comment]
That's surprising. Loguru doesn't manage color values or their rendering. It simply uses [ANSI sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) corresponding to "black", for example.
