### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by robina80** [Delgan/loguru#1170]
hi all,

this is a snippet of my code

`logger.remove()
logger.add("password.log", format="{time:YYYY-MM-DD HH:mm:ss} {level} {message}", rotation="3 seconds", retention=3, level="DEBUG")`

and this is the error im getting

`--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=27, microseconds=826134), 'exception': None, 'extra': {}, 'file': (name='password.py', path='C:\\python\\venv\\password.py'), 'function': 'password', 'level': (name='WARNING', no=30, icon='⚠️'), 'line': 62, 'message': 'cant find user luke.pearson on the domain, please click back and try again', 'module': 'password', 'name': '__main__', 'process': (id=15380, name='MainProcess'), 'thread': (id=22568, name='Thread-2 (process_request_thread)'), 'time': datetime(2024, 7, 7, 15, 34, 54, 352175, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'GMT Summer Time'))}
Traceback (most recent call last):
  File "C:\python\venv\Lib\site-packages\loguru\_handler.py", line 206, in emit
    self._sink.write(str_record)
  File "C:\python\venv\Lib\site-packages\loguru\_file_sink.py", line 204, in write
    self._terminate_file(is_rotating=True)
  File "C:\python\venv\Lib\site-packages\loguru\_file_sink.py", line 276, in _terminate_file
    os.rename(old_path, renamed_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\python\\venv\\password.log' -> 'C:\\python\\venv\\password.2024-07-07_14-04-50_079397.log'
--- End of logging error ---
127.0.0.1 - - [07/Jul/2024 15:34:54] "POST /password HTTP/1.1" 200 -`

thanks,
rob

**Comment by Delgan** [comment]
Hi.

I'm sorry but there is not enough information for me to help you. Can you give more details about your setup and use of Loguru? What other libraries does your application use?

**Comment by robina80** [comment]
Hi @Delgan yes of course, im using loguru with my flask-wtf web form, il show you my code and sorry if its long

im running this in a venv

`from flask import Flask, render_template, request
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, DecimalField, RadioField, SelectField, TextAreaField, FileField, SubmitField
from wtforms.validators import InputRequired, Length, DataRequired, EqualTo, Regexp, ValidationError
import re
from loguru import logger
import time
import subprocess
import smtplib
from email.mime.text import MIMEText

logger.remove()
logger.add("password.log", rotation="30 seconds", retention=3)
#logger.add(format="{time:YYYY-MM-DD HH:mm:ss} {level} {message}")
#logger.add(level="DEBUG")

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secretkey'

class PasswordForm(FlaskForm):
    un = StringField('Username', [InputRequired(message='please enter your Username')])
    op = PasswordField('Current Password', [InputRequired(message='please enter your current password')])
    np = PasswordField('New Password', [InputRequired(message='please enter your new password')])
    cnp = PasswordField('Confirm New Password')
    dom = SelectField('Domain', choices=[('lon-prod-dc01.domain1.com', 'prod'), ('lon-corp-dc01.domain2.com', 'corp'), ('dc01.robo84.net', 'robo84')])
    
    def validate_un(form, field):
        if not field.data == form.un.data.lower():
            raise ValidationError('Username needs to be Lowercase')
    
    def validate_np(form, field):
        if form.un.data:
            if any (name in field.data.lower() for name in form.un.data.split(".")):
                raise ValidationError('New password cant contain firstname or lastname')
        if field.data.lower() == form.op.data.lower():
            raise ValidationError('New password cant match Current password')
        if re.search(r"\s", field.data):
            raise ValidationError('New password cant contain any spaces')
        if not re.search(r"[0-9]", field.data):
            raise ValidationError('New password has to contain one number')
        if not re.search(r"[a-z]", field.data):
            raise ValidationError('New password has to contain one lower case character')
        if not re.search(r"[A-Z]", field.data):
            raise ValidationError('New password has to contain one upper case character')
        if not re.search(r"[\`\¬\!\"\£\$\%\^\&\*\(\)\-\_\=\+\\\|\[\]\;\'\#\,\.\/\{\}\:\@\~\<\>\?]", field.data):
            raise ValidationError('New password has to contain one special character')
        if len(field.data) < 12:
            raise ValidationError('New password must be at least 12 characters')
        if not field.data == form.cnp.data:
            raise ValidationError('New password has to match Confirm new password')
        
@app.route('/password', methods=['GET', 'POST'])
def password():
    form = PasswordForm()
    if request.method == 'POST' and form.validate():
        result = subprocess.run(f'powershell.exe $cred = Import-CliXml -Path C:\\python\\venv\\cred.xml; Set-ADAccountPassword -Credential $cred -Identity {form.un.data} -OldPassword (ConvertTo-SecureString -AsPlainText {form.op.data} -Force) -NewPassword (ConvertTo-SecureString -AsPlainText {form.cnp.data} -Force) -Server {form.dom.data}', capture_output=True, text=True, shell=False)
        if 'The specified network password is not correct' in result.stderr:
            logger.warning(f'{form.un.data}your current password is wrong, please click back and try again')
            return 'your current password is wrong, please click back and try again'
        if 'The password does not meet the length, complexity, or history requirement of the domain' in result.stderr:
            logger.warning(f'{form.un.data}cant re-use one of your old passwords or cant change password as still less than one day old, please click back and try again')
            return 'cant re-use one of your old passwords or cant change password as still less than one day old, please click back and try again'
        if 'Cannot find an object with identity:' in result.stderr:
            logger.warning(f'cant find user {form.un.data} on the domain, please click back and try again')
            return f'cant find user {form.un.data} on the domain, please click back and try again'
        if result.returncode == 0:
            try:
                une = subprocess.run(f'powershell.exe $cred = Import-CliXml -Path C:\\python\\venv\\cred.xml; Get-aduser -credential $cred -server {form.dom.data} -identity {form.un.data} -properties * | select-object -expandproperty mail', capture_output=True, text=True, shell=False)
                smtp_server = '172.17.1.5'
                smtp_user = 'robertkwild@gmail.com'
                smtp_connection = smtplib.SMTP(smtp_server)
                email_body = f'hello {form.un.data} your new password is {form.cnp.data} for {form.dom.data}'
                email_message = MIMEText(email_body)
                email_message['Subject'] = 'password change'
                email_message['From'] = 'robertkwild@gmail.com'
                smtp_connection.sendmail(smtp_user, {une.stdout}, email_message.as_string())
                smtp_connection.quit()
                logger.info(f'{form.un.data}found an email for your user, please check email for your new password')
                return 'found an email for your user, please check email for your new password'
            except:
                logger.info(f'{form.un.data}changed your password but could not find an email address for you, please contact IT to add one')
                return 'changed your password but could not find an email address for you, please contact IT to add one'
    return render_template('password.html', form=form)

if __name__ == '__main__':
    app.run(debug=True, ssl_context='adhoc', host='0.0.0.0')
    
#'<h1>The username is {}. The old password is {}. the new password is {}. changing for domain {}'.format(form.un.data, form.op.data, form.cnp.data, form.dom.data)`

**Comment by robina80** [comment]
at last got logging working

`logger = logging.getLogger("Rotating Log")
logger.setLevel(logging.DEBUG)
handler = TimedRotatingFileHandler(filename='password.log', when='S', interval=30, backupCount=5, delay=True)
logger.addHandler(handler)`

the key is delay=True

dont know if loguru has an option like this

**Comment by robina80** [comment]
any news about this?

**Comment by robina80** [comment]
at last loguru works with same option delay=True

`logger.remove(0)`
`logger.add("logs\\password.log", format="{time:YYYY/MM/DD HH:mm:ss} | {level} | {message}", rotation="20 seconds", delay=True)`

**Comment by Delgan** [comment]
Thanks for the additional details.

Since you mention that it works better with `delay=True`, this indicates a `multiprocessing` problem. This is a common problem when using web frameworks and Guvicorn.

Because `logger.add("password.log")` is called at the root of the Python file, this means it'll be executed by the main process, but also each time a new process is spawned. 
I suppose the file `"password.log"` is created by your main process. Then, when a child process is created, it'll have its own different handler logging to `"password.log"` too. However, because the file was already opened by the main process, it causes `PermissionError`.

I plan to add a new functionality to avoid this kind of trouble, but in the meantime you have to be careful that each process/worker uses a different file name.
