### ISSUE TITLE
how to log ip addresses in log

### ISSUE THREAD

**Issue by robina80** [Delgan/loguru#1181]
Hi all,

I want to keep track in the logs as well as time message level etc, I want to log down the clients ip address

Is this possible

Thanks,
Rob

**Comment by Delgan** [comment]
Hi.

You can [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch)  the `logger` or use [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) to update the `record` using the IP client you retrieved.

Here is an example using [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure):

```python
import sys
from loguru import logger

client_ip = "192.168.0.1"
logger.configure(
    extra={"client_ip": client_ip},
    handlers=[{"sink": sys.stderr, "format":"{time} {extra[client_ip]} {message}"}]
)

logger.info("Some message")
```

**Comment by robina80** [comment]
i mean i want to log ip addresses who access/use my python flask wtf web form, so i wouldnt know there ip address ie 192.168.0.1

**Comment by AlTosterino** [comment]
Hey,

I think this log: `127.0.0.1 - - [21/Jul/2024 20:40:11] "POST /password HTTP/1.1" 200 -` comes directly from [Werkzeug](https://werkzeug.palletsprojects.com/en/3.0.x/)

What you want to achieve is not directly connected to the `loguru` logger.

You have the couple of options to log the IP address:

1. Log IP address directly in the resource
```python
from loguru import logger
from flask import request

DEFAULT_FORMAT = (
    "| <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | "
    "<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    " | {extra}"
)

logger.remove()
logger.add(sys.stderr, level="INFO", format=DEFAULT_FORMAT)

@app.route("/foo", methods=["GET"])
def foo():
    logger.info("PC IP: {}", request.remote_addr)
```

2. Log IP address with context (so all logs within context manager will have IP address included)
```python
from loguru import logger
from flask import request

DEFAULT_FORMAT = (
    "| <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | "
    "<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    " | {extra}"
)

logger.remove()
logger.add(sys.stderr, level="INFO", format=DEFAULT_FORMAT)

@app.route("/foo", methods=["GET"])
def foo():
    with logger.contextualize(ip=request.remote_addr):
        logger.info("I have IP address in the context!")
    logger.info("I do not IP address in the context :<")
```

3. Write custom middleware which will add IP address to every log in the resource
```python
import sys

from flask import Flask
from loguru import logger

DEFAULT_FORMAT = (
    "| <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | "
    "<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    " | {extra}"
)

logger.remove()
logger.add(sys.stderr, level="INFO", format=DEFAULT_FORMAT)

app = Flask(__name__)

class IPLoggerMiddleware:
    def __init__(self, app):
        self.app = app

    def __call__(self, environ, start_response):
        user_ip = environ.get('REMOTE_ADDR')
        with logger.contextualize(user_ip=user_ip):
            return self.app(environ, start_response)

# Apply the middleware
app.wsgi_app = IPLoggerMiddleware(app.wsgi_app)

@app.route('/foo')
def index():
    logger.info("I do have IP in my log!")
    do_something()
    return "Hello, World!"

def do_something():
    logger.info("I also have an IP in my log")
```

**Comment by robina80** [comment]
thanks pointed me in the right direction

`@app.route('/password', methods=['GET', 'POST'])
def password():
    ip_addr = request.remote_addr
    form = PasswordForm()
    if request.method == 'POST' and form.validate():`

`logger.warning(f'{ip_addr} {form.un.data} your current password is wrong, please click back and try again')`

and in log file i get this

`2024-07-22-12-55-27 | WARNING | 127.0.0.1 robert.wild your current password is wrong, please click back and try again`

**Comment by Xanderplayz16** [comment]
The reason that 127.0.0.1 is given is because 127.0.0.1 is basically Flask telling you that this is coming from the computer that Flask is being ran on. The reason this exists is because you wouldn't want to type `159.214.173.135` just to refer to the local computer, so you can just use `127.x.x.x`.

Just a quick tip: Use 3 grave characters (\`) instead of one, and put them at the start and end of your code block. This makes it so you don't have to put \` line \` for every line.
Example:
\`\`\`
print('this is my code')
print('etc')
\`\`\`
What you are doing:
\`print('this is my code')\`
\`print('etc')\`
