### ISSUE TITLE
Send log messages with async function

### ISSUE THREAD

**Issue by wpmjones** [Delgan/loguru#119]
I am writing a bot for Discord and using the [discord.py](https://discordpy.readthedocs.io/en/latest/index.html) library which is async.  I want to send some log messages to Discord using the bot.  

Essentially, all of the bot activity happens inside a class.  I am having a lot of trouble figuring out where to put the logger.add and whether the sink function should be inside the class or outside the class.  If it's outside, then the bot can't be accessed from the function (critical to send the message).  If it's inside, then I don't know where to put logger.add.  

Here is where I am at the moment, but I get errors that `Push.send_log` was never awaited.

```
from discord.ext import commands, tasks
from config import settings
from loguru import logger

class Push(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.test_loop.start()
        logger.add(self.send_log, level="WARNING")

    def cog_unload(self):
        self.test_loop.cancel()

    @tasks.loop(seconds=15)
    async def test_loop(self):
        print("success")
        self.logger.warning("Yes!")

    async def send_log(self, message):
        await self.bot.get_channel(settings['pushChannels']['pushLog']).send(message)

def setup(bot):
    bot.add_cog(Push(bot))
```

Any help would be appreciated.

**Comment by Delgan** [comment]
Hi @wpmjones. :slightly_smiling_face: 

I don't know very well async programming in Python. While providing a function to `logger.add(func)`, Loguru will try to call it as a basic normal function: `func()`. I suppose async functions are not callable this way, hence the "Push.send_log was never awaited" error. Is there a way to wrap the `send_log()` async method in a normal one?

Also, I never developed any Discord bot. Is it possible for you to give me a minimal example where I could just replace token / server / channel and start debugging this, please?

**Comment by wpmjones** [comment]
Actually, with the help of a few friends, I got it working.  

```import asyncio
from discord.ext import commands
from loguru import logger
from config import settings


class LogTest(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        logger.add(self.send_log)

    @commands.command(name="log_test")
    async def log_test(self, ctx):
        logger.info("Logging is working")

    def send_log(self, message):
        print("inside send_log")
        asyncio.ensure_future(self.send_message(message))

    async def send_message(self, message):
        print("inside send_message")
        record = message.record
        await self.bot.get_channel(settings['logChannels']['push']).send(record)


def setup(bot):
    bot.add_cog(LogTest(bot))```

Essentially, loguru calls the regular function which then uses asyncio to call the async function.  It's an extra step, but it works.  Now I just have to work on formatting so that it's a gorgeous as it is in the console! :)

**Comment by Delgan** [comment]
Ok, I'm not so sure on why and how it works, but if you say so, great then. :grin: 

Also to answer you initial question, I usually call `logger.add()` outside of any class, actually near to the entry point to my program where the configuration generally occurs. I guess it will works fine as you did, but be careful with multi-instantiation of `LogTest()` objects (logs send from the first one may also appear in the channel of the second one). :wink:

**Comment by t-mart** [comment]
I was just about to make an issue about async support myself, but I'm glad I found this one.

Yes, I too would like to see async support in loguru. In my otherwise asynchronous application, I was a bit frustrated that I had to resort to threading because I couldn't call my sinks asynchronously (I'm calling an HTTP API with log records).

To me, the cleanest approach would be to add a whole 'nother set of logging functions on the Logger that are coroutines (`async def`) like `trace_async`, `debug_async`, etc. I'm not totally sure how this would work with the concurrency mechanisms in this project (like the `enqueue` flag provides) without more investigation.

I've done a bit of asynchronous programming in Python. From 20,000 feet, I **don't** think this would be a huge addition.

@Delgan, would you have an appetite for my PR on this? (No promises, but just curious to see if that's a direction you'd consider for the project.)

**Comment by Delgan** [comment]
Using Loguru `v0.4.0`, using the `send_log()` asynchronous method as a sink should work out-of-the-box. :+1: 

Make sure to await [`complete()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.complete) before leaving the event loop.
