### ISSUE TITLE
feature request: add a built-in InterceptHandler so loguru can be used with logging.fileConfig

### ISSUE THREAD

**Issue by trim21** [Delgan/loguru#1192]
I have some project using uvicorn and it will config python stdlib logging with fileConfig or dictConfig.

I want to pipe logging from stdlib logging to loguru, hope we can have a InterceptHandler in loguru module so I don't need to copy it in all my project.

**Comment by Delgan** [comment]
Initially, Loguru was designed to be independent of the standard logging library. However, I understand that it would be much more convenient for users to have this built-in functionality.

I therefore consider implementing a new `logger.bridge()` method to replace `InterceptHandler` and `PropagateHandler` recipes.

See https://github.com/Delgan/loguru/issues/633
I'm gonna close this ticket as "Duplicate" if you don't mind.
