### ISSUE TITLE
Can I make loguru to throw an exception when use it to log an exception?

### ISSUE THREAD

**Issue by dclong** [Delgan/loguru#120]
By default, none of error/exception/critical throws an exception when used to log messages. Can I make loguru to actually throw an exception?

**Comment by Delgan** [comment]
Hey.

I don't think this is the `logger`'s job to throw an exception.
The method `logger.exception()` is just there to conveniently log the stacktrace while an exception is caught, but that's all. The logger should interfere as little as possible with the control flow of your program, it only servers to record what's happening in your code.

Why would you want the `logger` to also raise an exception? Maybe to reduce duplicating error messages?

That being said, you can just use a function to log **and** throw. Furthermore, you could also add it to the `logger` object if you prefer.

```python
def throw(_, error, message, *args, **kwargs):
    logger.opt(depth=1).error(message, *args, **kwargs)
    raise error(message)

logger.__class__.throw = throw

logger.throw(ValueError, "Something bad happened")
```

**Comment by dclong** [comment]
@Delgan You are right. I wanted to reduce redundant error messages. Thank you for the example code! It helps a lot.
