### ISSUE TITLE
very bad perf on `_datetime.datetime.__format__`

### ISSUE THREAD

**Issue by trim21** [Delgan/loguru#1201]
current text format use `YYYY-MM-DD HH:mm:ss.SSS` and handled by `_datetime.datetime.__format__`, which is very slow comparing to stdlib version `%Y-%m-%d %H:%M:%S.%f%z`.

For example, I use `os.devnull` as sink and try these 2 format, `YYYY-MM-DD HH:mm:ss.SSS` will use 44s but `%Y-%m-%d %H:%M:%S.%f%z` use only 20s. (also it's 10s for stdlib logging)

```python
import os
import timeit

from loguru import logger as logger_new
from loguru_old import logger as logger_old

logger_new.info("hello world")
# exit(0)

logger_new.remove(0)
logger_new.add(os.devnull)
logger_old.remove(0)
logger_old.add(os.devnull)

def loguru_new_case():
    logger_new.info("hello {}", "b")


def loguru_old_case():
    logger_old.info("hello {}", "b")


print(timeit.timeit(loguru_new_case))
print(timeit.timeit(loguru_old_case))
```

**Comment by Delgan** [comment]
Fixed by 80f05fd2635a9f728565585fed02bed7c2be968a.

Thank you for investigating possible performance improvements. :+1:
