### ISSUE TITLE
Use extra keys for TypedDict

### ISSUE THREAD

**Issue by reneleonhardt** [Delgan/loguru#1208]
https://github.com/Delgan/loguru/blob/fa3746fe8ce354e8e32e444b2bc7e4221a88ac86/loguru/__init__.pyi#L215

It seems mypy 1.9.0 implemented a fix https://github.com/python/mypy/pull/14225, can `_HandlerConfig` be made actually usable now? 😅

**Comment by Delgan** [comment]
I'll try again when I have some time, thanks for the notification. :)
