### ISSUE TITLE
How to set console output level

### ISSUE THREAD

**Issue by obrua** [Delgan/loguru#121]
the current console outputs all the logs, how to set it like logging, the console only outputs a specific level log ; 
just like: logging.basicConfig(level=logging.INFO) 

```
from loguru import logger

# logging.basicConfig(level=logging.INFO) 
logger.debug('debug') #do not console output debug level
logger.info('info')
logger.success('success')
```

> PS C:\*> python .\test.py
> 2019-07-28 09:57:08.459 | INFO     | __main__:<module>:4 - info
> 2019-07-28 09:57:08.461 | SUCCESS  | __main__:<module>:5 - success
> 2019-07-28 09:57:08.462 | DEBUG    | __main__:<module>:6 - debug

**i want just outputs level INFO like this**
> PS C:\*> python .\test.py
> 2019-07-28 09:57:08.459 | INFO     | __main__:<module>:4 - info
> 2019-07-28 09:57:08.461 | SUCCESS  | __main__:<module>:5 - success

_thank you for your help_

**Comment by obrua** [comment]
I found a solution, set in the environment variable, but how to set it in the program?

> .env
`LOGURU_LEVEL='INFO'`

**Comment by Delgan** [comment]
Hi. You can simply [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default handler, and re-[`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) it with your favorite level:

```python
logger.remove()
logger.add(sys.stderr, level="INFO")
```

Alternatively, you can use [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) which automatically suppress the default handler:

```python
logger.configure(handlers=[{"sink": sys.stderr, "level": "INFO"}])
```

The `LOGURU_LEVEL` [environment variable](https://loguru.readthedocs.io/en/stable/api/logger.html#env) is meant to be set from within your terminal (using `setx` or `export` depending on your OS). If Loguru find such variable, it will configure the default handler with the given level for all of your programs, avoiding having to configure it manually.

**Comment by obrua** [comment]
This is what I want, thank you.
