### ISSUE TITLE
Python 3.14: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated

### ISSUE THREAD

**Issue by pawamoy** [Delgan/loguru#1218]
...and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead.

Triggered by:

```pytb
  .venvs/3.14/lib/python3.14/site-packages/loguru/_simple_sinks.py:13: in __init__
      self._completable = asyncio.iscoroutinefunction(getattr(stream, "complete", None))
```

Just started getting these deprecation warnings while running my test suite, where pytest treats warnings as errors. Just a heads up, nothing urgent :slightly_smiling_face:

**Comment by Delgan** [comment]
Thanks for the early notice! :D

I fixed the deprecation warning (as well as another test) and added Python 3.14-dev to the CI test suite. :+1:
