### ISSUE TITLE
default message color

### ISSUE THREAD

**Issue by obrua** [Delgan/loguru#122]
Can add default color configuration to document?

I need to show more information, such as: thread, but I want the color settings to be the same as the default.

**After this setting, the color is gone.**

> I want Ctrl+C and then add {thread.name}  over

`logger.add(sys.stderr, format="{time} | {level} | {name}:{module}:{line};{thread.name} - {message}", level=level)`

thank you for your help

**Comment by Delgan** [comment]
If you want to customize the logging format, you have to take care of colorization too which is done though `"<color>"` tags.

You can see the default colors used here: https://github.com/Delgan/loguru/blob/94f158349ef3320a9a46b592c4f1d526a364cb28/loguru/_defaults.py#L31-L37

If this seems a little bit too verbose, note that there exist abbreviation and that you can auto-close the color tags with `"</>"`, [see documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#color).

In your case, the format would look like this:

```python
fmt = "<g>{time}</> | <lvl>{level}</> | <c>{name}</>:<c>{line}</>:<c>{line}</>;<c>{thread.name}</> - <lvl>{message}</>"
logger.add(sys.stderr, format=fmt)
```

**Comment by obrua** [comment]
3q

**Comment by obrua** [comment]
this is great, thank you.
