### ISSUE TITLE
More customized logging methods

### ISSUE THREAD

**Issue by Rafficer** [Delgan/loguru#123]
I'm trying to customize the way how loguru logs, but I'm not really getting anywhere.

Might also be that it's not possible, would be great to get some support. Here's what I'd like to do:

1. I want to give the user the ability to enable the logging output to screen (I got this so far. Basically wrap `logger.disable("")` in an if clause)

2. Even when output is disabled, it should still log to the sink/log file

3. When using `logger.catch()` it only shows the output/error message of an exception when logging isn't disabled. Is there some way to always show the output? Otherwise a program would just quit if there is an issue instead of printing some information.

Is this possible with loguru? Or something close to that? Would really appreciate any help!

**Comment by Delgan** [comment]
Hi @Rafficer. :)

I think you don't need `disable()`, you can simply `add()` a sink file all the time, and `add()` another `stderr` sink only if required by the user. This should solve your first and second points.

```python
logger.remove()  # Remove default 'stderr' sink
logger.add("myapp.log")

if show_input:
    logger.add(sys.stderr)
```

About your third point, I guess you can set the `reraise` option of `catch()` to `True`, so the error will be propagated to the Python exception handler:

```python
@logger.catch(reraise=True)
def foo():
    1 / 0
```

**Comment by Rafficer** [comment]
Thanks a lot! This is exactly what I needed! :)
