### ISSUE TITLE
Loguru inserts a newline after every log record

### ISSUE THREAD

**Issue by sanmai-NL** [Delgan/loguru#1234]
Like so:

```text
2024-11-15T14:02:36.888251+0100 - DEBUG - aimtools.cli - execute - [stdout] installing to /home/unprivileged/.local/bin

2024-11-15T14:02:36.888521+0100 - DEBUG - aimtools.cli - execute - [stdout]   uv

2024-11-15T14:02:36.888833+0100 - DEBUG - aimtools.cli - execute - [stdout]   uvx

2024-11-15T14:02:36.889237+0100 - DEBUG - aimtools.cli - execute - [stdout] everything's installed!
```

with configuration
```python
            {
                "backtrace": False,
                "enqueue": True,
                "diagnose": False,
                "format": "<d>{time}</d> - <red>{level}</red> - {name} - {function} - <b>{message}</b>",
                "serialize": False,
                "sink": stderr,
            }
```

In particular for file output I want to reduce the number of lines, and this doubles their amount.

**Comment by Delgan** [comment]
Hey @sanmai-NL.

Do you have maybe a fully reproducible example? I'm not observing any extra new line added with the following snippet:

```python
from loguru import logger

from sys import stderr

logger.configure(
    handlers=[
        {
            "backtrace": False,
            "enqueue": True,
            "diagnose": False,
            "format": "<d>{time}</d> - <red>{level}</red> - {name} - {function} - <b>{message}</b>",
            "serialize": False,
            "sink": stderr,
        }
    ]
)

logger.info("Message 1")
logger.info("Message 2")
```

Is `stderr` something else than `sys.stderr`? Is there a particular configuration in your runtime environment? Under certain conditions, it's not impossible for the `sys.stderr` to be replaced by another custom stream. Or maybe it comes from your log viewers.

Basically, when `sys.stderr` is used< as a sink for Loguru, it's roughly equivalent to the following snippet:

```python
import sys

sys.stderr.write("Message 1\n")
sys.stderr.write("Message 2\n")
```

Does the above code also cause extra new lines?

Note that you can disable the `"\n"` added by using a custom `format` function:

```python

logger.configure(
    handlers=[
        {
            "backtrace": False,
            "enqueue": True,
            "diagnose": False,
            # Note: You should also put `{exception}` somewhere
            "format": lambda _: "<d>{time}</d> - <red>{level}</red> - {name} - {function} - <b>{message}</b>",
            "serialize": False,
            "sink": stderr,
        }
    ]
)
```

If `stderr` happens to be a standard [`StreamHandler`](https://docs.python.org/3/library/logging.handlers.html#streamhandler), you also need to set the [`terminator`](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler.terminator) attribute to `""`.

**Comment by sanmai-NL** [comment]
> ```python
> "format": lambda _: "<d>{time}</d> - <red>{level}</red> - {name} - {function} - <b>{message}</b>",
> ```

Thanks, this is marvelous support! Of course all for free, but it shows great craftspersonship. 🥇 

The problem has been solved. I perform a `readline()` call on the stderr of a subprocess, and write it into your log. Suprisingly to me, the returned line string contained its final newline too.

One remaining question though, why is including "{exception}" advisable? I do a `logger.catch()` around this function.

**Comment by Delgan** [comment]
No problem, glad you figured this out. :+1: 

The `{exception}` specifies the formatting of `Exception` captured by `logger.catch()` or logged using `logger.exception()`. If it does not appear in the logging `format`, then the exception won't be formatted (the usual traceback associated with an error won't be displayed).

Note that this is only a concern when the `format` is defined as a custom function. When `format` is a string, then `"\n{exception}"` is automatically appended to the format for convenience. However, when `format` is a function, the users are free to customize the logs format in its entirety, and they are therefore responsible for placing (or not) `"{exception}"` as desired.

**Comment by sanmai-NL** [comment]
Is this info missing from the docs?

**Comment by Delgan** [comment]
It's [there](https://loguru.readthedocs.io/en/stable/api/logger.html#message):

> If fine-grained control is needed, the `format` can also be a function which takes the record as parameter and return the format template string. However, note that in such a case, you should take care of appending the line ending and exception field to the returned format, while `"\n{exception}"` is automatically appended for convenience if `format` is a string.
