### ISSUE TITLE
New release for Python 3.13?

### ISSUE THREAD

**Issue by jelly** [Delgan/loguru#1242]
The last release of loguru requires some patching to be compatible with Python 3.13, as Arch Linux distribution packager it would be convenient if there was a new release with 3.13 compatibility so we could avoid patching.

Reported an issue as discussions aren't open for this repository.

**Comment by jelly** [comment]
Thanks, very much appreciated!

**Comment by Delgan** [comment]
Release v0.7.3 is available by the way. Closing this issue then. :+1:
