### ISSUE TITLE
Analog of isEnabledFor(level) in loguru.

### ISSUE THREAD

**Issue by a18** [Delgan/loguru#1243]
Hello!
We want to move from "logging" to "loguru".
What is the best way to rewrite our numerous use-cases like this one:
```python
import logging
logger = logging.getLogger(__file__)
...

if logger.isEnabledFor(logging.DEBUG):
    # Prepare the heavy message only if DEBUG level (or more verbose one) is enabled
    heavy_message = prepare_heavy_message()  # ~100 ms CPU time
    logger.debug(heavy_message)
else:
    ... # Some explanations to user how to get details.
 ```

**Comment by Delgan** [comment]
Hi!

You can take a look at this section of the documentation: [Replacing `isEnabledFor()` method](https://loguru.readthedocs.io/en/stable/resources/migration.html#replacing-isenabledfor-method).

Basically, using Loguru you can rely in the `lazy` argument of the `opt()` method:

```python
logger.opt(lazy=True).debug(prepare_heavy_message)  # The function will be called only if needed.
```

It's not possible to use an `else` clause, though.

**Comment by a18** [comment]
> You can take a look at this section of the documentation: [Replacing `isEnabledFor()` method](https://loguru.readthedocs.io/en/stable/resources/migration.html#replacing-isenabledfor-method).

Thank you so much! We should have found these docs ourselves )
Looks exactly what is needed! (apart from informing user about the current effective log level).

**Comment by Delgan** [comment]
Note that I've amended the above snippet, I'd made an error initially (the lazy function must be passed as `*args` or `**kwargs`, the first argument must be the log message).
