### ISSUE TITLE
多进程使用logger的问题  （The problem of using loggers for multiple processes）

### ISSUE THREAD

**Issue by 212413616** [Delgan/loguru#1245]
我的英文不是很好，我使用中文进行说明我的问题

多进程使用loguru时，我参考：https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument

在主进程配置好logger，然后传递给子进程，但是使用的时候有很多麻烦的地方，下面是我的测试代码

```
# workers_a.py
import time

from loguru import logger

from print_log import printLog


class WorkerA:

    @staticmethod
    def setLogger(logger_):

        global logger
        logger = logger_

    @staticmethod
    def work(msg):
        while True:
            printLog(msg)
            time.sleep(1)
```

```
# print_log.py

import workers_a


def printLog(msg):
    workers_a.logger.debug(msg)
```

```
# main.py

from multiprocessing import Pool

from loguru import logger

from workers_a import WorkerA

if __name__ == "__main__":

    logger.remove()
    format = "<green>{time:YYYY-MM-DD HH:mm:ss,SSS}</green> - <level>{level:<8}</level> - <magenta>{process}</magenta>:<yellow>{thread}</yellow> - <cyan>{name}</cyan>:<cyan>{function}</cyan>:<yellow>{line}</yellow> - <level>{message}</level>"
    logger.add("error.log", rotation="5 MB", format=format, enqueue=True)

    with Pool(4, initializer=WorkerA.setLogger, initargs=(logger,)) as pool:
        pool.map(WorkerA.work, ["hello"])
```

上面就是我的测试代码，可以看出子进程调用**其他文件**函数时，其他文件如果想输出日志，就需要使用 **workers_a.logger**进行输出日志，如果子进程很多文件都需要输出日志，这样很麻烦，请问有什么解决办法吗

我的希望是直接使用下面这种就能正常使用main函数中进行配置的logger
```
# print_log.py

from loguru import logger


def printLog(msg):
    logger.debug(msg)

```

**Comment by Delgan** [comment]
Hey @212413616.

Thanks for the comprehensive example. I agree with you that the suggested workaround for `multiprocessing` is not convenient at all.

A much simpler alternative is to simply mutate the `logger` itself, using a trick described here: https://github.com/Delgan/loguru/issues/818

That means you could update your code as follow:

```python
# main.py

from multiprocessing import Pool

from loguru import logger

from workers_a import WorkerA

def update_global_logger(logger_):
    logger.__dict__ = logger_.__dict__.copy()

if __name__ == "__main__":

    logger.remove()
    format = "<green>{time:YYYY-MM-DD HH:mm:ss,SSS}</green> - <level>{level:<8}</level> - <magenta>{process}</magenta>:<yellow>{thread}</yellow> - <cyan>{name}</cyan>:<cyan>{function}</cyan>:<yellow>{line}</yellow> - <level>{message}</level>"
    logger.add("error.log", rotation="5 MB", format=format, enqueue=True)

    with Pool(4, initializer=update_global_logger, initargs=(logger,)) as pool:
        pool.map(WorkerA.work, ["hello"])
```

After that, you could import and use the Loguru's `logger` directly, as in your second `print_log.py` example.

In a future release of Loguru, I'll provide a `logger.reinstall()` method to make it more convenient.

**Comment by 212413616** [comment]
> Hey @212413616. 嘿 。
> 
> Thanks for the comprehensive example. I agree with you that the suggested workaround for `multiprocessing` is not convenient at all.感谢您提供全面的示例。我同意你的观点，建议的`multiprocessing`解决方法根本不方便。
> 
> A much simpler alternative is to simply mutate the `logger` itself, using a trick described here: #818一个更简单的替代方案是使用此处描述的技巧简单地改变`logger`本身： #818
> 
> That means you could update your code as follow:这意味着您可以按如下方式更新代码：
> 
> ```python
> # main.py
> 
> from multiprocessing import Pool
> 
> from loguru import logger
> 
> from workers_a import WorkerA
> 
> def update_global_logger(logger_):
>     logger.__dict__ = logger_.__dict__.copy()
> 
> if __name__ == "__main__":
> 
>     logger.remove()
>     format = "<green>{time:YYYY-MM-DD HH:mm:ss,SSS}</green> - <level>{level:<8}</level> - <magenta>{process}</magenta>:<yellow>{thread}</yellow> - <cyan>{name}</cyan>:<cyan>{function}</cyan>:<yellow>{line}</yellow> - <level>{message}</level>"
>     logger.add("error.log", rotation="5 MB", format=format, enqueue=True)
> 
>     with Pool(4, initializer=update_global_logger, initargs=(logger,)) as pool:
>         pool.map(WorkerA.work, ["hello"])
> ```
> 
> After that, you could import and use the Loguru's `logger` directly, as in your second `print_log.py` example.之后，您可以直接导入并使用 Loguru 的`logger` ，如第二个`print_log.py`示例中所示。 One caveat of this solution is that the loggers created with `logger.bind()` won't be affected. Therefore, you have to be careful.此解决方案的一个警告是，使用`logger.bind()`创建的记录器不会受到影响。因此，你必须小心。
> 
> In a future release of Loguru, I'll provide a `logger.reinstall()` method to make it more convenient.在 Loguru 的未来版本中，我将提供`logger.reinstall()`方法以使其更加方便。

你太棒了，牛逼
