### ISSUE TITLE
how i can split log file based on logging level ?

### ISSUE THREAD

**Issue by mosi-kha** [Delgan/loguru#125]
hi 
how I can split a log file based on logging level?
for example, I want to `error` level save in `error.log` and just `debug` level save in `debug.log` ...
thanks :)

**Comment by Delgan** [comment]
Hi @mosi-kha. :)

I'm not sure this is the intended usage for logging level (generally it's more like "show DEBUG and all higher to developer, show INFO and all above to user"), but this is totally doable using `filter` (only logs passing the function will be propagated to the sink):

```python
logger.add("error.log", filter=lambda record: record["level"].name == "ERROR")
logger.add("debug.log", filter=lambda record: record["level"].name == "DEBUG")
```

**Comment by mosi-kha** [comment]
thanks ❤🌹

**Comment by Delgan** [comment]
Your welcome. :wink:
