### ISSUE TITLE
Can suppress better_exceptions functionality in a block of code that handles passwords?

### ISSUE THREAD

**Issue by jsaponara** [Delgan/loguru#1253]
Is it possible to write a contextmanager to suppress better_exceptions/diagnose=True functionality in a block of code that is handling sensitive info, in order to avoid (for example) passwords showing up in the log?

**Comment by Delgan** [comment]
That's not possible out of the box. You would need to implement a custom exception formatter: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).

I advise to disable `diagnose` in production.

**Comment by jsaponara** [comment]
Thanks!
