### ISSUE TITLE
How to simply change the format of the default sink?

### ISSUE THREAD

**Issue by Lawouach** [Delgan/loguru#126]
Hi,

Thank for your loguru, I appreciate it's goals and API. Quite modern.

However, as a new user, I find it doesn't seem well documented for simple things. For instance:

```$ python
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from loguru import logger
>>> logger.info("hello")
2019-08-13 13:16:38.312 | INFO     | __main__:<module>:1 - hello
```

I couldn't find a simple way to change the default format of the log. I saw the `configure` method but it's not clear if it works on the pre-defined logger? It also doesn't seem clear to me how to modify something that was set by default.

Sorry for this stupid question then but, how to change the format of the default logger?

**Comment by dragoscirjan** [comment]
@Lawouach You have this in the gif example from the project homepage:

```python
logger.remove()
logger.add(sys.stdout, format=">> <lvl>{message}</lvl>", level="INFO")
```

**Comment by Lawouach** [comment]
Thanks!

I must admit, I was looking in the README not in the gif in the README :D 
My bad.

Thanks a lot!

**Comment by Delgan** [comment]
Thanks @dragoscirjan for answering @Lawouach. :smile: 

There is a small mention to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) in the Readme, but this is true that this is maybe not very explicit.
