### ISSUE TITLE
How can I catch global exceptions without @logger.catch

### ISSUE THREAD

**Issue by VitorCioletti** [Delgan/loguru#127]
I'm trying to log unhandled exceptions using `sys.excepthook`, however, it is not called when an error is raised in another module. Im suspecting of this library because when I use `logging` everything works fine.

OBS: I am using asyncio with uvloop.

```py
from loguru import logger
import sys

logger.remove()

logger.add(sys.stderr, level='DEBUG')
logger.add('log/mylog{time}_.log', backtrace=True, diagnose=True, level='DEBUG', rotation='23:59', retention=10)

sys.excepthook = lambda type, exception, traceback: (
    logger.exception('error')
)

try:
    run_my_udp_asyncio_uvloop_endpoint()
except Exception e:
    logger.exception(e)
```
What am I missing here?

Thanks.

**Comment by Delgan** [comment]
Hi @VitorCioletti.

If you have a fully reproducible code sample it could help, but from what I see maybe you could try to replace `logger.exception('error')` with `logger.opt(exception=(type, exception, traceback)).error('error')`?

**Comment by VitorCioletti** [comment]
Of course!

I have figured out that when raising `BaseException` instead of `Exception`, `excepthook`is normally called. Maybe my problem has nothing to do with your lib.

`pip install uvloop`
`pip install loguru``

```py
from asyncio import set_event_loop, get_event_loop
from loguru import logger
import sys
import uvloop

# Handle connections and received messages
class events:
    def connection_made(self, transport):
        self.transport = transport

    def datagram_received(self, data, _):
        print(f'Received: {data.decode()}')

        raise Exception('Hi.')

# Configuring loguru
logger.remove()

logger.add(sys.stderr, level='DEBUG')
logger.add('log/configurador_{time}_.log', backtrace=False, diagnose=False, level='DEBUG', rotation='12:02', retention=4)

# Handle global exceptions
sys.excepthook = lambda tipo, excecao, traceback: (
    logger.exception(excecao)
)

# Configuring Uvloop loop in Asyncio
set_event_loop(uvloop.new_event_loop())
loop = get_event_loop()
loop.run_until_complete(loop.create_datagram_endpoint(events, local_addr=("127.0.0.1", 5000)))

# Start listening
print('Server initialized.')
loop.run_forever()
```

If you are on linux or mac, you can `nc -u 127.0.0.1 5000` to send messages to an UDP server.

Thanks for helping.

**Comment by VitorCioletti** [comment]
Totally my fault.

`loop.set_exception_handler` solves the probleme. Not loguru`s fault...

 Sorry for opening an issue for that.

**Comment by Delgan** [comment]
Ok, great you figured this out! :smile:
