### ISSUE TITLE
multithread log error with TimedRotatingFileHandler

### ISSUE THREAD

**Issue by shuxp** [Delgan/loguru#13]
I am using logging now and I have many threading, which all log to a log file.
If not using TimedRotatingFileHandler, everything fine.
If using TimedRotatingFileHandler, wich will cause error at the rotate time.
So I want to know whether loguru can solve this problem?

**Comment by Delgan** [comment]
Hey @shuxp 

Could you please provide me an example of your code not working?
Also, do you have the stacktrace or errors messages please?

I don't have extensvely tested `loguru` with `logging.Handler`, thank you for taking the time to report the issue, I will investigate this for sure.

**Comment by Delgan** [comment]
Ok, re-reading this I see that I slightly misunderstood your issue.

I'm sure that `loguru` can solve your problem, but I'm also sure that a proper use of `TimedRotatingFileHandler` using the standard `logging` module should not cause errors!

Unfortunately, it's complicated to help you without a code sample that would trigger the error.

**Comment by Delgan** [comment]
Thanks for the code snippet.

> each of my code use an instance of this function, including some extended threads.

Do you mean that you call `handler = logging.TimedRotatingFileHandler ("app.log")` and `root.addHandler(handler)` **multiple times** in your code?

If that is the case, that would be a problem. You should add the rotating handler only once, and then in your call just call `logger = logging.getLogger(name)`.

**Comment by shuxp** [comment]
> Thanks for the code snippet.
> 
> > each of my code use an instance of this function, including some extended threads.
> 
> Do you mean that you call `handler = logging.TimedRotatingFileHandler ("app.log")` and `root.addHandler(handler)` **multiple times** in your code?
> 
> If that is the case, that would be a problem. You should add the rotating handler only once, and then in your code just call `logger = logging.getLogger(name)`.

OK, I will try it now. thanks a lot.
