### ISSUE TITLE
How to suppress the exceptions occured in notifiers?

### ISSUE THREAD

**Issue by jithurjacob** [Delgan/loguru#130]
Hi,

I've configured Slack notification for exceptions occured in the application(code below). The integration is working really well. But when I'm running the application on my system without internet the underlying notifier is throwing network error, which is expected. However I would like to suppress these errors occuring in notifier handler. I tried with catch flag in logger.add but didn't get desired result. Is there any functionality to suppress them?

` from notifiers.logging import NotificationHandler
    handler = NotificationHandler("slack", defaults={"webhook_url": SLACK_WEBHOOK_URL})
    logger.add(handler, level="ERROR")
    `

**Comment by Delgan** [comment]
Hey @jithurjacob. :)

I think you have to manually catch possible exception using a custom sink function, like this for example:

```python
def send_slack_message(message):
    notifier = notifiers.get_notifier('slack')
    try:
        notifier.notify(webhook_url=SLACK_WEBHOOK_URL, message=message) 
    except Exception:
        pass

logger.add(send_slack_message, level="ERROR")
```

Alternatively, maybe can you test for connectivity before adding the Slack's handler, or using a command line flag to disable it:

```python
if network_connected() and "--no-slack" not in sys.argv:
    handler = NotificationHandler("slack", defaults={"webhook_url": SLACK_WEBHOOK_URL})
    logger.add(handler, level="ERROR")
```

The `catch` argument only controls whether the exception should be handled by printing a error message on `stderr` or propagated to the caller (and likely killing your application).

**Comment by Delgan** [comment]
@jithurjacob Are you satisfied with this solution?

**Comment by jithurjacob** [comment]
Yes., thank you
