### ISSUE TITLE
logger.error and logger.exception not displaying traceback and type

### ISSUE THREAD

**Issue by VitorCioletti** [Delgan/loguru#134]
Hi,

How to I correctly log errors using loguru?

I'm receiving an exception from `sys.excepthook` and calling `logger.error` to log it, however, loguru only displays its message. The thrown exceptions have values in `__traceback__`.

I've look into the docs but found no example on how to correctly use `.error` or `.exception`.

I was wondering on how to manually pass type and traceback as parameters but its useless since the library already does that.
```python
        if exception:
            if isinstance(exception, BaseException):
                type_, value, traceback = (type(exception), exception, exception.__traceback__)
            elif isinstance(exception, tuple):
                type_, value, traceback = exception
            else:
                type_, value, traceback = sys.exc_info()
            exception = ExceptionRecattr(type_, value, traceback)
        else:
            exception = None
```

Thanks.

**Comment by Delgan** [comment]
Hey. :)

The `error()` method just write a message with severity level `"ERROR"`, like the other ones. Using `exception()` would also add the traceback but only if you are currently catching an exception in a `except` block.

If you want to manually log an exception with any level you want, you can make use of the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method with the `exception` argument:

```python
exception = sys.exc_info()
logger.opt(exception=exception).info("Logging exception traceback")
```

**Comment by VitorCioletti** [comment]
It worked. Thanks.
