### ISSUE TITLE
integrating loguru with Flask and/or Celery loggers

### ISSUE THREAD

**Issue by havok2063** [Delgan/loguru#137]
I really like loguru and it simplifies my whole setup.  I have a hacked custom `Logger` that I use in my code and Flask webapps.  I'd like to replace it with loguru, since it basically does the things I hacked.  What's the procedure to properly integrate loguru into other apps that might have loggers based on the standard logger?  

This is what I've done to integrate `loguru` into my code and Flask web app, and the error I am getting.

```
#Function to initialize a loguru logger
def initLog(logpath):
    ''' test loguru '''
    from loguru import logger
    import sys
    import logging

    logger.add(sys.stderr, format="{level} | {message} ",
               level="INFO", colorize=True, enqueue=True, backtrace=True)

    fmt = "{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message} [{function} @ {file}]"
    logger.add("logtest.log", rotation='10 seconds', format=fmt,
               colorize=True, backtrace=True, enqueue=True)

    new_level = logger.level("IMPORTANT", no=25, color="<magenta>")

    # capture warnings
    showwarning_ = warnings.showwarning

    def showwarning(message, *args, **kwargs):
        logger.warning(message)
        showwarning_(message, *args, **kwargs)

    warnings.showwarning = showwarning

    # propagate to standard logger
    class PropagateHandler(logging.Handler):
        def emit(self, record):
            logging.getLogger(record.name).handle(record)

    logger.add(PropagateHandler(), format="{message}")

    return logger
```

Then I'm trying to integrate it into my Flask webapp 

```
log = initLog('testlog.log')

app = Flask()
# add custom logger to the Flask app
app.logger.addHandler(log)

# use the Flask logger to log messages
app.logger.info('Loading Development Config!')
```
but I get the following error:
```
    app.logger.info('Loading Development Config!')
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1375, in info
    Log 'msg % args' with severity 'INFO'.
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
TypeError: '>=' not supported between instances of 'int' and 'method'
```
What's the correct way to integrate loguru into other libraries like Flask or Celery?

**Comment by Delgan** [comment]
Hey @havok2063.

I think a confusion between "handler" and "logger" may explain the error you are seeing. The logger is a basic object to use when you want to write a log message. Handlers are objects which are in charge or receiving this log messages, and processing adequately: write it on `stderr`, write it in a file, send it by email, etc.

A logger has methods like `.info()`, `.debug()` and `.warning()` while an handler has methods like `.write()` and `.emit()`.

So, when you use `app.logger.addHandler(log)`, you pass a logger object while Flask expects an handler, hence bug occurs. :smile: 

Maybe you can try to use an `InterceptHandler()` instead, which should send Flask's logs back to Loguru's handlers:

```
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Retrieve context where the logging call occurred, this happens to be in the 6th frame upward
        logger_opt = logger.opt(depth=6, exception=record.exc_info)
        logger_opt.log(record.levelno, record.getMessage())
handler = InterceptHandler()
handler.setLevel(0)
app.logger.addHandler(handler)
```
```

**Comment by havok2063** [comment]
@Delgan Thanks for the update.  That makes sense, and that code block works.  I got confused since I'm using a custom `Logger` class but when I passed it into Flask's `app.logger.addHandler` it seemed to parse it correctly, and extract the handlers within it.  So I assumed it could do that generally.  

Currently it seems like `loguru` is slower compared to the standard logging.  What's the status on when `loguru` will move to use C-code instead?

**Comment by Delgan** [comment]
> Thanks for the update. That makes sense, and that code block works. I got confused since I'm using a custom Logger class but when I passed it into Flask's app.logger.addHandler it seemed to parse it correctly, and extract the handlers within it. So I assumed it could do that generally.

Oh, I did not knew that. As Loguru's logger does not inherit from standard one, this could not work, but this is maybe not explicitly stated in tge Loguru documentation.

> Currently it seems like loguru is slower compared to the standard logging. What's the status on when loguru will move to use C-code instead?

Honestly, I did not expect that it take so much time to develop Loguru once it has been published! I was think that the C implementation could come in the few weeks or months after the initial release. Considering how bad I am at estimating required development time, I can hardly give you any reliable indication.

However, most of requested features and reported bugs since the beginning has been solved. The API is quite stable, I have a few more features to implement, but then I hope I could start working on the performance side. No ETA I could share, though, sorry.

**Comment by cyberic99** [comment]
> Currently it seems like loguru is slower compared to the standard logging. What's the status on when loguru will move to use C-code instead?

@havok2063 how did you bench?

**Comment by havok2063** [comment]
@cyberic99 Not in any systematic manner.  I timed the import of my main package, which currently prints a fair number of warnings from numpy and other packages as I import them.  My package, when using the standard logger,  takes ~4-5 seconds to import.  By eye, you can see the print messages scroll by quite fast.  When using `loguru`, the import time increases to ~11-15 seconds, and the log messages scroll by at a much slower rate.  

My package also runs as Flask web application.  The time to start up the application is also slowed down similarly when I switch to `loguru`.

@Delgan Thanks for the update.  My two cents is the C implementation should be a top priority as that would definitely help people switch over to using this logger as a standard.  It really is much simpler to enable and implement.

**Comment by Delgan** [comment]
I'm closing this since it seems I answered the initial question. Be sure that I will work on the C implementation as soon as possible. :smile:
