### ISSUE TITLE
WatchedFileHandler analog in loguru?

### ISSUE THREAD

**Issue by Yolley** [Delgan/loguru#139]
I want to use logrotate to rotate my logs, therefore in logging module I use WatchedFileHandler, so, when my logs are rotated, logging can just create new file, is it possible to achieve the same thing with loguru?

**Comment by Delgan** [comment]
You probably figured this out, but to potential reader: Loguru should work fine with `WatchedFileHandler` used as a sink (like any other `logging`'s handler class).
