### ISSUE TITLE
Async Version

### ISSUE THREAD

**Issue by HarveySummers** [Delgan/loguru#14]
It would be great if we could "fire & forget" log entries using an async handler that uses a seperate thread or process with options to guarantee order, commit,  performance (lazy write) and/or confirmation that the write was completed.

**Comment by Delgan** [comment]
Hello @HarveySummers. What do you think of the current `enqueue` option which does just that: run a separate thread where are send and processed log entries according to the configured handler?

**Comment by Delgan** [comment]
I'm closing this as I think the `enqueue` option answers the question.

If this is not the case, feel free to re-open it. 😉

**Comment by HarveySummers** [comment]
Sorry for the late response - but yes, it does. Thanks!

**Comment by Patchouli-CN** [comment]
wow, it's seven years....
