### ISSUE TITLE
Get relative file.path

### ISSUE THREAD

**Issue by wlgrd** [Delgan/loguru#141]
First, THANK YOU! This is amazing!

Also, I would love a way to get the relative path from `{file.path}`, as it is clogging up my console with absolute, but it is amazing to be able to just ctrl+click my way to the spot where the log was called.

**Comment by Delgan** [comment]
My pleasure. :)

I think `{file.path}` should already display the file path relative to your current working directory. See:

![2019-09-17-195304_1920x1080_scrot](https://user-images.githubusercontent.com/4193924/65066525-ca08de00-d984-11e9-8abb-451c080c4500.png)

It's surprising that the behavior differs for you. Do you have more information?

**Comment by Delgan** [comment]
@wlgrd As I'm re-reading this issue, I realize I may have misunderstood you the first time.

Is is a problem with `{file.path}` displaying an absolute path, or a feature request to make such file path clickable?

**Comment by wlgrd** [comment]
That is weird. In my case, when using `{file.path}`, it displays the absolute path do the file, _not_ the relative. My format is 

```
TRACE_LOG_FORMAT = (
    "<yellow>{thread.name}</yellow> | "
    "<green>{time:HH:mm:ss.SS}</green> | "
    "<level>{level: <8}</level> | "
    "<cyan>{file.path:}</cyan>:<cyan>{line:}</cyan> - <level>{message}</level>"
)
```
which will display something like `MainThread | 09:31:20.01 | ERROR    | /home/wlgrd/work/logging/main.py:35 - "Failed to get thing"`

**Comment by Delgan** [comment]
No problem. ;)
Is it ok to close this issue then?

**Comment by wlgrd** [comment]
of course =)
