### ISSUE TITLE
only log into files

### ISSUE THREAD

**Issue by yfyvan** [Delgan/loguru#142]
I just want to write records to my log files ,but i don't want to see them on console, how should i do with loguru - -

**Comment by Delgan** [comment]
For convenience, Loguru automatically `add()` a default handler which logs to `stderr`, so you can simply import the `logger` and immediately start using it with no setup needed.

If you don't want to use it, you can [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) it first before adding your file sinks.

```python
logger.remove()
logger.add("file.log")
```

**Comment by yfyvan** [comment]
(^_^) thank u very much !

**Comment by Delgan** [comment]
You're welcome. :)
