### ISSUE TITLE
Separate formatting into a public class

### ISSUE THREAD

**Issue by clafoutis42** [Delgan/loguru#143]
Hi!

I would like to implement a formatting class that would display the extras like in the go library [sirupsen/logrus](https://github.com/sirupsen/logrus).  
I can manage to do it with a custom handler that I pass as a sink. However I can not apply the colors as I receive an already formatted message (what I mean is I can't do `<level>{key}=</level>{value}` as it is actually already parsed, and don't really want to spend time coding this as it is actually, in some ways, already done but simply inaccessible 😅). 

I think it's a shame, and would find great to be able to do something like:
```
class CustomFormatter(LoguruFormatter):
# ...
# ...
```

Or may be is there already a way to format the extras in a fancy way (other that the `{"key": value}` format, which I find kinda ugly), but I did not find it (if so I'm sorry 🙊)

**Comment by Delgan** [comment]
Hi @clafoutis42 (God, I'm hungry now!). :)

I think you could use a custom `format` function to arrange log formatting at your convenience, right?

Maybe something like this for example:

```python
from loguru import logger
import sys

def format(record):
    extra = " ".join('<lvl>%s</>=%s' % item for item in record["extra"].items())
    return "<lvl>{level: <8}</> <g>{time}</> {message: <20} " + extra + "\n"

logger.remove()
logger.add(sys.stderr, format=format)

logger = logger.bind(foo=123, bar="baz")

logger.info("Ok!")
logger.warning("Right?")
```

Instead of using a static `format`, passing a function permits to dynamically configure it according to each logged message.

**Comment by clafoutis42** [comment]
Wow thanks, I did not think of doing that way, this is really easier that I thought!  
And now I understand a little better the way you format and colorize the logs :+1:

Thank you very much!

Sorry for making you hungry 😁 

I'm closing this issue as my problem is solved :)

Thanks a lot for this library and keep up the good work :+1:
