### ISSUE TITLE
How to settting multi loggers for logging into different files (Maybe the same level)?

### ISSUE THREAD

**Issue by VinceWg** [Delgan/loguru#145]
I wanna to initialize multi loggers that can log into different logfile, for example, access.log[Level: INFO], info.log[Level: INFO], error.log[Level: ERROR], but now, it always logs into all files.

**Comment by Delgan** [comment]
I think you need to combine the usage of `.bind()` and `filter`, something like this:

```python
logger_a = logger.bind(name="a")
logger_b = logger.bind(name="b")
logger.add("file_a.log", filter=lambda record: record["extra"].get(name) == "a")
logger.add("file_b.log", filter=lambda record: record["extra"].get(name) == "b")

logger_a.info("Sent solely to file A")
logger_b.info("Sent solely to file B")
```

This is a little cumbersome. This is why in the next release, I planned to slightly refactor the `logger` so one can actually use multiple truly independent loggers.

**Comment by VinceWg** [comment]
Great, thank u.

**Comment by Delgan** [comment]
You're welcome. :+1:
