### ISSUE TITLE
Is it possible to only include the ISO-8601 date in the log file name and only have "daily" logs?

### ISSUE THREAD

**Issue by jayBana** [Delgan/loguru#146]
I am trying to if there are any further formatting options for `time` when doing:

```python
logger.add("output_{time}.log"
```

I have managed to find the `FileDateFormatter` class in`_file_sink.py`, but it is not clear to me how can I pass in anything to `datetime` argument in the constructor.

**Comment by Delgan** [comment]
You can use [date formatter](https://loguru.readthedocs.io/en/stable/api/logger.html#time) in the filename too:

```python
logger.add("output_{time:YYYY-MM-DD}.log")
```

Would that work for your use case?

**Comment by Delgan** [comment]
@jayBana Does that solve your problem?

**Comment by jayBana** [comment]
Yes, it does. Thank you.

**Comment by modaye** [comment]
非常棒
