### ISSUE TITLE
PyPi raw directive

### ISSUE THREAD

**Issue by azzamsa** [Delgan/loguru#149]
Sorry this is merely a question on how `loguru` published to PyPi. I know that PyPi prevent us from using `raw` directive, saying:

```bash
$ twine check dist/*
Checking dist/mypackage-0.1.0-py2.py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 1: Warning: "raw" directive disabled.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
Checking dist/mypackage-0.1.0.tar.gz: FAILED
  `long_description` has syntax errors in 
```

Some of the error solved, by adding `long_description_content_type="text/x-rst",`:

```bash
$ twine check dist/*
Checking dist/mypackage-0.1.0-py2.py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 1: Warning: "raw" directive disabled.
Checking dist/mypackage-0.1.0.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 1: Warning: "raw" directive disabled.
```

We can't upload the package while these errors still exists:

``` bash
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: The description failed to render for 'text/x-rst'. See https://test.pypi.org/help/#description-content-type for more information. for url: https://test.pypi.org/legacy/
```

---

How come `loguru` solve this problem? 

I see the [README](https://raw.githubusercontent.com/Delgan/loguru/master/README.rst) file still use `:raw` but the [README](https://pypi.org/project/loguru/#modal-close) pypi files use `.. image`.

I can't find where the magic happened ? do you replace/convert the readme before pushing to pypi?

Thanks a lot.

**Comment by Delgan** [comment]
Ha ha, no magic involved here.

>  do you replace/convert the readme before pushing to pypi?

That's it. :smile: 

I have a `PYPIREADME.rst` file on my local repository, and I use it to modify `README.rst` whenever I need to publish a new release. Sadly, PyPI is quite limited regarding raw directives, so I have to keep two slightly modified versions of the same file. I would be interested to know it if you find a more elegant solution. ;)

**Comment by azzamsa** [comment]
> That's it. smile

:) :)

I thought the same, and I did it yesterday.

Some "advance" solution are there, e.g convert raw content to rst, append to file then, replacing with script. But I think replacing it manually by hand is easier and enough for me (for now).

If you automated this process later, please inform us in this thread. So we can adopt more elegant way :)

Thanks for loguru.

**Comment by Delgan** [comment]
_5 years later..._

Finally fixed by migrating the README from reStructuredText to GitHub Flavored Markdown and using `myst-parser` for the Sphinx docs.

Reference: ef12cbbaf54fb2e64ca66b0a90675cdf9e8a522f

**Comment by azzamsa** [comment]
> 5 years later...

🤣 

> Finally fixed by migrating the README from reStructuredText to GitHub Flavored Markdown and using myst-parser for the Sphinx docs.

Yes, I was inspired by this project to use RST for the documentation, but I have since been migrating everything to GFM. :)

Thanks for Loguru 🍞
