### ISSUE TITLE
Enable suppression of DEBUG messages on default logger

### ISSUE THREAD

**Issue by joshuaellinger** [Delgan/loguru#15]
I don't want the default logger to show DEBUG messages on the console in my scripts.

I see that I could just change the min level by going:
    logger._min_level = 20
but I hate to touch the internals.

If there is a supported way to do this, I didn't see it in the docs.

**Comment by Delgan** [comment]
Hi @joshuaellinger.

Indeed, better not touch `logger._min_level`, that's actually not related to your problem (it's the global minimum level of all handlers, used for optimization to avoid to create useless log records).

If you don't like the default level of the pre-configured handler, you should [set an environment variable](https://loguru.readthedocs.io/en/stable/api/logger.html#env) adequately. 

For example, supposing that you are on Linux and you would want the minimum level to be "INFO", just do `export LOGURU_LEVEL="INFO"`.

Alternatively, if you want to log to `stderr` with a "INFO" level for only one of your script, you probably should remove the default handler and configure a new one which fits your needs: `logger.remove(0); logger.add(sys.stderr, level="INFO", ...)` (or you could use `.configure()` too).

**Comment by joshuaellinger** [comment]
Thanks -- that works.
