### ISSUE TITLE
Change color of {LEVEL} depending on the level

### ISSUE THREAD

**Issue by 0blio** [Delgan/loguru#150]
Hi,

congratulations for making such a great library.
I'm testing it right now and I want to use it for my upcoming projects.

I don't need it for advanced usage but just for writing on the stdout.

I need to change the {LEVEL} color depending on the level, so I wrote this code.

```python
import sys
from loguru import logger

logger.remove()
logger.add(sys.stdout, colorize=True, format="[<fg #66a3ff>{time:YYYY-MM-DD HH:mm:ss}</fg #66a3ff>] [<fg #00ff00>{level}</fg #00ff00>] {message}")
logger.info("test")
logger.error("TEST")
```

I need {LEVEL} to be red in case the method **error** is being used, yellow for **warning** etc. etc.

I just read the whole documentation but I can't find a way to make it work.
How can I do that?

**Comment by Delgan** [comment]
Hi @0blio. ;)

Yeah, this is possible using the special `<level>` [markup tag](https://loguru.readthedocs.io/en/stable/api/logger.html#color):

```
logger.add(sys.stdout, format="[{time}] [<level>{level}</level>] {message}")
```

The `<level>` tag is automatically converted to the corresponding configured level's color. If needed, ou can update it using the `[.level()`](https://loguru.readthedocs.io/en/stable/api/logger.html#color) method:

```python
logger.level("INFO", color="<red>")
```

**Comment by 0blio** [comment]
Ok! It is working like a charm.
Thanks so much.
