### ISSUE TITLE
Using Markup Within Messages

### ISSUE THREAD

**Issue by hanyoonLDA** [Delgan/loguru#151]
Is it possible to use markup within logger messages themselves? For example, `logger.info("This does not make <b>this text bold</b>")` obviously does not parse the markup correctly. 

Any way around it?

Thanks :)

**Comment by Delgan** [comment]
Yes it is! You can use the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method with the `ansi` attribute:

```python
logger.opt(ansi=True).info("This makes <b>this text bold</b>")
```

**Comment by hanyoonLDA** [comment]
@Delgan Thank you!
