### ISSUE TITLE
why it will print twice times, everytime the printed log were different

### ISSUE THREAD

**Issue by policeme** [Delgan/loguru#152]
![image](https://user-images.githubusercontent.com/30991932/66623423-2e365f00-ec1e-11e9-96c1-4220396e901d.png)
![image](https://user-images.githubusercontent.com/30991932/66623425-32627c80-ec1e-11e9-8dee-dd290bca4c8b.png)

**Comment by policeme** [comment]
@Delgan

**Comment by Delgan** [comment]
For convenience, a default handler logging to `sys.stderr` is automatically added to the `logger` while you import it.

You did not [`.remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) this default handler, but you added another one logging to `sys.stdout`, which creates duplicate.

Try to call `logger.remove()` right before all of your `.add()` calls, this should fix your problem.

**Comment by policeme** [comment]
I don't want use the format of the log, but I want to use  some parts of default log format original color, how to use?

**Comment by policeme** [comment]
![image](https://user-images.githubusercontent.com/30991932/66627860-89248200-ec2f-11e9-9d15-1d847f0d3a04.png)

**Comment by policeme** [comment]
all right, I found the solution, thx for you answering.

**Comment by policeme** [comment]
I don't want to write the INFO level log to DEBUG log file, how to do this

**Comment by policeme** [comment]
I want to create different loguru instance, but in your project, whatever I do, the loguru instance always only one, is there any ways to do this?

**Comment by policeme** [comment]
@Delgan

**Comment by Delgan** [comment]
You need to use different `filter` for each of your added handlers:

```python
logger.add("debug.log", filter=lambda record: record["level"].name == "DEBUG")
logger.add("info.log", filter=lambda record: record["level"].name == "INFO")

logger.debug("Debug messages go to the debug file")
logger.info("Info messages go to the info file")
```

**Comment by RoniFinTech2** [comment]
Hi,

How do I do this if I don't have a file?

```
 logger.add(sys.stderr, format="<yellow>{extra[trace_id]}</yellow> "
                                      "<blue>{time}</blue> "
                                      "<yellow>[{level}]</yellow> "
                                      "message=<green>{message}</green> ", colorize=True)

        logger.add(sys.stderr, format="<yellow>{extra[trace_id]}</yellow> "
                                      "<blue>{time}</blue> "
                                      "<yellow>[{level}]</yellow> "
                                      "message=<green>{message}</green> "
                                      "error={extra[error]}", colorize=True, level="ERROR")
```
I need a specific logger for the EROR level

**Comment by RoniFinTech2** [comment]
> Hi,
> 
> How do I do this if I don't have a file?
> 
> ```
>  logger.add(sys.stderr, format="<yellow>{extra[trace_id]}</yellow> "
>                                       "<blue>{time}</blue> "
>                                       "<yellow>[{level}]</yellow> "
>                                       "message=<green>{message}</green> ", colorize=True)
> 
>         logger.add(sys.stderr, format="<yellow>{extra[trace_id]}</yellow> "
>                                       "<blue>{time}</blue> "
>                                       "<yellow>[{level}]</yellow> "
>                                       "message=<green>{message}</green> "
>                                       "error={extra[error]}", colorize=True, level="ERROR")
> ```
> 
> I need a specific logger for the EROR level

Got it...
added `filter=lambda record: record.get('level').no < logger.level('ERROR').no,` to one and 
`filter=lambda record: record.get('level').no == logger.level('ERROR').no,` to the other
