### ISSUE TITLE
Custom format function hides exception logging

### ISSUE THREAD

**Issue by clafoutis42** [Delgan/loguru#156]
Hi!  
I noticed that when I use a custom format function, the exception trace does not show as it would if I simply passed a format string.  
Is this a wanted behavior? If so is there anything I can do to get the error trace back (other than implementing a different sync for the exceptions)?  
Or is there anything I am doing wrong?

Current behaviour:
```
In [20]: logger.add(sys.stdout, format=_custom_format, backtrace=True, diagnose=True)
    ...:
    ...: def func(a, b):
    ...:     return a / b
    ...:
    ...: def nested(c):
    ...:     try:
    ...:         func(5, c)
    ...:     except ZeroDivisionError:
    ...:         logger.exception("What?!")
    ...:
    ...: nested(0)
ERRO[19/10 20:41] What?!
```

Wanted behaviour:
```
In [18]: logger.add(sys.stdout, format=_custom_format, backtrace=True, diagnose=True)
    ...:
    ...: def func(a, b):
    ...:     return a / b
    ...:
    ...: def nested(c):
    ...:     try:
    ...:         func(5, c)
    ...:     except ZeroDivisionError:
    ...:         logger.exception("What?!")
    ...:
    ...: nested(0)
ERRO[19/10 20:40] What?!
Traceback (most recent call last):
... # (truncated for lisibility)
  File "<ipython-input-18-ca46b2fcd434>", line 12, in <module>
    nested(0)
    └ <function nested at 0x110a623b0>
> File "<ipython-input-18-ca46b2fcd434>", line 8, in nested
    func(5, c)
    │       └ 0
    └ <function func at 0x11081fef0>
  File "<ipython-input-18-ca46b2fcd434>", line 4, in func
    return a / b
           │   └ 0
           └ 5

ZeroDivisionError: division by zero
```

The `_custom_format` function:
```python3
def _custom_format(record):
    extra = " ".join(f"<lvl>{key}</>={value}" for key, value in record["extra"].items())
    return (
        "<lvl>{level:.4}</><blue>[{time:DD/MM HH:mm}]</blue> {message: <20} "
        + extra
        + "\n"
    )
```

_Notice that the format string alone allows me to see the trace, however I can't compute the extras I want to display._

If there is anything more you need to diagnose this, I would be happy to provide it to you.

Thanks!

**Comment by Delgan** [comment]
Hi. :slightly_smiling_face: 

> Is this a wanted behavior?

Yes, while using a custom `format` function, the user gains full control over logs formatting. This means that you have to manually add `{exception}` at the end of the returned format, the same way that you had to manually add the `"\n"` while those are automatically added when `format` is a string. This is shortly explained in the documentation: [The logged message](https://loguru.readthedocs.io/en/stable/api/logger.html#message)

**Comment by clafoutis42** [comment]
Alright, thanks a lot!  
I clearly missed that while looking for a solution 😅 

Thanks again for this great library, keep up the good work 👍  
Have a great night (or day, depending on the timezone)!

**Comment by Delgan** [comment]
Thanks! 

Bonne soirée à toi aussi... :stuck_out_tongue:
