### ISSUE TITLE
Logging error in Loguru Handler

### ISSUE THREAD

**Issue by brl0** [Delgan/loguru#159]
Perhaps unsafe characters could be escaped or simply replaced when this occurs?

```
Traceback (most recent call last):
  File "E:\py\flask\lib\site-packages\loguru\_handler.py", line 253, in _queued_writer
    self._writer(message)
  File "E:\py\flask\lib\site-packages\loguru\_logger.py", line 696, in writer
    write(m)
  File "E:\py\flask\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 272: character maps to <undefined>
```

**Comment by Delgan** [comment]
Hi @brl0.

What kind of sink did you precisely use? Logging to the `sys.stdout` console? Logging to a file?

I don't think this is Loguru's role to deal with strings encoding. If one needs to write unicode character better configure the handler to support utf8 encoding.

**Comment by brl0** [comment]
Logging to `sys.stdout`.  

If loguru wouldn't deal with string encoding, can you point me in the right direction for configuring a handler to support this scenario?  

Thanks for the great tool!

**Comment by Delgan** [comment]
This is a common problem with `sys.stdout` on Windows, see #124.

I will quote a comment I made at that time, because it perfectly apply to your problem. :smile: 


> I think you can either:
> 
> * Replace [`sys.stdout`](https://docs.python.org/3/library/sys.html#sys.stdout) with [`sys.stderr`](https://docs.python.org/3/library/sys.html#sys.stderr) (the later will escape faulty characters rather than raising exception)
> 
> * Set the [`PYTHONIOENCODING`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING) environment variable to `utf-8`
> 
> * Call [`sys.stdout.reconfigure()`](https://docs.python.org/3/library/io.html#io.TextIOWrapper.reconfigure) with `encoding='utf-8'` and / or `errors='backslashreplace'`

**Comment by brl0** [comment]
You are right, applied perfectly.  
`sys.stdout.reconfigure(encoding='utf-8', errors='backslashreplace')`
That did the trick.  
Thanks for your help, and thanks again for the great tool.

**Comment by Delgan** [comment]
You're welcome! Glad that solved your problem. :+1:
