### ISSUE TITLE
Multiprocessing workers use default handler

### ISSUE THREAD

**Issue by Danmou** [Delgan/loguru#160]
My program configures loguru to log to some files with a custom format string. However, when I log from inside a `multiprocessing.Process`, it only uses the loguru default stderr handler. How can I fix this?

**Comment by Delgan** [comment]
Yeah, this is a known problem with `multiprocessing` on Windows... Fortunately, this has been finally fixed a few days ago!

This is discussed in #108. Please, read the new documentation entry to better understand what will be the workaround and why it should be done like this: [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/latest/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)

The changes are not yet usable, they are only effective on the `loguru` development version. You will have to wait for the next version (`v0.4.0`) before being able to fully enjoy logging with `multiprocessing`. Hopefully, it should be published in the next week or so.
