### ISSUE TITLE
Recompile with Nuitka

### ISSUE THREAD

**Issue by NiksonBinsk** [Delgan/loguru#163]
Nuitka is great python to c compiler. Maybe you should compile library with it?

**Comment by Delgan** [comment]
Yeah, Nuitka is a great tool, it's a project I've been following for a while. The work that Kay Hayen has done almost on his own is very impressive.

However, Loguru is first and foremost a Python library, so it make little sense to include a Nuitka build in this repository. If people use Nuitka to compile their projects, they can include `loguru` to be compiled alongside, right?

Improving Loguru performances using C is something I planned, though. I wish to do this using the official Python C API. That way, people using CPython will benefits from the optimizations.

**Comment by Delgan** [comment]
I'm closing this issue as I plan to use straight [C Python API](https://docs.python.org/3/c-api/intro.html) rather than Nuitka.
