### ISSUE TITLE
Dynamic Named Loggers

### ISSUE THREAD

**Issue by obviousrebel** [Delgan/loguru#168]
Trying to switch over application to loguru as I need a multiprocessing logger. 

I have many base classes, classes, etc. Using the name attribute in the log format I get the name but I need to be able to dynamically change this when an object is instantiated with this class and given a name. Is there a preferred way to do this? 

Normally in all classes I had `logger = logging.getLogger(f"{name}_Controller")`...etc.

Loguru is great btw!

**Comment by obviousrebel** [comment]
dug into the documentation and saw the solution, apologies!

**Comment by Delgan** [comment]
Hey @obviousrebel, glad you like Loguru! :smile: 

I think you are maybe looking for [`.bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind), which could basically be used like `getLogger()`:

```python
logger = logger.bind(name=f"{name}_Controller")
```

The `record["extra"]` dict of each log emitted using the bound `logger` is populated with the keyword arguments passed to `.bind()`. So, you can use that to display the assigned name in your messages for example:

```python
logger.add("output.log", format="[{time}][{extra[name]}] {message}")
```

This would be more efficient that using the [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) method as it avoids the function call.

**Comment by obviousrebel** [comment]
@Delgan That will work! Thank you very much!

**Comment by obviousrebel** [comment]
Just a note, it seems you can't use "name" as an extra argument in bind.
`logger.bind(name=name)`
results in:
`KeyError: "Attempt to overwrite 'name' in LogRecord"`

**Comment by Delgan** [comment]
@obviousrebel Oups, I did not think about that. This happens while using a standard `logging.Handler`, because in such case some keywords are forbidden: [`logging/__init__.py#L1548-L1552`](https://github.com/python/cpython/blob/c6b20be85c0de6f2355c67ae6e7e578941275cc0/Lib/logging/__init__.py#L1548-L1552).
