### ISSUE TITLE
Data scrubbing

### ISSUE THREAD

**Issue by 360developer** [Delgan/loguru#17]
*sentry.io* (https://docs.sentry.io/data-management/sensitive-data/) comes with a nice way to scrub sensitive data (as stipulated by data privacy guidelines or regulations, such as the GDPR).

We are looking for a convenient way to hide/obfuscate sensitive data which can be enabled/disabled by configuration for staging/production environments.
We would like to use a predefined filter (identical to sentry.io) that allows customization, so we could add more filters to it.

**Comment by Delgan** [comment]
Hi @360developer, does a `filter` function would suit your needs?

However, the filtering process is not as easy that with Sentry.io, because logging mainly uses string messages.

This entirely depends on how you intend to log the sensitive data.

For example, if you planned to do something like:

```python
logger.info("It's ok, no sensitive data")
# Add "username" and "password" to the "extra" dict of each recorded log
user_logger = logger.bind(username="user", password="xyz) 
user_logger.info("Warning, sensitive data bound")
```

The filter function of your handler would look like:

```python
def scrub(record):
    forbidden = ["username", "password", "apikey"]
    for field in forbidden:
        if field in record["extra"]:
            return False
    return True

logger.add("file.log", filter=scrub)
```

Alternatively, you could decide which logs should be filtered-out while calling the logger function:

```python
logger.info("It's ok")
logger.bind(sensitive=True).info("Username is '{}' and password is '{}'", "user", "xyz")
```

And use a filter function like this:

```python
def scrub(record):
    if "sensitive" in record["extra"]:
        return False
    return True
```

I think I may need more examples about how you plan to use `loguru` to conditionally log sensitive data.

**Comment by Delgan** [comment]
If you need more support, feel free to re-open or comment this issue further. 👍

**Comment by 360developer** [comment]
@Delgan - thanks, your comment helped. We have to better structure the way we create the log entries. Then a filter does the job.

**Comment by fredrikaverpil** [comment]
@Delgan what about if I have something today for the standard library logging module:

```python
import logging
import re


class SensitiveFormatter(logging.Formatter):
    """Formatter that removes sensitive information in urls."""
    @staticmethod
    def _filter(s):
        return re.sub(r':\/\/(.*?)\@', r'://', s)

    def format(self, record):
        original = logging.Formatter.format(self, record)
        return self._filter(original)
```

Is it possible to mask parts of the log string like this using loguru?

**Comment by fredrikaverpil** [comment]
Ah, I realized now that I can probably use a formatter in loguru, where I modify the `record["message"]`:

From [the docs](https://loguru.readthedocs.io/en/stable/resources/recipes.html):
```python
class Formatter:

    def __init__(self):
        super().__init__(*args)
        self.padding = 0
        self.fmt = "{time} | {level: <8} | {name}:{function}:{line}{extra[padding]} | {message}\n{exception}"

    def format(self, record):
        length = len("{name}:{function}:{line}".format(**record))
        self.padding = max(self.padding, length)
        record["extra"]["padding"] = " " * (self.padding - length)
        return self.fmt

formatter = Formatter()

logger.remove()
logger.add(sys.stderr, format=formatter.format)
```

So likely something like this (haven't tried it):

```python
class Formatter:

    def __init__(self):
        super().__init__(*args, scrub_patterns=None)
        self.scrub_patterns = scrub_patterns
        self.fmt = "{time} | {level: <8} | {name}:{function}:{line} | {message}\n{exception}"

    def format(self, record):
        for search, replace in self.scrub_patterns.items():
            record["message"]= re.sub(search, replace, record["message"])
        return self.fmt

scrub_patterns = {r':\/\/(.*?)\@': r'://[REDACTED]@'}
formatter = Formatter(scrub_patterns=scrub_patterns)

logger.remove()
logger.add(sys.stderr, format=formatter.format)
```

Would this work, @Delgan ?

**Comment by Delgan** [comment]
Hi @fredrikaverpil. 

I would suggest adding a new attribute to the `extra` dict and use it in the format rather than replacing the `message` value. This can be a problem when `opt(colors=True)` is used. In general, it is better to avoid changing the attributes of the `record` because they may be used internally by `loguru`.

```python
class Formatter:

    def __init__(self, scrub_patterns=None):
        super().__init__()
        self.scrub_patterns = scrub_patterns
        self.fmt = "{time} | {level: <8} | {name}:{function}:{line} | {extra[scrubbed]}\n{exception}"

    def format(self, record):
        scrubbed = record["message"]
        for search, replace in self.scrub_patterns.items():
            scrubbed = re.sub(search, replace, scrubbed)
        record["extra"]["scrubbed"] = scrubbed
        return self.fmt
```

Using `stderr` over `stdout` is preferred for logging, I think. Quoting the documentaiton:

> As for standard logging, default logs are sent to `sys.stderr` rather than `sys.stdout`. The POSIX standard specifies that `stderr` is the correct stream for “diagnostic output”. The main compelling case in favor or logging to `stderr` is that it avoids mixing the actual output of the application with debug information. Consider for example pipe-redirection like `python my_app.py | other_app` which would not be possible if logs were emitted to `stdout`. Another major benefit is that Python resolves encoding issues on `sys.stderr` by escaping faulty characters (`"backslashreplace"` policy) while it raises an `UnicodeEncodeError` (`"strict"` policy) on sys.stdout.

**Comment by fredrikaverpil** [comment]
Allright, great!
Thanks for your feedback and thanks for this absolutely excellent project! 😃👍

**Comment by Delgan** [comment]
@fredrikaverpil Thank you too for those sweet words! :smile:

**Comment by durgeksh** [comment]
@Delgan When we have an exception in connecting to a service, we get all the credentials exposed.

Attaching the screenshot for your reference.
<img width="1680" alt="image" src="https://github.com/Delgan/loguru/assets/110120464/12bd1901-9881-49b2-9578-ea4d29db8d84">

**Comment by Delgan** [comment]
@durgeksh You should re-add your sink with `diagnose=False` or set the `LOGURU_DIAGNOSE` environment variable to `False`.
