### ISSUE TITLE
Is it possible to integrate loguru with gunicorn logger ?

### ISSUE THREAD

**Issue by suvojit-0x55aa** [Delgan/loguru#172]

**Comment by Delgan** [comment]
Yeah, that's surely possible. I don't know much about `gunicorn`, but depending on your use case you can rely on either `InterceptHandler()` or `PropagateHandler()` [as stated in the Readme](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging):

```python
# All standard logs are intercepted and sent to your Loguru handlers
logging.getLogger("gunicorn").addHandler(InterceptHandler())

# All Loguru logs are propagated to the standard handlers
logger.add(PropagateHandler(), format="{message}")
```

**Comment by Delgan** [comment]
I think you need to add this snippet to your app in order to propagate Loguru logs to the Gunicorn logging system:

```python
from loguru import logger
import logging


class PropagateHandler(logging.Handler):
    def emit(self, record):
        logging.getLogger("gunicorn.error").handle(record)


logger.remove()
logger.add(PropagateHandler(), format="{message}")

logger.warning("Logging with Gunicorn")
```

If this is not enough, please give more indications so that a suitable solution can be found. ;)
