### ISSUE TITLE
Setting environment from Windows 10

### ISSUE THREAD

**Issue by yoonghm** [Delgan/loguru#175]
Thank you for the great library and I am using it in a Windows 10 environment.

I tried to configure loguru using environmental variables.  For Windows 10, I noticed that I do not need to use double quote for variables, for examples,

```bash
set LOGURU_LEVEL=ERROR
```

However, I could not set for variables that have `"{"`

Hence, the following commands would not work

```bash
set LOGURU_FORMAT="{time} - {message}"
```

and neither did this:

```bash
set LOGURU_FORMAT={time} - {message}
```

**Comment by Delgan** [comment]
Hi @yoonghm. 🙂 

It's working fine on my computer with `cmd`. Are you using `PowerShell` maybe? Because from what I understand, curly braces `{}` has a special meaning in such enviroment (it's used to display string literally without possible interpolation). I think you should try to [duplicate them for escaping](https://stackoverflow.com/questions/27257333/how-do-i-escape-curly-braces-in-powershell):

```bash
set LOGURU_FORMAT="{{time}} - {{message}}"
```

**Comment by yoonghm** [comment]
No, I am using normal command prompt. I made a change to `env()` in `_defaults.py` to handle this:

```Python
def env(key, type_, default=None):
    if key not in environ:
        return default

    val = environ[key]
    if os.name=="nt":
    	val=val.replace('"', '')

    if type_ == str:
        return val
    elif type_ == bool:
        if val.lower() in ["1", "true", "yes", "y", "ok", "on"]:
            return True
        if val.lower() in ["0", "false", "no", "n", "nok", "off"]:
            return False
        raise ValueError(
            "Invalid environment variable '%s' (expected a boolean): '%s'" % (key, val)
        )
    elif type_ == int:
        try:
            return int(val)
        except ValueError:
            raise ValueError(
                "Invalid environment variable '%s' (expected an integer): '%s'" % (key, val)
            )
```

**Comment by Delgan** [comment]
Oh. Then, I'm not sure to properly understand the problem. :confused: 

Why can't you set variables that have `"{"`? Why doesn't the command work? Does it raise an error on Windows command prompt while calling `set`? Why does replacing `'"'` with `""` fix the problem? What is the link with `"{"`?

**Comment by yoonghm** [comment]
Hi Delgan, from my cmd prompt

```Bash
C:\home\Anaconda3>set LOGLEVEL="DEBUG"

C:\home\Anaconda3>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> loglevel = os.environ["LOGLEVEL"]
>>> print(loglevel)
"DEBUG"
>>> loglevel = loglevel.replace('"','')
>>> print(loglevel)
DEBUG
>>>
```

Please try on your Windows 10. Thanks.

**Comment by Delgan** [comment]
@yoonghm Yep, that's what I understood from your pull request. So, as you explained, `set LOGLEVEL=DEBUG` should be used instead, without the quotes (although it works fine with `setx`).

On my computer, `set LOGURU_FORMAT={time} - {message}` does not reveal any problem, though. Only if colors marks are added, like `set LOGURU_FORMAT={time} - <lvl>{message}</lvl>`, then it raises an error. But those can be escaped with `^`: `set LOGURU_FORMAT={time} - ^<lvl^>{message}^</lvl^>`. It looks like there exists workaround for your problem, or am I missing something else?

**Comment by yoonghm** [comment]
Hi Delgan,  the `^` works for Windows 10.  However, please update the documentation https://loguru.readthedocs.io/en/stable/api/logger.html#env

Thanks.

**Comment by Delgan** [comment]
@yoonghm The examples in the documentation use `setx`, that's why it works fine despite `"` and `<`. I will make sure to add a mention about the workaround for `set`.

**Comment by yoonghm** [comment]
Ya, it works. I did not use `setx` as it affects the whole operating system. I wanted to set different logging level, formatting for different Python program.  Thank you for the great and easy to use library.
