### ISSUE TITLE
Enable logging for Discord.py

### ISSUE THREAD

**Issue by Dextroz** [Delgan/loguru#178]
Hi,

I am having issues enabling logging for Discord.py with this package.

With the standard logging module Discord.py's documentations says to do the following:
```python
import discord
import logging

logger = logging.getLogger('discord')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(filename='discord.log', encoding='utf-8', mode='w')
handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger.addHandler(handler)
```

I thought with your module the following code would work; but it does not 😞 
```python
logger.enable("discord")
logger.add("discord-{time}.log", format="{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}")
```

What am I missing?

Thanks.

**Comment by Delgan** [comment]
Hi. :)

Actually, the [`.enable()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.enable) method is only useful for modules using `loguru` for their logging system. However, the `discord` library doesn't use `loguru`, it uses the standard `logging` module.

Therefore, if you want to intercept logs from the `discord` module, you need to add a special `InterceptHandler` that you can find [in the Readme](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging):

```python
import logging

discord_logger = logging.getLogger('discord')
discord_logger.setLevel(logging.DEBUG)
discord_logger.addHandler(InterceptHandler())

from loguru import logger

logger.add("discord-{time}.log", format="{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}")
logger.info("Message sent to the file")
discord.do_something()  # Discord logs are sent to the file too
```

**Comment by Dextroz** [comment]
So to clarify. I need to use both the logging and loguru module at the same time?

Also, I don't understand the line `discord.do_something()  # Discord logs are sent to the file too` ? Do you mean `discord_logger.do_something()` ?

Thanks for the quick response 😄

**Comment by Delgan** [comment]
> Do you mean `discord_logger.do_something()` ?

No, I really mean `discord.do_something()`. :smile: 
I don't know how you are using the `discord` module. It was just a way for me to represent some usage of the Discord API generating logs that you want to retrieve.


> I need to use both the logging and loguru module at the same time?

Well, yes. The standard `logging` library and `loguru` are actually implemented very differently, so they do not work with each others out-of-the-box, there is some extra steps needed to achieve interoperability.

**Comment by Dextroz** [comment]
Hmm ok. Seems like I might just go with standard logging module then.

**Comment by Delgan** [comment]
Yep, if you just need to redirect logs from `discord` to a file, and that you don't need them to interoperate with your own logs, there is little reason to use the `InterceptHandler()`.

**Comment by Dextroz** [comment]
Thanks @Delgan. 😄
