### ISSUE TITLE
How to use loguru in gunicorn config file?

### ISSUE THREAD

**Issue by Eternity-SXH** [Delgan/loguru#180]
Could you please show me an example?

**Comment by Delgan** [comment]
Well, I don't know much about Gunicorn... Maybe you can help me too.

I guess you can use an `PropagateHandler` or `InterceptHandler` depending if you want to propagate logs from loguru to the Gunicorn logger and its handlers, or if on the contrary you want to intercept Gunicorn log messages and emit them to yours Loguru configured sinks. Please, look at the [Readme](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging) for respective implementations.

Your Gunicorn configuration file may look like this:

```python
# All standard logs are intercepted and sent to your Loguru handlers
logging.getLogger("gunicorn").addHandler(InterceptHandler())

# All Loguru logs are propagated to the standard handlers
logger.add(PropagateHandler(), format="{message}")```

**Comment by Delgan** [comment]
I don't think it's possible to configure Loguru's `logger` using the Gunicorn config file. The following code should be added to your app so that logs are emitted to the Gunicorn logging system too:

```python
from loguru import logger
import logging


class PropagateHandler(logging.Handler):
    def emit(self, record):
        logging.getLogger("gunicorn.error").handle(record)


logger.remove()
logger.add(PropagateHandler(), format="{message}")

logger.warning("Logging with Gunicorn")
```

I'm closing this issue as there's not much I can do, but if you have more details about your use case we can discuss it. ;)

**Comment by gsph** [comment]
https://github.com/tiangolo/fastapi/issues/1276#issuecomment-615877177
