### ISSUE TITLE
Issue for Fully descriptive exceptions when { or } in the log string

### ISSUE THREAD

**Issue by hawktang** [Delgan/loguru#182]
![image](https://user-images.githubusercontent.com/2004071/69934401-c826d380-150c-11ea-9b4e-da6baf5bc689.png)
![image](https://user-images.githubusercontent.com/2004071/69934417-d07f0e80-150c-11ea-86a3-bd97d9ed9390.png)

**Comment by hawktang** [comment]
None is either working.

![image](https://user-images.githubusercontent.com/2004071/69935400-b8f55500-150f-11ea-98eb-ecab7b1130b9.png)

**Comment by Delgan** [comment]
Hi @hawktang.

The `diagnose` and `backtrace` parameters are both options for the [`.add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) method, at the time of configuring your handler.

When you pass keyword arguments to `.debug()` (and other logging methods), it's used to `.format()` the message:

```python
logger.info("abc {backtrace}", backtrace=123)
# => "abc 123"
```

Internally, Loguru makes `message.format(*args, **kwargs)`. That explains the error you are seeing.

The two `diagnose` and `backtrace` options only apply to added sinks.

**Comment by hawktang** [comment]
Thank you a lot  @Delgan. I use it in a wrong way.

**Comment by Delgan** [comment]
No problem. :+1:
