### ISSUE TITLE
Using loguru in flask, different function modules record to different log files, what should I do

### ISSUE THREAD

**Issue by gssjl2008** [Delgan/loguru#183]
Using loguru in flask, different function modules record to different log files, what should I do

**Comment by Delgan** [comment]
Can you share a little more information about the code you use to configure Flask and Loguru?

If logs are emitted to different files, surely multiple handlers have been added somewhere.

**Comment by gssjl2008** [comment]
For example, my flask application contains upload and download information. I want to record this information separately in a log file, and other logs are recorded in another main log file.

**Comment by Delgan** [comment]
So it's a question about *how* to send logs to multiple, not *why* logs are sent to multiple files, right?

You could basically use a `filter` argument to choose between logs coming from your different modules.

```
logger.add("uploads_and_downloads.log", filter=lambda record: "transfer" in record["extra"])
logger.add("myapp.log"). # No filter => all logs
```
When you want to write to the `"uploads_and_logs.log"` file, annotate your `logger` using `bind()`:
```python
logger.bind(transfer=True).debug("File uploaded: {}", filename)
```
The `filter` function can take many forms. You just need a way to differentiate between your logs so they are adequately dispatched to the different files.

**Comment by gssjl2008** [comment]
It met my needs, thank you very much!

**Comment by Delgan** [comment]
Great. :+1:
