### ISSUE TITLE
PermissionError(13, 'The process cannot access the file because it is being used by another process。') when rename log file.

### ISSUE THREAD

**Issue by yulei0619** [Delgan/loguru#184]
I set rotation="20 MB" as the prameter of logger.add method as follows:
- normal_dict = dict(encoding="utf-8", rotation="20 MB", retention='1 days')
- logger.add(sink="xx.log", level=LogLevel.DEBUG.value, **self.normal_dict)

I keep writing text to the file(i.g xx.log)，when the size of the file exceed 20 MB, the error will happen.

```
--- Logging error in Loguru Handler #419 ---
Record was: {'elapsed': datetime.timedelta(seconds=76, microseconds=861600), 'exception': None, 'extra': {}, 'file': (name='base_pipeline.py', path='F:\\project_GaoKaoZhiYuan\\server\\gkzy_ba
ckend\\z_project_spiders\\webcrawler\\common\\base_pipeline.py'), 'function': 'handle_error', 'level': (name='ERROR', no=40, icon='❌'), 'line': 169, 'message': 'MySQL: <class \'RuntimeError\
'> ("reentrant call inside <_io.BufferedWriter name=\'<stderr>\'>",) unhandled exception from item_list: \n[{\'average\': \'--\',\n \'local_batch_name\': \'本科二批\',\n \'local_province_name
\': \'内蒙古\',\n \'local_type_name\': \'文科\',\n \'max\': \'--\',\n \'min\': 483,\n \'proscore\': 399,\n \'school_id\': 90,\n \'school_name\': \'天津职业技术师范大学\',\n \'year\': 2018}}]', 'module': 'base_pipeline', 'name': 'z_project_spiders.webcrawle
r.common.base_pipeline', 'process': (id=12012, name='MainProcess'), 'thread': (id=15560, name='MainThread'), 'time': datetime(2019, 12, 3, 18, 26, 51, 448643, tzinfo=datetime.timezone(datetim
e.timedelta(seconds=28800), '?D1¨²¡À¨º¡Á?¨º¡À??'))}
Traceback (most recent call last):
  File "f:\project_gaokaozhiyuan\server\gkzy_backend\venv\lib\site-packages\loguru\_handler.py", line 153, in emit
    self._sink.write(str_record)
  File "f:\project_gaokaozhiyuan\server\gkzy_backend\venv\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._initialize_file(rename_existing=True)
  File "f:\project_gaokaozhiyuan\server\gkzy_backend\venv\lib\site-packages\loguru\_file_sink.py", line 194, in _initialize_file
    os.rename(new_path, renamed_path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:\\project_GaoKaoZhiYuan\\server\\gkzy_backend\\output\\logs\\gkzy_backend.log' -> 'F:\\project_GaoKaoZhiYuan\\serve
r\\gkzy_backend\\output\\logs\\gkzy_backend.2019-12-03_18-20-29_816686.log'
--- End of logging error ---
```

Any help would be greatly appreciated.

**Comment by yulei0619** [comment]
Add a note:
I keep writing text to the file，when the size of the file exceed 20 MB, the above exception will happen.

**Comment by Delgan** [comment]
Hum... It's weird. I see that you have (at least) 419 handlers attached to the `logger`... That's quite a lot, isn't it? 😅 

Are you not adding them in a loop, which could create some conflicts? Or are you often calling `.remove()` maybe?

**Comment by yulei0619** [comment]
> Hum... It's weird. I see that you have (at least) 419 handlers attached to the `logger`... That's quite a lot, isn't it? 😅
> 
> Are you not adding them in a loop, which could create some conflicts? Or are you often calling `.remove()` maybe? Are you running your Python program multiple times in parallel?

Thank you very much for your reply.
1. I did not add it in a loop.  If the size of file less than 20 MB,  it is normal for the logs were writed in a file. Only exceed greater than 20 MB, the program start print the above logging error for many times(you see, at least 419 times.)
2. I have never called the remove method once。
3. I runned my program for one times in parallel.

**Comment by Delgan** [comment]
You're welcome. :+1: 

>  Am I only add one handler into 'logger' in whole project?

Yes, anytime you call `.add()`, all modules using the `logger` object get access to the newly added handler. This happens because the `logger` is one global instance, so its state and the handlers attached to it are shared among your files. 

If you want to use one handler for your whole project, make sure to call `.add()` only once and before executing your others files. You can do this at the beginning of your program, for example:

```python
if __name__ == "__main__":
    logger.remove()  # Remove the default handler
    logger.add(sys.stderr, format="{time} {message}")  # The handler you would like to use
    main()  # The logic of your program
```

**Comment by Delgan** [comment]
Don't hesitate to ask me if you have any other questions :wink:
