### ISSUE TITLE
0.4.0 causing "RuntimeError: SimpleQueue objects should only be shared between processes through inheritance"

### ISSUE THREAD

**Issue by sn0opy** [Delgan/loguru#185]
See title.

It's kinda hard to track down the actual source of this. I've got a project that heavily relies on Multiprocessing and Multithreading and it looks like this somehow interferes with loguru's latest update. Is there anything I can provide to track down the issue?

In case it helps:

```
Traceback (most recent call last):
  File "start.py", line 194, in <module>
    mapping_manager: MappingManager = mapping_manager_manager.MappingManager(db_wrapper, args, data_manager, False)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 662, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 556, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 78, in dispatch
    c.send((id, methodname, args, kwds))
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 326, in getstate
    context.assert_spawning(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 356, in assert_spawning
    ' through inheritance' % type(obj).name
RuntimeError: SimpleQueue objects should only be shared between processes through inheritance
```

The project in question: https://github.com/map-a-droid/mad

**Comment by Delgan** [comment]
Yes, there have been some changes made lately to the interfacing with `multiprocessing`. This was required to make `multiprocessing` actually work on Windows.

I added some explanation to the documentation:

* [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)

Basically, the `logger` is no longer able to be serialized. This means it can't be passed to processes already started, it should be "inherited" while process is created.

I think on Linux it should work out-of-the-box. Do the `_logger` needs to be an attribute of your `DataManager` [here](https://github.com/Map-A-Droid/MAD/blob/dc7454ed5fc1c43b1ff87f6168481be637809e9a/utils/data_manager.py#L25)?

**Comment by sn0opy** [comment]
That in fact did the trick! There's no other place in the code that gets a logger instance passed. Guess it's just a smaller oversight. Thanks for looking into the code! 

I was able to fix the problem.

**Comment by Delgan** [comment]
Great! The refactoring process to `v0.4.0` was quite heavy with many changes. I'm glad to know it works well for your application. :wink:

**Comment by mancioshell** [comment]
@Delgan  i have the same issue. I'm actually used loguru with 3x of [Apscheduler](https://apscheduler.readthedocs.io/en/3.x/).
Apscheduler has both Thread Executors and Process Pool executors. With Thread Executors i have no problems, but i have same issue with Process Pool Executors. I'm using windows in my local env, and linux on production.
Could you help me to solve the issue with Process Pool Executors?

**Comment by Delgan** [comment]
@mancioshell Please open a new issue with fully reproducible example if possible.
