### ISSUE TITLE
v0.4.0 on conda

### ISSUE THREAD

**Issue by a-slide** [Delgan/loguru#189]
Hi @Delgan 
Do you plan to release v0.4.0 on anaconda ? I can only see up to v0.3.2 at the moment.
Thanks

**Comment by Delgan** [comment]
Hi @a-slide, thanks for the report. I opened a PR on the `loguru-feedstock` repository: https://github.com/conda-forge/loguru-feedstock/pull/10

**Comment by Delgan** [comment]
Closed by https://github.com/conda-forge/loguru-feedstock/pull/11: `v0.4.1` is now available on Conda. ;)
