### ISSUE TITLE
Custom loglevel function example

### ISSUE THREAD

**Issue by gazpachoking** [Delgan/loguru#191]
In the example to [add a function to log at custom loglevels](https://github.com/Delgan/loguru/blob/master/docs/resources/recipes.rst#using-logging-function-based-on-custom-added-levels), the current method will ignore things like `.bind` that were called on the logger. For example:

```python
def foobar(_, message, *args, **kwargs):
    logger.opt(depth=1).log("foobar", message, *args, **kwargs)

logger.__class__.foobar = foobar

# This bind gets ignored
logger.bind(something='otherthing').foobar("A message")
```
I think the example just needs to be updated to something like this:
```python
def foobar(self, message, *args, **kwargs):
    self.opt(depth=1).log("foobar", message, *args, **kwargs)
```
Not sure if there are any other ramifications of that I'm not thinking of.

**Comment by Delgan** [comment]
Oh, that was really bad, thanks for having caught that! :+1:
