### ISSUE TITLE
Can't chain .opt() calls

### ISSUE THREAD

**Issue by gazpachoking** [Delgan/loguru#192]
Calling opt more than once on a logger instance overrides all options that aren't specified to default, meaning you can't chain .opt() calls together.
For example in the following call, the color codes are ignored.
```python
logger.opt(ansi=True).opt(depth=1).debug('<red>aoeu</>')
```
This doesn't make a lot of sense when done directly like this, but if you are using the [recipe for adding custom loglevel methods](https://github.com/Delgan/loguru/blob/master/docs/resources/recipes.rst#using-logging-function-based-on-custom-added-levels), it calls .opt() to set the depth. The consequence of this is that you can no longer use .opt() directly from you code, since it will always be overridden by the depth call, including all of the options other than depth.

**Comment by Delgan** [comment]
Huh, this is a serious design issue indeed. Thanks for the report and the pull request.

I'm not a big fan of sentinel values, as it makes the signature of the function less readable. I wonder if there is any other possible workaround... If not, I will probably merge your fix. :+1:

**Comment by gazpachoking** [comment]
Could switch to `**kwargs` instead of having a sentinel value... but that makes the signature even worse. Not sure a better way. At least the signature in the pyi file is still nice with type hints.

**Comment by Delgan** [comment]
I don't think there's much point in chaining `opt()` calls, apart from the problem with custom levels you've raised. So, what do you think of replacing the documented recipe with:

```python
from functools import partialmethod

logger.__class__.foobar = partialmethod(logger.__class__.log, "foobar")
```

I was delightfully surprised to find out that it worked just fine! I guess the Python interpreter somehow optimize [`partialmethod()`](https://docs.python.org/3/library/functools.html#functools.partialmethod) so it does not add another frame to the stack, thus avoiding the need for `opt(depth=1)`. Then the `foobar()` logging method can be combined with any `opt()` attribute.

**Comment by gazpachoking** [comment]
I think that recipe change sounds like a good plan regardless of whether opt gets changed.
I sorta like the idea of it working as expected when chained, but it's much less important with that updated recipe. The only other instance I can think of is if someone perhaps wanted to do something like turn on colors by default when logging in only one of their modules. e.g.

```python
from loguru import logger

logger = logger.opt(ansi=True)


try:
    somethingdangerous()
except:
    logger.opt(exception=True).debug('Everything <blue>went</> wrong')
```

**Comment by Delgan** [comment]
It seems possible to achieve the desired behavior using the same principle:

```python
from functools import partial

logger = logger.opt(ansi=True)
logger.opt = partial(logger.opt, ansi=True)
```

Of course, this is not very intuitive, so this recipe needs to be properly documented. Nevertheless, I prefer this workaround. None of the solutions are perfect, so it's a matter of perspective, and I think it's more important to have a "clean"  signature rather than allowing `opt()` chain calls (actually, see https://github.com/Delgan/loguru/commit/2b8e6f967db01ed606a32f8265b5e25ed44dfde6).

**Comment by gazpachoking** [comment]
Sounds good, I'll defer to you on this one. Might also be worth a mention in the `.opt` docs that the last call is the only one that takes effect.

**Comment by Delgan** [comment]
I updated the recipe for custom level, created a new entry about `opt(ansi=True)` and added a note in the `opt()` documentation. Thanks again for the report. :wink:

**Comment by gazpachoking** [comment]
Awesome, looks good. Thanks!

**Comment by michalplat** [comment]
Do You have any way of working with `logger.__class__.foobar = partialmethod(logger.__class__.log, "foobar")` and mypy? Obviously mypy can't see that loguru.logger has attribute "foobar" and I didn't find any WA for this.

**Comment by kornicameister** [comment]
I don't think I will be able to make any changes. Frankly I am quite busy nowadays. If you feel like you're up too, give it a shot.
