### ISSUE TITLE
Log deletion too greedy

### ISSUE THREAD

**Issue by gazpachoking** [Delgan/loguru#195]
Using the file sink, when loguru goes to clean up old logs due to retention setting. It is a bit too greedy with what it thinks are old logs. I am using the filename `flexget.log`, and the glob for deletion comes out to `flexget.*`. This strikes me as a bit greedy, and in my particular case it tries to delete a folder called `FlexGet.egg-info` (which is read only and causes a crash.) The two easy improvements I can see are:
- Include the extension in the glob
- Exclude folders

**Comment by Delgan** [comment]
Good catch, thanks. The filenames can take many forms due to `"{time}"`, `rotation` and `compression`. I will modify the collect of files based on your two suggestions. In the meantime, I guess you will need to manually re-filter and remove files using a custom `retention` function. :wink:

**Comment by Delgan** [comment]
Closed by #196.
