### ISSUE TITLE
Replace newline `\n` with literal `\\n` in log

### ISSUE THREAD

**Issue by AllanLRH** [Delgan/loguru#199]
I'd love the option to force log messages to span just one line by replacing `\n` with `\\n`.

This is an issue which are sometimes encountered when logging Pandas DataFrames and Numpy Arrays.

**Comment by Delgan** [comment]
Hi @AllanLRH.

If you need to customize the line-ending of an handler, you can use a custom `format` function like this for example:

```python
def my_format(record):
    return r"[{time}] {function}:{file}:{line} - {message}\\n"

logger.add(sys.stderr, format_my_format)
```

**Comment by AllanLRH** [comment]
Thanks, but what I'd really like is an (easy) way to configure the logger to transforn the input as such:

```python
# This is what I want
logger.debug(str(my_numpy_array).replace('\n', '\\n'))
# Perhaps with the option of `repr` instead of `str`
logger.debug(repr(my_numpy_array).replace('\n', '\\n'))

# But I'd love to just write this, and configure the logger to do the work for me :)
logger.debug(my_numpy_array)
```

I tried looking at the docs for quite a while, but I can't find a straightforward way of doing this.

**Comment by Delgan** [comment]
Oh, yeah, sorry, I completely misinterpreted your question.

So, here is another workaround I can offer you. :smile: 

```
>>> from loguru import logger
>>> multi = "foo\nbar\nbaz\n"
>>> logger.info(multi)
2020-01-11 17:32:33.496 | INFO - __main__ - foo
bar
baz

>>> def flatten_message(record):
...     record["message"] = record["message"].replace("\n", "\\n")
... 
>>> logger = logger.patch(flatten_message)
>>> logger.info(multi)
2020-01-11 17:33:16.592 | INFO - __main__ - foo\nbar\nbaz\n
```

I think you can use [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) to force the `message` to span only one line. You can also apply the change for your whole application by using the `patch` parameter of the [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) method.

**Comment by AllanLRH** [comment]
Sorry to reopen this, but it seems silly to create a new issue... can I patch the messages (or record-dict, I guess) on a sink-level?
Would be nice to force one-line output in files but keep multi-line output in console.

**Comment by Delgan** [comment]
Yep, that's totally possible. Instead of modifying `record["message"]`, just create a new entry to be used by the `format` parameter of some specific sinks only.

```python
def flatten_message(record):
    record["message"] = record["extra"]["flattened_message"].replace("\n", "\\n")

logger.add("file.log", format="[{time}] {extra[flattened_message]}")
```

**Comment by Delgan** [comment]
Closing as it seems solved. :+1:
