### ISSUE TITLE
ImportError: cannot import name 'Logger' from 'loguru'

### ISSUE THREAD

**Issue by heckad** [Delgan/loguru#206]
```
from logure import Logger

def f(log:Logure):
    pass
```

**Comment by Delgan** [comment]
Hey @heckad.

You're not supposed to import the `Logger` class, you should use the `logger` instance. 

```python
from loguru import logger
```

**Comment by heckad** [comment]
I want to import `Logure` class for type hints like in example.

**Comment by heckad** [comment]
It doesn't work. Exception: `AttributeError: module 'loguru' has no attribute 'Logger'`
```
import loguru

def f(log: loguru.Logger):
    pass
```

**Comment by Delgan** [comment]
@heckad Which Python version are you using? I think you may need to use string literals:

```python
import loguru

def f(log: "loguru.Logger"):
    pass
```

**Comment by heckad** [comment]
I use the latest version of python (3.8.1). String literal work fine. Thank you very much for the help

**Comment by Delgan** [comment]
Oh, actually I thought **Postponed Evaluation of Annotations** ([**PEP 563**](https://www.python.org/dev/peps/pep-0563/)) was usable out of the box with Python 3.8 but it is not. As for Python 3.7, it requires a `__future__` import. I will update the documentation accordingly.

So, if you wish, you can replace string literals by prepending your file with:

```python
from __future__ import annotations
import loguru

def f(log: loguru.Logger):
    pass
```

**Comment by roganartu** [comment]
Neither `from __future__ import annotations`, nor using a string literal for the annotation appears to work with `typing.get_type_hints`. Here's a minimal example demonstrating this (tested in Python 3.9.3 with `loguru==0.5.3`):
```
#!/usr/bin/env python3.9
from __future__ import annotations
import typing

import loguru

def test(log: loguru.Logger) -> None:
    pass

typing.get_type_hints(test)
```
Running the above results in:
```
Traceback (most recent call last):
  File "/tmp/./test.py", line 11, in <module>
    typing.get_type_hints(test)
  File "/home/tl/.pyenv/versions/3.9.3/lib/python3.9/typing.py", line 1449, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/home/tl/.pyenv/versions/3.9.3/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/home/tl/.pyenv/versions/3.9.3/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'loguru' has no attribute 'Logger'
```
Commenting out the `typing.get_type_hints(test)` line prevents the exception.

Alternatively, you can change the function signature to the following:
```
def test(log: loguru._Logger) -> None:
```
Obviously neither of these are ideal, though.

**Comment by Delgan** [comment]
Hi @roganartu.

This is indeed a problem that has been brought up recently: https://github.com/Delgan/loguru/issues/480

For some reason, `get_type_hints()` does not work well with forward references. This looks to be a known problem, though:  
* https://github.com/python/typing/issues/508
* https://bugs.python.org/issue34700

Loguru uses a stub file on purpose, so unfortunately I can't do much. Is it possible for you to check the `__annotations__` attribute of the function instead of using `get_type_hints()`?

**Comment by ijaniszewski** [comment]
In my case, I named python file `logger.py` which casued confusion. Changing the name of script solved the problem.

**Comment by SergeyDevyatkov** [comment]
I found this as the best way for me:

```
if TYPE_CHECKING:
    from loguru import Logger

def some_method(logger: "Logger"): ...
```

**Comment by tropicoo** [comment]
To use with `ruff`:
```python
if TYPE_CHECKING:
    from loguru import Logger  # noqa: TC004


async def get_stdout(
    log: Logger | None = None,
    ...
```
