### ISSUE TITLE
Why does it logs duplicated message?

### ISSUE THREAD

**Issue by rightx2** [Delgan/loguru#208]
## Code
```
import sys

from loguru import logger
logger.add(sys.stdout, colorize=True, format="{message}~~~~")


logger.debug("This is my logger\n awesome!! haha")
>> 2020-02-01 09:11:45.204 | DEBUG    | __main__:<module>:1 - This is my logger
 awesome!! haha
This is my logger
 awesome!! haha~~~~
```

## Problems

1. It shows the same message twice
2. I was meant to print just `message` alone but it always print `2020-02-01 09:11:45.204 | DEBUG    | __main__:<module>:1`... 

Why does it happen?

**Comment by Delgan** [comment]
Hi @rightx2.

For convenience, a default sink logging to `stderr` is automatically attached to the imported `logger`. If you want to get ride of it, you can just call [`logger.remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) at the start of your script (it will disable all previously added handlers). :+1:

**Comment by Delgan** [comment]
@rightx2 Did the provided solution solved your issue?

**Comment by rightx2** [comment]
@Delgan  Yes. Thank you for a solution : )
