### ISSUE TITLE
feature request: migration path for print calls

### ISSUE THREAD

**Issue by jamescasbon** [Delgan/loguru#212]
Many times I have received code from a non log enlightened coworker.  These scripts can have 100s of print statements.  Currently, the path to logging is painful.  You cannot simply run s/print/log.info/ as you need to change all the first arguments to print to support string formats.

eg 

    print('HERE', something, another_thing)

must become 

    log.info('HERE %s %s', something, another_thing)

I would love a log library that would make the upgrade path easier so that you could in one step move to logging and then decide how to update the statements on a case by case basis.  This would also help *sell* logging modules as straight away the unenlightened coworker could see what line the print statement comes from!

So perhaps we could have a print function defined something like: 

     def print(self, *msg, level='INFO'):
          fmt = '{} ' * len(msg)
          self.log(level, ..., fmt, msg)

Which would enable a trivial source change to use logging.

**Comment by Delgan** [comment]
Hi @jamescasbon, this reminds me of a similar issue raised a few days ago: #207

Basically, your adapted `print()` function could look like this:

```python
def print(*args, level="INFO"):
    message = " ".join(map(str, args))
    logger.opt(depth=1).log(level, message)
```

I don't plan to add this as "built-in" to Loguru, but I think you can fairly easily use this snippet and integrate it to your code base.

**Comment by jamescasbon** [comment]
Ah thank you - this is great. I was missing the depth option :+1:
