### ISSUE TITLE
Logging from multiple modules.

### ISSUE THREAD

**Issue by Devarsh-UTD** [Delgan/loguru#217]
Hello there,
Firstly thank you for such an amazing and convenient package for logging in python.

### Goal : Log messages from multiple python modules to different log files. 
        For example- We have two modules by the name file1.py, file2.py.

### Failed approaches :

- Attempt 1,
      In file1.py

         from loguru import logger
         import file2.py

         temp_1 =  '/analytics/log/file1.log'
         temp_2 = '/analytics/log/file2.log'
         logger.configure(handlers=[dict(sink=order_channel, format="[{time:YYYY-MM-DD 
                                      HH:mm:00}, {name}] {level}: {message}",rotation="4 days", level="INFO"),
                                      dict(sink=application, format="[{time:YYYY-MM-DD HH:mm:00}, {name}] 
                                     {level}: {message}", rotation="4 days", level="INFO")])

          # The below log message should be directed to `file1.log`
          logger.info('Hi, this  log message is from file1')

  In file2.py

         from loguru import logger
         # The below log message should be directed to `file2.log`
          logger.info('Hi, this  log message is from file2')

- Result1,
   Both the log files are created but all the log messages are passed to both the log files.

--------------------------------------------------------------------------------------------------
          
- Attempt 2,

      In file1.py

         from loguru import logger
         import file2.py

         temp_1 =  '/analytics/log/file1.log'
         logger.add(temp_1,
                   format="[{time:YYYY-MM-DD HH:mm:00}, {name}] {level}: {message}", rotation="4 
                   days", level='INFO', filter='file1.py')

          # The below log message should be directed to `file1.log`
          logger.info('Hi, this  log message is from file1')

  In file2.py

         from loguru import logger

         temp_2 = '/analytics/log/file2.log'
         logger.add(temp_2,
                   format="[{time:YYYY-MM-DD HH:mm:00}, {name}] {level}: {message}", rotation="4 
                   days", level='INFO', filter='file2.py')

         # The below log message should be directed to `file2.log`
          logger.info('Hi, this  log message is from file2')

- Result1,
   Both the log files are created but all the log messages are passed to both the log files.

**Comment by Delgan** [comment]
Hi @Devarsh-UTD. :slightly_smiling_face: 

The second approach is the way to go: you need a `filter` in order to assign logging messages to the appropriate file. However, while using a `str` as the `filter` argument (it can also be a function), you need to pass the module **name**, not the module file. The module name correspond to the value of `__name__` inside your module. So, you should try to use `filter=file1` instead and see if it works better.

**Comment by Delgan** [comment]
@Devarsh-UTD Did I answered your questions?
