### ISSUE TITLE
Basic Setup Issue

### ISSUE THREAD

**Issue by scottfurry** [Delgan/loguru#219]
Platform: Linux - Python 3.7.6
Package: 0.4.1 (latest revision available)

Instructions say usage is "out-of-the-box", but there is something about a basic setup in multiple files in the same module that is just unclear to me.

In module `__init__.py` I have the following:

```
import sys
from loguru import logger
logger.add(sys.stderr, format="[defined format in str]", filter='my_module', level="INFO")
logger.info('module init')
```

In other python files in the same folder I have:
```
from loguru import logger
...
    [elsewhere in code]
   logging.info('a message')
```

Problem is that the formatting defined in `__init__.py` is not being used. The logger will use the default formatting in defined loguru. If I remove the `filter=...` line, I now have two log outputs for each usage.

Documentation suggests the logging defined with `add` should just be _picked up_ but I'm not finding that to be the case. Do I need to use the `logger.bind=(...` call? Is there some other salient detail in the docs that I missed (after scouring the *ReadTheDocs* page and issues/questions raised here). Something is just not making sense.

**Comment by Delgan** [comment]
You should try to remove the default handler (automatically added for convenience), call `logger.remove()` before `logger.add()` (that should remove all already existing handlers).

Also, try to remove the `filter` argument. Maybe that your file structure doesn't match the filter configuration. That would explain why you are seeing logs twice if you remove the filter: the ones coming from the default handler (incorrectly formatted), and the ones of your handlers (presumably well formatted).

**Comment by scottfurry** [comment]
That did it. I did numerous web searches for help in configuring a multi-file loguru setup all to know avail. I didn't think to remove the "default" (or root?) logger.

Don't get me wrong, I love the premise of what this package can do. Tons of features (with colours!). Prorverbial swiss army knife of logging and allows f-strings! I just needed some help figuring out the tooth-pick holder. :laughing: 

Thanks for the help.

**Comment by Delgan** [comment]
No problem, glad you like Loguru! :smile: :+1:
