### ISSUE TITLE
Add/Remove are not thread-safe

### ISSUE THREAD

**Issue by joshuaellinger** [Delgan/loguru#22]
import threading
from loguru import logger

def open_log_file(fn:str):

    logger.add(fn)
    logger.info("test message")

logger.info("write to 10 files")
for i in range(10):
    fn = "test_" + str(i) + ".log"
    logger.info(f"fn = {fn}")
    t = threading.Thread(target=open_log_file, kwargs={"fn":fn})
    t.start()

**Comment by Delgan** [comment]
Thanks for the bug report! I will submit a fix as soon as possible.

**Comment by Delgan** [comment]
I just pulished version `0.2.4` of Loguru with a fix for this.

Please, don't hesitate to open a new issue if you encounter another problem. 👍

**Comment by Delgan** [comment]
NB: My "fix" introduced another type of race condition that is properly fixed by https://github.com/Delgan/loguru/commit/2bc0cda1a0ca069f83ab6eb223b0f62770301f15
