### ISSUE TITLE
Why does loguru use option exception instead of traceback?

### ISSUE THREAD

**Issue by heckad** [Delgan/loguru#222]
Propose to add `traceback` or `with_traceback` to opt method.

**Comment by Delgan** [comment]
I quite like the `traceback` parameter, I think it more accurately describes what is being done by this option (I prefer it over `with_traceback` as it is consistent with the rest of the API which uses single-word names).

However, I've been thinking a bit about this and I think I will stay with the `exception` parameter for the following reasons:
* Actually, the traceback is followed by the exception type and message (even if no error is currently handled), so it seems the wording is correct.
* It would lead to confusion with the `backtrace` parameter of the `add()` method, I can easily imagine people inadvertently using one instead of the other.

**Comment by heckad** [comment]
As it turned out, exception works only for exceptions, but I need a universal method. For example this code 
```
from loguru import logger

logger.opt(exception=True).info('foo')
```
Return 
```
2020-03-13 11:43:01.669 | INFO     | __main__:<module>:3 - foo
NoneType: None
```

**Comment by Delgan** [comment]
I think you should make use of [`traceback.format_stack()`](https://docs.python.org/3.8/library/traceback.html#traceback.format_stack), that would probably help you to achieve the desired behavior in combination with a custom  [`logger.patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) (using a custom `format` function is also possible).

For example:

```python
def patching(record):
    if record["extra"].get("traceback"):
        record["extra"]["formatted_tb"] = "\n" + "".join(traceback.format_stack())
    else:
        record["extra"]["formatted_tb"] = ""

logger = logger.patch(patching)
logger.remove()
logger.add(sys.stderr, format="{time} - {message}{extra[formatted_tb]}")

logger.info("No traceback")
logger.bind(traceback=True).info("With traceback")
```

**Comment by heckad** [comment]
It would be nice to see this option under `with_traceback` in loguru.

**Comment by Delgan** [comment]
What would be your use case for this? Printing the full traceback means it will contain Loguru internals too.

**Comment by heckad** [comment]
When debug I need to know where did we get to this line. It may happen from different places.

**Comment by Delgan** [comment]
I don't think Loguru is the appropriate tool for this kind of debugging. I would suggest using a proper debugger or a library like [`PySnooper`](https://github.com/cool-RR/PySnooper) for example. You see, I think adding a `traceback` option would be an imperfect solution. It would help you to debug part of your code, but it won't help you as much as using an appropriate tool. Printing the traceback is nice, but also being able to see the actual values of different variables is very useful for debugging. That's not Loguru's purpose, but there exist several alternative libraries that I think may be of interest to you.

**Comment by Delgan** [comment]
As discussed, I don't think it's appropriate for Loguru to flirt with debugging-oriented features. For this reason, I'm closing this issue. I added [some code recipes](https://loguru.readthedocs.io/en/latest/resources/recipes.html#displaying-a-stacktrace-without-using-the-error-context) to the documentation, though.
