### ISSUE TITLE
rotation to mutli file when logging in mutli-process

### ISSUE THREAD

**Issue by bcwk** [Delgan/loguru#225]
test code such as : 

```
fix_rotation = "18:30"
def LoguruTest(token=None):
    logger.add('loguru_test_{time:YYYY:MM:DD_HH:mm}.log', rotation=fix_rotation, enqueue=True)
    test_count = 0
    while test_count<30:
        time.sleep(2.0+random.uniform(0.3,2.6))
        logger.debug('11111111')
        test_count+=1

if __name__ == "__main__":
    p = Pool(5)
    for i in range(5):
        p.apply_async(LoguruTest, args=(f't_{i}',))
    p.close()
    p.join()
```

before 18:30, all 5 processes wirte to one file; but after 18:30 they write to 5 files.

-----------
Python 3.7.0
loguru 0.4.1
CentOS Linux release 7.2.1511

**Comment by bcwk** [comment]
Python 3.7.0
loguru  0.4.1  
CentOS Linux release 7.2.1511

**Comment by bcwk** [comment]
i found the docs said " If there is already an existing file with the same name that the file to be created, then the existing file is renamed by appending the date to its basename to prevent file overwriting. ", but why they can write to one file at the first time, how can i write to the same file always?

**Comment by bcwk** [comment]
i know why now. 
first time use ```self._initialize_file(rename_existing=False)```
but rotation use ```self._initialize_file(rename_existing=True)```
:joy: :joy: :joy:

**Comment by Delgan** [comment]
Hi @bcwk.

You are calling `logger.add()` in five multiple processes, that means that five handlers will be added. Every logged message will be propagated to each of these handlers.
The name of your files is `'loguru_test_{time:YYYY:MM:DD_HH:mm}.log'`, so the five handlers will generate the same name as they are added at the same time. When you call `.add()`, the file is opened with "append" mode (as in `open("file.log", "a")`). Whichever of your five process is initialized first will create a new file, the four others processes will just re-open the newly created file as all your handlers use the same filename. As a result, the five processes will log to the same file.
When rotation occurs, a check is made to ensure the newly created file will not overwrite an existing one. The five handlers were not "aware" that they were sharing the same file. So, to avoid conflicts, they will individually create five new files.

Anyway. I think you should ensure that `logger.add()` is not called five times. You have to put the handler configuration outside of the function sent to the processes, before creating the `Pool()` for example. That way, only one handler will be used, and so only one file will be created during rotation.

See also (should be fine as you are using Linux, but may worth reading): [Compatibility with multiprocessing using enqueue argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)

**Comment by bcwk** [comment]
Hi @Delgan, Thanks for your reply. 
I use multiprocessing.Pool to simulate the real situation. Actually, the mutli-process maybe come from web server or script, i can't pass the handler to them. You know, the diffent script have similar functions, and i want to save their log to the same file.

**Comment by Delgan** [comment]
Well, in such a case you should not try to write to the same file with different processes. If these processes can't be synchronized in any way this may create corrupted logs.

So, I see two solutions:
* Make sure that your different processes create logs with different filenames and use some "logs aggregator" like Fluentd / Loggly / Papertrail / Logstash / Graylog / Sentry.
* You can try to use [a special handler to send log across processes](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes)

**Comment by bcwk** [comment]
@Delgan I got it, thank you very much.

**Comment by Delgan** [comment]
I hope you can find implement a solution that suits your needs. Can I close this issue or do you have any other questions?

**Comment by bcwk** [comment]
Yes, i have no more questions, please close this issue . And thanks again for your suggestion, you are so kind and patiently.
