### ISSUE TITLE
Sentry breadcrumbs and loguru

### ISSUE THREAD

**Issue by heckad** [Delgan/loguru#226]
How to make sentry capture breadcrumbs from loguru too?

**Comment by Delgan** [comment]
I don't know much about Sentry. Maybe can you use a custom sink to create breadcrumbs when logs are emitted?

```python
def breadcrumb_sink(message):
    record = message.record
    sentry_sdk.add_breadcrumb(
        category: record["name"],
        message: record["message"],
        level: record["level"].name,
    )

logger.add(breadcrumb_sink)
```

**Comment by Delgan** [comment]
@heckad Does the provided solution would work? Do you need more help in any way?

**Comment by heckad** [comment]
Yes, Thanks great! You are the best maintainer!

**Comment by Delgan** [comment]
Ha ha, thanks! :smile: 

I'm closing this issue then. :+1:
