### ISSUE TITLE
Loguru in module imported by Jupyter Notebook

### ISSUE THREAD

**Issue by ChasNelson1990** [Delgan/loguru#228]
Hi there,

I really like loguru and have converted a couple of packages that I've been writing to use it.

I like to provide a jupyter notebook in my repos to demo the use of the module and what I'd like to do is show logs >=INFO in the jupyter notebook and ignore all <=DEBUG logs.

In my module I have `logger.disable("my_module_name")` and, if I do nothing in the notebook, I get no outputs (so far so good).

If I then add
```python
import my_module_name as mmn
logger.enable("my_module_name")
logger.add(sys.stderr, level="INFO")
```

I get all logs, including DEBUG. Not, what I expected.

Any suggestions?

Thanks for your time.

**Comment by Delgan** [comment]
Hi @ChasNelson1990. :slightly_smiling_face: 

I don't use Jupyter Notebook much, so I'm not sure if this is relevant, but did you `.remove()` the default handler (which logs to `sys.stderr` too)? For convenience, a handler with `DEBUG` level is automatically attached to the `logger`, without even calling `.add()`.

**Comment by ChasNelson1990** [comment]
Ahhh, you were spot on! That also explains why my tests were showing all the debug messages despite the `.disable()`, which, to be fair, was useful.

As a suggestion, shouldn't an `.add()` that's going to the same output overwrite any previous ones? It seems odd to me that if a user of something I write wants to log the info and success messages they have to know to turn a default logger off first?

Or are you expecting that, for best practise, people add a `logger.remove()` as well as a `.disable()`?

**Comment by Delgan** [comment]
I don't think `.add()` should automatically replace existing handler of the same type. It is the responsibility of the user to ensure that the logger is configured with the appropriate handlers. Moreover, I'm sure there are cases where having two `sys.stderr` handlers is desirable (if combined with `filter` for example).

You don't necessarily need to call `.remove()` when you call `.disable()`, it's not really related. I think you should configure your handlers in one place when your script starts. While configuring your handlers, you may need to `.remove()` the default one. Later, you can call `.disable()` or `.enable()` based on your logging preferences.

**Comment by ChasNelson1990** [comment]
Hmm... but if you are making a module that you want others to use but want others to have the option of seeing the INFO logs (this results of this module are very data-dependent) then I need to use `.remove()` somewhere in my module. Because my users are not programmers and I want them to have as little to do on their end but still be able to vary the level. I guess, what I'd like is a one-liner, e.g. `.update_level()` that they can quickly modify in my notebook or copy and paste into their notebooks... 

Sorry if this seems silly. As I say, I really like your modules, just trying to work out exactly how to get things how I need them. I develop with programmers but distribute to both python-proficient and very much not proficient and I want them all to easily get the information they need with as little extra as possible.

Question about your intended philosophy: Do you think it makes sense to, in my module, `.remove()` your default handler and replace is with a `.add(level="WARNING")` and then, I believe this is right, if a user adds a `.add(level="INFO")` or `"DEBUG"` it will, in effect, overwrite the original add and give them that extra info that they rarely, but occasionally, need?

**Comment by Delgan** [comment]
Ok, I see. :slightly_smiling_face: 

Loguru was created in such a way that the user has to fully manage handlers and levels. It makes sense that there are some complications if the API is not exposed to the end user.

The issue with calling `.add()` twice is that the users will see logs twice. Ideally, if you provide some code a a module (and not as a script), you should not call `.remove()` or `.add()` because as I said this is the end-user who should manage handlers where logs are sent. Is there a way for you to ask the users to call a custom function like `configure_logging()` at the start of their notebook?

```python
def configure_logging(level="DEBUG"):
    from loguru import logger
    logger.enable("my_module_name")
    logger.remove()
    logger.add(sys.stderr, level=level)
```

By default they will get no logs, except if they call this method. Otherwise, you can call this method in your `mm` module to provide a default output. But, if your user need to adjust the level, you will probably need to `.remove()` any other added handler (that's why I call it in the function).

**Comment by ChasNelson1990** [comment]
Yea, that sounds like a sensible solution.

Great. Thanks for your help!

**Comment by Delgan** [comment]
No problem. Ask me if you have any other doubts. It's always instructive to know about particular use cases. :+1:
