### ISSUE TITLE
Per-sink line terminator

### ISSUE THREAD

**Issue by nonamethanks** [Delgan/loguru#230]
I am in need to be able to occasionally strip newlines from logging for various reasons. These include being able to replace the last printed line in the terminal for long loops that need constant progress being shown (for example the download of a very large file with a progress bar, which can be overwritten with ansi codes to return at the start of the line), or being able to append output when I'm looping an input() inside a try-catch and testing for valid answers.
I did this to avoid the problem:

```python
def logger_print(message, terminator="\n", *args, **kwargs):
    if terminator == "\n":
        logger.info(message, *args, **kwargs)
    else:
        logger.opt(raw=True).info(message + terminator, *args, **kwargs)
```
		
It works fine when the sink is sys.stdout. however if I'm also logging to a file (with different formatting, too) this causes a mess because the lines end up forming a single large line.
Is there no way to configure line terminator per-sink, like it's already possible in python's default logging library? Because I want to be able to strip the newline only when printing to terminal even if other sinks are active.
For reference: https://docs.python.org/3/library/logging.handlers.html#streamhandler

**Comment by nonamethanks** [comment]
Seems the issue is that commit 49c5560825f4c8e60ab11cba9ead62d4df06048e added terminators but no way to configure them on a per-stream basis.

**Comment by Delgan** [comment]
I think you might benefit from using a custom `format` function. What about something like this:

```python
def my_format(record):
    end = record["extra"].get("end", "\n")
    return "{time} {message}" + end + "{exception}"

logger.add(sys.stderr, format=my_format)
logger.info("Line ending added as usual.")
logger.bind(end="").info("No line ending.")
```

**Comment by nonamethanks** [comment]
Yes, that does it. Unfortunately, since then subsequent lines then have to start with "\n" to end up in a new line, as a result the log file also gets the newline, and end up looking like this:

```
2020-03-26 21:19:56.790 | INFO     | lib:func:108 - <stuff>
2020-03-26 21:19:57.288 | WARNING  | __main__:process:95 -
My output.
2020-03-26 21:20:56.632 | INFO     | lib:func:102 - <more stuff>
```
So I have to either litter the code with `log.warning("")` instead of using newlines, or write a wrapper to split the message by newline before sending it to the logger, but that means I have to write a wrapper for every log level, so something like

```python
def logger_info(message="", end="\n", *args, **kwargs):
    for line in message.split("\n"):
        logger.bind(end=end).info(message, *args, **kwargs)

logger._info = logger_info
```
which would be fine if there weren't 8 different levels. Note that I also cannot easily overwrite the methods to the same name because the bind method returns a new Loader instance instead of temporarily change internal parameters, which causes all changes to the class to be useless, so I end up with eight additional methods names to deal with.

I understand however that this is an edge case and devolves from the purpose of this issue, so your solution kind of solves the question I asked. For my issue I think I'll just have to write a wrapper class and assign as properties as many loggers as the outputs I'm using are, and let the wrapper class deal with the various terminators for each output.

**Comment by Delgan** [comment]
Can you make use of the [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) method to avoid the need of a wrapper for each level? You could populate the `extra` dict of the record with a `reformatted_message` string and access it from your custom `format` function.

Alternatively, you could maybe `filter`-out problematic messages from your file sink. I guess you don't need to write a progress bar in there.

What would be the expected output inside your file?

There is a snippet in the tests which basically looks like that:

```python
def formatter(record):
    end = record["extra"].get("end", "\n")
    return "[{time}] {message}" + end

logger.add(sys.stderr, format=formatter)
logger.add("foo.log", mode="w")

logger.bind(end="").debug("Progress: ")

for _ in range(5):
    logger.opt(raw=True).debug(".")

logger.opt(raw=True).debug("\n")

logger.info("Done")
```
```
# sys.stderr
[2020-03-26T22:47:01.708016+0100] Progress: .....
[2020-03-26T22:47:01.709031+0100] Done
```
```
# file.log
2020-03-26 22:47:01.708 | DEBUG    | __main__:<module>:12 - Progress: 
.....
2020-03-26 22:47:01.709 | INFO     | __main__:<module>:19 - Done
```
Otherwise, why not share the custom formatter to all the sinks?
