### ISSUE TITLE
Improve contextualize doc and pyi files.

### ISSUE THREAD

**Issue by heckad** [Delgan/loguru#233]
You use for `contextualize` python's `contextmanager` wich creates `_GeneratorContextManager` wich inherits from `ContextDecorator` which allow use context manager as decorator. For example 
```
from loguru import logger


@logger.contextualize(task_id=123)
def task():
    logger.opt(record=True).info("Processing {record[extra]}")


if __name__ == '__main__':
    task()
```

Now mypy raise error: `example.py: 4: error: "ContextManager[Any]" not callable`

**Comment by Delgan** [comment]
Good catch, thanks! 

Initially, `logger.contextualize()` was not intended to be used as a decorator but I don't see any reason to prohibit such usage, so I will update the type hints accordingly.

**Comment by heckad** [comment]
It can be useful for add states in additional params. For example
```
class App:
    @logger.contextualize(state='init_app')
    def init(self):
         # do something
```
If there weren't such an opportunity, you would have to add a level of nesting

**Comment by heckad** [comment]
@Delgan, when do you planning to change the type in type-hint?

**Comment by Delgan** [comment]
I'll probably add it to the `master` branch this weekend, but you will have to wait a few weeks because there are other bugs I want to fix before publishing a new release.

**Comment by Delgan** [comment]
Merged. :+1:
