### ISSUE TITLE
Using logger.exception() with a custom exception object.

### ISSUE THREAD

**Issue by baptiste0928** [Delgan/loguru#235]
Hello everyone! 😄 

I use a global function to handle all errors in a program, to which I pass the exception object. I needed in this function to modify `logger.exception()` in order to display an exception with traceback from an object (and not from `sys.exc_info()`).  With my changes, the function asks for an optional exception argument to manually pass the exception object.

I would like these changes to be implemented in loguru, but **as requested in the contribution guidelines, I ask here if this is a good idea 😋**

The new code (without tests) looks like this : 
```python
# loguru/_logger.py:1905
def exception(__self, __message, *args, exception=None, **kwargs):
    r"""Convenience method for logging an ``'ERROR'`` with exception information."""
    options = ((True if not exception else exception),) + __self._options[1:]
    __self._log("ERROR", None, False, options, __message, args, kwargs)
```

Well, I hope my idea will be useful! 💪

**Comment by Delgan** [comment]
Hey @baptiste0928, thanks for your interest in contributing to the project! :smiley: 

I'm not sure you noticed it, but it seems to me that such a feature is already possible by using the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method:

```python
logger.opt(exception=your_exception).error("Your error message")
```

This argument will automatically call  `sys.exc_info()` if equals to `True`, but it also accepts an exception `tuple`. :+1:

**Comment by baptiste0928** [comment]
Oh great, I didn't actually know. 👍 It would be good to make this clear in the readme example, in my opinion.

Thanks for your help 😄

**Comment by Delgan** [comment]
Alright, I tried to indicate that one could also use a tuple for `opt(exception=...)` directly in the Readme. :+1: 

Keep on having fun.  :smiley:
