### ISSUE TITLE
Adding dynamic payload to record

### ISSUE THREAD

**Issue by alberto-miranda** [Delgan/loguru#236]
Hi @Delgan,

Is it possible to add dynamic information to a message record when the message is emitted? That is, something like `bind()` but for messages:

```python
# illustrative syntax, can probably be improved
logger.opt(extra=("requires_prefix", True)).info("hello world!")
```

In this case, a new entry `record["extra"]["requires_prefix"]` would be added to the record, which could be validated in a formatter. The reason why we would like do this, is to dynamically decide in a custom formatter whether certain messages should include a prefix or not. Was this to be supported our formatter could work like this:

```python

class Formatter:
    def format(self, record):
        fmt_prefix = "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} | "

        # this cannot be done right now AFAIK
        if "requires_prefix" in record["extra"] and record["extra"]["requires_prefix"]: 
            return fmt_prefix + "{message}";
        else:
            return "{message}";

```

**Comment by Delgan** [comment]
Hi @alberto-miranda. I don't understand: why not use `bind()`?

```python
logger.bind(requires_prefix=True).info("hello world!")
```

**Comment by alberto-miranda** [comment]
As far as I understood (and correct me if I'm wrong), `bind` serves to add context to a logger instance, but there is not mechanism to modify that context individually for each logger message, isn't there?. 

In my example with the syntax above, the statements below would produce two very different results:

```python
In[1]: logger.opt(extra=("requires_prefix", True)).info("hello world!")
Out[1]: "2020-04-02 19:48:32.162 | INFO     | conftest:caplog:182 | hello world!"

In[2] logger.info("hello world!")
Out[2]: "hello world!"
```

**Comment by Delgan** [comment]
The `bind()` method returns a new logger instance to which the value is bound. The logger instance on which `.bind()` was called is not mutated, that's why chaining `logger.bind(requires_prefix=True).info("hello world!")` will modify the context only for the currently logged message.

**Comment by alberto-miranda** [comment]
Nice, that certainly solves our problem. As an additional question, is it in any way possible to access the parent logger from the `record` instance passed to the custom formatter? Or are they completely decoupled?

**Comment by Delgan** [comment]
They are decoupled, but the new logger instance "inherits" from the bound values of the parent.

```python
logger = logger.bind(foo=1)  # extra == {'foo': 1}
logger = logger.bind(bar=2)  # extra == {'foo': 1, 'bar': 2}
```

**Comment by alberto-miranda** [comment]
Ok, good enough. Thanks!
