### ISSUE TITLE
Repeat Write Log

### ISSUE THREAD

**Issue by biggerbiggest** [Delgan/loguru#240]
Continuous running, plus one per repetition

**Comment by biggerbiggest** [comment]
looger.remove()

**Comment by biggerbiggest** [comment]
logger.remove()   #  <----------Add this sentence !!!!!
logger.add(f'demo/demo.log', enqueue=True)
logger.debug(info)

**Comment by Delgan** [comment]
Hi @biggerbiggest. Can you please be more specific about the problem you are facing? I'm having trouble understanding your question / suggestion. Do you need help to configure the `logger`?

**Comment by Delgan** [comment]
In the absence of an answer, I'm closing this issue. If you have any questions left feel free to reopen it and add details about the problem you are facing.
