### ISSUE TITLE
Log rotate by time and size

### ISSUE THREAD

**Issue by mahadi** [Delgan/loguru#241]
Hi, is it possible to rotate a logfile by duration and file size (and finally compress it)? Currently i only see that o can choose duration or file size but not both at the same time.

**Comment by Delgan** [comment]
Hi. :)

Loguru does not provide such possibility directly. To do this, you need to implement a custom `rotation` function. For example:

```python
def rotation(message, file):
    file.seek(0, 2)
    if file.tell() + len(message) > 10000:
        return True
    if message.record["time"].time() > datetime.time(12, 0, 0):
        return True
    return False

logger.add("file.log", rotation=rotation)
```

**Comment by mahadi** [comment]
Hi, you are right, this is one way to do this :)

But i guess
``` python
if message.record["time"].time() > datetime.time(12, 0, 0):
        return True
```
would rotate for every message after 12am?

How would you write that for a timedelta? (Since it needs to know the start time of the current file?)

**Comment by Delgan** [comment]
@mahadi Oups, yeah, sorry. >.<

Well, you probably need to use a `class` then. Something like this:

```python
from datetime import datetime, timedelta, time

class Rotator:

    def __init__(self, size, time):
        self._size = size
        self._time = datetime.now().replace(hour=time.hour, minute=time.minute, second=time.second)

    def should_rotate(self, message, file):
        file.seek(0, 2)
        if file.tell() + len(message) > self._size:
            return True
        if message.record["time"].timestamp() > self._time.timestamp():
            self._time += timedelta(days=1)
            return True

rotator = Rotator(10000, time(12, 0, 0))
logger.add("file.log", rotation=rotate.should_rotate)
```

**Comment by mahadi** [comment]
Thanks for the hint! Will use it :)
Thanks also for the great library!

Btw: `rotation=rotate.should_rotate` should be `rotation=rotat**or**.should_rotate`.

**Comment by Delgan** [comment]
Great, glad it worked for you! :smile: 

I'm closing this issue then. :+1:

**Comment by mahadi** [comment]
Just for completeness: This is a small fix to prevent immediate log rotation if the current time is already past the given time:

``` python
class Rotator:

    def __init__(self, size, at):
        self._size = size
        now = datetime.now()
        today_at_time = now.replace(hour=at.hour, minute=at.minute, second=at.second)
        if now >= today_at_time:
            # the current time is already past the target time so it would rotate already
            # add one day to prevent an immediate rotation
            self._next_rotate = today_at_time + timedelta(days=1)
        else:
            self._next_rotate = today_at_time

    def should_rotate(self, message, file):
        file.seek(0, 2)
        if file.tell() + len(message) > self._size:
            return True
        if message.record["time"].timestamp() > self._next_rotate.timestamp():
            self._next_rotate += timedelta(days=1)
            return True
        return False
````

**Comment by dushitaoyuan** [comment]
that't great!,may be a small fix:
`
class Rotator:
    def __init__(self, str_size, str_time):
        self._size = string_parser.parse_size(str_size)
        at = string_parser.parse_time(str_time)
        now = datetime.now()
        today_at_time = now.replace(hour=at.hour, minute=at.minute, second=at.second)
        if now >= today_at_time:
            # the current time is already past the target time so it would rotate already
            # add one day to prevent an immediate rotation
            self._next_rotate = today_at_time + timedelta(days=1)
        else:
            self._next_rotate = today_at_time

    def should_rotate(self, message, file):
        file.seek(0, 2)
        if file.tell() + len(message) > self._size:
            return True
        if message.record["time"].timestamp() > self._next_rotate.timestamp():
            self._next_rotate += timedelta(days=1)
            return True
        return False
size_time_rotator = Rotator("500 MB", "20:41")

`
and the test code

`
limit_min = 43
while True:
    now = datetime.now()
    if now.minute > limit_min:
       break
    else:
        LOG.info(" LOG LOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOGLOG")
        time.sleep(1)

print("finsh")

`

**Comment by mathurdeepak13** [comment]
hello there,

I followed the Rotator.should_rotate, but the name of rotated file is in order of "name.time.log". Is it possible that it rotates in order of "name.log.time" ?

this is my code:

```
class Rotator:
    def __init__(self, at):
        now = datetime.datetime.now()
        self.time_limit = now.replace(
            hour=at.hour,
            minute=at.minute,
            second=at.second
        )
        if now >= self.time_limit:
            self.time_limit += datetime.timedelta(days=1)

    def should_rotate(self, message, file):
        if message.record["time"].timestamp() > self.time_limit.timestamp():
            self.time_limit += datetime.timedelta(days=1)
            return True
        return False

def create_logger(conf: dict):
    logger.remove()
    rotator = Rotator(at=datetime.time(0, 0, 0))
    logger.add(
        "test_app.log",
        rotation=rotator.should_rotate,
        retention=conf['retention'],
        backtrace=False,
        level=conf['log_level'].upper(),
        format=formatter
    )
```

below is list of log files it creates:
```
-rw-r--r--  1 159 May  4 12:44 test_app.2021-05-04_12-44-55_191362.log
-rw-r--r--  1 185 May  4 12:44 test_app.2021-05-04_12-44-55_194395.log
-rw-r--r--  1 163 May  4 12:44 test_app.2021-05-04_12-44-55_192883.log
-rw-r--r--  1 205 May  4 12:45 test_app.log
```

however, the needed behavior should be:
`-rw-r--r--  1 159 May  4 12:44 test_app.log.2021-05-04`

any help would be much appreciated.

thanks,
D

**Comment by mancioshell** [comment]
And if i would like to rotate every hour and every time log exceeds a file size ?

**Comment by Delgan** [comment]
@mancioshell Surely you can adapt the `should_rotate()` function in the above snippets so that it returns `True` only when both condition are met, right?

**Comment by mancioshell** [comment]
I'm sorry, I explained myself badly :)
I would like to rotate every hour **or** every time log exceeds a file size. But i think in the example above it rotate every time log exceeds a file size or at a particular time (eg. 12:00 PM)

**Comment by mahadi** [comment]
Then your question is actually, how to achieve a rotation every hour, right? Because the size issue is already solved above.

**Comment by mancioshell** [comment]
@mahadi yep. I would like to rotate the log every hour or every time it exceeds 100Mb of size. Any advice to edit the example in the docs for my use case?

**Comment by Delgan** [comment]
@mancioshell Did you try amending the snippet with `self._next_rotate += timedelta(hours=1)` instead of `self._next_rotate +=  timedelta(days=1)`?

**Comment by mancioshell** [comment]
@Delgan could the following code works ?

```
class Rotator:

    def __init__(self, *, size, at):
        now = datetime.datetime.now()

        self._size_limit = size
        self._time_limit = now + datetime.timedelta(hours=1)

    def should_rotate(self, message, file):
        file.seek(0, 2)
        if file.tell() + len(message) > self._size_limit:
            return True
        if message.record["time"].timestamp() > self._time_limit.timestamp():
            self._time_limit += datetime.timedelta(hours=1)
            return True
        return False
```

**Comment by Delgan** [comment]
@mancioshell I guess it should. :)

**Comment by kanghaov** [comment]
if I want loguru rotate everytime I run the thread,How should I do 
ple

**Comment by Delgan** [comment]
@kanghaov Please can you open a new ticket describing more precisely the issue you're facing?
"Every time I run the thread" is not very clear to me.
