### ISSUE TITLE
Intercepting logging logs

### ISSUE THREAD

**Issue by xeor** [Delgan/loguru#247]
I am using the recommended `InterceptHandler` as documented, but I am still getting logs from different loggers around from 3rd party libs.

I am able to get them intercepted by using something like:

```py
_log = logging.getLogger('aioredis')
_log.handlers = [InterceptHandler()]
```
But then I am getting double log-messages for `aioredis`, one default and one with the loguru format.

Setting `logging.basicConfig(handlers=[InterceptHandler()], level=0)` isnt doing much either.

Have I missunderstood what this InterceptHandler() is supposed to do?
I have the log-config code as early in my code as possible.

Maybe the aioredis lib is changing my config later?

Any tips on a proper way to setup interception of ALL logger logs would be nice.. It would be nice to essentially switch over, monkeypatch and route all the logger logs via loguru :)

**Comment by Delgan** [comment]
Usually the `basicConfig()` snippet should work fine: it adds the handler to the root logger of the standard `logging` system, so it will intercept all logs coming from third-applications. It we look at the [`basicConfig()`](https://docs.python.org/3/library/logging.html#logging.basicConfig) configuration, it's explained that the function does nothing if handler is already registered. Is it possible in your case that another handler is configured for standard `logging`? It would explain why you are seeing the logs twice when you manually add the handler to the `aioredis`'s logger. Also, it seems [`aioredis` automatically setups a logger](https://github.com/aio-libs/aioredis/blob/050e4dd87d177bb5a9fb2f681b25af5826ac85f5/aioredis/log.py) if `"AIOREDIS_DEBUG"` is found in the environment variables, maybe you should double-check that.

**Comment by xeor** [comment]
Thanks for the quick reply! I tried the `_log.handlers = [InterceptHandler()]` trick for everything I could find in `logging.root.manager.loggerDict`, including the `root`-logger :(

I will look around some more, keeping the issue open for some days so I can post the solution if I find it :)

**Comment by Delgan** [comment]
If you can share any reproducible example using `aioredis` maybe I can help you debugging this. :grin:

**Comment by xeor** [comment]
Thats nice! Thanks

I wrote up a quick demo of the problem at https://gist.github.com/xeor/894f332975042902a0ab265877b171ef

It outputs now:

```
2020-04-15 10:16:46.683 | INFO     | __main__:setup_loguru:19 - hello 1 from loguru
hello 1 from logger
2020-04-15 10:16:46.684 | INFO     | __main__:setup_classic:13 - hello 1 from logger
2020-04-15 10:16:46.684 | INFO     | __main__:<module>:59 - hello 2 from loguru
hello 2 from logger
2020-04-15 10:16:46.684 | INFO     | __main__:<module>:60 - hello 2 from logger
```

If there was a way to disable the output stream from the `logging` module in this example, I think it would have fixed the issue.. The output I'm trying to get is hello 1 (from both), and hello 2 from both, but formatted using loguru..

**Comment by xeor** [comment]
Thanks for the explanation! I hoped loguru would take away some of these pain-points, but I see the problem now... :)

I am just starting with loguru, so is there a better way to do this then?

Basicly, the goal is to use loguru for as much as possible, but there are a bunch of 3rd party libs that is problematic.

One way I kinda got it to work (unless it's cheating) :p

`logging.StreamHandler = InterceptHandler`

and then just don't do any of `overwrite_loggers` or `setup_intercept`

Is there any reason this shoulnt be done in this case as you can see?

**Comment by Delgan** [comment]
Unfortunately, Loguru can't fix libraries which are inherently "broken". :sweat_smile: 

It is explicitly stated in the `logging` documentation that libraries should **not** add any handler: [Configuring Logging for a Library](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library).
I don't even think it's technically fixable except by monkeypatching `logging` functions.

Replacing `logging.StreamHandler` with `InterceptHandler` is, well... A pretty hack. :)
It may work but one day or the other, it will backfire on someone expecting an actual `StreamHandler`.

Ideally, you should modify the "classic logger" after importing the library, but before using its functions. This way, we can imagine that the logger will have finished being configured (so you can remove the `StreamHandler`), but it will not have started logging messages yet.

**Comment by xeor** [comment]
I've learned a lot about logging today... Thanks for taking the time to explain all this!

It wasnt the lib not behaving. I looked at the `logging` object that was sending the logs, and it had propegate=True, and since I used `--log-level debug` in uvicorn, it had set the root logger to DEBUG as well..

The simple solution was to add the line `logging.getLogger().handlers = [InterceptHandler()]` as well as the one for basicConfig..

Strange that not anyone else have hit this problem.. I think the root cause is that I want to use the uvicorn cli param. So to get the loglevel inside the app, I use `logging.getLogger('uvicorn').getEffectiveLevel()` as  well..

Should `logging.getLogger().handlers = [InterceptHandler()]` be added as a note in the doc?

**Comment by Delgan** [comment]
Great you figured out a workaround! :tada: 

I just found this issue opened a few days ago on the `uvicorn` bug tracker, it looks related to the problem you faced: https://github.com/encode/uvicorn/issues/630

I don't think it should be added to the documentation, as it's more of a solution specific to a particular "misconfigured" library. Usually, the snippet with `basicConfig()` alone works fine. But I could always redirect people to this issue if they encounter the same problem.

**Comment by xeor** [comment]
Thanks for the finding! Removing the root-logger line (https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L86) from uvicorn also fixed the issue for me. After removing, the aioredis (and all other logs) are now handled by loguru, no `logging.getLogger().handlers = [InterceptHandler()]` needed :)

**Comment by pawamoy** [comment]
I posted a solution to intercept everything (gunicorn/uvicorn/fastapi/etc.) [here](https://github.com/benoitc/gunicorn/issues/1572#issuecomment-638391953), hope this helps the next ones who want to do the same thing :slightly_smiling_face:

**Comment by Delgan** [comment]
Thanks a lot for sharing your solution, @pawamoy! :smiley: 

From now on, I will systematically refer to [your blog post](https://pawamoy.github.io/2020/06/02/unify-logging-for-a-gunicorn-uvicorn-app/) as soon as an user asks for help to configure `loguru` with `guvicorn`. :smiley:

**Comment by nbraun-wolf** [comment]
How can we have hot reload when following this blogpost? @Delgan  @pawamoy ? When I pass reload to the server, it isnt working.

**Comment by Delgan** [comment]
@nbraun-wolf I don't know about the hot reload, but if you don't want logs to be saved to a file, can't you simply remove the corresponding `logger.add()` call?

**Comment by pawamoy** [comment]
@nbraun-wolf if you read the comments on the blog post, you'll see that someone offered [a solution](https://github.com/pawamoy/pawamoy.github.io/issues/17#issuecomment-887259019) that works with hot-reloading.
