### ISSUE TITLE
Missing exception log data when using pyinstaller

### ISSUE THREAD

**Issue by jacobthetechy** [Delgan/loguru#250]
I'm using loguru in one of my projects while using pyinstaller to create an EXE to run it on several Windows machines. I noticed some log data missing from exceptions when running the EXE. Here is an example of what I'm seeing.

```python
# test.py

from loguru import logger

logger.add('test.log')

def div(n, d):
    try:
        return n / d
    except Exception as e:
        logger.exception(e)

div(2, 0)
```
When running this from the terminal it will produce this log file as expected.

```log
2020-04-20 12:46:32.123 | ERROR    | __main__:div:9 - division by zero
Traceback (most recent call last):

  File "test.py", line 11, in <module>
    div(2, 0)
    └ <function div at 0x7f81f5ee43b0>

> File "test.py", line 7, in div
    return n / d
           │   └ 0
           └ 2

ZeroDivisionError: division by zero
```

But once you use pyinstaller (`pyinstaller test.py -F`) and run the resulting EXE this is what is in the log file.

```log
2020-04-20 12:45:19.427 | ERROR    | __main__:div:9 - division by zero
Traceback (most recent call last):

  File "test.py", line 11, in <module>

> File "test.py", line 7, in div

ZeroDivisionError: division by zero
```

I have been able to reproduce this with python 3.8 on Windows 10 and python 3.7 on Fedora 30 using loguru==0.4.1 & PyInstaller==3.6

Not sure if this is an pyinstaller issue or a loguru issue, trying here first.

**Comment by Delgan** [comment]
Hey @jacobthetechy, thanks for the report and the reproducible example!

I made some tests. 

Running `./test` from within the generated `dist` folder:

```bash
2020-04-20 21:58:50.027 | ERROR    | __main__:div:10 - division by zero
Traceback (most recent call last):

  File "test.py", line 12, in <module>

> File "test.py", line 8, in div

ZeroDivisionError: division by zero
```

Running `./dist/test` from the repository where the `pyinstaller` command was run:
```bash
2020-04-20 21:58:44.926 | ERROR    | __main__:div:10 - division by zero
Traceback (most recent call last):

  File "test.py", line 12, in <module>
    div(2, 0)
    └ <function div at 0x7f6fdf29b040>

> File "test.py", line 8, in div
    return n / d
           │   └ 0
           └ 2

ZeroDivisionError: division by zero
```

I guess this is related to [`linecache.getline()`](https://docs.python.org/fr/3.8/library/linecache.html#linecache.getline) which can't retrieve the source for some unknown reason. 

However, I don't think we can fix that on the `loguru` side. You can try to replace `logger.exception()` with `traceback.print_exc()` and you're gonna see the same problem. :confused:

**Comment by jacobthetechy** [comment]
Do I need to create an issue with pyinstaller then?

**Comment by Delgan** [comment]
Yeah, I think they'll be better able to give you an explanation. :+1:

**Comment by jacobthetechy** [comment]
[Pyinstaller issue filed](https://github.com/pyinstaller/pyinstaller/issues/4826)

**Comment by jacobthetechy** [comment]
[https://github.com/pyinstaller/pyinstaller/issues/4826#issuecomment-617728206](https://github.com/pyinstaller/pyinstaller/issues/4826#issuecomment-617728206) This worked for me. Thanks again for the help @Delgan
