### ISSUE TITLE
Support getting/updating handlers?

### ISSUE THREAD

**Issue by ysmu** [Delgan/loguru#251]
I'm looking for something similar to #239.

I have a program that is designed to run arbitrary many plugins sequentially during its lifetime. The program initializes the global loguru logger with the appropriate handlers for itself and the plugins to use. Now, I have a plugin that would like to use tqdm. For the logger to play well with tqdm, it needs to reconfigure the logger to not write directly to `stderr`, but with `tqdm.tqdm.write` (while keeping the other handlers intact). I'm looking for a way for the plugin to not only achieve this, but also restore the handler to write to `stderr` after it is done with tqdm.

Of course this is just one example. The plugin may use a different progress bar library or spawn worker processes and require all handlers to have `enqueue=true` during its execution.

If it's not possible to do a live update on the handlers, is it possible to expose copies of the handlers? The `logger.get_config()` API suggested in #239 would be amazing to have.

**Comment by Delgan** [comment]
Hi @ysmu.

I'd really rather not expose the handlers. Still, there is certainly a solution to your problem. 

One possibility is to move the logic to choose the "write mode" inside the sink, which avoids having to remove / add / modify the handlers.

```python
def sink(message):
    if message.record["extra"].get("with_tqdm", False):
        tqdm.write(message, end="")
    else:
        sys.stderr.write(message)

logger.add(sink)

with logger.contextualize(with_tqdm=True):
    for i in tqdm(range(100)):
        logger.info("=>", i)
```
However, it has the disadvantage that the main program has to be "aware" of all possible alternatives. As you said, each plugin can have very different needs. If you want it to be perfectly independent, this is not a viable solution.

Alternatively, you could allow your plugins to re-configure the handlers by themselves. Each plugin will manage its own set of handlers, by letting your main program call `plugin.configure_logger()`. This seems the more appropriate solution.

If you really want to have one common list of handlers, you will need to explicitly pass a custom `{id: sink}` dict from your main program to your plugins, but I don't think it's advisable to try to modify handlers once they've been added.

**Comment by ysmu** [comment]
Thanks for the suggestions. I would prefer if I have one common list of handlers. If the user configures the logger to log to a specific file, logs produced by the plugins should also go into the same file.

I'm sure updating the handlers won't be ideal in a lot of cases (i.e. I don't think I can just set `enqueue=True` to a handler`), which is why I really like the proposed `logger.get_config()` API. That being said, I can probably save the arguments passed to `add()` and create my own `get_handler_config()` for the plugins. I'll probably explore this route.

Thank you again for the quick response and the great library!

**Comment by Delgan** [comment]
Ok, sorry for not wanting to add the function you suggested, but the idea of "get the current configuration to re-add handlers" doesn't seem globally "good" to me. That's why I'd rather not add it to the api. If you encouter any trouble implementing a workaround, feel free to ask me for help though. :+1:
