### ISSUE TITLE
loguru vs python-telegram-bot

### ISSUE THREAD

**Issue by heliomcp** [Delgan/loguru#252]
I need some help,

I am using the built-in logging in my [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) and it works fine

After trying **loguru** instead the built-in logging and if I have some issue in the code (any error) I don´t have any error message. Is like everything is ok...

 I only realize the error if I go back to build-in logging.

[python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) uses [built-in logging](https://github.com/python-telegram-bot/python-telegram-bot#logging).

Is there a way I can use **loguru** with [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot)?

**Comment by Delgan** [comment]
Hi @heliomcp.

Did you try to add an handler to intercept messages from standard `logging` and propagate them to `loguru`? There is a snippet about this in the documentation:

```python
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())

logging.basicConfig(handlers=[InterceptHandler()], level=0)
```

**Comment by heliomcp** [comment]
Thank you for your answer. It works great 👍 

My fault I didn't read the documentation... sorry.
