### ISSUE TITLE
An idea for getting around Windows multiprocessing

### ISSUE THREAD

**Issue by JulianOrteil** [Delgan/loguru#259]
Good day,

I would like to start out this by saying I am no expert in how multiprocessing works in Windows. What I do know is that modules in Python are reloaded in subprocesses when the subprocesses are started. Also, not all objects can be pickled by multiprocessing and hence why loguru is not multiprocessing-safe.

Here's an idea:
In my limited experience with this topic, I've noticed that the os.environ variables set in the main process are available in any child processes.

For example:
The main process enters 'A', 'B', and 'C' using os.environ["LETTER_HERE"] = "SOME_VALUE".
In the child processes, these variables are still available and are retrievable via os.environ.get or os.environ["LETTER_HERE"], to name a few.

Based on this information, would there be any value to exporting the sink configurations in loguru as a dictionary (as you can convert a dictionary to a string using the built-in 'str', which is required by os.environ) to the environment variables?  Then you can retrieve them at loguru's instantiation (i.e. 'from loguru import logger') in the child processes and rebuild the sinks?

Just an idea, let me know what you think.

**Comment by Delgan** [comment]
Hi @JulianOrteil.

There is an entry on the documentation about `mutliprocessing` with `loguru`, particularly on Windows. Can you please tell me if this answers any of your questions?

* [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)

Rebuilding the sink in the child process would be quite complicated. It's better to configure the sink with `enqueue=True` (for mulitprocess-safety) in the main process, and then pass the `logger` while spawning child process using the `initializer`.

**Comment by Delgan** [comment]
@JulianOrteil Did you manage to deal with `multiprocessing` using the recommendations the documentation?

**Comment by JulianOrteil** [comment]
My apologies for my absence with this @Delgan 
I got caught up in a different area of the project I'm working on that I completely forgot about this. Yes, we were able to. The primary backend engineer took a look at your suggestions in the documentation and was able to implement it correctly. Thank you for your suggestions.

**Comment by Delgan** [comment]
No problem, thanks for the update @JulianOrteil. :+1:
