### ISSUE TITLE
How to capture excpetion

### ISSUE THREAD

**Issue by heckad** [Delgan/loguru#260]
```
@logger.catch
def some_method(...):
     raise SomeError
```

I want to capture this error by [capture_exception](https://docs.sentry.io/platforms/python/#capturing-errors). How to do it best?

Thanks

**Comment by Delgan** [comment]
Maybe by using the (future) `onerror` argument?

```python
@logger.catch(onerror=capture_exception)
def some_method(...):
    raise SomeError
```

**Comment by heckad** [comment]
When will this feature be released?

**Comment by Delgan** [comment]
Next week or so. :thinking:

**Comment by Delgan** [comment]
The `0.5.0` is released, `onerror` argument is now available. :+1:
