### ISSUE TITLE
Completely change format depending on active level

### ISSUE THREAD

**Issue by esciara** [Delgan/loguru#264]
Hi,

I would like to have the simplest format (only the records' message, no color or anything else) being displayed when the active level is `INFO`, and use `loguru`'s default format when active level lower (`DEBUG`, `TRACE`... anything below `INFO`'s value of `20`.

Could not quite workout how to do this, by trying to:

* Use two loggers and have one not display anything passed a certain severity level
* Use `filter` and `format` that would change depending on active level

Could you give any pointer?

**Comment by Delgan** [comment]
Hello @esciara. Both of your solutions seems good.

You can either use two different sinks like this:
```python
logger.add(sys.stderr, level="INFO", format="{message}")
logger.add(sys.stderr, level=0, filter=lambda record: record["level"].no < 20)
```
Or alternatively use a custom `format` function based on the level:
```python
def formatter(record):
    if record["level"].no >= 20:
        return "{message}\n{exception}"
    else:
        return (
            "<green>{time}</green> | <level>{level: <8}</level> | "
            "<cyan>{name}:{function}:{line}</cyan> - <level>{message}</level>"
            "\n{exception}"
        )

logger.add(sys.stderr, format=formatter, level=0)
```
