### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by mycaiden** [Delgan/loguru#265]
How to solve？

UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f4a5' in position 108: illegal multibyte sequence

**Comment by Delgan** [comment]
Take a look at this section of the documentation:

* [Resolving `UnicodeEncodeError` and other encoding issues](https://loguru.readthedocs.io/en/stable/resources/recipes.html#resolving-unicodeencodeerror-and-other-encoding-issues)

It's basically a problem with the encoding of your sink.

**Comment by Delgan** [comment]
@mycaiden Did you magage to solve this issue?

**Comment by Delgan** [comment]
I'm closing as I didn't get an answer, but I'm still willing to help you if you need it.
