### ISSUE TITLE
does loguru support multiple rotation ,like max_size and day  rotation="500 MB,00:00"

### ISSUE THREAD

**Issue by dushitaoyuan** [Delgan/loguru#266]
does loguru support multiple    rotation ,like max_size and day  rotation="500 MB,00:00"
i am a new pythoner,
should i set 
 logger.add(log_filename, rotation="500 MB")
 logger.add(log_filename, rotation="00:00")
can suit the logic?

**Comment by Delgan** [comment]
Loguru does not support rotation based on both size and time. :(

You will have to implement your own `rotation` function, look at the snippet here: https://github.com/Delgan/loguru/issues/241#issuecomment-612918318

```python
rotator = Rotator(5e+8, datetime.time(0, 0, 0))
logger.add(log_filename, rotation=rotator.should_rotate)
```
Adding two sinks logging to the same `log_filename` will very likely cause problems.

**Comment by dushitaoyuan** [comment]
ok,I understand, thank you ,have a good day!
