### ISSUE TITLE
Is it possible to catch the result of system command and record them in .log file?

### ISSUE THREAD

**Issue by IncubatorShokuhou** [Delgan/loguru#267]
Is it possible to catch the result in system command listed in terminal ( generated by `os.system` for example) and record them in .log file?

i.e.
```
import os
from loguru import logger

os.system("tar -zxvf 1.tar.gz")
```
if execute this stript, the files of `tar.gz` will be shown on the terminal. Is it possible to record the files in `.log` files, using loguru?

**Comment by Delgan** [comment]
This is a known problem with `os.system()`, it's not possible to capture the printed output. This [this question on Stackoverflow](https://stackoverflow.com/q/3503879/2291710).

You probably have to use [`subprocess.run()`](https://docs.python.org/3/library/subprocess.html#subprocess.run) or [`subprocess.Popen()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) if you want to be able to log the output of your command.

**Comment by IncubatorShokuhou** [comment]
@Delgan Thank you for your reply.
