### ISSUE TITLE
API Post/Put example

### ISSUE THREAD

**Issue by Sendery** [Delgan/loguru#268]
Question:
Please could you post a code example to use an http async post/put
I'm trying to use this:

```
async def publish(message):
... await api.post(message)
...
logger.add(publish, serialize=True)
´´´
```
replacing the "api" for requests(url, message)

but I only get it to work when i use custom asyncio:

```
class LoggerClass:
    def __init__(self,.....):
        from loguru import logger
        logger.remove()
        logger.add(sys.stdout,colorize=True, format="<green>{time}</green> | <level>{level:^6}</level> | <cyan>{file}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>",filter=non_errors)
        logger.add(sys.stderr,colorize=True, format="<green>{time}</green> | <level>{level:^6}</level> | <cyan>{file}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>",filter=errors_only)
    
        logger.add(self.publish, serialize=True,format="{message}")

    async def publish(self,message):
        print("API -> "+message)
        res= requests.post(self.log_api_url,data=message)
        print("RES STATUS -> "+str(res.status_code))
        #did try await request.post(self.log_api_url,data=message)

def main():
   import asyncio
   customclasslog=LoggerClass()


   loop = asyncio.get_event_loop()
   loop.run_until_complete(customclasslog.publish("api__"))
   loop.close()

   customclasslog.logger.info("THIS ENTRY DO NOT POST")
```

Thank you very much

**Comment by Delgan** [comment]
Hey @Sendery.

Maybe you need to await [`logger.complete()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.complete) to make sure the loop is not exited while some logging tasks are pending?

Here is an example of asynchronous logging:

```python
import asyncio
from loguru import logger


async def api_post(message):
    await asyncio.sleep(1)
    print("Async http post:", message)

async def publish(message):
    await api_post(message)

async def main():
    logger.info("Entry")
    await asyncio.sleep(0.5)
    logger.info("Exit")
    await logger.complete()

if __name__ == "__main__":
    logger.add(publish, serialize=True)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

**Comment by Sendery** [comment]
Thank you @Delgan after your example I understand that I was aming to a different implementation I was looking more for a "fire&forget" implementation, compare with the code above that is kinda "asyncronous loop scheduler", (sorry for the extrange wording)

Well this is more or less what I have:
```
import requests
from loguru import logger

def api_post(message):
    api_thread = threading.Thread(target=requests.post, args=(api_url,{"body":message},)) #the inline requests.post can be wrap in other function to process de response
    api_thread.start()
    
if __name__ == "__main__":
    logger.add(api_post, serialize=True)
```

Thank you very much for your time and for the loguru project

Feel free to close the issue.

**Comment by Delgan** [comment]
Did you try to `.add()` your handler with the `enqueue=True` argument? In this case, an internal thread is started to process log messages "asynchronously". It should prevent your HTTP requests to block your main thread.

However, it will not work very well if `api_post` is an `async` function. I think I can improve `loguru` on that side, probably by creating a new event loop inside the thread in order to handle log messages.

**Comment by Delgan** [comment]
I thought I could implement something internally so that the use of `async` sink would be handled concurrently automatically, but it looks too complicated (particularly because it is difficult to schedule a task in a different thread).

The best way to get "fire & forget" logging is to set `enqueue=True` with an regular sink function.
