### ISSUE TITLE
Capturing formatted message as a string

### ISSUE THREAD

**Issue by minitriga** [Delgan/loguru#269]
Hello, 

I need to capture a formatted message as a string to be used by something else. 

Is this possible?

```
>>> from loguru import logger
>>> logger.debug("That's it, beautiful and simple logging!")
2020-05-20 19:34:08.246 | DEBUG    | __main__:<module>:1 - That's it, beautiful and simple logging!
>>> string = logger.debug("That's it, beautiful and simple logging!")
2020-05-20 19:34:14.564 | DEBUG    | __main__:<module>:1 - That's it, beautiful and simple logging!
>>> string
>>> print(string)
```

Idealy i want the string variable to contain the formatted message of `2020-05-20 19:34:14.564 | DEBUG    | __main__:<module>:1 - That's it, beautiful and simple logging!`

I have been also trying this with the standard python logging module with no luck. 

> I do not want this log visible in the console view.

**Comment by Delgan** [comment]
Well, not really. Using the `logger` is meant to log message, not just format them. The best I can think of is to use a custom sink and combine it with `.bind()` to filter special messages.

Example:

```python
def do_something_special(message):
    print(message)

logger.add(do_something_special, filter=lambda record: "special" in record["extra"])
logger.add(sys.stderr, filter=lambda record: "special" not in record["extra"])

# Sent to 'stderr' but not 'do_something_special'
logger.info("Basic message")

# Sent to 'do_something_special' but not 'stderr'
logger.bind(special=True).info("Special message")
```

**Comment by Delgan** [comment]
@minitriga Have I answered your question?

**Comment by Delgan** [comment]
Closing, if you have any other question please ask me.
