### ISSUE TITLE
[Question] How to list exising handlers? How to add a filter to an existing handler?

### ISSUE THREAD

**Issue by radugrosu** [Delgan/loguru#270]
Currently I have to do:
```
def make_filter(spam: str) -> Callable[[Mapping[str, Any]], bool]:
    def spam_filter(record) -> bool:
        return spam not in record["message"]
    return spam_filter
logger._core.handlers[1]._filter = make_filter("spam")
```
I should mention that the logger is already configured, I just want to temporarily modify it when interacting with my application. This means I don't want to remove handlers and add new ones, I just want to modify existing ones.

Is there a non-hacky way to do this? 
Thanks

**Comment by Delgan** [comment]
It's not possible to access nor modify handlers once they have been added.

If you need to dynamically update some attribute, you have to do it through your object and not through the logger.

Example:

```python
class Filterer:
    def __init__(self, spam=None):
        self.spam = spam

    def filter(self, record):
        if self.spam is None:
            return True
        return self.spam not in record["message"]

filterer = Filterer()
logger.add(sys.stderr, filter=filterer.filter)

logger.info("No spam filtered")
filterer.spam = "spam"
logger.info("Spam filtered")
```

**Comment by radugrosu** [comment]
Thank you for the comments, I really appreciate them, and they will probably serve me well in other situations. Unfortunately for my particular situation the solutions you propose won't silence my existing handlers. 

I'm pasting my workaround below for people who want to selectively mute things when working in an interactive environment, e.g a jupyter notebook (see the hardcoded the `_stream` attribute of the sink in `set_filter`).
```
def make_filter(key: str, spam: str):
    def spam_filter(record) -> bool:
        return spam not in record[key]
    return spam_filter

def set_filter(sink: str, log_filter: Callable):
    for hid, handler in logger._core.handlers.items():
        name = getattr(handler._sink,  "_stream", None)
        if name is not None:
            handler._filter = log_filter
```
