### ISSUE TITLE
Is it fine to set a default return value for `logger.catch`?

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [Delgan/loguru#272]
Perform something like this
```python
try:
    return some_function()
except Exception:
    logger.exception("An error occurred")
    return default_value
```

what I've tried but cannot work: `@logger.catch(message="test", onerror=lambda _: DefaultValue)`

**Comment by Delgan** [comment]
Sounds like a good idea. I could add a `default` argument to `catch()` which would be the returned value in case of error.

**Comment by Delgan** [comment]
The new `default` argument will be available in next release. Thanks for the suggestion. :+1:
