### ISSUE TITLE
Add documentation about the "loguru-mypy" plugin

### ISSUE THREAD

**Issue by Delgan** [Delgan/loguru#277]
See: https://github.com/kornicameister/loguru-mypy

This plugin could be referred in the documentation page about type hints: https://loguru.readthedocs.io/en/stable/api/type_hints.html

**Comment by kornicameister** [comment]
Thx for that issue. I thought I will be able to finish work faster, but turned out there are few other things I have to devote time to :/. Once I get those out of my way, I will jump back to plugin.

**Comment by Delgan** [comment]
@kornicameister Thanks for the update! No pressure anyway, there is no need to rush. The development can go at its own pace according to one's priorities and free time.
