### ISSUE TITLE
How do I add thread name to msgs w/o changing anything else?

### ISSUE THREAD

**Issue by johnmudd** [Delgan/loguru#279]

**Comment by Delgan** [comment]
@johnmudd You have use a custom `format` specifying that the name of the thread must be displayed:

```python
import sys
from loguru import logger

logger.remove()  # Remove default handle whose format doesn't contain thread name
logger.add(sys.stderr, format="[{time}][{thread.name}] {message}")

logger.info("Test")
# '[2020-06-07T08:19:22.368783+0200][MainThread] Test'
```

All available field format are listed [in the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#record).

**Comment by johnmudd** [comment]
Thanks. I found the default format in the doc and modified it based on your example.

`log.add(sys.stderr, format='<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{thread.name}</cyan>:<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>')`
