### ISSUE TITLE
Any particular reasons why Logger._log() and Logger._options are protected?

### ISSUE THREAD

**Issue by herzog0** [Delgan/loguru#281]
In order to create another logging levels and be able to access them with dot notation I'm doing the following:
```python
from loguru import logger

def on(__message, *args, **kwargs):
    r"""Log ``message.format(*args, **kwargs)`` with severity ``'ON'``."""
    logger._log("ON", None, False, logger._options, __message, args, kwargs)

logger.level(name="ON", no=21, color="<m>", icon="")
setattr(logger, "on", on)

logger.on("something")
# Works as expected:
# 2020-06-08 02:18:50.976 | ON       | __main__:test_function:10 - something
```

Although this works, I'm getting these "Access to a protected member _log of a class" warnings (the same for _options).  

Are there any particular reasons for these attributes be protected?
Either way, is there a chance to expose them through properties on `Logger` so we can use them?

**Comment by Delgan** [comment]
The main reason is to keep the api simple. I did not find any use cases that required these attributes to be publicly displayed. In particular, `_log()` is very complicated and is only intended for internal use with knowledge of many implementation details.

If you want to use a custom level as a instance method, I think you can make use of `functools.partialmethod()`. There is a snippet about this use case in the documentation: [Using logging function based on custom added levels](https://loguru.readthedocs.io/en/stable/resources/recipes.html#using-logging-function-based-on-custom-added-levels).

Would that solve your problem?
