### ISSUE TITLE
Bind different logs to different log files separately by extra parameters

### ISSUE THREAD

**Issue by atifemreyuksel** [Delgan/loguru#291]
Hi,
I am trying to use loguru in my class. My aim is writing specific log to specific log file without writing it on both of them. For this reason, I prefer to use extra parameters. I put my code below:

```
class TaskLogger():
    def __init__(self):
        for store_name in ["store1", "store2"]:
            logger.add(f"log_{store_name}.log", format="{time:YYYY-MM-DD - HH:mm:ss} | {level} | {message}",\
                        filter=lambda record: record["extra"]["store"] == store_name, level="INFO")
            logger.add(f"log_{store_name}.log", format="{time:YYYY-MM-DD - HH:mm:ss} | <red>{level}</red> | {message}",\
                         filter=lambda record: record["extra"]["store"] == store_name, level="ERROR")
    
    def info_message(self, message, store_name):
        logger.bind(store=store_name).info(message)
        
    def error_message(self, message, store_name):
        logger.bind(store=store_name).error(message)
```
I am using JupyterLab. After declaring my class. I run the following lines:
```
job_logger = TaskLogger()
job_logger.info_message(message="message1", store_name="store1")
job_logger.info_message(message="message2", store_name="store2")
```

The result is that logger writes only "message2" to both files. "message1" cannot be written to both files even it is called after message2 line.
@Delgan how can I solve my problem? I think the bind logic is not run as I think. Thanks.

Python version: Python 3.6.10
Loguru version: Loguru 0.5.1
OS: MacOS
Environment: JupyterLab

**Comment by Delgan** [comment]
Hi @atifemreyuksel.

You're combining `logger`, `.bind()` and `filter` correctly. :+1: 
This is the correct way using Loguru to have specific logs emitted to specific files.

The only problem is that you are calling `.add()` four times, causing confusion in your logs as there are four different handlers.

I think you don't need to add handlers twice. There is no need to add one handler per level, because if you add an handler with `level="INFO"`, the `"ERROR"` messages will be logged too because the level severity is higher.

```python
for store_name in ["store1", "store2"]:
    logger.add(f"log_{store_name}.log", format="{time:YYYY-MM-DD - HH:mm:ss} | {level} | {message}",\
                filter=lambda record: record["extra"]["store"] == store_name, level="INFO")
```

**Comment by atifemreyuksel** [comment]
Thanks for your answer. I omitted multiple handlers and my TaskLogger class is like below:
```
class TaskLogger():
    def __init__(self):
        for store_name in ["store1", "store2"]:
            logger.add(f"log_{store_name}.log", format="{time:YYYY-MM-DD - HH:mm:ss} | {level} | {message}",\
                        filter=lambda record: record["extra"]["store"] == store_name)
    
    def info_message(self, message, store_name):
        logger.bind(store=store_name).info(message)
        
    def error_message(self, message, store_name):
        logger.bind(store=store_name).error(message)
```

But the same problem occurs after using this class. Although I can use filter and bind functions correcly as you stated, why only "message2" is written for both log files?

**Comment by Delgan** [comment]
Argh, that's a known gotcha with Python `for` loop and `lambda`: [Late Binding Closures](https://docs.python-guide.org/writing/gotchas/#late-binding-closures)

Basically, when creating the `filter` function, the `lambda` captures the `store_name` by reference and not by value. Which means later, when a message is logged, both filter functions use the last value assigned to `store_name` which is `"store2"`. The `"store1"` is completely lost.

The usual workaround is to create the `lambda` function with a default argument equals to the expected value iterated:

```python
filter=lambda record, store_name=store_name: record["extra"]["store"] == store_name
```

**Comment by atifemreyuksel** [comment]
Oh, I understand my mistake. Thank you so much @Delgan :)
