### ISSUE TITLE
Logging to file and not to console 

### ISSUE THREAD

**Issue by ramonemiliani93** [Delgan/loguru#292]
I have added the `logger.add("file.log")` to use solely the file as sink but I still get the logging on the console, what should be modified to avoid printing the logs to the console?

**Comment by Delgan** [comment]
The `logger` comes with a default handler logging to `stderr` for convenience. If you want to get ride of it, you can just [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) it.

```python
logger.remove()  # Remove all handlers added so far
logger.add("file.log")
```

**Comment by Delgan** [comment]
I'm closing this issue since it seems resolved. If you have any other question, please ask me. :+1:
