### ISSUE TITLE
Regulate deepness of backtracing exceptions

### ISSUE THREAD

**Issue by chwba** [Delgan/loguru#293]
So if I do something like:

```python
try:
   requests.get("https://someunreliablewebsite.com")
except:
  logger.exception("The site was unreliable again but i want to see it in the logs")
```
It will log the backtrace for me be back to all the libraries that have dropped errors consequtively :D (A lot of them when working with net-stuff). - Is there a way to limit the backtrace-deepness to only my code but not any libraries? Basically I just want to see the exceptions name and its message, not any deeper.

**Comment by Delgan** [comment]
Hi @chwba.

Did you try to add your handler with `backtrace=False`? It's not possible to have more fine-grained control over deepness of exceptions, aparty by setting the [`sys.tracebacklimit`](https://docs.python.org/fr/3/library/sys.html#sys.tracebacklimit) variable.

**Comment by chwba** [comment]
Thanks for the hints, ill play around  with them

**Comment by Delgan** [comment]
@chwba Did that solve your issue? Can I close this ticket or should I leave it open?

**Comment by chwba** [comment]
Yes, that was sufficient, thank you very much, and sorry for the late reply!
