### ISSUE TITLE
Bind() and globals

### ISSUE THREAD

**Issue by pikeas** [Delgan/loguru#295]
I'd like to log some context in a function:

```
from loguru import logger
def foo():
    logger.bind(foo='bar').info('step 1')
    # work
    logger.bind(foo='bar').info('step 2')
    # more work
    logger.bind(foo='bar').info('finished')
```

This feels repetitive, so let's clean it up:
```
from loguru import logger
def foo():
    logger = logger.bind(foo='bar')
    logger.info('step 1')
    # work
    logger.info('step 2')
    # more work
    logger.info('finished')
```

This is better, but doesn't actually work due to an `UnboundLocalError`, until we do:
```
from loguru import logger
def foo():
    global logger
    logger = logger.bind(foo='bar')
    logger.info('step 1')
    # work
    logger.info('step 2')
    # more work
    logger.info('finished')
```

This works, but the global feels hacky. There are other options, all of which feel differently hacky:
- `from loguru import logger as default_logger`, but this is more verbose and means every function will need to do `logger = default_logger` even when not adding binds.
- `with logger.contextualize(foo='bar')`, but this adds an additional level of indentation just for logging.
- `foo_logger = logger.bind(foo='bar')`, which adds no extra lines but adds a new "type" of logger that makes code maintenance harder (eg, find and replace).

Is there a cleaner way to do this?

**Comment by Delgan** [comment]
Yeah, the `UnboundLocalError` is a real pain but there is not much I can do about that. :(

My preference is to assign `logger_ = logger.bind()` or use `logger.contextualize()`. Using `global` seems wrong.

Alternatives are to either rely on a class and use `self.logger = logger.bind()` or create a `get_logger(name=None)` function performing the import instead of populating the global variables.

**Comment by Delgan** [comment]
I just thought on another solution, one can use `logger.contextualize()` as a decorator:

```python
@logger.contextualize(foo="bar")
def foo():
    logger.info('step 1')
    # work
    logger.info('step 2')
    # more work
    logger.info('finished')
```

Of course this implies the value needs to be known at the moment the function is declared.

**Comment by Delgan** [comment]
I'm closing this issue as I don't think there is any other solution that the one listed.
