### ISSUE TITLE
Usage example with Django

### ISSUE THREAD

**Issue by jnoortheen** [Delgan/loguru#302]
I am not able to find any examples that translates logging/dictconfig to loguru. [Here](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/components/logging.py) is a template repo that configures structlog. How this can be translated to use loguru as the default handler?

**Comment by Delgan** [comment]
I think you can combine the [`InterceptHandler()`](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging) in the Loguru's Readme with the Django's [`LOGGING`](https://docs.djangoproject.com/fr/2.2/topics/logging/) settings variable.

```python
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'intercept': {
            '()': InterceptHandler,
            'level': 0,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['intercept'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}

logger.remove()
logger.add(sys.stderr, format="[{time}] <lvl>{message}</>", level="INFO")
```

Does it generate the output you expected?

**Comment by jnoortheen** [comment]
This looks like a good starting point although it is not having all variables as the example. Thanks @Delgan

**Comment by Delgan** [comment]
> although it is not having all variables as the example

Which variables and example are you referring too?

If you think this example can be improved, let me know. It was indeed a basic example.

**Comment by jnoortheen** [comment]
the config from the example results in 
![image](https://user-images.githubusercontent.com/6702219/89772259-5b45ed80-db1f-11ea-881b-9c0188869df8.png)

the missing things are logger name(module that sent the log), stack trace formatter and coloring.

**Comment by Delgan** [comment]
Surely I'm missing something. The snippet I provided generate the following logs on my computer:

```
August 14, 2020 - 06:43:12
Django version 3.1, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[2020-08-14T06:43:18.293381+0000] "GET / HTTP/1.1" 200 16351
[2020-08-14T06:43:18.433020+0000] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2020-08-14T06:43:18.476148+0000] Not Found: /favicon.ico
[2020-08-14T06:43:18.476921+0000] "GET /favicon.ico HTTP/1.1" 404 1972
[2020-08-14T06:43:18.504801+0000] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2020-08-14T06:43:18.510395+0000] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[2020-08-14T06:43:18.527441+0000] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2020-08-14T06:44:09.146986+0000] "GET / HTTP/1.1" 200 16351
[2020-08-14T06:44:09.274918+0000] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
```

It looks the output you're seeing does not come from `loguru` configuration. :confused:

**Comment by jnoortheen** [comment]
@Delgan the one in image is from the `structuredlog ` config that I mentioned in the description's link. I was telling that those parts like module name, log level are missing from the loguru example you have mentioned.

**Comment by Delgan** [comment]
Thanks for the clarification. :)

Indeed, the `format` I provided as an example was very basic and missed useful data. I guess you've figured out how to customize it by now. Otherwise, feel free to ask me for more help.

**Comment by jnoortheen** [comment]
Thanks @Delgan . 

Just one thing, is there any method to list all format items available for logger ? 
 
![image](https://user-images.githubusercontent.com/6702219/94018971-da8d3900-fdce-11ea-8ccc-7e733cc4d0d9.png)

like {time}, {message} 

how we add new such item?

**Comment by Delgan** [comment]
All values from the `record` dict can be used in the `format` (because messages are basically logged by calling `format.format_map(record)`). You can find the list here in the documentation: [The record dict](https://loguru.readthedocs.io/en/stable/api/logger.html#record).

You can add your own by using [`logger.patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) if needed.

**Comment by hustonCun** [comment]
Hello @Delgan, tell me please how I can build message in my custom Handler with using `Catcher` (`logger.catch`)?
Or maybe there is another way to use `catch()` in django to handle all errors with it?

**Comment by Delgan** [comment]
Hey @hustonCun.

I don't know Django very well so you're question is not very obvious to me. The `logger.catch()` is not meant to be used an Handler, it's just syntactic sugar for `try /  except` block. However, it seems possible to capture Django errors using the `custom_exception_handler` function, see: [Custom exception handling](https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling).

Feel free to open a new ticket if you wish to discuss this issue further.
