### ISSUE TITLE
logging.add() not picking up sys.stdout config

### ISSUE THREAD

**Issue by fenchu** [Delgan/loguru#303]
Why is this logging.add() config not picked up?, it shows the default logging in colors:
```
#!/usr/bint/env python3
import argparse, os, sys
from loguru import logger as log
log.add(sys.stdout, colorize=False, format="{time:YYYYMMDDHHmmss}|{level}|{message}")

parser = argparse.ArgumentParser(description="")
parser.add_argument('--dir', help=f"directory where to find the files (default: %(default)s)", default="<directory path>")
args, unkownargs = parser.parse_known_args()
files = os.listdir(args.dir)
for f in files[:1]:
    log.info(f)
```

```
(nt-test-user) PS C:\dist\work\nt-test-users> python .\test.py
2020-08-05 11:31:42.390 | INFO     | __main__:<module>:11 - failedinserts_platformidstart_0000000099018000_count_1000.txt
20200805113142|INFO|failedinserts_platformidstart_0000000099018000_count_1000.txt
```

```
python --version
Python 3.8.5
pip freeze | grep loguru
loguru==0.5.1
[Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

**Comment by fenchu** [comment]
found a fix using log.remove() before the log.add()

**Comment by Delgan** [comment]
There is one default handler automatically added when you import `loguru`. It outputs to `sys.stderr`. This allows the `logger` to be used easily without any configuration.

If you prefer not to use this default handler, and you have to explicitly [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) it as you realized. It's not a "fix", it's the standard way to get rid of it. :smile: 

The other possibilities are to use [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) (which resets the handlers) or to set the `LOGURU_AUTOINIT` environment variable to `FALSE`.

**Comment by Delgan** [comment]
I'm closing this issue as you figured out a solution. If you have any question, feel free to ask me. ;)

**Comment by AlexanderPershin** [comment]
If anyone is still wondering how to remove the default logger, it is done as follows:
```python
logger.remove(0)  # remove default logger, id == 0
logger.add(
     # new logger config
)
```
I made a mistake by calling `logger.remove()` which didn't work
