### ISSUE TITLE
Question: Log specific message only to file but not to console

### ISSUE THREAD

**Issue by chwba** [Delgan/loguru#305]
```python
logger.remove()
logger.add(stderr, colorize=True, diagnose=True, backtrace=True)
log_dir = (Path(__file__).parents[3] / "logs")
log_dir.mkdir(exist_ok=True, parents=True)
logger.add(str(log_dir / "my_app.log"), rotation="10MB", filter=lambda record: "log_to_file" in record["extra"])
logger = logger.opt(colors=True)
logger = logger.patch(lambda record: record.update(name="MyApp"))
# To log to a file in addition to console do logger.bind(log_to_file=True).info("mylog")
```
This is what I use to either log to console and file or only to console. I could not figure out yet to log certain messages only to a file but not to the console, can you help me out?

**Comment by Delgan** [comment]
You have to use the same technique, using `bind()` and `filter` as you did for the file handler. You have to do something similar if you want to log to the console alone. Here is an example:

```python
logger.remove()
logger.add(stderr, filter=lambda record: record["extra"].get("log_to_console", True))
logger.add("my_app.log", filter=lambda record: record["extra"].get("log_to_file", True))

logger.info("Send to console + file")

logger_console = logger.bind(log_to_file=False)
logger_console.info("Send to console only")

logger_file = logger.bind(log_to_console=False)
logger_file.info("Send to file only")
```

This is just one possible implementations, it surely can be adapted to fully suit your needs.

Also, see this related part of the documentation: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers)
```

**Comment by Delgan** [comment]
@chwba Did that answered your question?

**Comment by chwba** [comment]
Sorry for the very late reply, lots of work lately, yes that works perfeclty, thank you very much!
