### ISSUE TITLE
Question: Does loguru support stacklevel as a kwarg for logger.debug/logger.info?

### ISSUE THREAD

**Issue by CloudZazu** [Delgan/loguru#313]
```python
from loguru import logger

class Wrap:
     def test(self):
         logger.info('test', stacklevel=2)


def WrapCaller():
      word = Wrap()
      word.test()

if __name__ == "__main__":
     WrapCaller()
```
Just throwing an example above where it would print out the function and line num to be on the line where word.test() is at versus the logging caller statement. This feature was added in Python 3.8.
Above script would print out the following unless the standard logging package is directed used:
2020-08-25 21:49:51.173 | INFO     | __main__:test:5 - test

Any ideas on how to achieve the same behavior in a stable fashion would be great. 
I've attempted modifying the loguru logger formatter but it seems like it isn't easy to do for specific log statements.

> The third optional keyword argument is stacklevel, which defaults to 1. If greater than 1, the corresponding number of stack frames are skipped when computing the line number and function name set in the LogRecord created for the logging event. This can be used in logging helpers so that the function name, filename and line number recorded are not the information for the helper function/method, but rather its caller. The name of this parameter mirrors the equivalent one in the warnings module. (From https://docs.python.org/3/library/logging.html)

**Comment by Delgan** [comment]
Hi @CloudZazu.

Loguru does support this feature using the `depth` argument of the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method:

```python
logger.opt(depth=2).info('test')
```

**Comment by CloudZazu** [comment]
@Delgan Sweet! Appreciate the help! Thanks! I'll explore more on that method! 😄
