### ISSUE TITLE
Default log format not respected in imported module

### ISSUE THREAD

**Issue by tplueer** [Delgan/loguru#317]
Hello,

i have a problem with the log format which i have defined during startup. When i log from my main file the log format 
works. But in any imported file where i have imported the loguru package the log format changes to a different one.

**logging.py**
```python
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(
            level, record.getMessage()
        )

def init_logging():
    loggers = []
    for name in logging.root.manager.loggerDict:
      if name.startswith("uvicorn."):
        loggers.append(logging.getLogger(name))
    for uvicorn_logger in loggers:
        uvicorn_logger.handlers = []

    #change handler for default uvicorn logger
    intercept_handler = InterceptHandler()
    logging.getLogger("uvicorn").handlers = [InterceptHandler()]
    logging.getLogger("uvicorn.access").handlers = [InterceptHandler()]
    
    logger.configure(
        handlers=[{
          "sink": sys.stdout,
          "level": logging.DEBUG,
          "format": "[<green>{time:YYYY-MM-DD HH:mm:ss}</green>]: ||| <b><level>{level}</level></b> ||| <white>{message}</white>"
          }]
    )
```

**main.py**
```python
from services.logging import init_logging
from api.components.explore import controller

# Create the logger
init_logging()
logger.info("Test")
```
**Returns**
-> `[2020-09-07 21:26:53]: ||| INFO ||| Test`

**controller.py**
```python
from loguru import logger
logger.info("Hello from imported file")
```
**Returns**
-> `2020-09-07 21:28:37.864 | INFO     | api.components.explore.controller:<module>:8 - Hello from imported file`

**Comment by Delgan** [comment]
Hi @tplueer. :slightly_smiling_face: 

What happens is that `logger.info("Hello from imported file")` is executed **before** that `init_logging()` is called.

Indeed, when you do `from api.components.explore import controller`, then the entire content of the file is run. Only after that your logger will be configured, but the message has already been logged.

**Comment by tplueer** [comment]
Yes your'e absolutely correct. A log message inside the controller function (after a http request has been processed) works with the correct format... 

Sorry it was a long day im closing this ... 😅
