### ISSUE TITLE
Capture stdout/err to log

### ISSUE THREAD

**Issue by yurzo** [Delgan/loguru#32]
@Delgan Just curious here to know what you think of capturing stdout/stderr into the log
similar to what Ferry Boender proposes in:
https://www.electricmonk.nl/log/2011/08/14/redirect-stdout-and-stderr-to-a-logger-in-python/

**Comment by Delgan** [comment]
Hello @yurzo.

Well, the best would be to replace calls to `print()` in the code and directly use the `logger` instead.

If this is not possible, I guess redirecting `stdout` / `stderr` is a valid way to capture the output.

Just take care of first removing the default handler, and not adding a new `stdout` sink once redirected or that would cause dead lock (you may use `sys.__stdout__` instead).

```python
import sys
from loguru import logger

class StreamToLogger:

    def __init__(self, log_level="INFO"):
        self.log_level = log_level

    def write(self, buf):
        for line in buf.rstrip().splitlines():
            logger.log(self.log_level, line.rstrip())

    def flush(self):
        pass

logger.remove()
logger.add("out.text")

sys.stdout = StreamToLogger()
print("Test to standard output")
```

This is not something that will come "built-in" with Loguru, though.

**Comment by yurzo** [comment]
Thank you @Delgan, clarity on the following statement is what I was looking for.
> This is not something that will come "built-in" with Loguru, though.
