### ISSUE TITLE
Indent multi-line objects?

### ISSUE THREAD

**Issue by cwerner** [Delgan/loguru#320]
Hi. Loving loguru! 

One minor issue I have: I often want to i.e. log NumPy arrays, Pandas data frames or other multi-line outputs (here hydra-core config).

Is there a way to to have the second and all following lines of there multi-line repr's be indented so they align?

```
2020-09-11 16:47:00.033 | INFO     | __main__:my_app:36 - batch_size: 128
epochs: 10
nz: 100
cuda: true
sample_dir: images
```

```
2020-09-11 16:47:00.033 | INFO     | __main__:my_app:36 - batch_size: 128
                                                          epochs: 10
                                                          nz: 100
                                                          cuda: true
                                                          sample_dir: images
```

**Comment by Delgan** [comment]
Hi @cwerner!

That's a challenging problem. I'm afraid it's not even possible. I first thought one could use a custom `format` function to measure the length of the prefix and align the message properly. However, it's not possible to know which part of the `message` correspond to the `numpy` array, so it's not possible to know the exact length to be indented.

Example (this does not work well):

```python
import  sys
from loguru import logger
import numpy as np

a = np.zeros((10, 10))

def formatter(record):
    lines = record["message"].splitlines()
    prefix = "{time} - {level} - {function} - ".format(**record)
    indented = lines[0] +"\n" + "\n".join(" " * len(prefix) + line for line in lines[1:])
    record["extra"].update(prefix=prefix, indented=indented)
    return "{extra[prefix]} {extra[indented]}\n{exception}"

logger.remove()
logger.add(sys.stderr, format=formatter)

logger.info("Array: {}", a)
```

I think you explicitly needs to add a new line before printing the array:

```python
logger.info("Array:\n{}", a)
```

See also, possibly related question on StackOverflow: [Python print aligned numpy array](https://stackoverflow.com/questions/51327247/python-print-aligned-numpy-array)

**Comment by cwerner** [comment]
Hi and thanks for the quick response. I think I’d be happy to simply indent the full message. As you say, I could always put a description in front of the array on a single line. Will try to get started with your example...

I’m not on a computer right now so I can’t test, but do I get the nice colored output of loguru also with custom loggers?

Cheers,
C

**Comment by Delgan** [comment]
> I’m not on a computer right now so I can’t test, but do I get the nice colored output of loguru also with custom loggers?

Well... You need to add color markup tags to the returned string. Example:

```python
def formatter(record):
    lines = record["message"].splitlines()
    prefix = "{time} - {level} - {function} - ".format(**record)
    indented = lines[0] +"\n" + "\n".join(" " * len(prefix) + line for line in lines[1:])
    record["extra"]["indented"] = indented
    return "<g>{time}</> - <lvl>{level}</> - <e>{function}</> - <lvl>{extra[indented]}</>\n{exception}"
```

**Comment by cwerner** [comment]
Cool! Thanks

**Comment by cwerner** [comment]
Just a quick follow up. I implemented your suggestion and all is fine except that I do get extra empty lines between log messages. I tried various thing but I cannot determine where this extra newline comes from... if I remove the last \n in the return I get no clean break between the end of a multi-line log and the next log message?
