### ISSUE TITLE
Do not close/Get the filedescriptor if script is being run as Linux Daemon

### ISSUE THREAD

**Issue by sla-te** [Delgan/loguru#321]
For default logging, they describe how to do it here: https://github.com/thesharp/daemonize

In my usecase I want to log the output of all scripts I run to the same file, so I do:
```python
logger.remove()
logger.add(str(log_file_path), colorize=False, diagnose=True, backtrace=True, rotation="10MB")
```
on top of every file.

**Comment by Delgan** [comment]
The `daemonize` library looks really nice. It seems that it can be easily combined with `loguru`:

```python
import time
from daemonize import Daemonize
from loguru import logger
    
pid = "/tmp/test.pid"

fd = open("/tmp/test.log", "w")
keep_fds = [fd.fileno()]

logger.remove()
logger.add(fd)

def main():
    while True:
        logger.warning("Test")
        time.sleep(1)

daemon = Daemonize(app="test_app", pid=pid, action=main, keep_fds=keep_fds)
daemon.start()
```

It should work fine, right?

**Comment by chwba** [comment]
Hmm, I have multiple files though but I call daemonize with the fd only from main

**Comment by Delgan** [comment]
Sorry, can you share an snippet of your code which is not working as expecting? I have trouble understanding the problem you're facing.

**Comment by chwba** [comment]
app.py:
```python
import time
from daemonize import Daemonize
from loguru import logger
from file2 import do_work
    
pid = "/tmp/test.pid"

fd = open("/tmp/test.log", "w")
keep_fds = [fd.fileno()]

logger.remove()
logger.add(fd)

def main():
    do_work()

daemon = Daemonize(app="test_app", pid=pid, action=main, keep_fds=keep_fds)
daemon.start()
```

file2.py
```python
from time import sleep
from loguru import logger

logger.remove()
fd = open("/tmp/test.log", "w")  # What about this fd? 
logger.add(fd)

def do_work():
    while True:
        print("working")
        sleep(1)
```

**Comment by Delgan** [comment]
Do you really need to call `logger.add()` both in your `main.py`and `file2.py` files?

The `logger` object is the same, so if you call `.add()` only in your `main` file then messages logged from `file2` will be sent to the `/tmp/test.log` too.

**Comment by chwba** [comment]
Hmm, so you mean I can simply do from loguru import logger in all my other files and the settings defined in `main()` will be used?

**Comment by Delgan** [comment]
Yes as long as it's executed in the same process. That's how `loguru` works!

You configure the handlers you wish (`sys.stderr`, `file.log`, `my_function()`, etc.) in the `main.py` file. Then all your modules just need to use `from loguru import logger` and as the `logger` is global, the modules inherit from the configuration defined in `main.py`.

**Comment by chwba** [comment]
Ah, thats nice. When I add the keyword 'rotation' I get `TypeError: add() got an unexpected keyword argument 'rotation'`.
`logger.add(open(str(log_file), "w"), colorize=False, diagnose=True, backtrace=True, rotation="10MB")`

**Comment by Delgan** [comment]
Oh, yeah... That's the main issue actually. The `rotation` argument does not work with file-like objects used a sink (because in such case, `loguru` is not the owner of the file object so it can't be closed properly).

Another idea maybe: is it possible to configure the `logger` and call `.add()` only once the `daemon` is started?

**Comment by chwba** [comment]
Yeah, that would be possible, I dont have to log anything import from within `main()`, what do you have in mind?

**Comment by Delgan** [comment]
I was thinking to something like that:

```python
import time
from daemonize import Daemonize
from loguru import logger
from file2 import do_work

pid = "/tmp/test.pid"

def configure():
    logger.remove()
    logger.add("/tmp/test.log", rotation="1000 B")

def main():
    configure()
    logger.info("Starting work...")
    do_work()

daemon = Daemonize(app="test_app", pid=pid, action=main)
daemon.start()

```

**Comment by chwba** [comment]
Sorry for the very late reply, hmm well if we do it like this it removes the fun of passing the fd to leave open to daemonize, so it can close all others. I guess either we dont have daemonize close any fd's and have rotating log-files or we have it close it and have no rotating log-files :)

**Comment by Delgan** [comment]
Yeah, `loguru` does not expose the internal file handler, so there are not a lot of alternatives. There is no problem to open files once the program is daemonized, but it's a issue otherwise. Another possibility is maybe to use `delay=True` (but again, the `logger` should not be used before being daemonized).

**Comment by kace** [comment]
Hi chwba. I've faced a similar problem dealing with file descriptors in daemons. As Delgan says the best solution is probably to hold off of opening file handlers until your process has daemonized, but in cases where this isn't possible you can scrape the PID for it's open file descriptors using [psutil](https://github.com/giampaolo/psutil). Then it's a simple matter to pass this info to the daemonization library. It's a bit of a roundabout solution but it's been a reliable workaround in my experience.

**Comment by Delgan** [comment]
I'm closing this issue as I think a workaround have been provided and that there is not much I can do from Loguru internals to improve the current behavior. Feel free to re-open this ticket if further discussions is required. :+1:
