### ISSUE TITLE
Question: Modifying a default logging level

### ISSUE THREAD

**Issue by toto-bird** [Delgan/loguru#322]
Hello!

I have been using loguru for debug in a recent project. I was wondering if there is any way to modify a pre-existing logging level.
Example:
```python
from loguru import logger

logger.error('Something went horribly wrong')
```
Is there a way to change the name from `ERROR` to `FATAL` without creating a new logging level?
Note: I can not create a new logging level because I am using an `@logger.catch` which logs an `ERROR` when I want a `FATAL`.
```python
from loguru import logger

@logger.catch
    def div(a: int, b: int) -> int:
        return(int(a / b))

div(10, 0)
```

**Comment by toto-bird** [comment]
Update: I figured out how to change the name of a level,
```python
import loguru
from loguru import logger

logger._core.levels['ERROR'] = loguru._logger.Level('FATAL', 50, '<red><bold>', ' ')
```
but I still do not know how to change the colour.

I have tried the following two lines but neither worked:
```python
logger._core.levels['ERROR'] = loguru._logger.Level('FATAL', 50, '<yellow><bold>', ' ')
                                                                   ^^^^^^
```
```python
logger._core.levels.ansi_codes['ERROR'] = '\x1b[33m\x1b[1m'
                                           ^^^^^^^^
```

**Comment by Delgan** [comment]
Hi @toto-bird. It's not possible to modify an existing level, and I would advise against using `logger._core` as it's not part of the public API. :grimacing: 

>  Note: I can not create a new logging level because I am using an @logger.catch which logs an ERROR when I want a FATAL.

Maybe can you specify the `level` you want the exception to be logged with? The [`catch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch) method accept such argument:

```python
 @logger.catch(level="CRITICAL")  # You can alternatively use a custom level like "FATAL"
    def div(a: int, b: int) -> int:
        return(int(a / b))
```

Would that solve your problem without requiring to change the `"ERROR"` level?

**Comment by toto-bird** [comment]
Oh, I did not know that you could use a specific level for the handler. Thank you.

Side question: Is it possible to log a different level for a specific exception?
Example:
```python
from typing import Any
from loguru import logger

@logger.catch(level="CRITICAL")
def div(a: int, b: Any) -> int:
    return(int(a / b))

# Raises ZeroDivisionError
div(10, 0) # Logs: ERROR | An error has been caught...
                   ^^^^^

# Raises TypeError
div(10, 'Hello') # Logs: FATAL | An error has been caught...
                         ^^^^^
```

Preferably without having to do:
```python
@logger.catch(level='CRITICAL')
def div(a: int, b: int) -> int:

    @logger.catch(level='ERROR')
    def error(a: int, b: int):
        a / b

    try:
        return(int(a / b))
    except ZeroDivisionError:
        error(a, b)
```

**Comment by Delgan** [comment]
Sure, you can specify which error should be catch and decorate the function twice:

```python
@logger.catch(ZeroDivisionError,level="CRITICAL")
@logger.catch(TypeError, level="ERROR")
def div(a, b):
    return a / b
```

**Comment by toto-bird** [comment]
It worked. Thank you so much!
