### ISSUE TITLE
Running setup.py install for immutables ... error

### ISSUE THREAD

**Issue by jingyan6** [Delgan/loguru#324]
centos_7_7_x64

Collecting loguru
  Using cached https://mirrors.aliyun.com/pypi/packages/a0/f7/85704c74dd5b616a528aa724d359033f4dbec896b604cf12b65c4f9badb1/loguru-0.5.2-py3-none-any.whl (57 kB)
Collecting aiocontextvars>=0.2.0; python_version < "3.7"
  Using cached https://mirrors.aliyun.com/pypi/packages/db/c1/7a723e8d988de0a2e623927396e54b6831b68cb80dce468c945b849a9385/aiocontextvars-0.2.2-py2.py3-none-any.whl (4.9 kB)
Collecting contextvars==2.4; python_version < "3.7"
  Using cached https://mirrors.aliyun.com/pypi/packages/83/96/55b82d9f13763be9d672622e1b8106c85acb83edd7cc2fa5bc67cd9877e9/contextvars-2.4.tar.gz (9.6 kB)
Collecting immutables>=0.9
  Using cached https://mirrors.aliyun.com/pypi/packages/6b/58/c6be0577cccbe1658fcb1ec3673e9ac7508af26a2f5c814cc041c7d21212/immutables-0.14.tar.gz (42 kB)
Using legacy 'setup.py install' for contextvars, since package 'wheel' is not installed.
Using legacy 'setup.py install' for immutables, since package 'wheel' is not installed.
Installing collected packages: immutables, contextvars, aiocontextvars, loguru
    Running setup.py install for immutables ... error
    ERROR: Command errored out with exit status 1:
     command: /home/xuanpin-fastApi/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vx3alxos/immutables/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vx3alxos/immutables/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-egf7m9fx/install-record.txt --single-version-externally-managed --compile --install-headers /home/xuanpin-fastApi/venv/include/site/python3.6/immutables
         cwd: /tmp/pip-install-vx3alxos/immutables/
    Complete output (41 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/immutables
    copying immutables/_version.py -> build/lib.linux-x86_64-3.6/immutables
    copying immutables/map.py -> build/lib.linux-x86_64-3.6/immutables
    copying immutables/_testutils.py -> build/lib.linux-x86_64-3.6/immutables
    copying immutables/__init__.py -> build/lib.linux-x86_64-3.6/immutables
    running egg_info
    writing immutables.egg-info/PKG-INFO
    writing dependency_links to immutables.egg-info/dependency_links.txt
    writing top-level names to immutables.egg-info/top_level.txt
    reading manifest file 'immutables.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'immutables.egg-info/SOURCES.txt'
    copying immutables/_map.c -> build/lib.linux-x86_64-3.6/immutables
    copying immutables/_map.h -> build/lib.linux-x86_64-3.6/immutables
    copying immutables/_map.pyi -> build/lib.linux-x86_64-3.6/immutables
    copying immutables/py.typed -> build/lib.linux-x86_64-3.6/immutables
    running build_ext
    building 'immutables._map' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/immutables
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=x86-64 -mtune=generic -mfpmath=sse -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNDEBUG=1 -I/home/xuanpin-fastApi/venv/include -I/usr/include/python3.6m -c immutables/_map.c -o build/temp.linux-x86_64-3.6/immutables/_map.o -O2 -std=c99 -fsigned-char -Wall -Wsign-compare -Wconversion
    immutables/_map.c: 在函数‘map_node_bitmap_assoc’中:
    immutables/_map.c:905:62: 警告：‘Py_ssize_t’转换自‘uint32_t’时可能会改变结果的符号 [-Wsign-conversion]
                 new_node = (MapNode_Array *)map_node_array_new(n + 1, mutid);
                                                                  ^
    immutables/_map.c:988:57: 警告：‘Py_ssize_t’转换自‘uint32_t’时可能会改变结果的符号 [-Wsign-conversion]
                     (MapNode_Bitmap *)map_node_bitmap_new(2 * (n + 1), mutid);
                                                             ^
    gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/immutables/_map.o -L/usr/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/immutables/_map.cpython-36m-i386-linux-gnu.so
    /usr/bin/ld: 当搜索用于 /usr/lib/libpthread.so 时跳过不兼容的 -lpthread
    /usr/bin/ld: 当搜索用于 /usr/lib/libc.so 时跳过不兼容的 -lc
    /usr/bin/ld: i386 架构于输入文件 build/temp.linux-x86_64-3.6/immutables/_map.o 与 i386:x86-64 输出不兼容
    /usr/bin/ld: build/temp.linux-x86_64-3.6/immutables/_map.o: file class ELFCLASS32 incompatible with ELFCLASS64
    /usr/bin/ld: 最后的链结失败: 文件格式错误
    collect2: 错误：ld 返回 1
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1

**Comment by Delgan** [comment]
Hi @jingyan6.

Did you try installing `loguru` using `pip`?

You can also try to install [`immutables`](https://github.com/MagicStack/immutables) directly and to see if it raises the same error.

**Comment by Delgan** [comment]
I'm closing this issue as this more likely related to `immutables` and not `loguru`.
