### ISSUE TITLE
About @logger.catch decorator prevent to raise Exception

### ISSUE THREAD

**Issue by nzh1992** [Delgan/loguru#326]
Hi, all:
    I create a function which has @logger.catch decorator, hope to catch Exception and record to log file. yes, it works.
    but, when I catch the Exception out of the function, can't catch the Exception.

    I use as below:

    @logger.catch
        function_a():
            try:
                1 / 0
            except Exception as e:
                raise e

    function_b():
        try:
            function_a()
        except Exception:
            print("I want to go here, but I can't.")

    How can I deal with this problem?

**Comment by Delgan** [comment]
Hi.

You can the `reraise` argument of [`logger.catch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch) if you want the exception to be propagated to the caller. :+1: 

```python
@logger.catch(reraise=True)
function_a():
    try:
        1 / 0
    except Exception as e:
         raise e
```

**Comment by Delgan** [comment]
I'm closing this issue as it seems the answer is answered. Feel free to re-open it otherwise. :+1:

**Comment by durgeksh** [comment]
What if we want to print the exception through decorator?

**Comment by Delgan** [comment]
@durgeksh You can maybe use the `onerror` parameter.
