### ISSUE TITLE
[Query] Enabling encryption on logged messages.

### ISSUE THREAD

**Issue by piyush-das** [Delgan/loguru#332]
Hi,

I was wondering what would be the best way to enable the logged messages to be encrypted. I came across the following suggestion at [stackoverflow](https://stackoverflow.com/questions/44475816/python-logging-module-encrypt). As suggested it seems that creating a custom formatter for loguru should be the way to go for it. However, since I am new to this library, is there a better approach for achieving the same ?

Thanks for the great work.

**Comment by Delgan** [comment]
Hi. :)

Sure, you can use a custom `format` function. It looks to be the correct approach. 

For example:

```python
from cryptography.fernet import Fernet
key = Fernet.generate_key() #this is your "password"
cipher_suite = Fernet(key)
def encrypted_formatter(record):
    encrypted_message = 
```

**Comment by piyush-das** [comment]
Works like a charm. Thanks

**Comment by piyush-das** [comment]
@Delgan . I was also going to implement the same for exceptions. Going through the issues, I realized that you are using `stackprinter` for doing any modifications/formatting to the `record['exceptions']`, even though you have originally used the `better_exceptions` library. Would be great if you could share the rationale for the same, so that I can use the better one. :+1:

**Comment by piyush-das** [comment]
@Delgan . I was trying to work around with exceptions as well. However it seems the `stackprinter` example mentioned in the docs, doesn't utilize the great formatting utilized by better_exceptions. Is there a way we can encrypt the `record['exception']` as formatted by better exceptions.

**Comment by piyush-das** [comment]
from loguru._better_exceptions import ExceptionFormatter
As a temporary workaround , I have used the following:
```python
from base64 import b64encode
from loguru import logger
from cryptography.fernet import Fernet
from loguru._better_exceptions import ExceptionFormatter

key = Fernet.generate_key()
cipher = Fernet(key)
exception_formatter = ExceptionFormatter(
           # Can reuse the same parameters utilized in package
            colorize=False,
            backtrace=True,
            diagnose=True,
            theme=None,
            style=None,
            max_length=128,
            encoding="ascii"
        )

def encrypted_formatter(record):
    encrypted_message = cipher.encrypt(record["message"].encode("utf8"))
    record["extra"]["encrypted_message"] = b64encode(encrypted_message).decode("latin1")

    encrypted_exception = cipher.encrypt(exception_formatter.format_exception(*record["exception"]).encode("utf8"))
    record["extra"]["encrypted_exception"] = b64encode(encrypted_exception).decode("latin1")
    return "[{level}] {extra[encrypted_message]}\n{extra[encrypted_exception]}"

logger.add("file.log", format=encrypted_formatter)
logger.info("Test")
```

Please let me know if there are better ways of achieving the same.
Thanks

**Comment by Delgan** [comment]
Your workaround is fine, the only downside is that you're using the non-documented `loguru._better_exceptions` module. As it's not part of the official public API, there is not guarantee that the `ExceptionFormatter` will not be modified or plainly removed in the future.

I think you can directly import and use the [`better-exceptions`](https://github.com/Qix-/better-exceptions) library (from which `loguru._better_exceptions` is derived). For example:

```python
import better_exceptions

def encrypted_formatter(record):
    encrypted_message = cipher.encrypt(record["message"].encode("utf8"))
    record["extra"]["encrypted_message"] = b64encode(encrypted_message).decode("latin1")

    encrypted_exception = cipher.encrypt(better_exceptions.format_exception(*record["exception"]).encode("utf8"))
    record["extra"]["encrypted_exception"] = b64encode(encrypted_exception).decode("latin1")
    return "[{level}] {extra[encrypted_message]}\n{extra[encrypted_exception]}"
```

**Comment by piyush-das** [comment]
@Delgan, I had used the better_exceptions module as well, but apparently you have enhanced the `loguru._better_exceptions `which gives more detailed diagnosis :+1:  with values, which were not available with the default better-exceptions library.

**Comment by Delgan** [comment]
Indeed, I made some small adjustments. The most appropriate solution would be in my opinion to forward some of these changes to the upstream `better-exceptions` repository. That way, you could benefit from those small improvements without relying on non-public API.

Alternatively, maybe you may enjoy another library like [`tbvaccine`](https://github.com/skorokithakis/tbvaccine) or [`rich`](https://github.com/willmcgugan/rich#tracebacks) among probably many others.

**Comment by piyush-das** [comment]
Rich + Loguru has personally been the best of both worlds to me. `Rich` excels at printing to terminals in particular and `Loguru` to me is the best logging interface cum manager. Currently my setup involves `Loguru` logging interfacing and multiple sink capabilities, whereby I intercept all `INFO` using  `Loguru`  which are dumped to the terminal using the `Rich` handler and a log file at the same time..This improves readability for users who are more interested in the functioning rather than the implementation of the package. On the other hand all the errors , warnings , debugs etc go straight into the debug log file using Loguru bypassing the Rich handler. I am pretty sure there would be a much more optimized way to achieve it though. 

I am truly a great fan of your implementation of this library, allowing everyone to customize it to their own needs. :)

**Comment by Delgan** [comment]
Thanks for your kind words @piyush-das!

Indeed, I tried to make `loguru` easy to configure for the most common cases, while still allowing it to be fully customizable for advanced use cases. Glad to see it pays off!

**Comment by xFGhoul** [comment]
how would you decrypt this data for review?

**Comment by xFGhoul** [comment]
> how would you decrypt this data for review?

i can obviously do:
```py
record["extra"]["decrypted"] = cipher.decrypt(encrypted).decode("latin1")
````
but I do not know how to do this as a collective for all the logs that were sent, and keeping the formats...

**Comment by Delgan** [comment]
@xFGhoul I guess you need a regex parser to extract and decrypt fields from the output.

You can serialize the logs to a `.json` to ease this process.
