### ISSUE TITLE
network support fails (reference example in docs) at v4

### ISSUE THREAD

**Issue by huebell** [Delgan/loguru#337]
Exception happened during processing of request from ('127.0.0.1', 55432)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "./example11_server.py", line 27, in handle
    logger.patch(lambda record: record.update(record)).log(level, message)
  File "/home/user/.local/lib/python3.6/site-packages/loguru/_logger.py", line 1996, in log
    level_id, static_level_no = __self._dynamic_level(__level)
  File "/home/user/.local/lib/python3.6/site-packages/loguru/_logger.py", line 2014, in _dynamic_level
    "Invalid level, it should be an integer or a string, not: '%s'" % type(level).__name__
TypeError: Invalid level, it should be an integer or a string, not: 'RecordLevel'
---------------------------------------------------------------------------------------------------------------------------------------------------------
pip install --upgrade loguru==0.3.2
Defaulting to user installation because normal site-packages is not writeable
Collecting loguru==0.3.2
  Using cached loguru-0.3.2-py3-none-any.whl (44 kB)
Installing collected packages: loguru
  Attempting uninstall: loguru
    Found existing installation: loguru 0.5.3
    Uninstalling loguru-0.5.3:
      Successfully uninstalled loguru-0.5.3
Successfully installed loguru-0.3.2
user@user-mint-19:~/tmp/tmp/python/loguru$ ./example11_server.py 
2020-09-25 08:50:31.352 | INFO     | __main__:handle:27 - Sending message from the client

**Comment by Delgan** [comment]
Thanks for the catch!

I updated the corresponding recipe in the documentation.

Inside the `LoggingStreamHandler` class, it should be:

```python
level, message = record["level"].no, record["message"]
```

Instead of:

```python
level, message = record["level"], record["message"]
```

**Comment by huebell** [comment]
Sorry if I missed this this, Delgan and thanks for the nice library and
work. I was demoing to colleagues recently...

-Hue

**Comment by Delgan** [comment]
You didn't miss anything, it's an error in the documentation that has been around for a very long time and that I have just corrected thanks to your remark! :+1:
