### ISSUE TITLE
set timezone by manual

### ISSUE THREAD

**Issue by gaoming714** [Delgan/loguru#338]
The time zone obtained by tzset in my environment sometimes changes.
I want to know if there is a parameter that allows me to configure the required time zone in loguru.

In other words, I want to make the local time,  where the environment time zone is the US East,  is Asia Shanghai.

I can define it for arrow or pendulum as 
```
arror.now("Asia/Shanghai")
pendulum.now("Asia/Shanghai")
```

**Comment by Delgan** [comment]
The datetime displayed by Loguru relies on the `.tm_gmtoff` and `.tm_zone` attributes returned by the [`time.localtime()`](https://docs.python.org/3/library/time.html#time.localtime) function. These attributes are indeed related to the value configured by [`time.tzset()`](https://docs.python.org/3/library/time.html#time.tzset). So, if you can't force a reliable timezone, it will not work very well as you experienced.

There is a possible workaround, though. You can manually [`.patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) the record dict and add your own datetime object with the specified timezone. Then, you can use it in your log format instead of using `{time}`:

```python
def set_datetime(record):
    record["extra"]["datetime"] = pendulum.now("Asia/Shanghai")

logger.configure(patcher=set_datetime)
logger.add(sys.stderr, format="{extra[datetime]} {message}")
```

**Comment by gaoming714** [comment]
@Delgan thanks,

> time.tzset() Availability: Unix.

that's the my key point.

At last I make a venv with system timezone, which can be get by time.tzset().
It is more stable.

**Comment by Delgan** [comment]
Indeed, it seems quite hard to modify the system timezone on Windows using Python runtime.

If you can ensure stability thanks to a virtual environment, that's definitely the way to go. :+1:

**Comment by gaoming714** [comment]
In fact, I replaced the code of the windows platform, and forced to use linux.

**Comment by Delgan** [comment]
What kind of code did you replaced? Can this issue be considered as being fixed then?

**Comment by gaoming714** [comment]
I mean the code of my project.
My platform is msys2, which is mixed linux and windows. I force my code to use linux for this pendulum.
My problem is fixed. But pendulum on windows may be not work until supporting well.
I think it could be closed.

**Comment by gaoming714** [comment]
If i find a new way to fix it, i will make a PR

**Comment by Delgan** [comment]
Ok, great. Thanks for the answer. :+1: 

Let me know if you need help with `pendulum` or `loguru`.

**Comment by valaises** [comment]
@Delgan 
Hi! I'm stuck on the related issue. How can I set the exact timezone in the title of a log file, created by the rotation? Tried this:
`
fmt = '%Y-%m-%d-%H-%M-%S'
logger.add(f'{pendulum.now("Asia/Shanghai").strftime(format=fmt)}.log', rotation='1 minute')
`
The first time it creates log-file with a proper name like:
2021-07-13-03-59-29.log
But every next time I'm getting files like that:
2021-07-13-03-59-29.2021-07-12_22-59-29_217315.log
How can I fix that? Best regards!

**Comment by Delgan** [comment]
Hi @valaises.

You can't use `pendulum.now()` while defining the filename, the filename should contain the date format only.

```python
logger.add("{time:%Y-%m-%d-%H-%M-%S}.log", rotation="1 minute")
```

Unfortunately, that means you can't explicitly specify the `"Asia/Shangai"` timezone. If you really need it, you'll need to implement your own handler or manually rename the file using a custom `compression` function.

**Comment by valaises** [comment]
Thanks for an immediate answer, @Delgan 
Indeed, I'd recommend everybody to use UTC in a case when their local time changes constantly:
`logger.add('data/logs/{time: YYYY-MM-DD-HH-mm!UTC}.log')`
