### ISSUE TITLE
Different format for different files

### ISSUE THREAD

**Issue by Xeizzeth** [Delgan/loguru#343]
Almost sure this question asked before, yet cannot find it anywhere.  
How can I use different formatter for different modules?  
Like for example in the "main.py" module the output the color of the timestamp is red, in the module called "another.py" the timestamp is blue, to quickly differentiate them between each other in the log output.

**Comment by Delgan** [comment]
I don't remember being asked a comparable question. :)

I think you need to use a custom `format` function. You can find the list of available colors [in the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#color).

Here is as example, using random colors for each new module:

```python
import sys
from loguru import logger
from collections import defaultdict
from random import choice

colors = ["blue", "cyan", "green", "magenta", "red", "yellow"]
color_per_module = defaultdict(lambda: choice(colors))

def formatter(record):
    color_tag = color_per_module[record["name"]]
    return "<" + color_tag + ">[{time:X}][{name}]</> <bold>{message}</>\n{exception}"

logger.remove()
logger.add(sys.stderr, format=formatter)

logger.info("Test")
```

**Comment by Xeizzeth** [comment]
Perfect!!! This is exactly what I need.  
Thank you.

**Comment by Delgan** [comment]
> And also why not add it in recipes?

Sure, why not. This can be useful to others. I added this recipe to the documentation: [Adapting colors and format of logged messages dynamically](https://loguru.readthedocs.io/en/latest/resources/recipes.html#adapting-colors-and-format-of-logged-messages-dynamically).
