### ISSUE TITLE
How to show the process ID when multiporcessing

### ISSUE THREAD

**Issue by whillas** [Delgan/loguru#345]
Hey,

Nice model, use it exclusivly now.

BUT i'm doing some multiprocessing and would like to see the process ID as its all mixed up atm

thanks!

**Comment by Delgan** [comment]
Hi.

You can access it by specify `"{process.id}"` in your format, is that what you want?

```python
logger.remove()  # Remove default handler
logger.add(sys.stderr, format="[{process.id}] {message}")
```

The available fields for formatting are listed [here](https://loguru.readthedocs.io/en/stable/api/logger.html#record).

**Comment by whillas** [comment]
Thank you!

**Comment by whillas** [comment]
Hey, I lose all the pretty colours when i set a formatter :(

**Comment by whillas** [comment]
oh, i got it :)

**Comment by whillas** [comment]
I'm doing this
```python
logger.add(sys.stderr, colorize=True, format="<level>{time:HH:mm:ss} | {level} | [{process.name}] {name}:{function}:{line} \n {message}</level>")
```
But only the first message is colourized. The rest are white?

Whats the default formater look like? I would like a slightly modified version of that.

**Comment by Delgan** [comment]
You can find the default format here: https://github.com/Delgan/loguru/blob/93f199042c5612367aab0cbee018961b1748627b/loguru/_defaults.py#L31-L37

Also, check the [list of available colors markups](https://loguru.readthedocs.io/en/stable/api/logger.html#color). It contains examples to reduce verbosity.

Using this, you should be able to customize the `format` exactly as you wish. :+1:

**Comment by whillas** [comment]
thank you!
