### ISSUE TITLE
Feature Request: Redirect logger.catch

### ISSUE THREAD

**Issue by JulianOrteil** [Delgan/loguru#347]
Good day @Delgan,

I have a quick question for you:
In the app that I'm designing, I'd like to display all error messages to the user using a GUI (framework is specifically PyQt5). Is there any way `logger.catch` can redirect error messages to another function? I want to avoid creating a separate class that does this to avoid overlap between that and `logger.catch`.

I feel like this would be a great extension to the function for people who design apps that are as complex as mine.

As always, please let me know what you think.
Jules

**Comment by Delgan** [comment]
Hi @JulianOrteil.

I'm not sure exactly how you prefer the caught exception to be redirected to another function. Maybe can you use the `onerror` parameter?

```python
def display_error(exception):
    udpate_gui()

@logger.catch(onerror=display_error)
def main():
    1 / 0
```

Alternatively, maybe can you simply use a specific sink?

```python
def error_sink(message):
    exception = message.record["exception"]
    if exception is None:
        return
    display_error(exception)
```

**Comment by JulianOrteil** [comment]
I didn't think of a sink.

I was thinking that the same mechanism behind `enqueue` might work for this. But a sink would work perfectly, thanks.

Jules
