### ISSUE TITLE
HTTP Handler for Loguru

### ISSUE THREAD

**Issue by h4n53l** [Delgan/loguru#351]
Hi,
I enjoy using Loguru, however I'm unable to send it's logs via HTTP can you please provide a solution for this, as I wish to remotely access the logs from different PCs via a central server. Thank you very much.

**Comment by Delgan** [comment]
Hi @h4n53l.

You can use a custom function as the sink while calling `logger.add()`. It will serves as the handler in charge of sending logs whenever you want. Here is a very basic example to emit a `POST` request for each logged message:

```python
import request

def send_message(message):
    request.post("http://127.0.0.1:8000/logs/post", data={"message": message})

logger.add(send_message, level="INFO")
```

You can also use a logs aggregator like Sentry, Graylog, Loggly, etc. The `logger` will be configured just as easily by replacing `request` with the appropriate library.

**Comment by h4n53l** [comment]
Hi @Delgan , thank you very very much for your prompt reply. Initially, I was trying to adapt the SocketHandler example given in the documentation, but now I will try what you suggested and post an update of the outcome here before I close the issue. Thanks again.

**Comment by h4n53l** [comment]
Yes, I modified the code snippet you sent and it works perfectly for my needs, thank you very much.

**Comment by Delgan** [comment]
Great, no problem. :+1:
