### ISSUE TITLE
Code cleanup and fix flake8 errors

### ISSUE THREAD

**Issue by AndrewYakimets** [Delgan/loguru#353]
Hi, I am having a big desire to make my first contribution. And I would really like to start with helping loguru! I saw there is some unused imports (for e.g., setup.py:1), code that is hard to read and can be improved (loguru/__init__.py:17 - add key/value to params) and some amout of flake8 errors (mostly in tests). I would like to fix it and make the contribution to loguru.

Could you, please, tell me if I am allowed to do so and you don't mind?

**Comment by Delgan** [comment]
Hi @AndrewYakimets. 

Thanks for your interest in `loguru` and thanks for offering enhancing it. Of course, I would happily accept any improvement! Code cleanups are welcome. :wink:

**Comment by AndrewYakimets** [comment]
Hi @Delgan , thank you for fast response! Okay, I am starting :smiley:

**Comment by AndrewYakimets** [comment]
Hi, @Delgan ! I've finished implementing my proposed changes in PR #354. The CI checks were passed. Could you, please, check it?

**Comment by Delgan** [comment]
Checked and merged, thanks!
