### ISSUE TITLE
Examples using loguru with zmq

### ISSUE THREAD

**Issue by kc64** [Delgan/loguru#355]
I have multiple processes that need to log messages. With the standard logging module, I open a message queue with zmq using PUBHandler to send the log message. In another process, I collect the log messages from all of the logging processes and display them and write them to a file.
I really would like to move to loguru for all of my logging cases but am struggling to find an equivalent use case with zmq. I see the sockets example but my work flow and tools are built on zmq.
Any ideas or suggestions?

**Comment by Delgan** [comment]
Hi @kc64.

You should be able to use `PUBHandler()` with `loguru` too. 

```python
from loguru import logger

handler = PUBHandler('tcp://127.0.0.1:12345')
logger.addHandler(handler)
```

We can probably adapt the receiver. How is it implemented using standard `logging`?

**Comment by kc64** [comment]
When I use that code snippet, my logger doesn't appear to have an addHandler method.
Without loguru, using the standard library logging module, I do this for each sender:

```
import logging
import zmq
from zmq.log.handlers import PUBHandler

context = zmq.Context()

log_socket = context.socket(zmq.PUB)
log_socket.connect('tcp://127.0.0.1:12345')
handler = PUBHandler(log_socket)
handler.root_topic = device_name
log = logging.getLogger()
log.setLevel(logging.NOTSET)
log.handlers = []
log.addHandler(handler)
...
log.info('Log this message.')
```

In the logger process which receives the messages from all logger sources, I do this (I don't like this code and it seems to smell but it works):

```
import zmq
import logging.handlers

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.setsockopt(zmq.SUBSCRIBE, '')
socket.bind('tcp://127.0.0.1:12345')

format = '%(asctime)s  %(levelname)-6s%(message)s'
datefmt = '%y%m%d %H%M%S'
formatter = logging.Formatter(fmt=format, datefmt=datefmt)
handler = logging.handlers.RotatingFileHandler(LOG_FILENAME, maxBytes=1e9, backupCount=100)
handler.setFormatter(formatter)

file_logger = logging.getLogger()
file_logger.setLevel(logging.NOTSET)
file_logger.addHandler(handler)
...
message = socket.recv_multipart()

if message:
    last_message_time = time()
    root, message = message
    try:
        source, level = root.split('.')
    except:
        source, level = ['unknown'] * 2
    msg = string.strip('{src:20} {msg}'.format(src=source, msg=message))

    if level == 'DEBUG':
        func = file_logger.debug
    elif level == 'INFO':
        func = file_logger.info
    elif level == 'WARN':
        func = file_logger.warn
    elif level == 'ERROR':
        func = file_logger.error
    elif level == 'CRITICAL':
        func = file_logger.critical
    else:
        func = file_logger.info
    func(msg)
```

**Comment by Delgan** [comment]
> When I use that code snippet above, my logger doesn't appear to have an addHandler method.

Sorry, I made a mistake typing the snippet. You should use `logger.add()`, the `addHandler()` method corresponds to the standard `logging` library obviously.

On the receiver side, you can do something like this:

```python
from loguru import logger

logger.add("file.log", level=0)

message = socket.recv_multipart()
root, message = message

logger.log(0, message)
```

**Comment by kc64** [comment]
I'm puzzled. When debugging, I see messages received in the logging process but the log message do not appear. Here's my code where I replaced the file output with standard out to help debug. With or without the .add to stdout, I get no output.

```import zmq
from loguru import logger
import sys

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.setsockopt_string(zmq.SUBSCRIBE, '')
socket.bind('tcp://127.0.0.1:12345')

logger.add(sys.stdout)    # tried with and without but no results

while True:
    message = socket.recv_multipart()    # message = [b'INFO', b"2020-10-27 07:33:04.726 | INFO     | __main__:test:133 - {'a': 34, 'b': 14}\n"]
    logger.log(0, message)
```

**Comment by Delgan** [comment]
Did you set `level=0` while calling `.add()` for the receiver (see my snippet)? 

This is very important because the handler will only process message which are high enough. As logs are emitted with `logger.log(0, message)`, the handler needs to be configured with `level=0` too. If not specified it defaults to "INFO" which equals `10`, that's why you don't see any output.

**Comment by kc64** [comment]
You've done it! I am now getting messages. Thank you for your kind help in finding my omission.

On my senders, I have messages at stdout that look like this:

`2020-10-27 16:03:25.347 | INFO     | __main__:test:133 - {'a': 20, 'b': 62}`

On the receiver, I have a sort of nested message that looks like this:

`2020-10-27 16:03:23.544 | Level 0  | __main__:<module>:14 - [b'INFO', b"2020-10-27 16:03:23.544 | INFO     | __main__:test:133 - {'a': 60, 'b': 12}\n"]`

I'll being looking into this behavior next to see if I can learn why the message meta is inside the message on the receiver. I think I saw a post about that somewhere.

Many thanks!

**Comment by Delgan** [comment]
This is an easy fix! I hadn't thought about it, but you also have to set `format={message}` on the receiver.

```python
logger.add("file.log", level=0, format="{message}")
```

The `loguru` default format looks like `{time} | {level} | ... {message}`. You're seeing nested messages because the log received are already formatted by the sending handler, but the receiver handler try to reformat them.

Also, as I see it, the `message` variable is actually a `list`, right? You probably should unpack it before logging it:

```python
level, message = message
logger.log(0, message)
```

**Comment by kc64** [comment]
Thank you! I'm very happy about this.

We should put this nugget into the substantial documentation that you've provided. Can I help at all?

**Comment by Delgan** [comment]
Thanks for offering your help! :)

A few words of explanation and example snippets using `zmq` should be added to the end of the "[Sending and receiving log messages across network or processes](https://github.com/Delgan/loguru/blob/master/docs/resources/recipes.rst#sending-and-receiving-log-messages-across-network-or-processes)" section. Either I will do it this weekend, or you can open a PR if you wish.

**Comment by kc64** [comment]
I tried but have a few problems.

1. I can't install git tools on my network-connected PC since it is locked down and have no idea how to interact with git without those tools.
2. My code is not syntax highlighted, only black. I don't know how to fix that in a practical way.

Here's what I ended up with:

```
#senders
import zmq
from loguru import logger as log
from zmq.log.handlers import PUBHandler
context = zmq.Context.instance()
log_socket = context.socket(zmq.PUB)
log_socket.connect('tcp://127.0.0.1:12345')
log.add(PUBHandler(log_socket))
...
log.info('Send this message.')


#receiver
import zmq
from loguru import logger
import sys

context = zmq.Context.instance()
socket = context.socket(zmq.SUB)
socket.setsockopt_string(zmq.SUBSCRIBE, '')
socket.bind('tcp://127.0.0.1:12345')

logger.add(sys.stdout, level=0, format='{message}')

while True:
    level, message = socket.recv_multipart()
    logger.log(0, message.strip().decode('utf-8'))
```

**Comment by Delgan** [comment]
Thanks @kc64, I will use it to update the documentation. :+1:

**Comment by Delgan** [comment]
Example added to the recipe. ;)
