### ISSUE TITLE
how to log in the file 

### ISSUE THREAD

**Issue by aamir-gmail** [Delgan/loguru#361]
Not so much an issue, rather a question. When using logger info or error as in logger.info, I need the result to go into the log file and not printed on the screen, I need the python script to run without any stdout.

**Comment by ppmm9999** [comment]
loguru have recipe for you (I wasn't use this):
[https://loguru.readthedocs.io/en/stable/resources/recipes.html#capturing-standard-stdout-stderr-and-warnings](https://loguru.readthedocs.io/en/stable/resources/recipes.html#capturing-standard-stdout-stderr-and-warnings)

**Comment by Delgan** [comment]
Hi!

Thanks @ppmm9999 for proposing a solution. I'm not sure this what @aamir-gmail  was asking for, though. 

If I'm understanding correctly, I think you should take a look at [`.add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) and [`.remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) methods. They are used to configure the handlers, i.e. to choose how the log messages should be processed.

Here is an example to redirect logs to a file and not to the standard output:

```python
from loguru import logger

logger.remove()  # Remove default handler which writes logs to 'stderr' by default
logger.add("output.log")

logger.info("This message is not displayed in the terminal, but it's written to the 'output.log' file")

**Comment by ppmm9999** [comment]
I recomend the recipe because loguru don't capture _any_ errors without special setting at least. By default, if I understand correctly, errors from imported modules (without `logger.enable("")`) go to  `stdout`. I have a similar ploblem (look at issue [#360](https://github.com/Delgan/loguru/issues/360)) - some errors from tkinter are not being captured by loguru. But @aamir-gmail was asking for
> I need the python script to run **without any stdout**.

**Comment by Delgan** [comment]
You're right, thanks for pointing that out @ppmm9999. If some module relies on `sys.stdout` or `sys.stderr` instead of using a `logger` object, these messages can't be captured by `loguru` except by using the recipe you provided.

**Comment by aamir-gmail** [comment]
> Hi!
> 
> Thanks @ppmm9999 for proposing a solution. I'm not sure this what @aamir-gmail was asking for, though.
> 
> If I'm understanding correctly, I think you should take a look at [`.add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) and [`.remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) methods. They are used to configure the handlers, i.e. to choose how the log messages should be processed.
> 
> Here is an example to redirect logs to a file and not to the standard output:
> 
> ```python
> from loguru import logger
> 
> logger.remove()  # Remove default handler which writes logs to 'stderr' by default
> logger.add("output.log")
> 
> logger.info("This message is not displayed in the terminal, but it's written to the 'output.log' file")
> ```

Thank you

**Comment by aamir-gmail** [comment]
Thank you all for your quick reply, the logger.remove() worked, all information s now going to the log file and not displayed on the console. As a future suggestion, you may wish to include this on your GitHub page. Most people would just like to log info or error and not have it displayed in the console.  Thanks again for making logging so simple to use.

**Comment by Delgan** [comment]
There is an indication about this in the Readme, but perhaps I could make it clearer:

> Note that you may also `remove()` a previously added handler by using the identifier returned while adding it. This is particularly useful if you want to supersede the default `stderr` handler: just call `logger.remove()` to make a fresh start.

Anyway, glad it worked. :+1:
