### ISSUE TITLE
A feature request

### ISSUE THREAD

**Issue by aamir-gmail** [Delgan/loguru#363]
As with a function annotator logger. catch , would it be possible to have something like  logger.timeit, this would log how much time a function is taking to execute. Thank you.

**Comment by Delgan** [comment]
Hi @aamir-gmail.

This is a feature that [has been discussed in the past](https://github.com/Delgan/loguru/issues/65#issuecomment-486823044). I decided not to integrate it directly into `loguru` (it's not really logging specific), but I added [a snippet in the documentation](https://loguru.readthedocs.io/en/latest/resources/recipes.html#logging-entry-and-exit-of-functions-with-a-decorator):

```python
def timeit(func):

    def wrapped(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        logger.debug("Function '{}' executed in {:f} s", func.__name__, end - start)
        return result

    return wrapped
```

**Comment by Delgan** [comment]
I'm closing this issue as I don't plan to integrate it directly into Loguru.
