### ISSUE TITLE
how to Replace '__main__' with real python file name.

### ISSUE THREAD

**Issue by Jie-Yuan** [Delgan/loguru#368]
![image](https://user-images.githubusercontent.com/20265321/99782235-d2921100-2b53-11eb-9bff-503412866170.png)

**Comment by Delgan** [comment]
This corresponds to the value of the Python `__name__` variable for the executed file.

```python
>>> print(__name__)
__main__
```
If you don't like this, you can use `{file.name}` instead of `{name}` in the `format`.

```python
>>> logger.add(sys.stderr, format="[{file.name}] {message}"
>>> logger.info("Test")
[file.py] Test
```
Otherwise, you can `patch()` the `logger` (only in your main file, because `__name__` represents the module's name).

```python
logger = logger.patch(lambda record: record["name"] = "file"
```

**Comment by Jie-Yuan** [comment]
why not to use replace __name__ with __file__

**Comment by Delgan** [comment]
The value of `__main__` is used by convention. This is what is recommended by the standard logging library. [See](https://docs.python.org/3/library/logging.html#logger-objects):

>  The logger name hierarchy is analogous to the Python package hierarchy, and identical to it if you organise your loggers on a per-module basis using the recommended construction `logging.getLogger(__name__)`. That’s because in a module, `__name__` is the module’s name in the Python package namespace.

Using standard `logging`, each module is generally configured with `logger = logging.getLogger(__name__)`. Using `loguru`, it's automatic.

**Comment by attagata** [comment]
Thanks Delgan, you solved my problem using logger.patch.

**Comment by Delgan** [comment]
I'm closing this issue because the question seems answered. Let me know you have any other question.

**Comment by injust** [comment]
A few years late, but this is the best way I've found to output the module name:

```python
logger = logger.patch(lambda record: record.update(name=__spec__.name) if __spec__ else None)
```
