### ISSUE TITLE
not print log to console screen

### ISSUE THREAD

**Issue by MHX1203** [Delgan/loguru#369]
Can i just  write log to file and not print to console screen。how should i do.

**Comment by Delgan** [comment]
Yes, you need first to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default handler (which logs to `stderr`) and then [`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) your file handler.

```python
from loguru import logger

logger.remove()
logger.add("file.log")
```

**Comment by MHX1203** [comment]
i appreciated it, thank you very much
