### ISSUE TITLE
Any plan to make this work for python 2.7?

### ISSUE THREAD

**Issue by hu13** [Delgan/loguru#37]
I really like your project. And I want to integrate into my company's python codebase. However, we currently use python2.7 since some of our main libraries depend on it.

I am wondering if it is possible to support python2.7?

**Comment by Delgan** [comment]
Hello @hu13, thanks for your interest on Loguru!

Compatibility with Python 2.7 is something I considered, but I decided it did not worth the trouble.

It's really painful to maintain both Python 2 and 3 compatibility in the code base. Moreover, Python 2.7 will stop being officially maintained in [less than one year](https://pythonclock.org/). People should start to [drop support for Python 2.7](https://python3statement.org/), not add it.

I understand that Python 2.7 can be required to work with the few libraries that has not been ported to Python 3. If your project is stable, maybe is it better to stay with standard `logging` and use Loguru for future scripts and applications.
