### ISSUE TITLE
[Question] Standard Bold output when formatted?

### ISSUE THREAD

**Issue by JeromeK13** [Delgan/loguru#370]
Is there a way to remove the standard "bold" output? Since we formatted our handlers, we only get bold output.
```
logger.configure(
            handlers=[
                dict(sink=sys.stdout, format="{message}", level="INFO", colorize=True),
                dict(sink=LOG_FILE, level="INFO")
            ])
```

**Comment by Delgan** [comment]
I'm not sure I understand. Given the configuration you show here, messages should be displayed without any particular color or style. Are you sure this is not related to the configuration of your terminal?

**Comment by JeromeK13** [comment]
Yes thats the point. From this configuration i would not expect that the output is bold.
We are executing the python-script from bash-script(RHEL 7 with terminator)
I guess this has to in our terminal configs, because loguru does not automaticly like intepret this as "header" and then write it in bold-style right?

**Comment by Delgan** [comment]
No, Loguru does not try to interpret any header.

Also, Loguru does not provide any markup tag to disable / reset an ansi sequence. You may try to add it manually but I don't know if it will work:

```python
dict(sink=sys.stdout, format="\033[0m{message}", level="INFO", colorize=True)
```

 You can replace `sys.stdout` by `test.txt` and compare the output when `format={message}` and `format=<bold>{message}</bold>` . You should be able to see the difference. After that, it all depends on how your terminal interprets and displays the messages.

**Comment by JeromeK13** [comment]
Alright, many thanks I'll give it a try
