### ISSUE TITLE
loguru + discord.py 

### ISSUE THREAD

**Issue by JamesGitRichards** [Delgan/loguru#371]
Hey there! I've got issue while I'm using loguru and discord.py libs together. I use VS Code and python 3.8.5. If I launch script via VS Code it's ok, but if i kill the terminal it freezes and i've got vs coode warning about this, then i restart the app and it repeats again. If I use Sublime Text it works fine - I can run script, cancel one and so on. So I've realised that if I get rid off the loguru.logger.info stuff it works properly in vs code. So guys can u helps me to solve the problem? I want to use loguru lib but vs code doesn't work properly with it.

**Comment by Delgan** [comment]
Hey. :)

Loguru works fine with VSCode usually. How is configured your `logger`? Which handlers did you add?

Please, can you share a minimal example of your code so I can reproduce the problem?

**Comment by JamesGitRichards** [comment]
Sure, the piece of code is down below. This function just shows little message in console. But it's enough to brake vs code. Eexcuse me for bad appearance of example, I have not learned yet how to make it look better:)
`
@client.event
async def on_ready():
      logger.info("Bot successfully runned!")
`

**Comment by Delgan** [comment]
> Eexcuse me for bad appearance of example, I have not learned yet how to make it look better:)

No problem. You can surround your code with ` ``` ` to properly format it.

>  I have not configured logger, I just wanted to trace some actions like that in console. If you want to give some adivces about that would be interesting for me:)

This is weird because I don't seem to have any issue on my side.

```python
import discord
from loguru import logger

client = discord.Client()


@client.event
async def on_ready():
    logger.info("We have logged in as {0.user}".format(client))


client.run("NzgyMDA3MjMwOTk5OTUzNDE4.X8F6_A.ygj_1YcEmGU6mW_wxnOyLAZpBpE")
```

![Peek 2020-11-27 23-23](https://user-images.githubusercontent.com/4193924/100487242-e9160a80-3107-11eb-8b4f-e8630cbeb17d.gif)

The script does not freeze at exit. The terminal is still usable once the app is terminated, and VSCode does not complain about anything.

Maybe this is somehow related to one of your VSCode extensions? Are you using any particular development environment?

**Comment by JamesGitRichards** [comment]
Actually, I've tried your code ` client = discrod.Client() ` and it works! There was ` client = commands.Bot(command_prefix=".") `. I need to learn more about both libraries. Thank you a lot for your response! I aprreciate it

**Comment by Delgan** [comment]
Ok, fine. :+1: 

I don't know `discord.py` very well either.

Can I close this ticket? Or do you have any other questions?

**Comment by JamesGitRichards** [comment]
Yup, close it.
