### ISSUE TITLE
Allow custom serializers

### ISSUE THREAD

**Issue by XayOn** [Delgan/loguru#372]
The hability to specify a custom serializer for a file could be useful to save files in human-readable serializable formats such as the one followed by splunk. This would also open a door to save pickled, xml or any other log format the user wants (for whatever reason... I cant think of a good one to save pickled data or xml in logs tbh).

Should be simple enough. I'm proposing a backwards-compatible implementation where serializer is either a boolean, or a custom serializer directly.

https://github.com/Delgan/loguru/blob/1b41299643fbab269f89878226211a24bdb3e6b0/loguru/_handler.py#L258

**Comment by XayOn** [comment]
I'm leaving this idea here, but will come back tomorrow with a pull request for this proposal 😃

**Comment by Delgan** [comment]
Hi! Thanks for your interest on `loguru` and thanks for being willing to contribute. 

This feature has been requested several times but so far I have always been reluctant to add it.
The most recent discussion on this topic: https://github.com/Delgan/loguru/issues/339#issuecomment-702013972

I don't know if you saw it but there exists a snippet in the documentation: [Serializing log messages using a custom function](https://loguru.readthedocs.io/en/latest/resources/recipes.html#serializing-log-messages-using-a-custom-function)

I think using a custom `formatter` is not too cumbersome and should be the way to go. I prefer suggesting this solution over complicating the `serialize` parameter.

```python
def formatter(record):
    record["extra"]["serialized"] = orjson.dumps(record, default=str)
    return "{extra[serialized]}\n"

logger.add("file.log", format=formatter)
```

In this way, the user has the possibility to customize the serialization process entirely.

**Comment by XayOn** [comment]
The patch() function is actually better for what I was looking for!
I thought I read enough on the documentation but I missed that part.

Thanks and thanks for this great library!

**Comment by Delgan** [comment]
Thanks for your understanding, @XayOn!
