### ISSUE TITLE
How do I keep the console in the same format as the output to the file?

### ISSUE THREAD

**Issue by hege66** [Delgan/loguru#378]
Hello, Delgan

I want to use the add () method to keep the log format of the console and output files consistent, as follows:

```python

logger.add(sys.stderr, format="{time:YYYY-MM-dd HH:mm:ss.SSS} [{level}] [{file.name}]: {message}")
logger.add("file.log", format="{time:YYYY-MM-dd HH:mm:ss.SSS} [{level}] [{file.name}]: {message}")
logger.debug("This's a log message")

```
But when output to the console, there will be two logs, and the first log is loguru by default. Is there any way I can avoid this? Thank you very much!!!
The console log:
```shell
2020-12-12 19:17:41.419 | DEBUG    | __main__:<module>:7 - This's a log message
2020-12-55 19:17:41.419 [DEBUG] [log_demo.py]: This's a log message
```

**Comment by Delgan** [comment]
Hey @hege66. You need first to `.remove()` the default handler. :+1: 

```
logger.remove()  # Will remove all handlers added so far, including the default one
logger.add(sys.stderr, format="{time:YYYY-MM-dd HH:mm:ss.SSS} [{level}] [{file.name}]: {message}")
logger.add("file.log", format="{time:YYYY-MM-dd HH:mm:ss.SSS} [{level}] [{file.name}]: {message}")
logger.debug("This's a log message")
```

**Comment by hege66** [comment]
Hello, Delgan
Very fast and accurate answer, thank you very much for taking time out of your busy schedule to reply, thanks

**Comment by hege66** [comment]
@Delgan 
Hello, Delgan

Very fast and accurate answer, thank you very much for taking time out of your busy schedule to reply, thanks
