### ISSUE TITLE
How to call log levels symbolically?

### ISSUE THREAD

**Issue by metaperl** [Delgan/loguru#382]
I have written a method that conditionally issues a log message and am using this method throughout my code:

```python

def maybe_log(log_instance, message, *message_args):
    if business_logic():
        log_instance.debug(message.format(*message_args)
```

Because I use `debug` only, the current code is fine. However, is there someway to pass the log level as a parameter and then have loguru issue the log message at that level. I.e instance of `log_instance.debug` is something like `log_instance.at_level(passed_in_level, message)` possiblewhere `passed_in_level` is a constant ?

**Comment by Delgan** [comment]
So you mean something like the [`log()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.log) method?

```python
logger.log("DEBUG", message)
```

**Comment by Delgan** [comment]
@metaperl Is `log()` what you was looking for?

**Comment by metaperl** [comment]
Yes I think so. Thanks.
