### ISSUE TITLE
[QUESTION] Is it possible to mask certain values in the traceback output?

### ISSUE THREAD

**Issue by jtfidje** [Delgan/loguru#384]
Hi!
As much as I really love how the traceback output is formated when logging an exception, I realized today when looking at splunk that a "wild token suddenly appeared" in plain text. So my question is this: Is it possible to mask some variables so that their values are not shown in the traceback?

**Comment by Delgan** [comment]
Yes, it is a risk. This is why it is preferable to use `diagnose=False` in production.

It's not really possible to configure the exception formatting the way you suggest it. You should instead use a custom formatter, like [`stackprinter`](https://pypi.org/project/stackprinter/) for example. See [this snippet](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions) in the documentation.

```python
import pretty_errors
import re

def format(record):
    format_ = "{time} {message}\n"

    if record["exception"] is not None:
        stack = pretty_errors.format(record["exception"])
        stack = re.sub("token = .*", "token = ???", stack)
        record["extra"]["stack"] = stack
        format_ += "{extra[stack]}\n"

    return format_

logger.add(sys.stderr, format=format)
```

Maybe it exists another library which can be configured to automatically suppress some variables, but I don't know it.

**Comment by Delgan** [comment]
I'm closing this issue since I suggested possible solutions. If you need more help or have any question, feel free to reopen it. :+1:

**Comment by jtfidje** [comment]
@Delgan So sorry for the lack of response from my side! Thank you for answering! I've implemented a config option for `diagnose=True/False` in my code :)

**Comment by BearMan-Chen** [comment]
# This is my simple solution.
>  To avoid exposing sensitive data (such as passwords) in the diagnostic traceback output,
>  we now inspect each variable name. If a name matches any sensitive identifier (e.g., "password", "pw", or "passwd"),
>  its value is replaced with a masking string "********". This ensures that sensitive values remain hidden
>  while preserving the original traceback formatting and diagnostic information.

## Insert code
```python
if string.lower() in {"password", "pw", "passwd"}:
    value = "********"
```

## Edit function in `_better_exceptions.py`
```python
    def _get_relevant_values(self, source, frame):
        value = None
        pending = None
        is_attribute = False
        is_valid_value = False
        is_assignment = True

        for token in self._syntax_highlighter.tokenize(source):
            type_, string, (_, col), *_ = token

            if pending is not None:
                # Keyword arguments are ignored
                if type_ != tokenize.OP or string != "=" or is_assignment:
                    yield pending
                pending = None

            if type_ == tokenize.NAME and not keyword.iskeyword(string):
                if not is_attribute:
                    for variables in (frame.f_locals, frame.f_globals):
                        try:
                            value = variables[string]
                        except KeyError:
                            continue
                        else:
                            is_valid_value = True
                            # ︾︾︾︾︾︾︾︾︾︾︾︾︾︾︾︾︾︾︾︾
                            if string.lower() in {"password", "pw", "passwd"}:
                                value = "********"
                            # ︽︽︽︽︽︽︽︽︽︽︽︽︽︽︽︽︽︽︽︽
                            pending = (col, self._format_value(value))
                            break
                elif is_valid_value:
                    try:
                        value = inspect.getattr_static(value, string)
                    except AttributeError:
                        is_valid_value = False
                    else:
                        yield (col, self._format_value(value))
            elif type_ == tokenize.OP and string == ".":
                is_attribute = True
                is_assignment = False
            elif type_ == tokenize.OP and string == ";":
                is_assignment = True
                is_attribute = False
                is_valid_value = False
            else:
                is_attribute = False
                is_valid_value = False
                is_assignment = False

        if pending is not None:
            yield pending
```
