### ISSUE TITLE
About Loguru filter

### ISSUE THREAD

**Issue by Mankvis** [Delgan/loguru#385]
Can Fliter filter by module?
For example, there is a.py, b.py, each module records the log separately, but you don't want to use string filtering, because in this case, you must add a prefix before the log

**Comment by Delgan** [comment]
I'm not sure this is was you  are looking for, but are you aware you can use a `dict` instead of `str` as a `filter` attribute?

```python

>>>
level_per_module = {
    "a": "DEBUG",
    "b": False,  # Disabled
}
logger.add(sys.stderr, filter=level_per_module, level=0)
```
