### ISSUE TITLE
Hide exception from console but log them to file.

### ISSUE THREAD

**Issue by thewh1teagle** [Delgan/loguru#387]
I want to log all the messages to the console except for `logger.exception`
And in the same time log `logger.exception` only to file. 
How can I done that?
Thanks

**Comment by Delgan** [comment]
You can configure your two handlers with custom `filter` attributes:

```python
def no_exceptions(record):
    return record["exception"] is None

def exceptions_only(record):
    return record["exception"] is not None

logger.add(sys.stderr, filter=no_exception)
logger.add("errors.txt", filter=exceptions_only)
```

**Comment by thewh1teagle** [comment]
Thank you very much!
The best logger ever!
