### ISSUE TITLE
Accumulate Downstream Logs into One Upstream Log

### ISSUE THREAD

**Issue by MarioIshac** [Delgan/loguru#388]
Got introduced to loguru recently, been liking it a lot so far! 

In order to send upstream information to downstream logs without passing variables into their scopes, I used `logger.contextualize`. This allowed me to print the request ID alongside every log in the service or repository layers, even if they didn't have request ID in their scope. 

But as part of a recent redesign, I want to merge downstream logs for a particular request into one upstream JSON log (trying to achieve one log-line per request). Given downstream messages, I can take care of the logic for fusing them into one upstream JSON blob, but how would I approach accumulating all these messages in the first place? Specifically, is there a way to accumulate all messages logged under some context manager such that my sink can consolidate them?

**Comment by Delgan** [comment]
Hi @MarioIshac.

You are going to need to implement a custom sink. Something like this maybe:

```python
class MySink:

    def __init__(self):
        self.accumulated = []

    def write(self, message):
        if "some_context" in message.record["extra"]:
            self.accumulated.append(message)
            return

        if self.accumulated:
            print("Messages: ", self.accumulated)
            self.accumulated.clear()

        print(message, end="")

sink = MySink()
logger.add(sink)
```

Perhaps another more elegant solution is possible depending on your needs. For example, it may also be possible to use a custom `filter` to accumulate messages  in a similar way.

**Comment by MarioIshac** [comment]
@Delgan Thank you for the solution! I've made a minor change of delegating writing to another sink instead of `print`, but I can close this issue now.
