### ISSUE TITLE
QUESTION: can I put a coroutine into an argument in logger.opt(lazy=True)?

### ISSUE THREAD

**Issue by nacknime-official** [Delgan/loguru#389]
When I put a coroutine in
```
logger.opt(lazy=True).info(
        "{name}",
        name=my_coro,
    )
```
I get 
`RuntimeWarning: coroutine 'my_coro' was never awaited`

**Comment by Delgan** [comment]
No, the `lazy` argument is intended for use with basic synchronous function.

**Comment by nacknime-official** [comment]
> No, the `lazy` argument is intended for use with basic synchronous function.

Can it be a new feature for loguru?

**Comment by Delgan** [comment]
I'm not sure it's possible. The `logger` is meant to be run synchronously, solely the sinks can be async. The message can't be formatted if the arguments are not yet available.

**Comment by Delgan** [comment]
I'm closing this issue since the answer was given. I don't think it's technically possible to make `lazy` run asynchronously.
