### ISSUE TITLE
Could I get the log path if using time rotating?

### ISSUE THREAD

**Issue by liziwl** [Delgan/loguru#391]
```py
handler_id = logger.add("./log/" + file_name + "_{time}.log", encoding="utf8", newline='')
# time is given by loguru, so the log file name is `ANAME_2021-01-29_19-45-38_468645.log`
```
if it is possible to get the real logger path by `handler_id`?

**Comment by Delgan** [comment]
That is not possible, the `handler_id` only serves to remove it.

Why do you need the filepath? Maybe you can use a custom `rotation` or `retention` function.

Otherwise, you need to create the filename by yourself.

```python
from datetime import datetime

filepath = "./log_{}_{}.log".format(file_name, datetime.now().isoformat())
logger.add(filepath, encoding="utf8", newline="")
```

**Comment by liziwl** [comment]
the solution is working, thanks.
