### ISSUE TITLE
some pre-configured format remains even after logger.remove() when calling logger.exception()

### ISSUE THREAD

**Issue by origliante** [Delgan/loguru#394]
As in the title, I am doing

```
logger.remove()
logger.add(sys.stderr, format=fmt, level=lvl)
logging.basicConfig(handlers=[InterceptHandler()], level=0)
```

What happens is if I call logger.exception():

```
2021-02-09T17:16:44.768196+0100 | ERROR | # | test
NoneType: None
2021-02-09T17:16:44.768567+0100 | INFO | 123 | <-- this has tracking
```

the second line is also colored, so it seems some default format remains even after remove().
Third line is the consequence of logger.info():

```
if __name__ == "__main__":
    logger.exception("test")
    logger.info("<-- this has tracking", tracking_id="123")
```

**Comment by Delgan** [comment]
Hi @origliante.

I'm not sure of which default format you're talking about. The message `NoneType: None` is due to `logger.exception()`: it tries to print the current exception, but there is none as you're not in a `try / catch` block.

**Comment by origliante** [comment]
I mean the default logging format.
So I see, the extra output is controlled by an option, and in order to not
color that output (in this case nonetype etc) the colorised option should
be used. Thanks

Il giorno mar 9 feb 2021 alle 21:45 Delgan <notifications@github.com> ha
scritto:

**Comment by Delgan** [comment]
Ok I see. Indeed, if your `fmt` does not contain any color tag (like `"<green>{time}</green>"`) then it will appear to contain no color. However, exceptions are handled regardless of the format. Thus, they will be colored if the sink (`stderr`) supports colors.

As you discovered, you can plainly disable colors (including in exceptions) by specifying the `colorize` argument:

```python
logger.add(sys.stderr, format=fmt, level=lvl, colorize=False)
```
