### ISSUE TITLE
Specify a format for messages from the standard logging library when using the InterceptHandler()?

### ISSUE THREAD

**Issue by cscanlin** [Delgan/loguru#396]
Hi, thanks for making this library!

I have a case which seems relatively simple, but I'm having a hard time figuring out.

I'm essentially trying to pass a different format string to messages received from the standard logging library, but I can't figure out where it should go.

I've added a code snippet with some of my experiments and a reproduction of my problem as well.

Would greatly appreciate any tips or advice, thanks!

```python
import logging

from loguru import logger


# ?? Where does LOGURU_FORMAT go?
LOGURU_FORMAT = '{time:YYYY-MM-DD HH:mm:ss,SSS}|{name}|{process}|<level>{level}</level>| {message}'

# This doesn't work with messages coming from the logging module
# logger.add(sys.stdout, format=LOGURU_FORMAT)

class InterceptHandler(logging.Handler):
    # https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging
    def emit(self, record):
        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        # seems like LOGURU_FORMAT should go somewhere here,
        # but I didn't se any options for it
        loguru_opt = logger.opt(depth=depth, exception=record.exc_info)
        loguru_opt.log(record.levelno, record.getMessage())

def init(level=None):
    # The following lines are my original setup
    # log_format = '%(asctime)s|%(name)s|%(process)d|%(levelname)s| %(message)s'
    # logging.basicConfig(format=log_format, level=level or logging.INFO)

    # This is what I'm trying to replace it with, where does LOGURU_FORMAT go?
    logging.getLogger().setLevel(level or logging.INFO)
    logging.getLogger().addHandler(InterceptHandler())


if __name__ == "__main__":
    # This should show loguru messages with my custom format in any module that imports this one.
    init()
    logging.debug('debug msg')
    logging.info('info msg')
    logging.warning('warning msg')
    logging.error('error msg')


```

**Comment by Delgan** [comment]
Hi @cscanlin. :)

I think you may need to use `bind()` with a custom `format` function to differentiate the two types of messages.

You need to mark the logs in the `IntercepHandler` like this:

```python
loguru_opt.bind(intercepted=True).log(record.levelno, record.getMessage())
```

And then, define the two different formats you wish like that:

```python
def formatter(record):
    if record["extra"].get("intercepted, False):
        return "[loguru] {level} {message}\n{exception}"
    else:
        return "[standard] {level} {message}\n{exception}"

logger.remove()
logger.add(sys.stderr, format=formatter)

**Comment by cscanlin** [comment]
Hi @Delgan, thanks so much for the quick reply.

However, I don't think I explained my problem very well.

What I'd like to do is intercept the messages from the logging module, and exclusively replace them with the loguru formatted messages. Here's an example of what I'm trying to do
<img width="541" alt="Screen Shot 2021-02-23 at 6 35 24 PM" src="https://user-images.githubusercontent.com/2954573/108939214-39690f80-7606-11eb-92a5-03dade28d663.png">

Here's the code used to generate the image, based off of my example at the top of this issue.
```python
if __name__ == "__main__":
    init()  # This behavior must be supported in any module that calls this function

    logger.remove()
    logger.add(sys.stdout, format=LOGURU_FORMAT)

    print('This is what I would like all of my messages from logging to look like:')
    logger.debug('loguru debug msg')
    logger.info('loguru info msg')
    logger.warning('loguru warning msg')
    logger.error('loguru error msg')

    print('How do I format these messages to have loguru style, without using logger?')
    logging.debug('logging debug msg')
    logging.info('logging info msg')
    logging.warning('logging warning msg')
    logging.error('logging error msg')
```

The top messages are generated by loguru, using the `logger` object, and in the format that I want.

The bottom messages are generated by the logging library and appear to have been intercepted by loguru, but are only partially in the correct format (level number instead of name, no color).

I would like for messages generated by the logging library to have the same format as those generated by loguru.

Thanks again for the help, and please let me know if I can provide additional details!

**Comment by cscanlin** [comment]
Eck, I just read through the docs again, and it seems like I left out a critical part of the example code:
```
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno
```

Without this, the color formatting does not come through properly, but adding it back in fixed my problem.

Thanks again for the help and the great library!
