### ISSUE TITLE
How to log actions from child classes

### ISSUE THREAD

**Issue by Weyaaron** [Delgan/loguru#397]
Hi all,
consider the following scenario:
I implemented different implementations of a base-class, and I want a logfile for each of the children.
But since most of them run code from the base-class, and this is where the call to loguru happens,
its logged as a call from the base class. 

My question ist:
How wo i differentiate betweeen the children and log for each individually?

My current solution involves adding extra context for each of the children using bind, and filtering for 
this context, but this solution is (as far as I can tell) far from being elegant or obvious.

Any other ideas/solution?

Apart from this small issue, this library is a joy to work with, thanks a lot for
providing it!

**Comment by Delgan** [comment]
Hi @Weyaaron, thanks for the kind words. :+1: 

Usually combining `bind()` and `filter` is the way to go, even if I agree it's not very straightforward.

Basically, I don't think it's possible to differentiate between child classes apart from marking the `logger` using `bind()`.

Alternatively, maybe you can create one new `logger` for each of your child class, and attach it a unique logfile?

This part of the documentation may help: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers).

**Comment by Delgan** [comment]
I'm closing this issue since I think I answered it. If not, feel free to reopen it. ;)
