### ISSUE TITLE
Integration with notifiers

### ISSUE THREAD

**Issue by liiight** [Delgan/loguru#4]
So I'm checking out this amazing library, which happens to be exactly what I was looking for, and to my great surprise, the last segment talks about integration with notifiers, which I'm its creator. 

First off, I'm honored and flattened that you decided to include notifiers as a potential use case for your library. Thanks for that.

I'm not sure if you're aware of this, but I had the same idea in mind, so I created a custom logging handler for notifiers: https://notifiers.readthedocs.io/en/latest/Logger.html 

Using it with logger.start could be even nicer with less boilerplate, which is kinda the point of this great library. 

This is just a suggestion obviously, as your example is a perfectly valid use case.

Anyway, thanks again for mentioning notifiers and ofcourse, for this awesome library!

**Comment by liiight** [comment]
That's great to hear. I'll be keeping a close eye on this project 😁

**Comment by Delgan** [comment]
I improved the formatting of standard `Handler` and published a new version `0.2.2`.

At the same time, I updated the Readme to mention the `NotificationHandler` from `notifiers`. Thanks again for having proposing the improvement! 👍
