### ISSUE TITLE
Get the current logging level

### ISSUE THREAD

**Issue by dclong** [Delgan/loguru#402]
What is the recommended way to get the current logging level? I'm currently using `logger._core.min_level`. Is there a better way to query the current logging level (without accessing a private instance member)?

**Comment by Delgan** [comment]
Hi @dclong.

Where do you need to access the current level?
There is not really a concept of "current level". Each added sink is configured with one level, thus there is one level per handler. The `logger._core.min_level` only serves for internal usage as an optimization, and is not meant to become public.

**Comment by AGhost-7** [comment]
If it helps understand use cases, you may need to access the property to pass it over to a module that implements its own logging. That or you could be calling a subprocess with verbose flag if the loguru logging is set to verbose.

**Comment by Delgan** [comment]
@AGhost-7 Thanks for the example. In this case, I think it's better if the developer manages the storage of the minimum level himself. I understand that it would seem more convenient, but the `logger` is not intended to be a class to carry data. It is best in my opinion to create a class dedicated to the configuration parameters and pass it to your sub-module or sub-process.

**Comment by AGhost-7** [comment]
It is already carrying the data. We're just asking to expose it.

**Comment by Delgan** [comment]
@AGhost-7 I got your point but this is not something I'm willing to expose. It's not worth it in my opinion (in particular many more data could be exposed this way while there is currently none, I prefer to keep like that).

**Comment by kthy** [comment]
Came here looking for a solution to logging the loglevel (it's configurable from the command line in my application) but respect the design choice. Suggest closing the issue as `WONTFIX`.

**Comment by Delgan** [comment]
Thank you for your understanding @kthy. Closing the ticket as suggested. :+1:

**Comment by amitbcp** [comment]
@kthy how are you setting the loglevel for loguru from command line or code ?

I want to set it to print only INFO and above, how can we do that?

**Comment by kthy** [comment]
@amitbcp Something like this:

```python
from argparse import ArgumentParser
from loguru import logger

if __name__ == "__main__":
    # Argument parsing
    parser = ArgumentParser(add_help=False)
    parser.add_argument("-d", "--debug", action="store_true")
    args = parser.parse_args()
    DEBUG = args.debug

    # Loguru configuration
    if not DEBUG:
        logger.remove(0)
    logger.add(
        gettempdir() + "/my_application.log",
        backtrace=DEBUG,
        diagnose=DEBUG,
        format="{time:YYYY-MM-DD HH:mm:ss} | {level:<7} | {message}",
        level="DEBUG" if DEBUG else "INFO",
    )

    # Go!
    main()
```

Caveat: it's been nearly a year since I worked on this last, and I particularly don't remember what `logger.remove(0)` does.

**Comment by Delgan** [comment]
Hi.

The `LOGURU_LEVEL` environment variable (equals to `"DEBUG"` by default) serves to configure the default level of all added handlers (when `level` argument is omitted), including the pre-existing `sys.stderr` handler. It can be helpful to configure `LOGURU_LEVEL` according to your preferences during development.

If you want your Python script to only log `"INFO"` errors and above, it is recommended to explicitly add an handler with the desired `level` (so that it does not depend on environment when it's executed). To do so, you have to remove the pre-existing handler, and replace it with the properly configured handler. 

```python
import sys
from loguru import logger

logger.remove(0)  # This remove the pre-existing handler (which has the '0' id).
                  # It's also possible to call "logger.remove()" to remove all existing handlers.

logger.add(sys.stderr, level="INFO")
```

As pointed out by @kthy, you can use `argparse` to conditionally configure the level depending on command line arguments.

```python
import argparse
import sys
from loguru import logger

parser = argparse. ArgumentParser()
parser.add_argument("--verbose", action="store_true")
args = parser.parse_args()

logger.remove()
logger.add(sys.stderr, level="DEBUG" if args.verbose else "INFO")

logger.debug("Test")
```

Hope it helps

**Comment by sqlboy** [comment]
I have a whole section of code want to run if the app is in debug mode, is there a way to check if the effective logging level is debug?

**Comment by Delgan** [comment]
@sqlboy Assuming the purpose of this section is to conditionally log a debug message, you should use the `lazy` parameter of the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method:

```python
def compute_debug_value():
    # Blablabla
    return 42

# Function "compute_debug_value" will only be evaluated if "DEBUG" is an effective level.
logger.opt(lazy=True).debug("The value is: {}", compute_debug_value)  
```

**Comment by sglbl** [comment]
@Delgan, I use pyomo for linear optimization and since I don't have an option to put their print function in my debug logs, I want to do at least an option to check the level and if the level is `DEBUG`, I want to print the statements. How can I get the min level safely?

```python
# Print the parameters (optional)
print_params = True # Instead of this, I prefer something like 'if logger.min_level == "DEBUG"'
if print_params:
    logger.debug("Model.LINEAS: "); model_instance.LINEAS.pprint()
```

**Comment by Delgan** [comment]
@sglbl Ideally, Pyomo would provide a function to return a string instead of printing to `stdout` / `stderr`. If such thing does not exist, you may be able to create a wrapper to capture the output as a string and pass it to Loguru:

```python
from loguru import logger
import io
from contextlib import redirect_stdout


def lineas_pprint():
    print("<Debug value>")


def lineas_pprint_as_string():
    with io.StringIO() as buf, redirect_stdout(buf):
        lineas_pprint()
        return buf.getvalue()


logger.debug("Model.LINEAS: {}", lineas_pprint_as_string())
```

This can also be combined with the `lazy` attribute.

**Comment by sglbl** [comment]
> [@sglbl](https://github.com/sglbl) Ideally, Pyomo would provide a function to return a string instead of printing to `stdout` / `stderr`. If such thing does not exist, you may be able to create a wrapper to capture the output as a string and pass it to Loguru.

Thank you. I liked this solution, it solved my problem.
