### ISSUE TITLE
Store logger.log() output into variable

### ISSUE THREAD

**Issue by thewh1teagle** [Delgan/loguru#404]
Hi.
I want to store the output of `logger.log("Some logging message")` into variable.
The reason for that is that I want to send some logging messages into my Email from the program same as they shown in the terminal console
for instance

```
>> log_msg = logging.log("Storing data...")
# Nothing should print into the terminal console
>> print(log_msg)
# Expected output
2021-02-20 23:11:48.955 | INFO     | TeleBot:store_data:69 - Storing data...

# And of course, I would like to send it to my mail
>> send_logging_message_to_mail(log_msg)
```
![image](https://user-images.githubusercontent.com/61390950/108608701-5ec10800-73d1-11eb-8309-75d53e6c5c1c.png)

**Comment by obviousrebel** [comment]
I believe you can just use a [notifier sink](https://github.com/Delgan/loguru#exhaustive-notifier) to send the log messages.

**Comment by Delgan** [comment]
Thanks @obviousrebel for pointing that out. Indeed, it's not possible to retrieve the output of a logging call. Actually, there is no such output because it depends entirely of the added handlers and their `format` configuration. Each handler has its own output.

You should instead add your `send_logging_message_to_mail()` as a sink and use maybe a `filter` combined with `bind()` to decide when to send the email.

```python
def should_send_mail(record):
    return record["extra"].get("send_mail", False)

logger.add(send_logging_message_to_mail, filter=should_send_mail)

logger.info("Basic message")
logger.bind(send_mail=True).info("Storing data and sending mail...")
```

**Comment by thewh1teagle** [comment]
@Delgan 
Thank you. 
I have some misunderstanding. 
`logger.add(`**send_logging_message_to_mail**`, filter=should_send_mail)`
As i understand the first parameter is sink or logging Handler object.
I probably need custom logging handler that will receive the logging message from loguru and send it to mail. Can you help me with that handler? I tried myself and I didn't managed to make that.

**Comment by thewh1teagle** [comment]
> I believe you can just use a [notifier sink](https://github.com/Delgan/loguru#exhaustive-notifier) to send the log messages.

Thank you for this very useful tip. 
Currently my requirement is too simple to use `notifier sink`

**Comment by obviousrebel** [comment]
> @Delgan
> Thank you.
> I have some misunderstanding.
> `logger.add(`**send_logging_message_to_mail**`, filter=should_send_mail)`
> As i understand the first parameter is `sink` or logging Handler object.
> I probably need custom logging handler that will receive the logging message from `loguru` and send it to mail. Can you help me with that handler? I tried myself and I didn't managed to make that.

The first parameter can also be a callable (function) so should work as is, just update to point to your function that takes message as a parameter.

**Comment by Delgan** [comment]
Thanks again @obviousrebel for the support. :+1:

@thewh1teagle Can this issue be closed or do you have any other questions?

**Comment by thewh1teagle** [comment]
The issue can be closed. Thank you!
