### ISSUE TITLE
Minor redundancy in _filters.filter_by_level()

### ISSUE THREAD

**Issue by jonathn** [Delgan/loguru#407]
In this function.. https://github.com/Delgan/loguru/blob/bb7ee25c860d8203ea26fedff234d5ae5436e010/loguru/_filters.py#L17-L27
it looks like if a module name doesn't match anything in the `level_per_module` dict
(ie. none of the parent modules match either), then the full module name will be compared twice..
eg.
```
"foo.bar.baz" in level_per_module == False
"foo" in level_per_module == False
"foo.bar" in level_per_module == False
"foo.bar.baz" in level_per_module == False    << this match is redundant
```
Perhaps the checking could be done in the reverse order (ie. "foo.bar.baz", "foo.bar", "foo") and `break` at the first match?

**Comment by Delgan** [comment]
Well done for having noticed that! You're right, it seems more appropriate to start from the end anyway.

What do you think of the following implementation?

```python
def filter_by_level(record, level_per_module):
    name = record["name"]

    level = 0

    if name in level_per_module:
        level = level_per_module[name]
    else:
        while name:
            index = name.rfind(".")
            name = name[:index] if index != -1 else ""
            if name in level_per_module:
                level = level_per_module[name]
                break

    if level is False:
        return False

    return record["level"].no >= level
```

**Comment by jonathn** [comment]
Looks good..
If you prefer, this alternative does the same, just slightly shorter:
```python
def filter_by_level(record, level_per_module):
    name = record["name"]

    while True:
        if name in level_per_module:
            level = level_per_module[name]
            if level is False:
                return False
            return record["level"].no >= level
        if name == "":
            return True
        index = name.rfind(".")
        name = name[:index] if index != -1 else ""
```

**Comment by Delgan** [comment]
This is much more elegant, thanks!

I just replaced `if name == "":` with `if not name:` because there exists an special case in which `record["name"]` is `None`.
