### ISSUE TITLE
Support for pydantic attribute validation

### ISSUE THREAD

**Issue by matteosantama** [Delgan/loguru#408]
Loguru defines a `Logger` object in its `__init__.pyi` file, but does not have a corresponding `Logger` importable from `__init__.py`. This leads to slightly bizarre semantics where, in order to type hint a logger, you must have

```python
from __future__ import annotations
```

and then type hint your attribute with `loguru.Logger`. `loguru.Logger` is not a real object however, so `pydantic` throws an error when it tries to validate the type hints of your class: `AttributeError: module 'loguru' has no attribute 'Logger'`.

A proposed fix would be to change `from ._logger import Logger as _Logger` to `from ._logger import Logger` in `__init__.py`.

**Comment by Delgan** [comment]
The actual `Logger` class is not meant to be publicly exposed as the end user is not supposed to instantiate `logger` objects. That's why it's only part of the `.pyi` stub file. It can serve for type hints, but that's all. Actually, there are [many others types](https://loguru.readthedocs.io/en/stable/api/type_hints.html) which can be useful for annotations but do not even exist in the code.

Maybe `pydantic` will stop complaining if strings are used to annotate functions? Why would this not work with stub files?

**Comment by matteosantama** [comment]
`pydantic` checks the validity of a class's attributes upon instantiation. This means if I have a class

```python
@pydantic.dataclasses.dataclass
class Foo:

    the_logger: loguru.Logger
```

and I go to instantiate the class like 

```python
from loguru import logger

foo = Foo(the_logger=logger)
```

`pydantic` tries to import `loguru.Logger`, which obviously fails.

It's also rather verbose to have to specify `loguru.Logger` as a type hint.

**Comment by Delgan** [comment]
So it seems `pydantic` does not support stub files. I didn't realize this was a possible restriction at the time I implemented `.pyi` file. For example with `mypy` you can use `Logger` directly:

```python
from loguru import *

@dataclass
class Foo:
    the_logger: Logger
```
However, stub files are valid Python files as far as I know. I'm surprised Python does not come with a way to load them. Something like that could be useful for `pydantic` maybe:

```python
import types
import sys
import loguru

def load_stub_file(lib):
    name = lib.__name__ + "_types"
    path = lib.__file__ + "i"

    with open(path) as file:
        stub = file.read()

    module = types.ModuleType(name)
    exec(stub, module.__dict__)
    sys.modules[name] = module

load_stub_file(loguru)
from loguru_types import *
```
