### ISSUE TITLE
How to write logging helper functions that are reported as callers

### ISSUE THREAD

**Issue by jlumbroso** [Delgan/loguru#409]
I am writing a logging function called `log_intermediate_image()` that does the work of ([only lazily](https://github.com/Delgan/loguru/#lazy-evaluation-of-expensive-functions)) create an image file as a debug log. It works perfectly, my only annoyance is that this helper function replace the caller function in the log output:

```
2021-03-09 09:50:22.549 | DEBUG    | graphics.processing:log_intermediate_image:104 - Logged intermediate `' image: /var/folders/qc/hfft_g11071b0mj2f1vhbjt00000gn/T/tmp089sitka-incipit/_nozGWtNbJm.tiff
```

This logger is called from another function:
```python
def original_transformation():
    # ...
    log_intermediate_image(...)
    # ...
    log_intermediate_image(...)
    # ...
    log_intermediate_image(...)
    # ...
```

I would like to have this instead:
```
2021-03-09 09:50:22.549 | DEBUG    | graphics.processing:original_transformation:104 - Logged intermediate `' image: /var/folders/qc/hfft_g11071b0mj2f1vhbjt00000gn/T/tmp089sitka-incipit/_nozGWtNbJm.tiff
```

Is that possible, and if so how? (If it's possible, it would be a good recipe 😊)

**Comment by Delgan** [comment]
Hi @jlumbroso.

I think maybe you can use [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) with the `depth` argument?

Inside `log_intermediate_image()` you can do something like that:

```python
logger.opt(depth=1).debug("Logged intermediate ...")
```
It will force the frame retrieved for the context to be one level above, that is the frame of your `original_transformation()` function

**Comment by jlumbroso** [comment]
Hello @Delgan.

Thank you so much for your package and your help. I'm amazed it was so simple!

I now have exactly what I want, which is, a helper logging function but logging the caller function:
```
2021-03-11 09:08:41.410 | DEBUG    | incipit.processing:detect_regions_from_image:148 - Logged intermediate `' image: /var/folders/qc/hfft_g11071b0mj2f1vhbjt00000gn/T/tmpbutaghth-incipit/image_yrlhnBuXsq.tiff
2021-03-11 09:08:41.631 | DEBUG    | incipit.processing:detect_regions_from_image:150 - Logged intermediate `' image: /var/folders/qc/hfft_g11071b0mj2f1vhbjt00000gn/T/tmpbutaghth-incipit/image_GrOhpcgqmT.tiff
2021-03-11 09:08:42.099 | DEBUG    | incipit.processing:detect_regions_from_image:153 - Logged intermediate `' image: /var/folders/qc/hfft_g11071b0mj2f1vhbjt00000gn/T/tmpbutaghth-incipit/image_YZYDlcReef.tiff
```
I noticed that I had to use `logger.opt(depth=1, lazy=True)` because `logger.opt(depth=1).opt(lazy=True)` seemed to make the lazy work and `logger.opt(lazy=True).opt(depth=1)` seem to make the `depth` work (in other words, I found out that successive calls to `opt()` seem to overwrite previous calls in the chain).

So I am thinking of making a pull request with the following two changes to your README.md:
1. In [the passage that introduces `lazy` and `opts()`](https://github.com/Delgan/loguru/#lazy-evaluation-of-expensive-functions), I would like to put a note that explains how to chain multiple options.
2. I would like to add a subsection with an example on creating your own logging helper function that uses `opt(depth=1)` to report the caller function instead of the logger function.

What are your thoughts? Would you approve these changes?

Thanks again for all your help.

**Comment by Delgan** [comment]
Glad you like this project, @jlumbroso. :smiley:  

Also, thanks for offering your help!
To be honest, I think I prefer to keep the Readme minimal. There are possibly several quirks to be aware of when using Loguru, and it's not possible to cover them all in the Readme.
They should be detailed in the actual documentation. The Readme serves just a showcase of existing features. That's why I also point to the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) description, where can be found warning about chained calls and an example with wrapped function. If the explanations in the documentation are not clear enough, let me know how it could be improved!
