### ISSUE TITLE
CI/tests: use tox?

### ISSUE THREAD

**Issue by blueyed** [Delgan/loguru#41]
I think it is very useful to have a `tox.ini` to run tests in an isolated way.
This would also allow for using `tox-travis` on Travis then.

What is your opinion?  I'd be happy to provide a PR for this.

**Comment by Delgan** [comment]
I was a little worried that adding `tox` would clutter the repository needlessly and badly integrate with Travis, but thanks to `tox-travis` this is not the case. Using `tox` is best practice anyway, so there is no reason not to use it.

Thanks for the suggestion! A PR would be much appreciated when you have a little time, as you are surely more used to `tox` than I am. 🙂

**Comment by blueyed** [comment]
Cool.
I will also add some flake8 and pytest settings along the way: do you prefer to have them in setup.cfg (or maybe pyproject.toml), or within tox.ini then?

**Comment by Delgan** [comment]
> Cool.
> I will also add some flake8 and pytest settings along the way: do you prefer to have them in setup.cfg (or maybe pyproject.toml), or within tox.ini then?

I wish to limit the number of files and settings to the bare minimum. If it can fit into the `tox.ini`, it's perfect.

How would the integration of `flake8` looks like? This is very useful to improve overall code quality, on the other hand I don't want the CI tests to fail because of styling issues.

**Comment by blueyed** [comment]
Going with tox.ini then.
I would just add some config for flake8, we do not have to inforce it, but it helps already when editing files (I am checking Python files using it by default).  What max-line-length do you prefer?

**Comment by Delgan** [comment]
Yes, `flake8` integration for local development is something definitely missing in my workflow. This will be of great help, thank you!

The max-line-length should be 100.

**Comment by qcoumes** [comment]
@blueyed I can do it if you're to busy.

**Comment by Delgan** [comment]
Closing as it has been fixed. :+1:
