### ISSUE TITLE
Colors not working when using loguru with tqdm.write as sink

### ISSUE THREAD

**Issue by ma-sadeghi** [Delgan/loguru#411]
# With `tqdm.write` as sink
```python
import sys
from time import sleep
from tqdm import tqdm
from loguru import logger
logger.remove()
logger.add(lambda msg: tqdm.write(msg, end=""), level="INFO")


for i in tqdm(range(10)):
    sleep(0.1)
    logger.error("Ouch!")
```
<img src="https://user-images.githubusercontent.com/14086031/110737616-b3e78100-81fb-11eb-8d09-c6955afd01ce.png" width=50%>

# Without `tqdm.write` as sink
```python
import sys
from time import sleep
from tqdm import tqdm
from loguru import logger


for i in tqdm(range(10)):
    sleep(0.1)
    logger.error("Ouch!")
```
<img src="https://user-images.githubusercontent.com/14086031/110737654-c5308d80-81fb-11eb-9ea2-a1c000946556.png" width=50%>

**Comment by Delgan** [comment]
You need to specify `colorize=True` while adding the `tqdm` sink. By default, Loguru tries to guess if the sink supports colors or not. In the case of a `lambda` function, it usually doesn't.

```python
logger.add(lambda msg: tqdm.write(msg, end=""), colorize=True, level="INFO")
```

I should probably update the code snippet existing in the documentation.

**Comment by ma-sadeghi** [comment]
@Delgan Great, thanks!

**Comment by Delgan** [comment]
Docs updated. :+1:
