### ISSUE TITLE
Can I use 2 loggers?

### ISSUE THREAD

**Issue by Timtaran** [Delgan/loguru#413]
Hello! I'm Russian and I know English bad, if you can't read my issue, I'm pinned Russian version([translate](translate.yandex.ru)).
I'm using Framework [vkbottle](github.com/timoniq/vkbottle) and is have logging with loguru and I'm have my logs, I want to save only my logs with logger.add to file but saved vkbottle logs and my.
Приветстувую! Я Русский и плохо знаю английский, если вы не можете прочитать мой issue, ниже будет русская версия.
Я использую вреймворк  [vkbottle](github.com/timoniq/vkbottle), в нем используется логирование при помощи loguru, так же у меня есть мои логи, я хочу сохранить только свои логи с помощью logger.add, но у меня сохраняются и те и те.

**Comment by Delgan** [comment]
Hi @Timtaran.

You can use [DeepL](https://www.deepl.com/translator) to help translating. :+1:

From what I understand, if you don't want `vkbottle` messages to appear in your logs, you should [`disable()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.disable) it.

 ```python
logger.disable("vkbottle")
```

All logs coming from this library will be ignored then.

**Comment by Timtaran** [comment]
Thanks
