### ISSUE TITLE
Setting format parameter as a function that will add prefix to each line of the log message

### ISSUE THREAD

**Issue by hheather** [Delgan/loguru#415]
Hello!

The docs say I should be able to pass a function to the log obj's format parameter. I've written a function that will get each line of the log's message, and add the prefix to it. It doesn't work because I don't know how to access the log object to get the message properly. Would some one be able to help?

Thanks

```
def get_format():
    for new_line in '{message}'.splitlines():
        return '%s{time:YYYY-MM-DD HH:mm:ss.SSS} | <level>{level: <8}</level> | ' \
               '{name}:{function}:{line} - <level>%s</level>' % (get_env_vars(), new_line)

log.add(sys.stdout, format=get_format())
```

**Comment by Delgan** [comment]
Hi @hheather.

Your `get_format()` function should accept the `record` object as an argument. Thanks to it, you will be able to access the content of the logged message. You should also pass the actual function to `logger.add()` and you should not call it.

```python
def get_format(record):
    for new_line in record["message"].splitlines():
        return '%s{time:YYYY-MM-DD HH:mm:ss.SSS} | <level>{level: <8}</level> | ' \
               '{name}:{function}:{line} - <level>%s</level>' % (get_env_vars(), new_line)

log.add(sys.stdout, format=get_format)
```

**Comment by hheather** [comment]
> Hi @hheather.
> 
> Your `get_format()` function should accept the `record` object as an argument. Thanks to it, you will be able to access the content of the logged message. You should also pass the actual function to `logger.add()` and you should not call it. Finally, you need to return one unique string.
> 
> ```python
> def get_format(record):
>     fmt = ""
>     for new_line in record["message"].splitlines():
>         fmt += '%s{time:YYYY-MM-DD HH:mm:ss.SSS} | <level>{level: <8}</level> | ' \
>                '{name}:{function}:{line} - <level>%s</level>' % (get_env_vars(), new_line)
>     return fmt
> 
> log.add(sys.stdout, format=get_format)
> ```
> 
> Note that merging the message directly in this function is not recommended because it can cause errors if your message contains `{}` symbols for example (due to Loguru calling `.format()` on the returned string). I possible workaround is to use the `extra` parameters:
> 
> ```
> def get_format(record):
>     fmt = ""
>     lines = record["message"].splitlines()
>     record["extra"]["lines"] = lines
>     record["extra"]["env_vars"] = get_env_vars()
>     for i in range(len(lines)):
>         fmt += '{extra[env_vars]}{time:YYYY-MM-DD HH:mm:ss.SSS} | <level>{level: <8}</level> | ' \
>                '{name}:{function}:{line} - <level>{extra[lines][i]}</level>'
>     return fmt
> ```

Thanks so much for taking the time to respond, this is really helpful!!
