### ISSUE TITLE
threading variable binding

### ISSUE THREAD

**Issue by engineli** [Delgan/loguru#419]
I want log message with a threading tag . so I can search log with the tag . but I can't find the api. In python's logger  can use 
```
 logging.setLogRecordFactory(record_factory)
```
this function like sl4j's MDC.put("xxx","abc") in Java . we can add this Feature ?

**Comment by Delgan** [comment]
You can add a context to your log using through the `extra` dict of the log record. Depending on your use case, you may rely on [`.bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind), [`.contextualize()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.contextualize) or [`.patch()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch). It's not clear exactly for me which solution you're looking for.

**Comment by engineli** [comment]
> You can add a context to your log using through the `extra` dict of the log record. Depending on your use case, you may rely on [`.bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind), [`.contextualize()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.contextualize) or [`.patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch). It's not clear exactly for me which solution you're looking for.

My problem resolved with ``` .contextualize()```  .thank you
