### ISSUE TITLE
Terminate on ERROR level

### ISSUE THREAD

**Issue by dbrennand** [Delgan/loguru#425]
Hi,

I'm looking to log different levels for my application such as INFO and ERROR. 

When an ERROR is logged, I would like the application to terminate. Is there a way that loguru can handle this for me instead of checking the level manually and calling `exit()`?

Many Thanks.

**Comment by dbrennand** [comment]
I think I may have worked my issue out 😃 

After looking the API reference, I saw that I can provide the filter parameter to `logger.add()` and using lambda, provide my own function to check the record level.

Code:

```python
from loguru import logger

def check_log_record_level(record):
    if record["level"].name == "ERROR":
        exit()

logger.add("app.log", filter=lambda record: check_log_record_level(record))

logger.info("App doesn't exit here because level is not error.")
logger.error("App does exit here though!")
```

**Comment by Delgan** [comment]
Using a custom `filter` should work because in your case, the function returns `None` and thus no logs are sent to the `"app.log"` file. However, you can also simply use `check_log_record_level` as a sink. :+1:

```python
logger.add(check_log_record_level, level="ERROR")
```

**Comment by dbrennand** [comment]
Oh! I didn't realise it did not log to the file.

Hmm... How would I still have it log to the file as well.

Also, I tried adding `check_log_record_level` as a sink:

> ```python
> logger.add(check_log_record_level, level="ERROR")
> ```

And the following error occurs:

```
 if record["level"].name == "ERROR":
TypeError: string indices must be integers
```

**Comment by Delgan** [comment]
Meh. I overlooked the `sink` accept a `message` string and not the `record` directly, so it must be slightly modified.

You can also use two sinks: the first one will check the level and exit your application if needed. The other one will simply log the messages to your file unconditionally.

```python
def exit_on_error(message):
     if message.record["level"].name == "ERROR":
        exit()

logger.add(exit_non_error, level="ERROR")
logger.add("app.log")
```

But you can also use the `filter` solution just as before, make sure to return `True` so logs are not discarded.

```python
def check_log_record_level(record):
    if record["level"].name == "ERROR":
        exit()
    return True

logger.add("app.log", filter=check_log_record_level)
```

**Comment by dbrennand** [comment]
Awesome! Thanks a lot @Delgan
