### ISSUE TITLE
Logging in generator causing slowdown

### ISSUE THREAD

**Issue by halkony** [Delgan/loguru#427]
Hey Delgan, thanks for your work.

I have a generator in a project and I want to log a local variable to a file whenever it yields. However, logger.debug is slowing my main thread with its I/O. I have enqueue enabled on the handler, which I understand as pushing all the sink handling to another thread.

The debug message is directly before the return statement and my process is single thread. How do I write logs in parallel? 

I am unable to replicate my issue in a scratch file, though I have a py-spy flamegraph that confirms its using 500ms on I/O for every function call in my thread.

**Comment by Delgan** [comment]
Hey @halkony.

This confuses me a bit. You created your file handler with "enqueue=True", right? Then, as you understood, the `logger.debug()` function will not perform any I/O task, it will be executed in a background thread. So I have hard time to understand how it's possible for the function to be that slow.

Maybe the `logger` in general not fast enough for your use case (the log record is created in the main thread)?

**Comment by halkony** [comment]
Here is my profile on a log call within the main thread. My expectation is that py-spy wouldn't catch these from the same PID.

![image](https://user-images.githubusercontent.com/15790371/114745190-0bee3780-9d14-11eb-83cc-99c7dc0d8298.png)

I confirmed that the handler is properly fed to the `self._queue = multiprocessing.SimpleQueue()` daemon.

So it probably isn't fast enough for my use case. Does the logger run well with 250+ it/s?

**Comment by halkony** [comment]
I've downloaded the fastlogging module and it scales well for my use case. Definitely a volume thing. Thanks for the help!

**Comment by Delgan** [comment]
I didn't know about `fastlogging`, it looks interesting! Hopefully one day `loguru` will be as fast. Glad you have found a viable alternative. :+1:

**Comment by mo-han** [comment]
`fastlogging` might be faster, and it even provide `ast optimizer`. but the developer need to manually write the code to use it.
while loguru is much easier to use.
