### ISSUE TITLE
Thank you, I am back to sanity.

### ISSUE THREAD

**Issue by wsw70** [Delgan/loguru#429]
This is not an issue, this is just to say thank you. 

After 10+ years of (amateur) Python development and so many thousands of "what the fuck now?" (*) when dealing with the built-in logger, I discovered a moment ago `loguru`.

It just works.

I will read the docs in detail but just after the tour and one line of import everything just works. THANK YOU.

Please feel free to close this "issue" once you have seen it so that it does not pollute the real issues or questions.

---

(*) I am French so it was the localized version of this desperate incantation.

**Comment by Delgan** [comment]
Your comment made me very happy to read, thank you for sharing your happiness. :smile: 

I had the same headaches as you with the standard logging module...
That's what motivated me to create Loguru and I'm glad to know that you like it!
Simplicity is king.

I hope you continue to enjoy it, and let me know if you need help in the future. :+1:
