### ISSUE TITLE
how can i write to log file without writing to console in loguru

### ISSUE THREAD

**Issue by iamharikrishnank** [Delgan/loguru#436]

**Comment by Delgan** [comment]
You can simply remove the default handler (which logs to console) and add the file handler.

```python
logger.remove()  # Remove all handlers added so far
logger.add("file.log")
```

**Comment by iamharikrishnank** [comment]
Actually I am using custom log.py (https://medium.com/1mgofficial/how-to-override-uvicorn-logger-in-fastapi-using-loguru-124133cdcd4e)

**Comment by iamharikrishnank** [comment]
got corrected thank u
