### ISSUE TITLE
Wish:  Loguru to behave nicely in jupyter notebook

### ISSUE THREAD

**Issue by cems2** [Delgan/loguru#437]
Hi, Loguru is wonderful because it traces errors without having to use some cumbersome IDE.  The killer app for this however jupyter notebooks because you can't use jupyter with an ide (makes no sense).

The problem is the traceback is Brutal in jupyter notebook when using @logger.catch

It does work in the sense that the expected output from logger is there at the end of the traceback but theres many dozens of lines of obfuscating jupyer garbage that gets sucked into the logging making this not a convenient tool.  

I hope you will consider making the play nice with Jupyter notebook

**Comment by Delgan** [comment]
Hi @cems2.

Did you try to configure your handler with `backtrace` option disabled?

```python
logger.remove()
logger.add(sys.stderr, backtrace=False)
```

This should prevent the traceback from going back to the very beginning of the call stack.
