### ISSUE TITLE
How do I reproduce the default handler?

### ISSUE THREAD

**Issue by salmiakki** [Delgan/loguru#438]
I like the default handler, but sometimes I need to adjust the level. The [recommended way](https://loguru.readthedocs.io/en/latest/resources/recipes.html#changing-the-level-of-an-existing-handler) to do it is to remove the handler and add a new one with another level. So far so good.

The difficulty I'm having is the style of the default handler is somewhat involved (e.g. the colors!), certainly not as simple as the snippet in the relevant part of the documentation (`logger.add(sys.stderr, level="DEBUG")`). Love it though.

So how do I reproduce it?

**Comment by Delgan** [comment]
Hey @salmiakki.

If you `add()` a new handler without specifying the `format` then it will use the default one. If you call `logger.add(sys.stderr, level="DEBUG")` to change the level of the default handler, the colors and logs format should remain untouched. Are you experiencing the opposite? If you wish to customize the default format, you can copy-paste it from here: https://github.com/Delgan/loguru/blob/68616485f4f0decb5fced36a16040f5e05e2842f/loguru/_defaults.py#L31-L37

**Comment by salmiakki** [comment]
Thanks!

> If you call logger.add(sys.stderr, level="DEBUG") to change the level of the default handler, the colors and logs format should remain untouched. 

Please consider adding it to the recipes.
