### ISSUE TITLE
How to redirect logging logger to loguru logger?

### ISSUE THREAD

**Issue by FateScript** [Delgan/loguru#439]
I like loguru logger, but some code in other repo using logging logger to log message, what I want to do is when I call a function in which logging.logger log some messages inside, loguru will log those messages instead.

It might look like this:
```python3
def f():
     logging.logger.info("Hello world")
```
calling f will have logging.logger logs.
I wonder if loguru could do things like:
```python3
redirect(loguru.logger, loging.logger) # redirect all logging.logger to loguru
f()  # using logging.logger equals using loguru.logger
```
or
```python3
# context version
with redirect(loguru.logger):
    f()
```

Thanks  for your help !

**Comment by Delgan** [comment]
Hey @FateScript. Did you try to use the `InterceptHandler` from [the Readme](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging)?

```python
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())

logging.basicConfig(handlers=[InterceptHandler()], level=0)
```
This should have the desired effect and redirect messages from standard `logging` to `loguru`.

**Comment by FateScript** [comment]
Hello @Delgan, Thanks for your reply :) It works for me, so I close this issue.
