### ISSUE TITLE
How to hide time from default logger?

### ISSUE THREAD

**Issue by ozangungortuhh** [Delgan/loguru#446]
Hi,
Thank you for this great logging tool. Is it possible to hide the time information for the default logger?
I can create a log file as I want by the following command, but I also want to use this format in the terminal logs.

```
logger.add("project.log", format="{level} | {message}")
```
Thanks!

**Comment by Delgan** [comment]
Hi.

You can [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default handler (which logs to `sys.stderr`) and re-[`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) it with your favorite format.

```python
logger.remove()
logger.add(sys.stderr, format="{level} | {message}")
logger.add("project.log", format="{level} | {message}")
```

**Comment by ozangungortuhh** [comment]
Thank you so much!
