### ISSUE TITLE
Custom Time Source

### ISSUE THREAD

**Issue by brett1479** [Delgan/loguru#447]
Is there a way I can provide a custom time function to loguru?  I would like the logging functionality to behave the same (in terms of formatting and what not) as before, but simply use an alternative function providing the current time.

Thanks in advance.

**Comment by brett1479** [comment]
Sorry, it appears patch does everything I need.

**Comment by Delgan** [comment]
No problem. You got it, [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) seems appropriate. :+1:

**Comment by brett1479** [comment]
I may still have a question on this one.  If I patch the logger, how can I make sure this patched version is used by anyone that runs
```from loguru import logger``` ?

**Comment by Delgan** [comment]
If you use [`logger.configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) the change will be applied "globally" and be inherited by anyone using the `logger` object (even bound and patched ones).

```python
logger.configure(patcher=add_custom_patch_source)
```

**Comment by brett1479** [comment]
Thank you for the amazingly quick reply!
