### ISSUE TITLE
Sends loguru logs to loggly over httpshandler

### ISSUE THREAD

**Issue by Johnnyevans32** [Delgan/loguru#448]
```
handler = loggly.handlers.HTTPSHandler(url=('https://logs-01.loggly.com/inputs/TOKEN/tag/python', 'POST'))
logger.add(handler)
```
tried this and it doesnt send

**Comment by Delgan** [comment]
It seems the `HTTPSHandler` is incorrectly configured: you do not need to pass a tuple containing the `"POST"` parameter. The `url` solely suffice.

```python
handler = loggly.handlers.HTTPSHandler(url='https://logs-01.loggly.com/inputs/TOKEN/tag/python')
logger.add(handler)
```

**Comment by Johnnyevans32** [comment]
thank you so much!!!! 🥂

**Comment by Delgan** [comment]
You're welcome. I'm closing this ticket since the issue is resolved. :+1:
