### ISSUE TITLE
Mypy complains with type-hints

### ISSUE THREAD

**Issue by rafaellehmkuhl** [Delgan/loguru#449]
First of all, this library is really, really handy. Logging is so much easier with it. Thanks!
Regarding the issue:

I'm working on a project that enforces type-hints with Mypy, and I'm intercepting some logging activity from another process, thus using [the InterceptHandler documented on the README file](https://github.com/Delgan/loguru/blob/master/README.rst#entirely-compatible-with-standard-logging):

```python
# main.py

from loguru import logger

class InterceptHandler(logging.Handler):
    def emit(self, record) -> None:
        # Get corresponding Loguru level if it exists
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())


logging.basicConfig(handlers=[InterceptHandler()], level=0)

logger.remove()
logger.add(sys.stderr, format="<green>{time:HH:mm:ss.SSS}</green> | <level>{message}</level>")

logger.info("Hi!")
```

This is working perfectly, but Mypy is complaining about the missing type-hints:

```
main.py:4: error: Function is missing a type annotation
main.py:14: error: Incompatible types in assignment (expression has type "Optional[FrameType]", variable has type "FrameType")
Found 2 errors in 1 file (checked 1 source file)
```

The first one is noticing that the `record` argument is not typed and the second one is noticing the type of the variable is changing.

Is there a recommended way of solving them?

I tried to import `Record` from loguru to type-hint the `record` argument but got several errors after:

```
main.py:4: error: Argument 1 of "emit" is incompatible with supertype "Handler"; supertype defines the argument type as "LogRecord"
main.py:4: note: This violates the Liskov substitution principle
main.py:4: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
main.py:7: error: "Record" has no attribute "levelname"
main.py:9: error: "Record" has no attribute "levelno"
main.py:17: error: "Record" has no attribute "exc_info"
main.py:17: error: "Record" has no attribute "getMessage"
Found 5 errors in 1 file (checked 1 source file)
```

**Comment by Delgan** [comment]
Hey @rafaellehmkuhl, gad you like Loguru, thanks!

About your issue: the `InterceptHander` inherits from [`logging.Handler`](https://docs.python.org/3/library/logging.html#logging.Handler). The [`emit()`](https://docs.python.org/3/library/logging.html#logging.Handler.emit) method is the one from the standard `logging` module, just as the `record` is. The `record` is not from a Loguru type, it's a [`logging.LogRecord`](https://docs.python.org/3/library/logging.html#logging.LogRecord) object. I guess Mypy should stop complaining if you use this type hint instead. :+1:

**Comment by Delgan** [comment]
I'm closing this ticket as it seems resolved but feel free to re-open it if you have any other question. ;)

**Comment by rafaellehmkuhl** [comment]
Hey Delgan, sorry for not replying before. Was somewhat busy.

Your previous comment clarified things and solved the previous errors, but the problem remains with the `frame` variable, which has confliting types.

Also,  when the proper `LogRecord` type is added to the `record` argument, another complaint rises with the `level` variable, which is a string on the `try` block, but is an integer on the `except` block. This is resolvable declaring the type as `Union[int,str]` on the scope of the emit function, though.

**Comment by Delgan** [comment]
Hi @rafaellehmkuhl. ;)

I don't know Mypy much, but surely it's possible to refactor the `InterceptHandler` so it can be type-hinted more easily, right?

Just an idea:

```python
class InterceptHandler(logging.Handler):
    def emit(self, record: logging.LogRecord) -> None:
        # Get corresponding Loguru level if it exists
        try:
            level: str = logger.level(record.levelname).name
            self._log(record, level)
        except ValueError:
            level: int = record.levelno
            self._log(record, level)

    def _log(self, record: logging.LogRecord, level: Union[int, str]):
        # Find caller from where originated the logged message
        frame: Optional[FrameType], depth = logging.currentframe(), 2
        while frame and frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())
```

I didn't tested it, though.

**Comment by rafaellehmkuhl** [comment]
@patrickelectric came with this solution:


```python
from logging import LogRecord
from types import FrameType
from typing import Any, List, Optional, Union

class InterceptHandler(logging.Handler):
    def emit(self, record: LogRecord) -> None:
        # Get corresponding Loguru level if it exists
        level: Union[int, str]
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message
        frame: Optional[FrameType]
        frame, depth = logging.currentframe(), 2
        while frame and frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())
```

I think its pretty much what is needed. Tested here and it works fine.

**Comment by quantumpacket** [comment]
I was getting failing tests on my `InterceptHandler()` due to an exception being raised by:

```text
# loguru/_logger.py

...

try:
    level_id, level_name, level_no, level_icon = core.levels_lookup[level]
except (KeyError, TypeError):
    if isinstance(level, str):
        raise ValueError("Level '%s' does not exist" % level) from None
        ...
```

I narrowed it down to `level = str(record.levelno)`, which I had casted to a string because of Mypy complaining about the int/str types conflicting. Little did I know that would cause Loguru to give the above exception _(yay for tests!)_.

I've noticed many people casting the value just as I did, and likely for the exact same reason. I'm sure they are not aware that will cause Loguru to raise an exception at some point.

Maybe it's best the example `InterceptHandler()` snippet is pre-type-hinted so nobody makes the same mistake, as no linters notice because `loguru.logger.log()` does accept int/str as the first arg, but integers must not be in the form of a string.

**Comment by Delgan** [comment]
@quantumpacket That sound like a good idea, thanks for pointing this out. I'll update the snippets. :+1:
