### ISSUE TITLE
write  log file  for different py file in a folder

### ISSUE THREAD

**Issue by chencjiajy** [Delgan/loguru#450]
if I have three py file in folder, how could I get different log for each py file
I have tried put the following code in each py file
```python
logger.add(sys.stderr, format="{time} {level} {message}", level="INFO")
logger.add(__name__+'.log', enqueue=True, rotation="20 MB")
```
then all three log content is same

similar but different issue: https://github.com/Delgan/loguru/issues/44

**Comment by Delgan** [comment]
Hi.

You can probably use a specific `filter`.

```python
logger.add("module_a.log", filter="module_a", enqueue=True, rotation="20 MB")
```
Only messages coming from the `module_a` module and its descendants will be written in the `"module_a.log"` file.

**Comment by SourabhSNath** [comment]
Hello, filter doesn't seem to working. I end up getting no logs in the files when I use filter with the module name...

**Comment by Delgan** [comment]
@SourabhSNath Are you able to provide a minimum reproducible example so I can investigate it please?
