### ISSUE TITLE
How to combine compression with in memory file-like object as sink ?

### ISSUE THREAD

**Issue by mathbeal** [Delgan/loguru#451]
Hi,

I really like the compression mechanism, but I would like to use it with a StringIO file-like object as sink. Both can't be used at the same time.

```
     if email_notify:
         receivers = list(email_notify)
-        logger.add(email_settings.log_file_name, mode="w", compression=send_log(receivers))
+        logger.add(
+            sink=StringIO(), compression=send_log(receivers))
         logger.info(f"Test")
```

Is there any workaround to send email with execution log trace without writing logs into files ?

**Comment by Delgan** [comment]
Hey.

For advanced use cases of this kind, it is possible to extend your file-like object with the `stop()` function. This will be called at the end of the application, just like the `compression` function would have been.

```python
class Sink:
    def __init__(self):
        self.file = StringIO()
    
    def write(self, message):
        self.file.write(message)

    def stop(self):
        send_log(self.file.getvalue())

sink = Sink()
logger.add(sink)
```

This is briefly explained in the documentation: [The sink parameter](https://loguru.readthedocs.io/en/stable/api/logger.html#sink).

**Comment by Delgan** [comment]
Closing as it seems resolved. Feel free to reopen otherwise. :+1:
