### ISSUE TITLE
How to customize logging format (adding newlines and custom text in terminal)

### ISSUE THREAD

**Issue by ClimenteA** [Delgan/loguru#455]
I'm trying to customize the logging format but probably the extra new lines and words not in tags and curly braces are removed. 

Log file has the needed format but in terminal the extra newlines and text are ignored. 

```py
from loguru import logger as log

log_format = """<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | 

Module:<cyan>{name}</cyan>
Function:<cyan>{function}</cyan>
Line:<cyan>{line}</cyan>

{level}:
<level>{message}</level>

"""

log.add(
    "app.log", 
    rotation="monthly", 
    format=log_format
)

# log = log.patch(lambda record: record["extra"].update(newline="\n"))
log = log.patch(lambda record: record["extra"].update(double_newline="\n\n"))

```

I tried something with using `patch`, but it seems to add them at the end of the log and if many results in a key error.

How can I add some newlines (\n\n) and some custom text to `format`?

**Comment by Delgan** [comment]
Hi.

Did you try firs to `remove()` the default handler logging to the terminal, so you can `add()` you own with a custom `format`?

```python
import sys
from loguru import logger as log

...

log.remove()
log.add(sys.stderr, format=log_format)
```

It seems to work fine according to my tests.

**Comment by ClimenteA** [comment]
It seems only one output can be customized either `sys.stderr` or `file.log`. It's good enough for me :)

Thank you!

**Comment by Delgan** [comment]
Both outputs can be customized: just call `add()` twice with the same `format`. :+1: 

The new lines and your additional text should appear in `sys.stderr` and `file.log`.

**Comment by ClimenteA** [comment]
Without `.remove()` in console the logs are duplicated

```py

import sys
from loguru import logger as log


debug = True
log_level = 'DEBUG' if debug else 'WARNING'

log_format = """<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <4}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan>
<level>{message}</level>
"""


log.add(
    "app.log", 
    rotation="monthly", 
    level=log_level, 
    format=log_format
)

#log.remove() # this removes first config and doesn't write to app.log

# has the needed output format
log.add(
    sys.stderr, 
    format=log_format
)



## Test
log.debug("Debug log")
log.info("Info log")
log.success("Success log")
log.warning("Warning log")
log.error("Error log")
log.critical("Critical log")

try:
    raise Exception("Demo exception")
except:
    log.exception("Exception log")
    log.trace("Trace log")


```

**Comment by ClimenteA** [comment]
Awesome! 

Adding `log.remove(0)` before `log.add()`  works as expected :)
