### ISSUE TITLE
can i release some resource in stop method

### ISSUE THREAD

**Issue by AHLinJie** [Delgan/loguru#456]
```
configs = {
        "handlers": [
            {
                "sink": PushToRedisHandler,
            }
        ],
    }

class PushToRedisHandler:
    def write(self):
        redis_client = get_redis_client()
        redis_client.push_to_redis(self)

    def stop(self):
        redis_client.connection_poll.disconnect()

```

![image](https://user-images.githubusercontent.com/10792685/119953164-4c59fa00-bfd0-11eb-97e3-6c880dee1412.png)

i am so confuse why the self is a Message instance

**Comment by Delgan** [comment]
It seems that there are two problems in your example:
* The `write()` method should accept a `message` parameter
* The sink used to configure the `logger` should be an instanced object, not a class

```python
configs = {
        "handlers": [
            {
                "sink": PushToRedisHandler(),
            }
        ],
    }

class PushToRedisHandler:
    def write(self, message):
        redis_client = get_redis_client()
        redis_client.push_to_redis(self)

    def stop(self):
        redis_client.connection_poll.disconnect()
```

**Comment by Delgan** [comment]
I'm closing this ticket since the question seems to be answered. Feel free to let me know if you have any other problems. ;)
