### ISSUE TITLE
Capturing and logging cli tool stderr output from within python

### ISSUE THREAD

**Issue by Technerder** [Delgan/loguru#458]
I'm currently working on a script that calls uses a library for interacting with ffmpeg and was wondering if there was a way to capture any stderr output that could be printed by ffmpeg and logging it using loguru.

Is this possible?

**Comment by Delgan** [comment]
Hi. This is possible, there are some examples in the documentation: [Capturing standard `stdout`, `stderr` and `warnings`](https://loguru.readthedocs.io/en/stable/resources/recipes.html#capturing-standard-stdout-stderr-and-warnings)

Also, it depends on how you plan to capture `ffmpeg` output.
