### ISSUE TITLE
Support for dhooks

### ISSUE THREAD

**Issue by Technerder** [Delgan/loguru#460]
Are there any plans for supporting [dhooks](https://github.com/kyb3r/dhooks)?

**Comment by Delgan** [comment]
Hi @Technerder, what do you mean exactly about suppor for `dhooks`?

If you want to capture logs from a third party library, did you try to use the `InterceptHandler()` [from the documentation](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging)?

**Comment by Technerder** [comment]
I just noticed how vague I was, I meant support for logging to discord using the dhooks library.

**Comment by Delgan** [comment]
I don't know `dhooks` very well, what does "logging to discord" mean? Does Discord have a logging system, or do you want to send messages to Discord using Loguru?

Maybe what you are looking for is to use `hook.send()` as as sink?

```python
from dhooks import Webhook

hook = Webhook('url')

logger.add(hook.send, format="{message}")

logger.info("Hello there!")
```

**Comment by Technerder** [comment]
That seems to work properly, is there a way I can pass in custom arguments to the ``hook.send`` function?

**Comment by Delgan** [comment]
Sure, just use a custom function as your sink (it should work as long as it accepts a `message` argument):

```python
def discord_sink(message):
    hook = Webhook('url')
    hook.send(message, username="test")

logger.add(dhooks_sink, format="{message}")
```

**Comment by Technerder** [comment]
Awesome, would it also be possible to get the log level as a separate argument?

**Comment by Delgan** [comment]
If you need to access the level from within your sink, you can relies on the `record` object attached to the `message`:

```python
def discord_sink(message):
    level = message.record["level"].name
    hook = Webhook('url')
    hook.send(message, username="test")
```

**Comment by Technerder** [comment]
Works like a charm, thanks!
