### ISSUE TITLE
Context Manager logger.add() for Temporary Sinks

### ISSUE THREAD

**Issue by jacobian91** [Delgan/loguru#461]
I am finding it useful to define a custom context manager to temporarily add a sink to limit its scope. My use case is where the sink is a callable and it shows messages to the user but then is cleared when the user exits the scope and enters a new one.

The way I'm currently handling this is `contextlib` which seems to work well. Is there a way to do this in loguru as-is?

```python
@contextlib.contextmanager
def context_add(sink, **kwargs):
    handler= logger.add(sink, **kwargs)
    yield
    logger.remove(handler)
```

**Comment by Delgan** [comment]
Hi @jacobian91. This is an interesting use case. It doesn't exist as is in Loguru. Your solution is very straightforward and elegant. Given its simplicity, I don't think it's worth integrating it into the library, but it could eventually be added to the snippets in the documentation.

**Comment by jacobian91** [comment]
Thanks for the feedback, I appreciate it. And thank you for sharing/maintaining this library! Before we close this I wanted to share a few other thoughts.

This also would be to create separate log files each time the context is entered. A `{time}` parameter could be used in the file name. In the case of batch processing items, this would allow each log file to relate only to a single item. I am already using this case as well so that I can use the log of an individual item as a record to upload to a database (manufacturing environment).

The other nice thing about using it as a context manager is ensuring a sink gets torn down in the case of unhandled exceptions. This would be especially helpful in the case of retention cleanup since that happens only on the removal of the sink.

**Comment by Delgan** [comment]
Thanks for the details. I think that's why `@contextlib.contextmanager` is a perfect fit: it allows the user to arrange the function in any subtle way he desires. :+1:

**Comment by jacobian91** [comment]
Sounds good, thanks again for the feedback!
