### ISSUE TITLE
Patcher replacement

### ISSUE THREAD

**Issue by brett1479** [Delgan/loguru#462]
I have a question about the interface to logger (which may or may not be an issue).  Suppose I take a loguru.Logger as an argument and use that as my logger.  The code that passed that logger to me may have applied a patcher.  Suppose my code now wants to apply a patcher as well.  So I call logger.patch, but I believe this replaces the existing patcher on the logger.  Is there a way for me to query whether there is already a patcher on the logger, and thus potentially create a new patcher that runs the old patcher and the new one if I choose?

**Comment by Delgan** [comment]
Hi.

Indeed, calling `patch()` replaces the existing one (if any). You will have to implement your own system, using a global patcher for example. 

```python
class Patcher:
    def __init__(self):
        self.patches = []

    def add_patch(self, function):
        self.patches.append(function)

    def patch(self, record):
        for patch in self.patches:
            patch(record)

patcher = Patcher()
logger.configure(patcher=patcher.patch)
```

Otherwise, juste wrap the `logger` inside a custom class containing the patch function so you can pass it around:

```python
class PatchedLogger:
    def __init__(self, logger, patch):
        self.logger = logger.patch(patch)
        self.patch = patch
```

**Comment by brett1479** [comment]
Both of those methods do work, although they require clients to either take a (logger,patcher)-tuple instead of just a logger, or a different type of logger than they expected.  There is also the interesting behavior that if you call configure and patch with patchers, both do run since one is on the core logger and one is in the options.  I was hoping there was something like
logger.patch(patcher, chain=True) that would mean the library would call my new patcher after any existing patchers.

**Comment by Delgan** [comment]
Hey @brett1479, sorry for the late answer.

Adding a new `chain=True` seems reasonable. Actually, I've been thinking about it a bit, and I think that should be the default behavior. I think I won't even add a new argument but rather make sure that the patches are cumulative.

I need first to make sure there is no edge cases I didn't think about, but it will be a less surprising and more useful practice. I didn't imagine that the logger would be moved from one function to another.

**Comment by brett1479** [comment]
Yeah, I think that is a very sensible default.  I suggested ```chain=True``` for backwards compatibility, but maybe this will not be much of an issue.

**Comment by Delgan** [comment]
Fixed on `master` branch.
