### ISSUE TITLE
[Question] Merge multiple records into one

### ISSUE THREAD

**Issue by ThibaultLemaire** [Delgan/loguru#465]
Hey! Kind of in the same vein as #388, I want to accumulate logs, before sending them as a single one.

The use case is the same, I want to group all the logs of a single request into one before sending it.

My issue is a bit different though as I'm sitting in-between loguru and another library (namely `watchtower` to send logs to AWS CloudWatch) and I don't have control over how the messages are formatted and sent.

`watchtower` provides a `CloudWatchLogHandler` which works perfectly as a loguru sink, and looking at the code, when `.emit()`ing a log, it is formatted using `self.format()` before sending to AWS. `self` is an instance of `watchtower.CloudWatchLogHandler` but `.format()` is inherited from `logging.Handler` which seems to call its `.formatter` to format the message, so I'd like to understand the magic here:

**How does loguru manages to format those logs correctly in this situation? Does it inject its own formatter on instances of `logging.Handler` passed as sinks?**

**Comment by Delgan** [comment]
Hi!

When using a standard `logging.Handler` as a sink, Loguru will wrap it in an internal `StandardSink` class. When a log message is emitted, it will be formatted as usual according to the `format` used while adding the sink to the `logger`. Then, the Loguru `record` will be passed to the `StandardSink.write()` method as any other sink. Within this method, the Loguru `record` is converted to a standard `LogRecord` using [`logging.makeRecord`](https://docs.python.org/3/library/logging.html#logging.Logger.makeRecord). The message formatted by Loguru is used to create the `LogRecord`'s message. The created `LogRecord` is sent to the wrapped standard handler using `.handle()`.

Source code is here: https://github.com/Delgan/loguru/blob/68616485f4f0decb5fced36a16040f5e05e2842f/loguru/_simple_sinks.py#L43-L60

That means the `LogRecord` will be formatted again using the standard `Formatter` attached to the `logging.Handler`.

This leaves two possibilities:
* If you want to use Loguru to define the logging format, you should make sure the handler's formatter is configured with `fmt="%(message)s"` (which is the default)
* If you want the logs to be formatted by standard `Formatter`, you should make sure the handler is added to Loguru with `format="{message}"`

**Comment by ThibaultLemaire** [comment]
Thanks. In the end, I went with something like the following (which is not so loguru-specific actually):

```python
import typing as t
from types import TracebackType


class WatchTowerLog(t.Protocol):
    """ The minimum required set of attributes to be duck-type compatible with
        what `watchtower.CloudWatchLogHandler` expects as a log
    """

    def getMessage(self) -> str:  # pylint: disable = invalid-name
        ...

    @property
    def exc_info(
        self,
    ) -> t.Union[
        t.Tuple[type, BaseException, t.Optional[TracebackType]],
        t.Tuple[None, None, None],
        None,
    ]:
        ...

    @property
    def exc_text(self) -> t.Optional[str]:
        ...

    @property
    def stack_info(self) -> t.Optional[str]:
        ...

    @property
    def created(self) -> int:
        """ Unix timestamp """

    @property
    def name(self) -> str:
        ...

    @property
    def msg(self) -> str:
        ...


class RequestLogs(WatchTowerLog, t.List[WatchTowerLog]):
    """ A list of log records that quacks like a single record.
        Trying to access any of the log properties on an empty RequestLogs will
        raise an IndexError.
    """

    # pylint doesn't know that a `t.List` is a `list`
    # pylint: disable = not-an-iterable, unsubscriptable-object

    def getMessage(self) -> str:  # pylint: disable = invalid-name
        return "\n".join(x.getMessage() for x in self)

    @property
    def exc_info(
        self,
    ) -> t.Union[
        t.Tuple[type, BaseException, t.Optional[TracebackType]],
        t.Tuple[None, None, None],
        None,
    ]:
        return self[-1].exc_info

    @property
    def exc_text(self) -> t.Optional[str]:
        return self[-1].exc_text

    @property
    def stack_info(self) -> t.Optional[str]:
        return self[-1].stack_info

    @property
    def created(self) -> int:
        return self[-1].created

    @property
    def name(self) -> str:
        return self[-1].name

    @property
    def msg(self) -> str:
        return self[-1].msg

```

Combined with an `OrderedDict` to keep track of which `RequestLogs` was updated last.
