### ISSUE TITLE
Show a static message in every log message

### ISSUE THREAD

**Issue by nghorbani** [Delgan/loguru#466]
I want to be able to show experiment id at the beginning of every message that loguru shows up. Is there a way to achieve that when adding the sink?

**Comment by Delgan** [comment]
Hi.

This is probably possible using a custom `format`.

```python
my_id = 112
fmt = "[{time}] - {function}:{line} - [%d] {message}" % my_id

logger.add(sys.stderr, format=fmt)
```

**Comment by cristifalcas** [comment]
I have the same issue, I believe: add an "id" field that changes depending on context/thread.

For example in classic logging I have something like this:

```python
from flask import g, request
localstorage = gevent.local.local()

class AddTestIdFilter(logging.Filter):
    def filter(self, record):
        test_id = ""
        if request and "test_id" in g:
            test_id = g.test_id
        elif hasattr(localstorage, "test_id") and localstorage.test_id:
            test_id = localstorage.test_id
        record.test_id = test_id_str
        return True

def update_formatter(log):
    for log_handler in log.root.handlers:
        formatter = [%(asctime)s] %(levelname)s - %(name)s - %(test_id)s - %(message)s
        log_handler.setFormatter(logging.Formatter(formatter))        
        log_handler.addFilter(AddTestIdFilter())
```

Where `test_id` is set in the gevent thread.

 Is this possible with loguru?

**Comment by Delgan** [comment]
@cristifalcas Sure, this should be possible using a dynamic `format` function or the [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) method. Here is an example of globally patching the `logger` thanks to [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure):

```python
from flask import g, request
localstorage = gevent.local.local()

def add_test_id(record):
    test_id = ""
    if request and "test_id" in g:
        test_id = g.test_id
    elif hasattr(localstorage, "test_id") and localstorage.test_id:
        test_id = localstorage.test_id
    record["extra"]["test_id"] = test_id

# Add "test_id" to the record every time a message is logged, regardless of the handlers
logger.configure(patcher=add_test_id)

logger.add(sys.stderr, format="[{time}] {level} - {name} - {extra[test_id]} - {message}")
```

**Comment by cristifalcas** [comment]
This is great!! Thank you very much!

**Comment by nghorbani** [comment]
The issue in my case was the default sink. I was providing the static text as format yet in stderr i woldn't see the desired format. The culprit was the default sink. I would now first call logger.remove() before adding any new sinks.
Cheers! keep up the great work :)
