### ISSUE TITLE
Global logger patcher across Django project 

### ISSUE THREAD

**Issue by Alexmhack** [Delgan/loguru#469]
Hi @Delgan Great work on the library!!

I am using loguru for logging in my Django project but stuck in defining a global `patcher` which would execute a piece of code every time I use logger to log something, now the real issue is we are using loguru across many modules in our project and I don't want to change the loguru import statement to something like `from custom_loguru import logger` and also don't want to define `logger.configure(patcher=patcher.patcher)` in all my files across all modules due to huge usage of loguru in my project.

for e.g. I need to avoid something like below,
```
# custom_loguru.py
from typing import Any
from loguru import logger

from log.models import Log


class Patcher:
    def __init__(self):
        pass

    def pre_patch(self, record: Any) -> None:
        Log.objects.create(record=record)

    def patcher(self, record):
        self.pre_patch(record)
        return record


patcher = Patcher()
logger.configure(patcher=patcher.patcher)


# module/views.py
from custom_loguru import logger

logger.debug(...)
```

**Comment by Delgan** [comment]
Hello. :)

Maybe I don't fully understand your problem. The `patcher` applied using [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) will be effective globally. This is different from calling the [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) method which returns a new updated `logger`.

That means you can `.configure()` the `logger` only once (in your `custom_loguru` module for example), and all others modules using the `logger` will inherit from the changes you made. Indeed, each time you run `from loguru import logger`, it is actually the same `logger` object that is being used.

**Comment by Alexmhack** [comment]
You are spot on, didn't realize that `configure` will be effective globally. I just placed `logger.configure(patcher=patcher)` in `settings.py` and it worked like a charm across the project. Thanks!!
