### ISSUE TITLE
different log format strings

### ISSUE THREAD

**Issue by ekimia** [Delgan/loguru#47]
Unsure if this is supported (This could be a good candidate for an example in a nonexistent Examples section), but i'd like to essentially log something with extra data to pipe in a format string.

Specifically, a UUID that identifies a particular process. Having a logger that includes it would make it super easy to find all logs pertaining to that process.

**Comment by Delgan** [comment]
Hi @ekimia.

Isn't something you can achieve using the [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) method?

```python
logger.add("file.log", format="[{time}][{extra[uuid]}] {message}")
logger = logger.bind(uuid=123)
logger.info("Logging")
# => [2019-01-30 22:02:19.961][123] Logging
```

You can use a different bound logger for each of your processes. Would that work?

**Comment by Delgan** [comment]
In such case, I think you can use a dynamic `format` function, something like:

```python
def formatter(record):
    if "uuid" in record["extra"]:
        fmt = "[{time}][{extra[uuid]}] {message}"
    else:
        fmt = "[{time}] {message}"
    return fmt + "\n{exception}"

logger.add("file.log", format=formatter)
```

This is the best way to have different formats, I think.

**Comment by ekimia** [comment]
I'll give it a shot!

**Comment by Delgan** [comment]
@ekimia If this did not work or if you have others questions / suggestions, don't hesitate to re-open this issue. 😉
