### ISSUE TITLE
How to use self defined log message?

### ISSUE THREAD

**Issue by FateScript** [Delgan/loguru#470]
Hello, thanks for your wonderful repo. I have two questions about defining wanted log message, please help, thx : )

1.  Code [here](https://github.com/Delgan/loguru/blob/68616485f4f0decb5fced36a16040f5e05e2842f/loguru/_defaults.py#L36) defined name of caller. However, I want to define name level, for example,  when name  in loguru is a.b.c.d, could it be possible to log a.b as caller name instead? 
2. Also, I want to rename given caller name such as \_\_main\_\_ to a self-defined string, e.g. "given string", could it be possible to log "\_\_main\_\_:1" to "given string:1"?

Thanks for your attention anyway~

**Comment by Delgan** [comment]
Hey @FateScript.

I think you need to use a dynamic `format` function like this:

```python
def formatter(record):
    name = record["name"]
    if name == "a.b.c.d":
        name = "a.b"
    elif name == "__main__":
        name = "given string"
    record["extra"]["renamed"] = name
    return "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | " \
            "<level>{level: <8}</level> | " \
            "<cyan>{extra[renamed]}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - " \
            "<level>{message}</level>"

logger.add(sys.stderr, format=formatter)
```

**Comment by FateScript** [comment]
Thx~
BTW, it seems that after using dynamic format, '\n' is missing?

**Comment by Delgan** [comment]
@FateScript Sorry, I forgot it. When using a dynamic format, you indeed need to explicitly specify the trailing `"\n"` and also `"{exception}"` (those are automatically added for convenience when using a `str` format, but using a function give the user full control over formatting).

```python
def formatter(record):
    name = record["name"]
    if name == "a.b.c.d":
        name = "a.b"
    elif name == "__main__":
        name = "given string"
    record["extra"]["renamed"] = name
    return "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | " \
            "<level>{level: <8}</level> | " \
            "<cyan>{extra[renamed]}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - " \
            "<level>{message}</level>\n{exception}"

logger.add(sys.stderr, format=formatter)
```

**Comment by FateScript** [comment]
dynamic format func is powerful and helpful, thanks~
