### ISSUE TITLE
How to add discord-webhook to logger.exceptions

### ISSUE THREAD

**Issue by BarryThrill** [Delgan/loguru#472]
Hello there!

I have been trying to figure out how I could create a notification to my discord whenever I reach to logger.exceptions. I was able to create a function that generates the embed and then posts it to the discord but I would like to do it straight whenever I call logger.exception instead of calling the function itself. https://pypi.org/project/discord-webhook/

```py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import json
import pathlib
import time

import pendulum
from discord_webhook import DiscordWebhook
from loguru import logger


def report(msg):
    webhook = DiscordWebhook(
        url="Https://.......",
        username="Testing",
    )

    # -------------------------------------------------------------------------
    # Check if the path already exists, create if not
    # -------------------------------------------------------------------------
    file_path = pathlib.Path() / "Error"
    filename = f"{pendulum.now('Europe/Stockholm').format('YYYY-MM-DD_HH-mm-ss-SSSSS')}.json"
    target = file_path / filename

    if not file_path.exists():
        file_path.mkdir(parents=True)

    # Write to a JSON file
    target.write_text(
        json.dumps(
            msg,
            indent=4,
            ensure_ascii=False
        ),
        encoding="utf-8"
    )

    # -------------------------------------------------------------------------
    # Send files to discord
    # -------------------------------------------------------------------------
    webhook.add_file(file=target.read_text(encoding="utf-8"), filename=target.name)

    success: bool = False

    while not success:
        response = webhook.execute()
        success = response.ok

        # If we get a 429, retry after a short delay
        if response.status_code == 429:
            sleep_time = int(response.headers["retry-after"]) / 1000
            logger.debug(f"Rate limit -> Retrying in {sleep_time} seconds")
            time.sleep(sleep_time)
            continue

        # any response other than a 429 or a 200 OK is an error.
        if not response.ok:
            raise RuntimeError("failed to create discord reporter.")

        logger.info(f"Succesfully sent to Discord Reporter -> {filename}")

```

This is one example where I create a json file and then post the json file that has been created to discord but of course I could change it to send embeds instead of creating new json files.

My question is basically if its possible to migrate it together with Loguru whenever we call logger.exception and pass arguments such as the message, the exception etc etc

**Comment by Delgan** [comment]
Hi. ;)

It is perfectly possible. You just need to `.add()` your web-hook function as a sink and configure a custom `filer` to only allow error messages.

```python
def exception_only(record):
    return record["level"].name == "ERROR" and record["exception"] is not None

def discord_sink(message):
    webhook = DiscordWebhook(
        url="Https://.......",
        username="Testing",
        content=message,
    )
    webhook.execute()

logger.add(discord_sink, filter=exception_only, enqueue=True)
```

The `discord_sink` function will receive the logged message. From there, you can do whatever you want with it. You can also access the record dict with `message.record`. This record dict is used to filter logs in the `exception_only` function, so that usual log messages aren't sent to your discord hook.

Note that I used `enqueue=True` (this is optional) which spawn a background thread to process the messages and thus should prevent your web request from blocking the whole app.

Also, it's important to avoid using the `logger` from within the `discord_sink` or `exception_only` functions otherwise there is a risk of generating a deadlock (it's not possible to log a message while another one is already being logged in the same thread).

**Comment by BarryThrill** [comment]
> Hi. ;)
> 
> It is perfectly possible. You just need to `.add()` your web-hook function as a sink and configure a custom `filer` to only allow error messages.
> 
> ```python
> def exception_only(record):
>     return record["level"].name == "ERROR" and record["exception"] is not None
> 
> def discord_sink(message):
>     webhook = DiscordWebhook(
>         url="Https://.......",
>         username="Testing",
>         content=message,
>     )
>     webhook.execute()
> 
> logger.add(discord_sink, filter=exception_only, enqueue=True)
> ```
> 
> The `discord_sink` function will receive the logged message. From there, you can do whatever you want with it. You can also access the record dict with `message.record`. This record dict is used to filter logs in the `exception_only` function, so that usual log messages aren't sent to your discord hook.
> 
> Note that I used `enqueue=True` (this is optional) which spawn a background thread to process the messages and thus should prevent your web request from blocking the whole app.
> 
> Also, it's important to avoid using the `logger` from within the `discord_sink` or `exception_only` functions otherwise there is a risk of generating a deadlock (it's not possible to log a message while another one is already being logged in the same thread).

Oh wow! Did not expected that fast response, so I went outside while the sun is burning. I will give it a go and come back with a result but by reading this answer I am pretty sure it will work as I expected to :)

Im not sure if I completely understood: _Also, it's important to avoid using the logger from within the discord_sink or exception_only functions otherwise there is a risk of generating a deadlock (it's not possible to log a message while another one is already being logged in the same thread)._

By using your code, that should'nt happend or?

Anyways, is there by any chance you have a donation link such as buymeacoffee.com where I would like to support this amazing project? :)

**Comment by Delgan** [comment]
Haha, you're right to enjoy the sun when it's there. :)



> Im not sure if I completely understood: _Also, it's important to avoid using the logger from within the discord_sink or exception_only functions otherwise there is a risk of generating a deadlock (it's not possible to log a message while another one is already being logged in the same thread)._
> 
> By using your code, that should'nt happend or?

Yes, you're correct. Using the examples I gave, there should be no problem. It was an additional information in case you were considering evolving the function to something more advanced, like your initial `report` function.

Thanks for offering to support this library! I appreciate it.
I prefer to avoid introducing monetization in this project, but don't worry, I'm already very glad to know that you like Loguru! :+1:

**Comment by BarryThrill** [comment]
> > Hi. ;)
> > It is perfectly possible. You just need to `.add()` your web-hook function as a sink and configure a custom `filer` to only allow error messages.
> > ```python
> > def exception_only(record):
> >     return record["level"].name == "ERROR" and record["exception"] is not None
> > 
> > def discord_sink(message):
> >     webhook = DiscordWebhook(
> >         url="Https://.......",
> >         username="Testing",
> >         content=message,
> >     )
> >     webhook.execute()
> > 
> > logger.add(discord_sink, filter=exception_only, enqueue=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `discord_sink` function will receive the logged message. From there, you can do whatever you want with it. You can also access the record dict with `message.record`. This record dict is used to filter logs in the `exception_only` function, so that usual log messages aren't sent to your discord hook.
> > Note that I used `enqueue=True` (this is optional) which spawn a background thread to process the messages and thus should prevent your web request from blocking the whole app.
> > Also, it's important to avoid using the `logger` from within the `discord_sink` or `exception_only` functions otherwise there is a risk of generating a deadlock (it's not possible to log a message while another one is already being logged in the same thread).
> 
> Oh wow! Did not expected that fast response, so I went outside while the sun is burning. I will give it a go and come back with a result but by reading this answer I am pretty sure it will work as I expected to :)
> 
> Im not sure if I completely understood: _Also, it's important to avoid using the logger from within the discord_sink or exception_only functions otherwise there is a risk of generating a deadlock (it's not possible to log a message while another one is already being logged in the same thread)._
> 
> By using your code, that should'nt happend or?
> 
> Anyways, is there by any chance you have a donation link such as buymeacoffee.com where I would like to support this amazing project? :)


Tested and can confirm it is working like charm! 

I wanted to share my code for those who might need it in the future and of course each person should add their own webhook however they want but atleast a example!

```
import sys

from loguru import logger


# -------------------------------------------------------------------------
# Web-hook function as a sink and configure a custom filter to only allow error messages.
# -------------------------------------------------------------------------
def exception_only(record):
    return record["level"].name == "ERROR" and record["exception"] is not None


def discord_sink(message):
    print("The full exception message: ", message)
    print("The record: ", message.record)
    print("The message: ", message.record["message"])
    print("The exception: ", message.record["exception"].value)

    # webhook = DiscordWebhook(
    #     url="Https://.......",
    #     username="Testing",
    #     content=message,
    # )
    # webhook.execute()


# -------------------------------------------------------------------------
# Loguru add
# -------------------------------------------------------------------------
logger.remove()
logger.add(sys.stdout, filter=lambda record: record["level"].name == "INFO")
logger.add(sys.stderr, filter=lambda record: record["level"].name != "INFO")
logger.add(discord_sink, filter=exception_only, enqueue=True)

```

Thank you once again and have a wonderful weekend!
