### ISSUE TITLE
Release with support for Python 3.9

### ISSUE THREAD

**Issue by dotlambda** [Delgan/loguru#473]
Support for Python 3.9 was added in https://github.com/Delgan/loguru/commit/ebbf89c436e506d2e5c5fcd67ed8ea70d3ed8739. Can you make a release that includes support for Python 3.9?

**Comment by Delgan** [comment]
Hey @dotlambda.

Sorry, maybe the commit message was confusing. Actually, latest released version of Loguru (`v0.5.3`) is perfectly compatible with Python 3.9.  It was just missing the unit tests to run automatically on the CI.

You're safe to use Loguru with Python 3.9. I'm planning to release a new `v0.6.0` but it won't be soon, nothing justify much creating a new release for now (see [Changelog](https://github.com/Delgan/loguru/blob/master/CHANGELOG.rst#unreleased)).
