### ISSUE TITLE
not able to show module name

### ISSUE THREAD

**Issue by necan** [Delgan/loguru#475]
```python
from loguru import logger

logger.info('hello world')
```

it only shows `<module>` placeholder

```python
2021-07-08 02:07:15.378 | INFO     | __main__:<module>:3 - hello world
```

**Comment by Delgan** [comment]
The default format uses the `{name}` which is replaced with the `__name__` variable at runtime. Usually, the `__name__` represents the module name but it's not the case for your entry file, [see official Python documentation](https://docs.python.org/3/library/__main__.html) about that.

The `<module>` you're seeing is supposed to represent the function from where is called the log method. As your `logger.info()` is not in any function, it is say to be in the module itself.

See documentation about possible `format` fields, maybe you want to use `{file.name}` instead: [The record dict](https://loguru.readthedocs.io/en/stable/api/logger.html#record).
