### ISSUE TITLE
Native Implementation Questions

### ISSUE THREAD

**Issue by aaronclong** [Delgan/loguru#479]
Off the bat, I love your library. I plan to use it in all my new apps.

I was curious about the [speed up you were planning with **c extensions**](https://github.com/Delgan/loguru#10x-faster-than-built-in-logging). Did you have any of that code pushed already, and have you considered Rust?

**Comment by Delgan** [comment]
Hey @aaronclong, thanks for your interest in Loguru. :)

Unfortunately, I was not able to produce a C implementation as early as I would have liked. I still plan to do it, eventually, but life being what it is, I don't know when it will happen. 
https://github.com/Delgan/loguru/commit/aef4571b06de48a02f2fc2552291ea71ef553007

**Comment by Delgan** [comment]
Hi @aaronclong, thanks for your interest in Loguru. :)

Unfortunately, I was not able to produce a C implementation as early as I expected. I still plan to do it, eventually, but life being what it is, I don't know when it will happen. 

Here is a snippet of implementation that existed before the initial release: https://github.com/Delgan/loguru/commit/aef4571b06de48a02f2fc2552291ea71ef553007
This made the function in charge of retrieving the localized datetime much faster.
I withdrew it to focus myself on publishing a first Python version of the library, thinking to re-add it again soon after... But it never happened.

Again, I haven't given up on the idea of a C implementation. This will mark the transition to v1.0.0 I think, but I first need to implement some improvements for v0.6.0. And I haven't taken the time to do that yet.

I would love to work with Rust but I don't think it would be a good fit for Loguru. The main speedup will come from direct usage of the CPython API for internal structures and objects. Adding a layer in Rust would not allow to benefit from all the optimization potential in my opinion.

**Comment by aaronclong** [comment]
@Delgan thank you for responding to this and I will def look over that commit.

In defense of rust, since everything is at compile time, any abstraction overhead would be minimal. [Py03](https://github.com/PyO3/pyo3) would also make it easy to interface with the  Cython api. However, this is just a suggestion to consider it.
