### ISSUE TITLE
Why is the log printed twice

### ISSUE THREAD

**Issue by betterA** [Delgan/loguru#481]
loggerUseModel.work.py

```
from loguru import logger


def work_it():
    logger.debug("debug")
    logger.info("info")
    logger.warning("warning")

    try:
        1/ 0
    except Exception as e:
        logger.exception("exception")

-------------

import sys
from loguru import logger
logger.add(sys.stderr, level="WARNING")

from loggerUseModel.work import work_it

work_it()
```

"""
2021-07-29 09:37:16.836 | DEBUG    | loggerUseModel.work:work_it:5 - debug
2021-07-29 09:37:16.836 | INFO     | loggerUseModel.work:work_it:6 - info
2021-07-29 09:37:16.836 | WARNING  | loggerUseModel.work:work_it:7 - warning
2021-07-29 09:37:16.836 | WARNING  | loggerUseModel.work:work_it:7 - warning
2021-07-29 09:37:16.836 | ERROR    | loggerUseModel.work:work_it:12 - exception
Traceback (most recent call last):
"""

**Comment by Delgan** [comment]
Hi.

The `logger` is pre-configured for convenience with a default handler which logs to `sys.stderr`.
So, if you call `logger.add(sys.stderr)` the log messages will be printed twice. You need to first call `.remove()` to get rid of the default handler.

**Comment by varungupta31** [comment]
for anyone still slightly confused (as was I),

```python
from loguru import logger
import sys

for i in range(5):
    logger.remove()
    logger.add('checkoutthislog.log', format="{time} {level} {message}", level="DEBUG")
    logger.debug("Hello, world!")
    
```
This logs,
```python
2024-03-01T10:25:59.466244+0000 DEBUG Hello, world!
2024-03-01T10:25:59.472127+0000 DEBUG Hello, world!
2024-03-01T10:25:59.478096+0000 DEBUG Hello, world!
2024-03-01T10:25:59.483775+0000 DEBUG Hello, world!
2024-03-01T10:25:59.489666+0000 DEBUG Hello, world!
```
Would be suggested practice.

**Comment by Delgan** [comment]
@varungupta31 You don't need to call `loger.remove()` and `logger.add()` in a `for` loop. Configuring the handlers should be done only once.

**Comment by varungupta31** [comment]
@Delgan Thanks for the clarification. I realized this soon and forgot to update my comment.
This seems to be ideal way :)
```python
from loguru import logger
import sys

def main():
    # Configure the logger
    logger.remove()
    logger.add(sys.stdout, level="INFO")  # Log to stdout
    logger.add("app.log", level="INFO") 
    # Main loop to print "Hello, world!" and log the success
    for i in range(5):
        print("Hello, world!")
        logger.info("Printed 'Hello, world!' successfully")

if __name__ == "__main__":
    main()
```

**Comment by Delgan** [comment]
@varungupta31 Yes, this is the correct usage of Loguru. :+1:
