### ISSUE TITLE
Patch default logger to use loguru instead

### ISSUE THREAD

**Issue by chwba** [Delgan/loguru#483]
I am using a package, that has python default logging implemented everywhere - To enable logging it allows to  call the following method:

```python
def enable_logging(level=logging.INFO):
    handler = logging.StreamHandler()
    handler.setLevel(level)

    logger.addHandler(handler)
    logger.setLevel(level)
```

The package uses a named logger which one could eventually use to make loguru take over. Is this possible in any way?

**Comment by Delgan** [comment]
Hi.

Did you try to attach an [`InterceptHandler()`](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging) to the package logger (and maybe removing the `StreamHandler` also)?

This is the usual way to "patch" libraries relying on standard logging.

**Comment by chwba** [comment]
I mustve overread this one in the readme, thank you for pointing me there, works perfectly.
