### ISSUE TITLE
Can callbacks be added to @logger.catch

### ISSUE THREAD

**Issue by Mankvis** [Delgan/loguru#486]
I use @logger.catch in my program, which has an alarm mechanism, and if an exception occurs, I want to call the alarm interface to handle it

**Comment by Delgan** [comment]
You can probably use the `onerror` argument. There is an example [in the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch).

```python
def alarm(exception):
    print("Error: {}", exception)

with logger.catch(onerror=alarm):
    main()
```

**Comment by Mankvis** [comment]
Thanks, It worked.
