### ISSUE TITLE
With either sink (stdout or stderr) logs don't show in airflow logs

### ISSUE THREAD

**Issue by nsingla** [Delgan/loguru#488]
If i use standard logging python library or print statements , output shows up in airflow dashboard/logs
But if I switch to loguru, which i prefer - then nothing shows up on airflow dashboard

Is there a different type of sink setting that I need to apply here?

**Comment by Delgan** [comment]
Both standard logging and Loguru write messages to `sys.stderr` so it shouldn't be very much different. I don't know how Airflow works. Does it capture messages emitted with `print()` too? Does it add a custom handler to the root logger?

**Comment by nsingla** [comment]
Ya I agree, but it's really weird. It probably has to do with parallelization or something, I tried setting enqueue=False but nothing.

Only if I add loger.add statement within airflow script's python method at the start , then it works. But that's clunky to add to all the methods. If i set that as global then again it doesnt work.

**Comment by Delgan** [comment]
Sorry, I can't help much here. I have no idea how is Airflow processing the functions, perhaps their support can help you.

Did you try to call `logger.remove()` and then `logger.add(sys.stderr)` at the beginning of the script?

Does Airflow provide a way to pre-configure the script or function calls?

Otherwise, you may try to create a custom decorator to automatically call `logger.add()` before each of your function. It should be less clunky, but still not ideal.

**Comment by nsingla** [comment]
`import sys
from loguru import logger
#import logging as logger


logger.remove()
logger.add(sys.stderr, level="INFO")

def test_logger():
        logger.add(sys.stderr, level="INFO") # this line
        logger.info('info')
        logger.warning('test warning')
        logger.error('test error')
        print('test print stdout')


if __name__ == '__main__':
    #test_logger()
    print('nothing here')`

Delgan, appreciate trying to address this issue . 

It's weird , if i remove logger.add line (# this line) then nothing shows in airflow logs
If i keep it, then it shows up(don't need to set remove/add either outside the method)

**Comment by Delgan** [comment]
What it you put `logger.add()` inside the `if __name__ == "__main__":` branch instead?

Is there any way that I can experiment with Airflow process?

**Comment by nsingla** [comment]
Thanks again Delgan!
I'm not using if __name__, let me try to create a dummy airflow instance this weekend on my personal server so that you can check it out

**Comment by Delgan** [comment]
Thanks, that would certainly help understanding the issue, because honestly I now nothing about Airflow.

**Comment by nsingla** [comment]
Is there a way I could send you links to dummy airflow privately?

**Comment by Delgan** [comment]
@nsingla Sure, you can send me mail at delgan.py@gmail.com

**Comment by nsingla** [comment]
If helpfulf or anyone:

From what I see, it definitely looks related with the way Airflow handles the tasks. I think maybe Airflow replace the sys.stdout with their own stream, as suggested by the "StreamLogWriter" class ( https://github.com/apache/airflow/blob/9922287a4f9f70b57635b04436ddc4cfca0e84d2/airflow/utils/log/logging_mixin.py#L76 ) and the "redirect_stout" function ( https://github.com/apache/airflow/blob/34478c26d7de1328797e03bbf96d8261796fccbb/airflow/dag_processing/processor.py#L150 ).

So, if you call `logger.add(stdout)` at the root of your script, Airflow will later replace stdout before starting the task and Loguru logs won't be captured.
