### ISSUE TITLE
Serialize issues/questions

### ISSUE THREAD

**Issue by rsb177** [Delgan/loguru#489]
I was testing out loguru with a new app and ran into some issues with telling my logs to serialize.  The main issue is that it doesn't look like colorize and serialize are compatible.  If I set both to true, I get the ansi codes in my logs rather than the actual colors.  Serializing without colorizing works as expected, as well as colorizing without serializing.  

Also, I was looking for a way to "pretty print" the json logs during local development and the only option I could find was creating my own serializer and bypassing a lot of the built in functionality. 

Not sure that it makes much difference, but I'm running things in docker (python3.9 image) with Loguru 0.5.3.

**Comment by Delgan** [comment]
Hi @rsb177.

You're right, bey default Loguru will disable colorizing of logs if `serialize=True` as it generally doesn't interfere very well with each other. Why aren't setting `colorize=False` with `serialize=True`?

The serialization step occurs just before sending the message to the sink. You can maybe use a custom sink if you want to print it:

```python
from pprint import pprint

def debug_sink(message):
     record = json.loads(message)
     pprint(record)
     sys.stderr.write(record)

logger.add(debug_sink)
```

Note that you can also access the `record` dict directly with `message.record`.

**Comment by rsb177** [comment]
Ok, thanks.  I had previously set up a logger for one of my old projects that used colors and pretty-printing when working locally, but in production would just use plain JSON, so I was seeing how difficult it would be to implement with loguru.
