### ISSUE TITLE
ANSI escape codes supported in Jupyter Notebook, but color tags seem to be removed when used

### ISSUE THREAD

**Issue by maxshowarth** [Delgan/loguru#494]
ANSI escape codes seem to be supported in Jupyter notebook output (apparently including stdout?)

```print("\x1b[31m\"red\"\x1b[0m")``` produces red text.

However, adding a sys.stdout as a sink within a Jupyter notebook with a color tag does not change the color of the message. Perhaps the tags are being removed because the check for ANSI support is failing?

For example, adding the following sink prints out black text correctly:
```logger.add(sys.stdout, format="<green>{time:HH:mm:ss}</green> {level} | {module}:{function}:{line} | {message}")```

**Comment by Delgan** [comment]
> Perhaps the tags are being removed because the check for ANSI support is failing?

Yeah, exactly. You can force ANSI codes by adding you sink with `colorize=True` argument (by default Loguru will try to automatically detected if the output supports colors or not).

**Comment by Delgan** [comment]
I implemented color detection for Jupyter Notebook and Google Colab. It'll be available in next release.
