### ISSUE TITLE
[Question] Add handler for "backoff"

### ISSUE THREAD

**Issue by BarryThrill** [Delgan/loguru#495]
Hello again! 

After hours of searching and trying to find the answer. I did not managed to do it :'(

I am trying to combine [backoff](https://github.com/litl/backoff#logging-configuration) together with loguru:

```py
import sys

from discord_webhook import DiscordEmbed, DiscordWebhook
from loguru import logger

from config import configuration


# -------------------------------------------------------------------------
# Web-hook function as a sink and configure a custom filter to only allow error messages.
# -------------------------------------------------------------------------
def exception_only(record):
    return record["level"].name == "ERROR" and record["exception"] is not None


def discord_sink(message):
    embed = DiscordEmbed(
        title=str(message.record["exception"].value),
        description=f"```{message[-1500:]}```",
        color=8149447
    )

    embed.add_embed_field(
        name=str(message.record["exception"].type),
        value=str(message.record["message"])
    )

    webhook = DiscordWebhook(
        url=configuration.notifications.error_webhook,
        username="Exception",
    )

    webhook.add_embed(embed)
    webhook.execute()


# -------------------------------------------------------------------------
# Loguru add
# -------------------------------------------------------------------------
logger.remove()
logger.add(sys.stdout, filter=lambda record: record["level"].name == "INFO")
logger.add(sys.stderr, filter=lambda record: record["level"].name != "INFO")
logger.add(discord_sink, filter=exception_only, enqueue=True)

```

and the code I am currently using for backoff is:

```py
import requests
import backoff

def pred(e):
    return (
            e.response is not None
            and e.response.status_code not in (404, 401)
            and e.response.status_code in range(400, 600)
    )


@backoff.on_exception(
    backoff.expo,
    requests.exceptions.RequestException,
    max_tries=2,
    giveup=pred,
)
def publish():
    r = requests.get("https://stackoverflow.com/63463463456", timeout=10)
    r.raise_for_status()

    print("Yay successful requests")


publish()
```

What I am trying to do is that whenever I have reached the max_tries it would throw an exception:

` Therefore exception info is available to the handler functions via the python standard library, specifically sys.exc_info() or the traceback module.`

and together with loguru, I want it to basically print to my discord whenever I have reached the max_tries. but to be able to do that I need to figure out how I can add the handler for backoff inside loguru and I think this might be abit "off-topic" but I hope that I could get some help. If you feel like this is too off-topic for loguru question, you can feel free to close as well <3 

Looking forward!

**Comment by Delgan** [comment]
Hey @BarryThrill, I'll try to help as much as I can. :+1: 

I was thinking, can't you simply use the `on_giveup` argument to log the exception to Loguru?

```python
def giveup_hdlr(details):
    logger.exception(f"Function failed after {details[tries]} tries")

@backoff.on_exception(
    backoff.expo,
    requests.exceptions.RequestException,
    max_tries=2,
    giveup=pred,
    on_giveup=giveup_hdlr,
)
def publish():
    r = requests.get("https://stackoverflow.com/63463463456", timeout=10)
    r.raise_for_status()

    print("Yay successful requests")
```

In the case `publish` raises an exception in the end, you can also simply decorate if with [`logger.catch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch).

Finally, if you need to capture logs from standard `logging`, you may take a look at the `InterceptHandler` [in the Readme](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging).

**Comment by BarryThrill** [comment]
> Hey @BarryThrill, I'll try to help as much as I can. 👍
> 
> I was thinking, can't you simply use the `on_giveup` argument to log the exception to Loguru?
> 
> ```python
> def giveup_hdlr(details):
>     logger.exception(f"Function failed after {details['tries']} tries")
> 
> @backoff.on_exception(
>     backoff.expo,
>     requests.exceptions.RequestException,
>     max_tries=2,
>     giveup=pred,
>     on_giveup=giveup_hdlr,
> )
> def publish():
>     r = requests.get("https://stackoverflow.com/63463463456", timeout=10)
>     r.raise_for_status()
> 
>     print("Yay successful requests")
> ```
> 
> In the case `publish` raises an exception in the end, you can also simply decorate if with [`logger.catch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch).
> 
> Finally, if you need to capture logs from standard `logging`, you may take a look at the `InterceptHandler` [in the Readme](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging).

Once a hero and always a hero! All I needed was the on_giveup and that would have solved all my issues that I had with loguru and backoff! Such a amazing person! Thanks! <3 <3
