### ISSUE TITLE
New logfile every time the script is run

### ISSUE THREAD

**Issue by jacob-levit** [Delgan/loguru#497]
Hi! Please, tell me, how to create a new log file every time you run the script?

**Comment by Delgan** [comment]
Hi.

You can specify a date placeholder in the filename as follow:

```python
logger.add("file_{time}.log")
```
Otherwise, you can overwrite existing file like so (default is to append):

```python
logger.add("file.log", mode="w")
```

**Comment by jacob-levit** [comment]
> Hi.
> 
> You can specify a date placeholder in the filename as follow:
> 
> ```python
> logger.add("file_{time}.log")
> ```
> 
> Otherwise, you can overwrite existing file like so (default is to append):
> 
> ```python
> logger.add("file.log", mode="w")
> ```

Thank you very much for your reply

**Comment by Delgan** [comment]
Your welcome, I'm closing this issue then. :+1:
