### ISSUE TITLE
level DEBUG don't work out of the box for windows(cmd, git-bash)

### ISSUE THREAD

**Issue by xiaoTaoist** [Delgan/loguru#500]
debug level are not working in default loguru configuration for windows(cmd, git-bash)

* windows 10  +  cmd + Python(3.8.10) + loguru(0.5.3)
* default configuration  DEBUG  and INFO not working
* changing the level of an  handler  can work
```python
>>> from loguru import logger
>>> import sys

>>> logger.debug('d')
>>> logger.info('i')
>>> logger.error('e')
2021-09-08 11:00:51.789 | ERROR    | __main__:<module>:1 - e

>>> logger.remove()
>>> logger.add(sys.stderr, level="DEBUG")

>>> logger.debug('d')
2021-09-08 11:01:42.869 | DEBUG    | __main__:<module>:1 - d
>>> logger.info('i')
2021-09-08 11:01:49.621 | INFO     | __main__:<module>:1 - i
>>> logger.error('e')
2021-09-08 11:01:58.494 | ERROR    | __main__:<module>:1 - e
```

**Comment by Delgan** [comment]
Hi.

The default level can be overridden by the `"LOGURU_LEVEL"` environment variable.

Can you please check the following:
* What it the value of `os.environ["LOGURU_LEVEL"]`?
* What is the value of `loguru._defaults.LOGURU_LEVEL`?

**Comment by xiaoTaoist** [comment]
Thanks. 

I use  `setx`  setting  LOGURU_LEVEL .  But I don’t know `setx` modifies the value permanently.
I just want to modify the current shell environment value. (use  `set`)

Thank you for this awesome package.

**Comment by Delgan** [comment]
Glad you figured it out. :+1: 

I'm closing this ticket then. ;)
