### ISSUE TITLE
How to use an ECS (Elastic Common Schema) Formatter with loguru ?

### ISSUE THREAD

**Issue by kleysonr** [Delgan/loguru#503]
I have a python application where it's supposed the logs be sent to an elasticsearch server.

I'm trying to use the loguru to generate the logs in the ECS pattern.

The APM Elastic documentation show how to change the default logging formatter to get the ECS pattern (https://www.elastic.co/guide/en/apm/agent/python/current/log-correlation.html#log-correlation-in-es)
```python
import logging
from elasticapm.handlers.logging import Formatter

fh = logging.FileHandler('spam.log')
formatter = Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
fh.setFormatter(formatter)
```
This will automatically append apm-specific fields to your format string:
```python
formatstring = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
formatstring = formatstring + " | elasticapm " \
                              "transaction.id=%(elasticapm_transaction_id)s " \
                              "trace.id=%(elasticapm_trace_id)s " \
                              "span.id=%(elasticapm_span_id)s"
```
But I couldn't find a way to use the `elasticapm.handlers.logging.Formatter` with Loguru.

How can It be done ?

**Comment by Delgan** [comment]
Loguru supports standard `Handler` as sinks. You can create a `FileHandler` and configure its `Formatter` just as you did, then `add()` it to the `logger`. You'll probably also want to replace default Loguru's format.

```python
logger.add(fh, format="{message}")
``` 

Can you confirm that this generates the output you expect?

**Comment by kleysonr** [comment]
Yes. It worked. Thanks.

**Comment by Gokulnath31** [comment]
Is there a way to log all the fields outside extra when adding additional fields to log or when we log using with logger.contextualize()

**Comment by Delgan** [comment]
Hi @Gokulnath31. 
I'm not sure what you mean exactly. Can you share the expected output please?
The additional fields can be logged by using `"%(extra)s"` (standard logging) or `"{extra}"` (Loguru) in formatting configuration.

**Comment by Gokulnath31** [comment]
> Hi @Gokulnath31. I'm not sure what you mean exactly. Can you share the expected output please? The additional fields can be logged by using `"%(extra)s"` (standard logging) or `"{extra}"` (Loguru) in formatting configuration.

{"@timestamp":"2023-06-22T04:17:16.496Z","log.level":"info","message":"t2","ecs":{"version":"1.6.0"},"extra":{"j":9,"test2":9},"log":{"logger":"__main__","origin":{"file":{"line":31,"name":"log.py"},"function":"task2"},"original":"t2"},"process":{"name":"MainProcess","pid":2714,"thread":{"id":8149016064,"name":"MainThread"}}}

Above is a sample log. You could see here that fields j and test2 are inside extra key in log. I want all extra fields outside extra @Delgan

**Comment by Delgan** [comment]
@Gokulnath31 You need a custom formatter for that.  You can create a `dict()` and fill it with fields you're interested in, including the whole `extra` dict.
