### ISSUE TITLE
logger.exeption() with different logging level?

### ISSUE THREAD

**Issue by afeblot** [Delgan/loguru#507]
Hi,

This is a feature request, as well as a question on how to currently implement this behavior.

I'd like to be able to log exceptions as `logger.exception()` does, but not with an ERROR level (because I'm doing this in an `except` bloc, just for information and the program keeps running as expected). Ideally, `exception()` could support it this way:

```python
logger.exception(e) # This creates an error
logger.exception(e, level='WARNING') # This creates a warning
```
Is that a change you think you could provide?

In the meantime, what would you suggest to achieve this result?
Here is what I currently did in my own code, which seems to work, but which I'm not really proud of:

```python
def warnException(__self, __message, *args, **kwargs):
    options = (True,) + __self._options[1:] # pylint: disable=protected-access
    __self._log("WARNING", None, False, options, __message, args, kwargs) # pylint: disable=protected-access
logger.__class__.warnException = warnException
```
Thanks

**Comment by Delgan** [comment]
Hey @afeblot.

Maybe can you use the [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method?

```python
logger.opt(exception=True).warning("Warning message with exception")
```

**Comment by afeblot** [comment]
So much cleaner!! 👍 😃 
Thanks a lot for the fast answer! ❤️

**Comment by Delgan** [comment]
Your welcome. :smile: :+1:
