### ISSUE TITLE
Close the log files in loguru

### ISSUE THREAD

**Issue by naveen7v** [Delgan/loguru#508]
Hello,

Mine is more of a question on how to close the log.txt file that is generated/added inside a function that Im testing using `pytest`

my_module.py
```
def my_func():
    # some stuff
    logger.add('log.txt')
    logger.info("Logs added")
    return something
```

test_module.py
```
def test_func():
    res = my_module.func()  # Arrange and Act happens here 
    assert res = something
    shutil.rmtree(my_dir)  # Cleanup part my_dir contains the log.txt generated by my_func()
```

I even tried removing log.txt from `pytest_sessionfinish` which runs once the test session ends, but the `log.txt` file is still open and I get the below in Windows.

Actual Error:
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: C:\\Users\\name\\....\\log.txt
```
Any help please. Thank you :)

**Comment by Delgan** [comment]
You have to [`remove()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the added handler, and the file will be closed. ;)

**Comment by naveen7v** [comment]
It worked :)  

just a FYI on Ubuntu, the log file was deleted without any hassle, no need for `logger.remove()`
