### ISSUE TITLE
removing old compressed logs

### ISSUE THREAD

**Issue by perfecto25** [Delgan/loguru#513]
Hello, is there an option to automatically remove compressed old logs?

for example my loguru config is 

```

logger.add(
    f"{base_dir}/isync.log",
    format="{time} {level} {message}",
    level="DEBUG",
    rotation="50 MB",
    compression="tar.xz",
)
```

it generates tons of log.tar.xz files because the application is very chatty

is there a flag to remove any file that is tar.xz? Right now i have to do this manually. I basically want to have 1 log file that is rotated after 50MB and dont care about old logs, basically need the log for tail -f diagnostics (and dont want to pipe this into syslog since its chatter that will go to our Elasticsearch index - which creates lots of unnecessary noise)

Thanks.

**Comment by Delgan** [comment]
Hi.

Are you aware of the `retention` parameter? It can be used to remove old files based on their count or elapsed time.

```python
logger.add("file.log", retention=10)                 # Keep only 10 latest log files
logger.add("another_file.log", retention="1 month")  # Remove logs older than 1 month
```

See more information [in the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#file).

**Comment by perfecto25** [comment]
thank you will try that
