### ISSUE TITLE
Question: Avoiding empty and redundant logs

### ISSUE THREAD

**Issue by Maxximiliann** [Delgan/loguru#517]
Python 3.9.6
loguru 0.5.3

We primarily use loguru to track errors in a few different applications. We're having two issues with it: (I) one program's error logs are copied in all other program's error logs, and (II) empty logs are created despite no errors occurring. How can we ensure that loguru only creates logs when there is a legitimate issue to be documented, and that this logs is not repeated across all other logs?

**Comment by Delgan** [comment]
> (I) one program's error logs are copied in all other program's error logs

Can you please share your Loguru configuration?
Basically, if you do not use a specific `filter`, all logs will be sent to the added handlers, regardless of the program they came from. That's may explain why you're seeing the same message in multiple files if you added two file handlers.

> (II) empty logs are created despite no errors occurring

Did  you try the `delay` parameter?

```python
logger.add("file.log", delay=True)
```

I will postpone file creation until a message is logged.

**Comment by Maxximiliann** [comment]
Gotcha. Where can I find some filter-implementation recipes?

**Comment by Delgan** [comment]
You can find different example of `filter` in [API reference](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) and [others docs](https://loguru.readthedocs.io/en/stable/resources/recipes.html).

This arguments accept a function, so you can customize it the way you prefer:

```python
def my_filter(record):
    if record["level"].name != "ERROR":
        return False
    return True

logger.add("file.log", filter=my_filter)
```
You can also create files per-module like so:

```python
logger.add("module_a.log", filter="module_a")
logger.add("module_b.log", filter="module_b")
```
