### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by quantumpacket** [Delgan/loguru#519]
May be related to https://github.com/Delgan/loguru/issues/220? I'm not using multiprocessing, but I am using async. The file does exist as do multiple rotated logs. Could this be a race-condition when `all.log` is being rotated out and for that moment the filename does not exist? I am running a function on a scheduled loop, which logs its actions. So the same actions were run for hours and succesfully logged and rotated before and after this exception was raised. Not sure how to reproduce it other than crossing my fingers and hoping it happens again, but I would like to determine what caused it. :)

**Versions:**
- Loguru: _0.5.3_
- Python: _3.9.2_
- OS: _Debian 11_

**Config:**
```python
loguru.logger.remove()
loguru.logger.add(
    backtrace=True,
    diagnose=True,
    enqueue=True,
    format=log_format,
    level='TRACE',
    rotation='10 MB',
    sink='var/log/all.log',
)
loguru.logger.add(
    backtrace=False,
    colorize=True,
    diagnose=False,
    enqueue=True,
    format=log_format,
    level=logging.INFO,
    sink=sys.stderr,
)
```

**Error:**
```
Traceback (most recent call last):
  File "/.../loguru/_ctime_functions.py", line 32, in get_ctime
    return float(os.getxattr(filepath, b"user.loguru_crtime"))
FileNotFoundError: [Errno 2] No such file or directory: '/.../var/log/all.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../loguru/_handler.py", line 287, in _queued_writer
    self._sink.write(message)
  File "/.../loguru/_file_sink.py", line 174, in write
    self._terminate_file(is_rotating=True)
  File "/.../loguru/_file_sink.py", line 202, in _terminate_file
    creation_time = get_ctime(old_path)
  File "/.../loguru/_ctime_functions.py", line 34, in get_ctime
    return os.stat(filepath).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/.../var/log/all.log'
```

**Comment by Delgan** [comment]
Hi @quantumpacket.

I have a hard time figuring out what could be causing this issue. Are you using any third library that would be susceptible to spawn sub-processes internally?

**Comment by quantumpacket** [comment]
@Delgan the code in question is not using any 3rd party libraries except for Pandas (which surely isn't the culprit), but maybe it's the scheduling library https://github.com/dbader/schedule that I'm using for running the code on a 1 minute loop? I ran it all night long and generated about a dozen rotated logs, but did not get the error to appear again. :(

I'm trying to think of what situations would cause an existing file to not show up as existing. Another possibility is maybe my system did an update or something which caused the partition to be remounted during the 1 minute interval?

**Comment by quantumpacket** [comment]
I stripped out my async code and have not been able to reproduce this error since. I'm going to rework the async functionality back in at a later time and will see if the issue appears again. I'll re-open this if that happens. However, the multiple filename datetimes from above comment still happens, but may be an entirely different problem?
