### ISSUE TITLE
HTML report wrong created with multithreading

### ISSUE THREAD

**Issue by boris-becker-p** [Delgan/loguru#522]
Is html report right created with pytest parallel run?

**Comment by Delgan** [comment]
It should be correct, `loguru` does not interfere with `pytest` reports. Maybe parallel tests aren't suitable if that means multiple process will write to `stderr` at same time and maybe mix output logs. Do you have any reproducible example to share?

**Comment by Delgan** [comment]
I'm closing this issue as there was no follow up. Feel free to re-open if needed.
