### ISSUE TITLE
Is it possible to output critical logs to terminal?

### ISSUE THREAD

**Issue by adub08** [Delgan/loguru#524]
Sorry if this is a silly question, but is it possible to setup a sink in Loguru to output certain level events (such as critical ones) to all terminal users currently logged in? This is for when a script is running as a service by systemctl, not directly invoked by a user. i've been searching for a while for a way to achieve this but have so far been unsucessful.
Thanks very much

**Comment by Delgan** [comment]
Hi.

Sorry for the late answer. I do not exactly know what you mean by "all terminal users currently logged in". You can filter logs based on level like this:

```python
from loguru import logger

logger.remove()  # Remove the default handler
logger.add(sys.stderr, level="CRITICAL")
```

Then maybe you can find a way to conditionally add the handler based on your preferences. I don't know exactly how to differentiate between `systemctl` and direct invocation from within a Python script. Maybe you could use an optional command line flag?

**Comment by Delgan** [comment]
I'm closing this ticket as I feel I answered the question. Feel free to re-open it otherwise.
