### ISSUE TITLE
is it possible to print  pytest test name  and pytest item with parallel run in log?

### ISSUE THREAD

**Issue by boris-becker-p** [Delgan/loguru#527]

**Comment by Delgan** [comment]
Hi.

It should be possible but I'm not sure it is related to Loguru. You can probably use the [`request`](https://docs.pytest.org/en/latest/reference/reference.html?highlight=request#request) fixture as explained in [this StackOverflow answer](https://stackoverflow.com/a/34732269/2291710):

```python
def test_name1(request):
    testName = request.node.name
    logger.info("Test name: {}", testName)
```
