### ISSUE TITLE
日志rotate进行滚动的时候如何自定义滚动的文件名

### ISSUE THREAD

**Issue by Gu-f** [Delgan/loguru#529]
通过document看到可以给文件名用{time}去创建带有时间的日志文件名，但是我每找到如何自定义文件名或使用其他的key。
目前生成的滚动文件如下：
error.log
error.2021-10-19_17-42-14_757655.log
error.2021-10-19_17-42-14_757675.log
error.2021-10-19_17-42-14_757755.log
......
我希望能够自定义成如下的文件名
error.log
error.1.log
error.2.log
error.3.log
......
或者是下面这种
error.log
error.log.1
error.log.2
error.log.3
......
当前是否支持这种功能.
如果不支持的话希望能够作为新功能去更新一个版本。

**Comment by Delgan** [comment]
Hi.

It's possible to customize the name of rotated files using the [`compression`](https://loguru.readthedocs.io/en/stable/api/logger.html#file) argument with a custom function (which is executed after each successful rotation). It's up to you to implement the logic to avoid two files having the same name, though.

```python
def rename_rotated(filepath):
    head, tail = os.path.split(filepath)
    base, *_ = tail.split(".")
    num = 1
    while os.path.exists(os.path.join(head, f"{base}.{num}.log")):
        num += 1
    os.rename(filepath, os.path.join(head, f"{base}.{num}.log"))

logger.add("error.log", rotation="10 MB", compression=rename_rotated)
```
