### ISSUE TITLE
Modify logging level without sys import

### ISSUE THREAD

**Issue by mrx23dot** [Delgan/loguru#535]
Instead of 
```
from loguru import logger
from sys import stdout

logger.remove()
logger.add(stdout, level='INFO')
```

we could have something simpler:

```
from loguru import logger

logger.set(level='INFO') # dont change other parameters
```

as I see 'configure' is different.

**Comment by Delgan** [comment]
Such API isn't really possible because there isn't necessarily one unique handler, so `logger.set()` would actually modify all existing handlers. That's why it's preferable to specifically `.add()` an handler with the desired `level` rather than trying to update existing one.
