### ISSUE TITLE
Create log file dynamically

### ISSUE THREAD

**Issue by david-shiko** [Delgan/loguru#538]
Hello.
I'm not sure that it's a good idea but for multiple reasons, I want to create a personal log file for every client of my telegram bot (I'm using PTB library).
So I need to create a file dynamically when somebody uses my bot (filename is user_id).
I tried to pass a callable to sink but it's not helped me.
Surely I can create a separate logger for every user, but is it the right way?

Here is my decorator that I use for every update

```
# For hinding try/except block and notifing bot user about an error
def bot_logger(text: str = '', end: bool = False):
    def decorator(function):
        @loguru_logger.catch
        @wraps(function)
        def wrapper(*args, **kwargs):
            update = args[0]
            try:
                loguru_logger.error('some_info', sink=f'{user_id}.txt', filename=f'{user_id}.txt')  # That is what I want
                return function(*args, **kwargs)
            except Exception as e:
                update.message.reply_text(text=f'Unknow error. {text} Please try again later')
                loguru_logger.error(e)
                return -1 if end else None
        return wrapper
    return decorator
```

BTW, this decorator has a huge flaw: he's not showing the original function name and line, so every record has the same function name and line
(`2021-11-18 00:45:52.754 | ERROR    | bot:wrapper:43 - division by zero`). Maybe you know how to fix this flow?

**Comment by Delgan** [comment]
Hi.

> I want to create a personal log file for every client of my telegram bot

If you want an unique file you need to [`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) a new handler with the desired filename.

```python
logger.add(f"{user_id}.txt")
logger.error("An error occurred")
```

If multiple users exist at the same time, you may also need to [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) the `logger` and `filter` the logs to avoid sharing multiple user information in the same file. This is not very convenient but will be improve in a coming release, see current workaround: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers).
 
> Maybe you know how to fix this flow?

Sorry, I don't know exactly. Would you have maybe a minimal reproducible example for me to try please?

**Comment by Delgan** [comment]
I'm closing as this issue seems resolved. Feel free to re-open it otherwise.
