### ISSUE TITLE
[Feature request] Add function trace logging.

### ISSUE THREAD

**Issue by heckad** [Delgan/loguru#539]
Add ability to trace function enter and function exit with capture time in it.

 For example
```
@logger.trace()
def some_func():
     # do some work
```
Should out messages
```
Enter to `some_func`
Exit from `some_func` with `${time}` execution time
```

**Comment by Delgan** [comment]
Hi.

This has been suggested in https://github.com/Delgan/loguru/issues/65 but I don't think it should be added as a `logger` method. There exists a snippet in the documentation that you can copy/paste, though: [Logging entry and exit of functions with a decorator](https://loguru.readthedocs.io/en/latest/resources/recipes.html#logging-entry-and-exit-of-functions-with-a-decorator).
