### ISSUE TITLE
Adding a way to perform automatic logging of variables "a la icecream"? [feature request]

### ISSUE THREAD

**Issue by jerabaul29** [Delgan/loguru#541]
# My pain

I find it quite tiredsome to write lots of logs of variables of this kind:

```
from loguru import logger

some_var = 42
logger.info(f"some_var: {some_var}")
```

# How I would usually do this outside of loguru.logger

Usually in python when not using any form of logging but only printing to screen, I would just do something like:

```
from icecream import ic

some_var = 42
ic(some_var)
```

That is much faster to type, the output is nicely formatted etc :) . But it is not "logger managed" :( .

# Why this is hard to combine with loguru

However, if I try to go around this by doing something like:

```
from icecream import ic
from loguru import logger

some_var = 42
logger.info(ic(some_var))
```

then I only got the return value of ic printed by logger.info, while the ic string itself is only printed into normal terminal:

```
ic| some_var: 42
2021-11-23 16:22:03.062 | INFO     | __main__:<module>:12 - 42
```

If I try to instead re direct the output of ic to logger.info, things are not so much better, because then the call to logger.info is from within ic, so this is the line there, inside ic, that is provided as the location from which the log is performed, instead of the actual location in my script, so a lot of important information is lost. I.e.:

```
from icecream import ic
from loguru import logger

ic.configureOutput(prefix="", outputFunction=logger.info)

some_var = 42
ic(some_var)
```

gives:

```
2021-11-23 16:25:27.133 | INFO     | icecream.icecream:__call__:185 - some_var: 42
```

which says where in icecream the loguru.logger.info function was called, instead of indicating where in my script ic was called from.

# What I would like as a user

So far I have not found a way to have the conveniences of icecream.ic with the "logger management" of loguru, while avoiding lots of boilerplate. If I have missed something, please let me know!

If I am right and this is not so easy to get as of now, I wonder if it would be possible to have dedicated loguru functions for performing logging "a la icecream". Something like:

```
from loguru import logger

some_var = 42
logger.icinfo(some_var)
```

that would print:

```
2021-11-23 16:20:12.140 | INFO     | __main__:<module>:15 - some_var: 42
```

And similar "additional loguru.logger functions" for the other levels of logging.

**Comment by Delgan** [comment]
Hi @jerabaul29.

I haven't looked closely yet at how IceCream could be incorporated with Loguru, but while reading your question I thought you could maybe use the [f-string debugging feature](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging) from Python 3.8?

```python
>>> some_var = 42
>>> logger.info(f"{some_var=}")
2021-12-05 17:50:53.973 | INFO     | __main__:<module>:1 - some_var=42
```

**Comment by jerabaul29** [comment]
Aaah, amazing, many thanks, I did not know about this f-string debugging feature, this is indeed exactly what I needed :) . Many thanks, feel free to close, as this fills my need :) . Wonder if this may be a nice example to show "just passing by" on the main readme, as I think this is a quite common pattern? :) .

**Comment by char101** [comment]
There are several ways to do this but only one prints the correct location

```python
import inspect

from icecream import ic
from loguru import logger

a = 10

# prints correct location
logger.info(ic.format(a + 10))

# wrong location from icecream
ic.configureOutput(outputFunction=logger.info)
ic(a + 10)


def iclog(*args):
    import inspect
    frame = inspect.currentframe().f_back
    logger.info(ic._format(frame, *args))


# wrong location from icinfo
iclog(a + 10)

logger.icinfo = lambda *args: logger.info(ic._format(inspect.currentframe().f_back, *args))

# wrong location from lambda
logger.icinfo(a + 10)

```

```
2022-01-14 00:25:13.940 | INFO     | __main__:<module>:9 - ic| a + 10: 20
2022-01-14 00:25:13.949 | INFO     | icecream.icecream:__call__:185 - ic| a + 10: 20
2022-01-14 00:25:13.952 | INFO     | __main__:iclog:19 - ic| a + 10: 20
2022-01-14 00:25:13.961 | INFO     | __main__:<lambda>:25 - ic| a + 10: 20
```

**Comment by Delgan** [comment]
I'll probably soon replace `{}` formatting with f-strings, so this feature will be documented de facto. :+1:
