### ISSUE TITLE
[Feature Request] Short form timezone logging 

### ISSUE THREAD

**Issue by Bainsbe** [Delgan/loguru#543]
Would it be possible to implement short form timezone display, ex:

"Central Standard Time" -> "CST" 

Thanks!

**Comment by Delgan** [comment]
Hi.

This should be already possible using [a custom time format](https://loguru.readthedocs.io/en/stable/api/logger.html#time) and the `zz` specifier, right?

```python
>>> logger.add(sys.stderr, format="[{time:YYYY-MM-DD HH:mm:ss zz}] {message}")
1
>>> logger.info("Test")
[2021-12-05 17:54:24 CET] Test
```

**Comment by Bainsbe** [comment]
I thought so as well, but "zz" outputs as a full string in my logs:

`>> logger.add(sys.stderr, format="{time:YYYY-MM-DD HH:mm:ss zz} - {level}: {message}", level="INFO")
>> logger.info("Test")
2021-12-07 14:18:42 Central Standard Time - INFO: Test
`

**Comment by Delgan** [comment]
Hey @Bainsbe, sorry for the late answer.

The timezone string is handled by the system so it's no something I can easily modify from within Loguru, unfortunately.

Maybe we can try to understand why your output is different from mine. What is your OS and Python version?

**Comment by Bainsbe** [comment]
Hey @Delgan, no worries

OS: Windows 11 Enterprise
Python: 3.8.12

Seems you're right though, played around with it a bit and I'm having the same issue with the tz functions in the datetime and time modules as well. So likely an issue on my end. Weird as the OS seems to have it defined correctly when checked in powershell...  I'll try to update if I find anything. Thanks again

**Comment by Delgan** [comment]
The timezone used by Loguru comes from the `tm_zone` attribute of the [`struct_time`](https://docs.python.org/3/library/time.html#time.struct_time) returned by [`localtime()`](https://docs.python.org/3/library/time.html#time.localtime). This is populated by the equivalent C function and thus platform-dependent.

If you find an interesting explanation let me know, otherwise you can use the following workaround:

```python
from datetime import timezone

def fix_timezone(record):
    offset = record["time"].tzinfo.utcoffset(None)
    tzinfo = datetime.timezone(offset, "CST")
    record["time"] = record["time"].replace(tzinfo=tzinfo)

logger.configure(patcher=fix_timezone)
```
