### ISSUE TITLE
bind logger not work

### ISSUE THREAD

**Issue by foozzi** [Delgan/loguru#551]
I have 2 loggers, one of them writes to a file

```
TASK_LOGGING_CONFIG = {
        "handlers": [
            {
                "sink": os.path.join(LOGS_PATH, "tasks.log"),
                "format": "[{time:YYYY-MM-DD at HH:mm:ss}] [{level}]: {message}",
                "rotation": "5 MB",
                "retention": "3 days",
                "filter": lambda record: "task" in record["extra"],
            },
        ]
    }
```
then:
`logger.bind(task=True).debug(...)`
but everything is written to the file, not just with bind, how to fix this?

**Comment by Delgan** [comment]
Cab you share your entire configuration and a reproducible example please?

The following snippet works as expected:

```python
from loguru import logger

K_LOGGING_CONFIG = {
        "handlers": [
            {
                "sink": "tasks.log",
                "format": "[{time:YYYY-MM-DD at HH:mm:ss}] [{level}]: {message}",
                "rotation": "5 MB",
                "retention": "3 days",
                "filter": lambda record: "task" in record["extra"],
            },
        ]
    }

logger.configure(**K_LOGGING_CONFIG)
logger.info("Not logged in file")
logger.bind(task=True).info("Logged in file")
```

Note that there is technically only one `logger` object, so anytime you `.add()` an new handler it will receive all logs from your application (if not filtered out).

**Comment by foozzi** [comment]
> Cab you share your entire configuration and a reproducible example please?
> 
> The following snippet works as expected:
> 
> ```python
> from loguru import logger
> 
> K_LOGGING_CONFIG = {
>         "handlers": [
>             {
>                 "sink": "tasks.log",
>                 "format": "[{time:YYYY-MM-DD at HH:mm:ss}] [{level}]: {message}",
>                 "rotation": "5 MB",
>                 "retention": "3 days",
>                 "filter": lambda record: "task" in record["extra"],
>             },
>         ]
>     }
> 
> logger.configure(**K_LOGGING_CONFIG)
> logger.info("Not logged in file")
> logger.bind(task=True).info("Logged in file")
> ```
> 
> Note that there is technically only one `logger` object, so anytime you `.add()` an new handler it will receive all logs from your application (if not filtered out).

everything is fine, my problem, I'm sorry
