### ISSUE TITLE
How to prevent other packages from changing my logger?

### ISSUE THREAD

**Issue by marhoy** [Delgan/loguru#553]
I'm using loguru as the logger in my package (package A).
Inside one of my modules in package A, I'm importing another package (package B) that *also* uses loguru as the logger.

This other package B contains:

```
# Configure Loguru logging
logger.remove()
logger.add(sys.stderr, level=config.LOG_LEVEL)
```

After having imported package B in my module in package A, the logger-object in package A is replaced by the one configured by package B.

How can I import package B without having it mess with my already configured logger?

**Comment by Delgan** [comment]
Hi @marhoy.

Packages shouldn't touch the `logger` handlers, it's the user responsibility to configure them.

The package should only be configured while used as a script:

```python
if __name__ == "__main__":
    # Configure Loguru logging
    logger.remove()
    logger.add(sys.stderr, level=config.LOG_LEVEL)
```

That way it won't conflict with any other logging configuration when used as a library and imported by the user.

You can also provide a function to configure the logger:

```python
def configure_logger_A():
    # Configure Loguru logging
    logger.remove()
    logger.add(sys.stderr, level=config.LOG_LEVEL)
```

Again, the user should be responsible for calling it if he needs it.

See also [`logger.enable()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.enable) and [`logger.disable()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.disable) for controlling log messages displayed by your libraries.
