### ISSUE TITLE
Thread.local and contextvars ?

### ISSUE THREAD

**Issue by yonnig** [Delgan/loguru#555]
Hello,

It seems there is currently no support for binding some log context to a thread.local, nor a contextvars, as what structlog can do ([thread-local context](https://www.structlog.org/en/stable/thread-local.html#thread-local-context), [context variables](https://www.structlog.org/en/stable/contextvars.html#context-variables)).

Although these mechanisms have known [downsides & caveats](https://www.structlog.org/en/stable/thread-local.html#downsides-caveats), would you plan to introduce such things in Loguru ?

**Comment by Delgan** [comment]
Hi.

The [`logger.contextualize()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.contextualize) method does use `contextvars`. Is that what you're looking for?

**Comment by yonnig** [comment]
Hello,

That's it! I didn't realize `contextvars` were applicable to asynchronous tasks as well as threads... I should have read more carefully both the Python and the Loguru documentation. Moreover, using a context manager for that feature is a perfect choice.

Thanks a lot for your response.

**Comment by Delgan** [comment]
I'm glad the solution fits your needs! :smiley: 

I'm closing this ticket consequently. :+1:
