### ISSUE TITLE
Question: is there an option not to truncate collection types in better error tracing?

### ISSUE THREAD

**Issue by cibolog** [Delgan/loguru#556]
I want to be able to see the full render of a long collection and full path to some non `__repr__`ed class when getting error trace, so
```python
SomePydanticSerializer(**kwargs)
│                        └ {'long_key1': 'string', 'long_key2': 1, 'long_key3': 123, 'lon...
└ <class src.folder.folder.folder.fold...
```
would become
```python
SomePydanticSerializer(**kwargs)
│                        └ {'long_key1': 'string', 'long_key2': 1, 'long_key3': 123, 'long_key3': 'done'}
└ <class src.folder.folder.folder.folder.SomePydanticSerializer object at 0xaa>
```

Is that possible?

**Comment by Delgan** [comment]
Hi @cibolog.

Lines longer than 128 characters are truncated to avoid flooding the logs. For simplicity reasons I don't want to make this value accessible to the user.  However you can configure a custom exception formatter as demonstrated in the documentation: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions). Then you'll be able to directly use [`better_exceptions`](https://github.com/Qix-/better-exceptions) with the desired `MAX_LENGTH`.

Note that values displayed are intended to give a quick overview of the issue during development, but using a debugger is more appropriate for advanced cases.. :+1:
