### ISSUE TITLE
[Question] Is it possible to add sleep on logger.debug

### ISSUE THREAD

**Issue by BarryThrill** [Delgan/loguru#557]
Hello Loguru!

I have been trying to figure out how I can be able to add a sleep on x seconds when I use logger.debug. - The reason of it is that I have my own env that I have called `configure.utils.debug` which is a bool of True/False. If its True then I want the `logger.debug` to be printed out and if its not then I don't want the` logger.debug` to print out anything. 

So I have created something like this:

```py
logger.remove()
if not configuration.utils.debug:
    logger.add(sys.stdout, filter=lambda record: record["level"].name == "INFO")
    logger.add(sys.stderr, filter=lambda record: record["level"].name not in ["INFO", "DEBUG"])
    # Print to discord if logger.exception
    logger.add(discord_sink, filter=exception_only, enqueue=True)
else:
    logger.add(sys.stderr, level="DEBUG")
```

So the question is if its possible that I could add a long sleep whenever I do use the logger.debug e.g. that once it printed the logger.debug, to sleep in 500 secs? 

I am also up to improvements if I am even doing the function correctly. It works but if it can be even better, im also up for that :) 

But my main question is that if its possible to add sleep automatically whenever we call logger.debug?

**Comment by Delgan** [comment]
Hey there. :)

That's certainly possible by wrapping `sys.stderr` in a custom sink:

```python
def sleeping_sink(message):
    sys.stderr.write(message)
    if message.record["level"].name == "DEBUG":
        time.sleep(0.5)
 
logger.add(sleeping_sink, level="DEBUG")
```

Alternatively you can just add another sink with the appropriate `filter`:

```python
logger.add(sys.stderr, level="DEBUG")
logger.add(lambda _: time.sleep(0.5), filter=lambda record: record["level"].name == "DEBUG")
```

Overall your configuration is perfectly fine regarding Loguru usage. I think you could replace `logger.add(sys.stderr, filter=lambda record: record["level"].name not in ["INFO", "DEBUG"])` with `logger.add(sys.stderr, level="WARNING")` (except if you specifically intended to receive `"TRACE"` but not `"DEBUG"` events).

**Comment by BarryThrill** [comment]
> 

Hello there!

I didn't knew how to add the label set to "question" so thank you for that!

I ended up doing something like this:

```py
logger.remove()
if not configuration.utils.debug:
    logger.add(sys.stdout, filter=lambda record: record["level"].name == "INFO")
    logger.add(sys.stderr, level="WARNING")
    logger.add(discord_sink, filter=exception_only, enqueue=True)
else:
    logger.add(sys.stderr, level="DEBUG")
    logger.add(lambda _: time.sleep(500), filter=lambda record: record["level"].name == "DEBUG")
```

and I can say that it is now working as indented :D Thank you very much for the quick help and if you do not have anything I could improve from here. feel free to close the comment. Thank you once again for being a great person who created this awesome repo <3 <3

**Comment by BarryThrill** [comment]
> Hey there. :)
> 
> That's certainly possible by wrapping `sys.stderr` in a custom sink:
> 
> ```python
> def sleeping_sink(message):
>     sys.stderr.write(message)
>     if message.record["level"].name == "DEBUG":
>         time.sleep(0.5)
>  
> logger.add(sleeping_sink, level="DEBUG")
> ```
> 
> Alternatively you can just add another sink with the appropriate `filter`:
> 
> ```python
> logger.add(sys.stderr, level="DEBUG")
> logger.add(lambda _: time.sleep(0.5), filter=lambda record: record["level"].name == "DEBUG")
> ```
> 
> Overall your configuration is perfectly fine regarding Loguru usage. I think you could replace `logger.add(sys.stderr, filter=lambda record: record["level"].name not in ["INFO", "DEBUG"])` with `logger.add(sys.stderr, level="WARNING")` (except if you specifically intended to receive `"TRACE"` but not `"DEBUG"` events).

Hello there!

I didn't knew how to add the label set to "question" so thank you for that!

I ended up doing something like this:

```py
logger.remove()
if not configuration.utils.debug:
    logger.add(sys.stdout, filter=lambda record: record["level"].name == "INFO")
    logger.add(sys.stderr, level="WARNING")
    logger.add(discord_sink, filter=exception_only, enqueue=True)
else:
    logger.add(sys.stderr, level="DEBUG")
    logger.add(lambda _: time.sleep(500), filter=lambda record: record["level"].name == "DEBUG")
```

and I can say that it is now working as indented :D Thank you very much for the quick help and if you do not have anything I could improve from here. feel free to close the comment. Thank you once again for being a great person who created this awesome repo <3 <3

**Comment by Delgan** [comment]
Thanks for your kind words once again! :smile: 

Your snippet looks good. Glad I could help. :+1:
