### ISSUE TITLE
Context manager to disable the recording and logging ?

### ISSUE THREAD

**Issue by jizongFox** [Delgan/loguru#558]
Hello,

Exists there one function (context manager) to temporally disable the output of the logger and then revert this operation? 

I see  I can use logger.disable(name) with an attribute `name`, however, I want to disable all messaging recording, instead of a single name. 

Any suggestions?

**Comment by Delgan** [comment]
Hi.

This looks possible using a custom `filter` combined with [`contextualize()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.contextualize):

```python
from loguru import logger
import sys

logger.remove()
logger.add(sys.stderr, filter=lambda r:r["extra"].get("enabled", True))

logger.info("Logging as usual")

with logger.contextualize(enabled=False):
    logger.info("Logging disabled")

logger.info("Logging enabled again")
```
