### ISSUE TITLE
Question: Inject metainformation about a log record

### ISSUE THREAD

**Issue by NeoCortex97** [Delgan/loguru#562]
I am building a primitive distributed system and want to optionally transmit logs to a different process and would like to preserve the info like module, file, function,...  
Transmitting and receiving is already taken care of, but I do not understand, how i could artificially inject the information.

I would prefer to avoid building an intercept handler and transmitting pickled objects, because of different platforms. 
And i would like to avoid using a different format for the remote events that has loads of external data.

But all in all I am pretty clueless.

**Comment by Delgan** [comment]
Hi.

What you are trying to achieve is not very clear to me. Do you have a more concrete example please?

Maybe you could use [`logger.bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) to attach additional data to a log record.

**Comment by NeoCortex97** [comment]
Okay, a concrete example could be the following:
You have a number of nodes - lets say two for example.
One is a "Server" or running as a service.
The other acts as an interface or client that has some logic on its own.

while the client is running, I want to see logs from the service inside the logs of the client too. I'll include a few line of example log in here, so it is more clear:
(Please excuse that I am not coming up with different times)
```
[2021-12-28 15:29:19][0:00:00.012668] |INFO    | monitor: Created monitoring socket
[2021-12-28 15:29:19][0:00:00.012668] |INFO    | server: Received command from client
[2021-12-28 15:29:19][0:00:00.012668] |INFO    | monitor: waiting for response
[2021-12-28 15:29:19][0:00:00.012668] |DEBUG   | server: Missing command parameter! assuming default value
[2021-12-28 15:29:19][0:00:00.012668] |WARNING| monitor:  unknown command "catvideos"!
[2021-12-28 15:29:19][0:00:00.012668] |INFO| server: requested data from client
[2021-12-28 15:29:19][0:00:00.012668] |INFO| monitor: Sending addtional data
[2021-12-28 15:29:19][0:00:00.012668] |DEBUG   | server: completed command, sending response
[2021-12-28 15:29:19][0:00:00.012668] |INFO| monitor: command complete
```
Hope this helps. It is hard to come up with a better example without going into great detail with my project, but i hope this helps. The example log should be viewed as the stderr output of the client.

**Comment by Delgan** [comment]
Thanks for the update. It's all clear no that I'm re-reading your initial comment.

Did you see these snippets in the documentation: [Sending and receiving log messages across network or processes](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes)?

It's looks very similar to what you're trying to achieve, although it makes use of the `pickle` module.

You mentioned that "transmitting and receiving [was] already taken care of". If so, you could create a new log message and [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) it using the received meta-information. You'll probably need to manually update [the record `dict`](https://loguru.readthedocs.io/en/stable/api/logger.html#record):

```python
from collections import namedtuple

def update_record(record, received_data):
    record["function"] = received_data.function
    record["name"] = received_data.name
    record["line"] = received_data.line
    record["file"] = namedtuple("File", ["name", "path"])(received_data.name, received_data.path)
    # Keep going with fields you're interested in.
    ...

def on_data_received(received_data):
    level, message = received_data.level, received_data.message
    logger.patch(lambda record: update_record(record, received_data)).log(level, message)
```

That's way the incoming message will be handled by all configure handlers. Another possibility is just to use a custom sink and format the message by yourself:

```python
class CustomSink:

    def write(self, message):
        # Default entry point for usual log messages handled by Loguru.
        sys.stderr.write(message)
 
    def write_incoming_message(self, received_data):
        # Alternative entry point which is not handled by Loguru.
        message = "[{date}] {level} - {message}\n".format(**received_data)
        self.write(message)

sink = CustomSink()
logger.add(sink)

def on_data_received(received_data):
    sink.write_incoming_message(received_data)

logger.info("Logging as usual")
```

**Comment by NeoCortex97** [comment]
Thanks a lot!
I had seen the snippet in the documentation, but was not that sure if it would work. As far as I know pickle - at least at some point in history had problems with interoperating lsb and msb hardware and since I did not find if it is still the case i did not bother to try yet.

I already have written a custom sink for the server side, that transmits relevant parts of the record dict as a msgpack list with a specific order and a function to transform it back into a dict.

But if you can tell me that pickle will work just fine even acrios different byte orders, I would gradly use the alredy existing funtionality.

**Comment by Delgan** [comment]
You can indeed replace `socket` with `zmq` without much trouble. Regarding the `pickle` module cross-platform compatibility, I only found [this answer from StackOverflow](https://stackoverflow.com/a/1850806/2291710). However, nothing is stated bout compatibility guarantees in the official documentation. Also, `pickle` is notoriously known to be unsafe while parsing possibly untrusted data, so if you already have access to a deserialized `dict` you can use it to update the record as well:

```python
logger.patch(lambda record: record.update(**deserialized_dict)).log(level, message)
```

**Comment by NeoCortex97** [comment]
That sounds reasonable to me and thanks for reminding me of the security aspect of `pickle`. I knew it already, but successfully displaced it from my memory :-D.
I thinks I'll go the update route and hope I'll find my way from here. 
I would leave the issue open in case I run into any more trouble, and would close it if it seams like it is working.
Thank you very much for helping me out around the holidays :+1:  :100:

**Comment by NeoCortex97** [comment]
As if I had known it:
I tried it out and it seems to work, but I get an `ValueError` exception with the description 
```
Traceback (most recent call last):
  File "/home/stefan/PycharmProjects/Data/venv/lib/python3.8/site-packages/loguru/_handler.py", line 151, in emit
    formatted = precomputed_format.format_map(formatter_record)
AttributeError: 'int' object has no attribute 'name'
```
sometimes.
I looked at it and realized, that the thread object is only an integer with the thread-id and not a dict with thread id and name.
Do you have any hints how i could force the thread name in?

**Comment by Delgan** [comment]
> Thank you very much for helping me out around the holidays :+1: :100:

You're welcome. ;)

> I looked at it and realized, that the thread object is only an integer with the thread-id and not a dict with thread id and name.
> Do you have any hints how i could force the thread name in?

Loguru expects the `record["thread"]` value to be a container with both `id` and `name` attributes. It's more like a `namedtuple` than an actual `dict`. When an handler is configured with `format="{thread.name} {message}"`, each log is then constructed by calling `handler_format.format(**record)` which causes an error if `record["thread"]` is an integer.

I think the easiest solution is to simply update the default `record["thread"]` using [`namedtuple._replace()`](https://docs.python.org/3/library/collections.html#collections.somenamedtuple._replace). Something like this for example:

```python
def patch_record(record, data):
    thread_id = data.pop("thread")
    # You can replace 'name' value as well if it's part of your received data.
    record["thread"] = record["thread"]._replace(id=thread_id, name="?")
    record = record.update(**data)
    return record

logger.patch(lambda record: patch_record(record, data)).log(level, message)
```
```
