### ISSUE TITLE
How to hide output in Jupyter notebook (but still continue logging)

### ISSUE THREAD

**Issue by kennethleungty** [Delgan/loguru#565]
Hi there,

Is there a way to hide the output inside Jupyter notebook (encircled in green) while still maintaining the info logging capabilities (including saving the .log file) ?

![image](https://user-images.githubusercontent.com/16691614/148789543-29ad7896-b0c6-476d-855d-1466bba398fa.png)

Thanks!

**Comment by Delgan** [comment]
Hi @kennethleungty.

I'm not very familiar with Jupyter but could you maybe [remove()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) the default `stderr` sink, before adding the file one? I guess it should prevent Jupyer from capturing and displaying the logs.

```python
logger.remove()  # Remove default 'stderr' sink (and all others, if any)
logger.ad("my_log_file.log", rotation="10 MB")
```

**Comment by kennethleungty** [comment]
Hey Delgan,

Thanks for the reply. Your solution worked! Awesome stuff. Cheers!
