### ISSUE TITLE
[Question] Where are the functions that parse module, and function information per log message?

### ISSUE THREAD

**Issue by sla-te** [Delgan/loguru#566]

**Comment by Delgan** [comment]
Hey @sla-te.

These informations are extracted from a Python [`frame`](https://docs.python.org/3/library/inspect.html#the-interpreter-stack) object, you can probably find the implementation you're looking fore here: https://github.com/Delgan/loguru/blob/3d5234541c81318e7f6f725eca7bab294fe09c23/loguru/_logger.py#L1894-L1926
