### ISSUE TITLE
Incorrect isInstance() checks when attempting Network Sink

### ISSUE THREAD

**Issue by AShriki** [Delgan/loguru#567]
https://github.com/Delgan/loguru/blob/3d5234541c81318e7f6f725eca7bab294fe09c23/loguru/_logger.py#L2004

Hello, this is my first issue on github so I apologize if it is unconventionally formatted.
I noticed that when using a network sink (essentially directly from loguru examples) there is an isInstance() check which cause loguru to fail due to a bad comparison between a class with a named tuple (RecordLevel) and built-in types (int and str). It fails consistently with the following error:
Also, I have included a minimal example with a server and a client.
<pre><code>
{'elapsed': datetime.timedelta(microseconds=23176), 'exception': None, 'extra': {}, 'file': (name='client.py', path='client.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 27, 'message': 'Hello!', 'module': 'client', 'name': '__main__', 'process': (id=14744, name='MainProcess'), 'thread': (id=22836, name='MainThread'), 'time': datetime(2022, 1, 12, 14, 44, 31, 712720, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'Eastern Standard Time'))}
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56579)
Traceback (most recent call last):
  File "C:\Users\person\.pyenv\pyenv-win\versions\3.7.9\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\person\.pyenv\pyenv-win\versions\3.7.9\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\person\.pyenv\pyenv-win\versions\3.7.9\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\person\.pyenv\pyenv-win\versions\3.7.9\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "server.py", line 20, in handle
    logger.patch(lambda record: record.update(record)).log(level, message)
  File "C:\Users\person\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\loguru\_logger.py", line 1996, in log
    level_id, static_level_no = __self._dynamic_level(__level)
  File "C:\Users\person\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\loguru\_logger.py", line 2014, in _dynamic_level
    "Invalid level, it should be an integer or a string, not: '%s'" % type(level).__name__
TypeError: Invalid level, it should be an integer or a string, not: 'RecordLevel'
----------------------------------------
</code></pre>

<h2>CLIENT:</h2>
<pre><code>
from loguru import logger
from sys import stdout
import pickle
import socket
import struct

class SocketHandler:

    def __init__(self, host, port):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        print(f"connect to {host} on port {port}")
        self.sock.connect((host, port))

    def write(self, message):
        record = message.record
        data = pickle.dumps(record)
        slen = struct.pack(">L", len(data))
        self.sock.send(slen + data)

env_var={"server_address":"localhost","server_port":1025}

logger.remove()
logger.add(stdout, format='<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <cyan>{name}</cyan> | {message}\n{exception}', level = 'INFO', enqueue=True)
if "server_address" in env_var.keys() and "server_port" in env_var.keys():
    logger.configure(handlers=[{"sink": SocketHandler(env_var['server_address'], int(env_var['server_port']) ) }] )

logger.info("Hello!")
</code></pre>

<h2>SERVER</h2>
<code><pre>
import socketserver
import struct
import pickle
from loguru import logger
from sys import stdout

class LoggingStreamHandler(socketserver.StreamRequestHandler):
    def handle(self):
        while True:
            chunk = self.connection.recv(4)
            if len(chunk) < 4:
                break
            slen = struct.unpack('>L', chunk)[0]
            chunk = self.connection.recv(slen)
            while len(chunk) < slen:
                chunk = chunk + self.connection.recv(slen - len(chunk))
            record = pickle.loads(chunk)
            print(record)
            level, message = record["level"], record["message"]
            logger.patch(lambda record: record.update(record)).log(level, message)

class LoguruServer:
    def run(_):
        addr = ('', int(env_var["server_port"]))
        with socketserver.TCPServer(addr, LoggingStreamHandler) as server:
            server.serve_forever()    

env_var={"server_address":"localhost","server_port":1025}
logger.remove()
logger.add(stdout, format='<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <cyan>{name}</cyan> | {message}\n{exception}', level = 'INFO', enqueue=True)

s = LoguruServer()
s.run()
</code></pre>

**Comment by AShriki** [comment]
Bad example from the documentation
<code>logger.patch(lambda record: record.update(record)).log(level, message)</code>
should be 
<code>logger.patch(lambda record: record.update(record)).log(level.no, message)</code>

**Comment by Delgan** [comment]
Sorry for such mistake, it has been reported in #337 and fixed accordingly but due to no new release until now, it is still not on the "stable" version of the documentation.
