### ISSUE TITLE
[Question] Why do string formatting happen for messages that will not be logged?

### ISSUE THREAD

**Issue by adamatan** [Delgan/loguru#568]
Consider the following example, using [loguru's modern string formatting](https://github.com/Delgan/loguru#modern-string-formatting-using-braces-style):

```python
from loguru import logger

def long_calculation(n: int):
    logger.critical(f"Long calculation called - was it neccesary?")
    return n

logger.trace("This log message will not be shown {long_calculation}", long_calculation=long_calculation(5))
logger.debug("This log message will be shown {long_calculation}", long_calculation=long_calculation(5))
```
Which will result in:
![image](https://user-images.githubusercontent.com/1014189/149507561-28ef04c2-af27-4cf9-991a-00f1ecff2464.png)

The `logging.trace` call was below the logger level, so it was not shown. This is OK, but the parameters were evaluated in a potentially expensive process.
This is important in a production environment, where trace logs - usually used only during development - should not be expanded in vain.

If you agree with the problem, I'll be happy to discuss and contribute possible solutions.

**Comment by Delgan** [comment]
This is because Python processes all the arguments before calling the function.

Passing anonymous arguments to a function is no different from using a variable, it **needs** to be evaluated first. 

```python
argument = long_calculation(5)
logger.trace("This log message will not be shown {long_calculation}", long_calculation=value)
```

However, Loguru allows lazy evaluation of arguments by using the [`.opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) method. You can take a look at [the snippet in the Readme](https://github.com/Delgan/loguru#lazy-evaluation-of-expensive-functions).

```python
logger.opt(lazy=True).trace("This log message will not be shown {long_calculation}", long_calculation=lambda: long_calculation(5))
```

In this case, the `lambda` function (and thus `long_calculation(5)`) will only be called if needed.

**Comment by adamatan** [comment]
Thanks for the quick and thorough answer!

This is a bit cumbersome:
```python
logger.opt(lazy=True).trace("This log message will not be shown {long_calculation}", long_calculation=lambda: long_calculation(5))
```

I would personally prefer the more readable:

```python
if (logging level >= level):
    logger.level(message)
```

However, I think this is applicable to almost any logging message. Is there a mechanism we can utilize to prevent the parameter evaluation for the calls? Perhaps having the `.opt()` call return something that would prevent the rest of the line from being executed at all?

**Comment by Delgan** [comment]
Yeah, I get your point about readability. The `.opt(lazy=True)` solution wasn't really designed for consecutive calls. I'd rather not add a new way to skip the arguments processing, but there may be alternative solutions that can help you I hope.

---

The  straightforward one is to store the minimum log level while configuring the `logger`, then compare it manually.

```python
# config_logger.py
from loguru import logger

debug_mode = False
level_name = "DEBUG" if debug_mode else "INFO"
logging_level = logger.level(level_name).no
logger.add(sys.stderr, level=level_name)
```
```python
# some_module.py
from config_logger import logging_level
from loguru import logger

if logging_level <= logger.level("DEBUG").no:
    logger.debug("This log message will be shown {long_calculation}", long_calculation=long_calculation(5))
```
This is only a basic example that can surely be improved using a context manager if you prefer.

---

It should also be noted that arguments are all lazily formatted. This means that if the logging level is too low, there will be no time wasted formatting the arguments, and the `__format__()` function of logged objects will not be called.

```python
from loguru import logger

class LazyFormatter:
    def __init__(self, callback):
        self._callback = callback

    def __format__(self, specs):
        return self._callback()

lazy_formatter = LazyFormatter(lambda: long_calculation(5))
logger.debug("This log message will be shown {long_calculation}", long_calculation=lazy_formatter)
```

This is not much better than the `opt(lazy=True)` solution but I wanted to mention it in case some of your classes might be designed with expensive parts done during formatting.

---

The last solution I have in mind is to put all your operations in a adjacent function and pass it to the logger with `opt(lazy=True)`.

```python
from loguru import logger

def log_debug_data():
    logger.info("Preparing debugging data")
    result_a = do_something_expensive()
    result_b = do_something_else_expensive()
    logger.debug("Result of a is: {}", result_a)
    logger.debug("Result of b is: {}", result_b)
    do_something_else_if_you_need_to()

logger.opt(lazy=True).debug("Logged debugging data", log_debug_data)
```

This might look a little bit hacky but this workaround [is actually unit tested](https://github.com/Delgan/loguru/blob/378a400b3e6a04d7317603ea05c08534a6c0395f/tests/test_opt.py#L150-L163) so it can be considered as a valid usage of Loruru API.

**Comment by adamatan** [comment]
Thanks a lot for your thorough and useful answer!
