### ISSUE TITLE
How can I add the logs for start and end of every function and the time for which a function runs if I am using @logger.catch before every function

### ISSUE THREAD

**Issue by rishika2416** [Delgan/loguru#569]
eg:

```python
@logger.catch
def area():
 a=s*s
  return a
@logger.catch
def perimeter():
  p=s*4
  return p
if __name__ == "__main__":
        logger.remove()
        logger.add("Output/file.log", format="{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}")
        perimeter()
        area()
```

**Comment by Delgan** [comment]
Hi.

Please, take a look at these examples in the documentation and let me know if it solves your problem: [Logging entry and exit of functions with a decorator](https://loguru.readthedocs.io/en/stable/resources/recipes.html#logging-entry-and-exit-of-functions-with-a-decorator).

There is no "built-in way" to log elapsed time of a function but such decorator can be easily created manually.
