### ISSUE TITLE
Running into issue trying to use enqueue.

### ISSUE THREAD

**Issue by scottjr22** [Delgan/loguru#571]
Hello, I am trying to implement loguru into my codebase as I think it would make logging easier. However, running into a very simple issue I can't understand.

Apologies, code markdown isn't working.

main.py:
```python
import multiprocessing
from loguru import logger
import sys

def init_log():
    # Remove all default handlers
    logger.remove()
    # Add new handler with enqueue
    logger.add(sys.stderr, level='DEBUG', enqueue=True)
    return logger

# This func throws an error.
def func_error():
    logger.debug('This function throws a key error.')
    my_dict['key error']


def do_work(pid, logger):
    logger.debug(f'This is me doing work! {pid}')
    logger.debug(f'Stil doing my work in  {pid}')


def main(logger):
    func_error()
    processes = []
    for idx in range(50):
        proc = multiprocessing.Process(target=do_work, args=(idx, logger))
        proc.start()
        processes.append(proc)
    for p in processes:
        p.join()


if __name__ == '__main__':
    logger = init_log()
    logger.debug("log output from main!")
    main(logger)
```

When I run this code, the output is a jarbled mess in the terminal. It's looks like the stack trace is mixed in with the debug logs. However, if i remove the func_error() then the output to the terminal is clean. Finally, if I change the handler to output to a file instead of sys.stderr then the debug logs will go to the file **but the stacktrace goes to the terminal.**

Note that I am using multiprocessing, but this issue seems unrelated to that besides using enqueue. If I set enqueue=False, then the everything works before entering multiprocessing and then the child process logs are jarbled as expected(enqueue=False).

This is my first time using loguru and very confused why this is happening. Using windows 10 and python 3.9.

**Comment by Delgan** [comment]
Hey @scottjr22. I updated your question adding the code markdown thanks to ` ``` ` backticks. ;)

Let me explain what I think is going on. By specifying `enqueue=True`, Loguru will start an internal thread in charge of processing logs in the background (in a non-blocking way). Consequently, there is a little day between the moment when `logger.debug()` is called and when the log message is displayed on the terminal. During this time, the main function can keep running.

This explains why you're seeing mixed output: `my_dict['key error']` causes an exception which is handled in the main thread by the built-in Python exception handler which display stacktrace on `stderr` (see [`sys.excepthook`](https://docs.python.org/3/library/sys.html#sys.excepthook)), and at the same time the Loguru handler is also processing the pending `debug` message on `stderr`. There are two threads trying to write on `stderr` at the same time.

It works fine with `enqueue=False` because in such case, no child thread is spawned and log messages are handled in the main thread. Also, while using a file handler, Python and Loguru do not try to write to the same output, so there is no issue.

Loguru does not automatically capture exceptions. If you want the exceptions to appears in logs (whether it's on the terminal or in a file), you can decorate your function with [`@logger.catch`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch) for example. It won't invoke the default Python exception handler and thus should not produce mixed terminal output.

**Comment by scottjr22** [comment]
Thank you! This was helpful!
