### ISSUE TITLE
Roadmap for C implementation and concern about multi-platform support

### ISSUE THREAD

**Issue by jennydaman** [Delgan/loguru#577]
The README mentions a C implementation.

https://github.com/Delgan/loguru#x-faster-than-built-in-logging

Is there a roadmap for the C implementation, and if/when it lands, will the pure Python implementation be supported concurrently?

I'm a weirdo who develops Python applications which run on PowerPC. Apple M1 users might also be concerned. `pip install` of natively implemented packages is not trivial on non-x86_64 platforms because `bdist_wheel` is not always provided for them, such as with the case with numpy.

**Comment by Delgan** [comment]
Well, I've been talking about the C implementation for a long time but unfortunately I still haven't published anything. I hadn't improved Loguru much lately, I'm recently trying to get back to it to release a `0.6.0` after which I'll start implementing it in C. There is no roadmap beyond that.

In any case, the Python implementation will always be supported and tested. During installation, if a precompiled version does not exist on PyPy and the local build is impossible, the implementation will fallback to the Python version at runtime. I was also thinking of adding an environment variable to possibly specify the preferred build type during installation.

**Comment by dmerejkowsky** [comment]
Would you be interested in a patch that would use Rust code to improve performance or do you want to stick to C ?

**Comment by dmerejkowsky** [comment]
Oh sorry, I see you've already answered in #479.

**Comment by Delgan** [comment]
@dmerejkowsky Yeah as discussed I would prefer to stick to the C api. Thank you anyway for your proposal! :smiley: 

I'm closing this ticket anyway, since the original question has been answered. :+1:
