### ISSUE TITLE
I am using logger info and loger.catch in many functions but I have declared log file in the main but later this might be a problem. Is there a standard logger function that can be call in all my functions so that I dont have to keep the logger global.

### ISSUE THREAD

**Issue by rishika2416** [Delgan/loguru#580]
```python
def timeit(func):
    def wrapped(*args, **kwargs):
        start = time.time()
        logger.info("Function '{}' starts",func.__name__)
        result = func(*args, **kwargs)
        end = time.time()
        logger.info("Function '{}'ends",func.__name__)
        logger.debug("Function '{}' executed in {:f} s", func.__name__, end - start)
        return result

    return wrapped
@timeit
@logger.catch
def area(s):
   a=s*s
   logger.info("area is")
   return a
@logger.catch
def primeter(s):
  p=s*4
  logger.info("perimeter is")
  return p
def main():
  area(4)
  perimeter(4)

if __name__ == "__main__":
        logger.remove()
        logger.add("Output/file.log", format="{time:YYYY-MM-DD at hh:mm:ss:zz} | {level} | {message}")
        main()
```

**Comment by Delgan** [comment]
Hi.

Can you elaborate about the problem you're afraid of facing in the future? The `logger` object is made to be global by design, so there isn't much you can do about this. You can create a wrapper class around the `logger` if you prefer, that's way you will just need to change if you ever replace Loguru with something else.

**Comment by rishika2416** [comment]
Hi if the server is down or in the middle of function execution if there is
an error from the server side Is it fine to keep the logger global will we
be able to debug and will the log file close automatically

**Comment by Delgan** [comment]
The file will be properly closed (see details here: https://github.com/Delgan/loguru/issues/570#issuecomment-1016411161). I'm not sure how it related to `logger` being global or not, though.
