### ISSUE TITLE
[Question] Is it possible to control effective terminal width/wrapping?

### ISSUE THREAD

**Issue by JSKenyon** [Delgan/loguru#583]
I am interested to know if there is some way to make log messages wrap at 80 characters for both stdout and a logfile. This can help enhance readability. 

Edit: I have scoured the docs and code but cannot find mention of the terminal width anywhere.

**Comment by Delgan** [comment]
Hi.

This is certainly possible by using a custom sink like so:

```python
import sys
from loguru import logger

def wrapping_sink(message):
    if len(message) > 80:
        chunks = (message[i:i + 80] for i in range(0, len(message), 80))
        message = "\n".join(chunks)
    sys.stderr.write(message)

logger.add(wrapping_sink)
```

There are some details you may need to consider (using `len(message)` is incorrect if the message contains `\n` and also ansi characters with `colorize=True` should not be counted), but it gives you an idea. :+1:

**Comment by JSKenyon** [comment]
Thanks!
