### ISSUE TITLE
How to log subprocess stdout/err

### ISSUE THREAD

**Issue by theunkn0wn1** [Delgan/loguru#584]
I am working with `asyncio.subprocess.create_subprocess_exec` and find myself wanting to redirect the subprocess output to a sink.

How can I achieve this?

**Comment by Delgan** [comment]
I think it will be difficult to log subprocess output "in live". However, you can certainly use [`communicate`](https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.asyncio.subprocess.Process.communicate) to retrieve and log sub-process output. Would that help you?

**Comment by theunkn0wn1** [comment]
I gave communicate a go, but it doesn't seem to be capturing any output!

**Comment by Delgan** [comment]
Are you able to share the code you tried please? You need also to create your process with `stderr=PIPE`.

**Comment by theunkn0wn1** [comment]
Functionally, this is what is being run
```py
    with logger.contextualize(cmd=cmd):
        logger.debug("Spawning {}[{}]", bin, cmd)
        proc = await asyncio.subprocess.create_subprocess_exec(
            *shlex.split(cmd),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE
        )
        stdout, stderr = await proc.communicate()
        logger.debug(stdout)
        logger.error(stderr)
```
  This unreliably captures the stdout and stderr of the invoked command, but as frequently doesn't.
  It also only produces two log records total, instead of a record for each line as the subprocess creates them.
  
  It would be far more convenient if Loguru supported handling the streams directly, or otherwise redirecting a suprocessies standard IO

**Comment by Delgan** [comment]
Thanks for the code sample. It works fine on my computer but displaying output in real time is a little more tricky. I think you should try to adapt [this example from the official documentation](https://docs.python.org/3/library/asyncio-subprocess.html#examples). In particular, you could use `proc.stdout.readline()` (in a loop) to get output line by line as desired.

This is not a problem really related to Loguru, so there isn't much I can do unfortunately. This looks more like a general problem on how to capture the output of a subprocess in Python (I found plenty of questions about this issue on StackOverflow). If we figure out a fully workable snippet, I could add it to the documentation though.

**Comment by Delgan** [comment]
I'm closing this ticket since I answered it. Let me know if you need more help.
