### ISSUE TITLE
[Question] Two loggers, change the first one to DEBUG at a later time

### ISSUE THREAD

**Issue by worthapenny** [Delgan/loguru#587]
Hi,

I have two loggers, 
a) `logger.add(sys.stdout,level='INFO',....)`
b) `logger.add("filePath",level='INFO',...)`

`block of codes...`

```python
# Somewhere else in the program I need to change the logging level for 
# "a", the first logger, to "DEBUG" completely, not just for one or two lines.
```

**So, how can I change the log level for the first one to say DEBUG?**

If I had just one logger, I suppose I can do `logger.level("DEBUG")`.

Many thanks.

**Comment by Delgan** [comment]
Calling `logger.add()` twice will create **two handlers** but there's still **one logger**.

In any case, it's not possible to dynamically update the `level` of an existing handler. You'll have to implement one of the workarounds described in the documentation: [Changing the level of an existing handler](https://loguru.readthedocs.io/en/stable/resources/recipes.html#changing-the-level-of-an-existing-handler).

The [`logger.level()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.level) method is not related and does not permit to modify the level of a handler, it's mainly used to create custom levels.

**Comment by worthapenny** [comment]
Thanks for the prompt response! Closed for now.
