### ISSUE TITLE
Question: how to log exception objects

### ISSUE THREAD

**Issue by theunkn0wn1** [Delgan/loguru#589]
I have exception objects that I have obtained outside of an exception handler. I would like to log these with their tracebacks, but it's not clear if this is possible.

logger.exception does not apply here since this is not an exception handler context.

**Comment by Delgan** [comment]
Hi. You can probably use [`opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt) to do that:

```python
logger.opt(exception=exc_object).error("Error message")
```

**Comment by theunkn0wn1** [comment]
That did the trick. Thanks!
