### ISSUE TITLE
How to disable logging of exception traceback?

### ISSUE THREAD

**Issue by MLNW** [Delgan/loguru#592]
Hey, I am using loguru together with rich. I just noticed that when I log exceptions via `logger.exception` the exception stack trace is logged twice. Once by loguru and once by rich.

I would like to only log it with rich so is there a way to disable the logging directly via loguru?

Here is the code I use to configure both rich and loguru:

```python
handler = RichHandler(
    console=console,
    rich_tracebacks=True,
)

logger.remove()
logger.add(handler, format=log_format, level=log_level)
```

I tried to set `catch=False, backtrace=False` but that did not help and I did not find anything else in the documentation.

**Comment by Delgan** [comment]
Hey. This is an interesting case. The 1st idea that comes to my mind would be to remove the `"{exception}"` part from Loguru's format. It is automatically added for convenience when `format` is a string, but you can disable this by using a formatting function instead.

```python
logger.add(handler, format=lambda _: log_format, level=log_level)
```

Does that help?

**Comment by MLNW** [comment]
I just tried it out but sadly it does not change anything about the situation.

**Comment by Delgan** [comment]
I tried and it looked to work fine:

![2022-02-17-192206_916x991_scrot](https://user-images.githubusercontent.com/4193924/154546001-6a0ec33d-906b-4ce3-9d95-eb08a0bd34c0.png)

Which different output are you expecting? Do you have a fully reproducible example maybe?

**Comment by MLNW** [comment]
You are right! Sorry, the wrong program was executed so the change didn't register.

Thanks for the fast replies!

**Comment by indigoviolet** [comment]
@Delgan I feel this should be addressed more comprehensively: it is a pretty hidden way of handling something commonly needed; plus if I use your `format=lambda` solution, all the nice default formatting is lost. Can you please consider an actual flag to turn off the traceback?

**Comment by Delgan** [comment]
Hi @indigoviolet.

To be honest I don't feel this an use case common enough to add a new configuration flag. Loguru provides a default exception formatting system. It is perfectly reasonable to want to customize it, but to do so, one has to go through a custom `format` just like many other customizations.

How the `format` argument works is explained [here](https://loguru.readthedocs.io/en/stable/api/logger.html#message) and an example of how to modify the formatting of exceptions can be found [here](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions). I may consider adding an easier way to format exceptions in the future.

You can also reduce verbosity of default exception by using `diagnose=False` and/or `backtrace=False`. Using a custom `format` does not mean nice formatting is lost, but you have to provide the colors as well (default format can be found [here](https://github.com/Delgan/loguru/blob/0f89a58d3279d31915224f329e90255e9c7f5449/loguru/_defaults.py#L34-L36)).
