### ISSUE TITLE
Duplicate log message in serialized json text field and record.message

### ISSUE THREAD

**Issue by aaksarin** [Delgan/loguru#594]
Hi. 
Thanks for great lib!
But I have a question.
We use loguru for simple logging in JSON format.
And when I enable serialization, text in log records is duplicated in text field and in record.message. 

```
logger.add(sink=sys.stdout, level=level, format="{message}", serialize=True)
logger.info(f"test")
foo  | {"text": "test\n", "record": {"elapsed": {"repr": "0:00:54.402913", "seconds": 54.402913}, "exception": null, "extra": {}, "file": {"name": "<input>", "path": "<input>"}, "function": "<module>", "level": {"icon": "??", "name": "INFO", "no": 20}, "line": 1, "message": "test", "module": "<input>", "name": "camunda_responder.settings", "process": {"id": 1, "name": "MainProcess"}, "thread": {"id": 140176902125376, "name": "MainThread"}, "time": {"repr": "2022-02-16 14:54:31.239496+03:00", "timestamp": 1645012471.239496}}}
```

Is there a way to disable this duplication?

And I think because of that logs take twice much space and double the size of each log message. For me this default is not obvious.
Thanks.

**Comment by Delgan** [comment]
Hi @aaksarin.

The `"text"` attribute represents the log formatted according to the `format` argument, while the `"message"` attribute is the raw message as passed to the logging function.

Maybe you can clear the `"text"` attribute by specifying an empty format like so:

```python
logger.add(sink=sys.stdout, level=level, format="", serialize=True)
```

**Comment by aaksarin** [comment]
Empty string in format almost solve this problem, there a still newline in text field but I think this solves double log message size problem and this should be enough.

```
>>> logger.add(sink=sys.stdout, level=level, format="", serialize=True)
foo  | 1
>>> logger.info("test message")
foo  | {"text": "\n", "record": {"elapsed": {"repr": "0:00:28.989323", "seconds": 28.989323}, "exception": null, "extra": {}, "file": {"name": "<input>", "path": "<input>"}, "function": "<module>", "level": {"icon": "??", "name": "INFO", "no": 20}, "line": 1, "message": "test message", "module": "<input>", "name": "camunda_responder.settings", "process": {"id": 1, "name": "MainProcess"}, "thread": {"id": 140499480377152, "name": "MainThread"}, "time": {"repr": "2022-02-17 09:58:12.398011+03:00", "timestamp": 1645081092.398011}}}
```

Thanks @Delgan 👍

**Comment by Delgan** [comment]
You're welcome. :+1:

You can also use a formatter function to get ride of the `"\n" (which is automatically added for convenience):

```python
logger.add(sink=sys.stdout, level=level, format=lambda _: "", serialize=True)
```

Alternatively, you can implement your own serializing sink:

```python
def sink(record):
    print(json.dumps(message.record, default=str))

logger.add(sink)
```
