### ISSUE TITLE
logger.catch to a specific handler

### ISSUE THREAD

**Issue by parad0x96** [Delgan/loguru#598]
Hello 
I'm wondering if there is a way to use `logger.catch()` to catch an exception in a desired `handler`.
Example:
```
def make_filter(name):
    def filter(record):
        return record["extra"].get("name") == name
    return filter

logger.add(sys.stderr, format="{time} {level} {message}", filter="my_module", level="INFO", filter=make_filter("my-handler"))
my_handler= logger.bind(name="my-sink")
logger.catch(name="my_handler")


```
Any way to do this properly ? thanks in advance

**Comment by Delgan** [comment]
Hi @parad0x96.

This is kind of possible using `bind()` and a custom `filter` added to your handlers. This is very similar to what you proposed, except you have to use the bound logger to call `catch()` (captured exception will be processed only handlers with same filtering name):

```python
import sys

from loguru import logger

def make_filter(name):
    def filter(record):
        return record["extra"].get("name") == name
    return filter

logger.remove()
logger.add(sys.stderr, format="{time} {level} {message}", level="INFO", filter=make_filter("my-handler"))


with logger.bind(name="my-handler").catch():
    1 / 0
```

**Comment by parad0x96** [comment]
> Hi @parad0x96.
> 
> This is kind of possible using `bind()` and a custom `filter` added to your handlers. This is very similar to what you proposed, except you have to use the bound logger to call `catch()` (captured exception will be processed only handlers with same filtering name):
> 
> ```python
> import sys
> 
> from loguru import logger
> 
> def make_filter(name):
>     def filter(record):
>         return record["extra"].get("name") == name
>     return filter
> 
> logger.remove()
> logger.add(sys.stderr, format="{time} {level} {message}", level="INFO", filter=make_filter("my-handler"))
> 
> 
> with logger.bind(name="my-handler").catch():
>     1 / 0
> ```

Yeah that makes sense thanks man.
