### ISSUE TITLE
multiple logger instance

### ISSUE THREAD

**Issue by matthoop** [Delgan/loguru#6]
hi, I read through the readme and api reference but didnot find out how to get multiple logger instances, like the standard `logging.getLogger('app.log')` `logging.getLogger('db.log')` `logging.getLogger('sub-process-task.log')` , each logger has their own handlers. Is there a way to do this?

**Comment by Delgan** [comment]
Hey @matthoop 

The Loguru design relies on one unique logger in charge of dispatching logs to (possibly multiple) handlers.

This is why there is no `getLogger()` function. If you need fine-grained control over logs processing, this should be done at the handler level. 
You can  possible use the `filter` attribute while registering a new handler. For example, `logger.start(sink, filter="app")` to log messages coming from `app` module and its child only (based on `__name__` value).

If you want to simulate named logger, you can alternatively do something like this at the start of your module: `logger = logger.bind(name="app.log")`.
Then, this `name` will be added to the `extra` dict of logged messages and accessible from the record. You can then use it wherever you want, for example for filtering: `logger.start(sink, filter=lambda record: record["name"] == "app.log")`.

**Comment by matthoop** [comment]
Thank you for your detailed explaination @Delgan . I get your point, it seems `filter` is the key to 'fanout' log records. 

Nice work :)
