### ISSUE TITLE
Notify error logs on exit (recipe)

### ISSUE THREAD

**Issue by Qazzquimby** [Delgan/loguru#601]
Originally this post was a question - then I figured out a solution while writing, and now it's sharing the solution in case it helps someone else (plus welcoming improvements). Feel free to add to the recipes page or completely ignore :)

When the program encounters an error, I'd like to be notified with the full log to properly debug it. 
Using the notifiers integration I can send myself the error messages themselves, but not the surrounding context of the rest of the log (eg, the version number and config of the program that's failing).
This approach sends the full log text when the program finishes running with at least one error.

```py
import notifiers
from loguru import logger

def set_encountered_error():
    global has_encountered_error
    has_encountered_error = True

#  ... Other logger setup
logger.add(lambda message: log_lines.append(message))
logger.add(lambda _: set_encountered_error(), level="ERROR")  # Set whichever level

try:
    # Your main function here
finally:
    if has_encountered_error:
        log = "".join(log_lines)
        notifiers.notify(...)  # Your notifier
```

**Comment by Delgan** [comment]
Hi @Qazzquimby, thanks for sharing. :+1:

You can also use a custom sink with a `stop()` method:

```python
class ErrorReporter:
    def __init__(self):
        self._log_lines = []
        self._has_encountered_error = False

    def write(self, message):
        self._log_lines.append(message)
        if message["level"].no >= 40:  # ERROR
            self._has_encountered_error = True

    def stop(self):
        if self._has_encountered_error:
            log = "".join(log_lines)
            notifiers.notify(...)
```

Note that keeping every message in  `_log_lines` can end up consuming a lot of memory.

Maybe you can use a file sink and send it using a custom `compression` function:

```python
logger.add("file.log", compression=lambda path: send_file(path))
logger.add(lambda _: set_encountered_error(), level="ERROR")
```
