### ISSUE TITLE
Make caplog pytest fixture either available from module in loguru or into a pytest plugin

### ISSUE THREAD

**Issue by mcarans** [Delgan/loguru#602]
Thanks for a great tool. The loguru caplog pytest fixture can be put into a module that is made available in conftest.py eg.
```python
from hdx.utilities.easy_logging import caplog
```
where the module hdx.utilities.easy_logging contains:
```python
@pytest.fixture
def caplog(caplog):
    class PropogateHandler(logging.Handler):
        def emit(self, record):
            logging.getLogger(record.name).handle(record)

    handler_id = logger.add(
        PropogateHandler(), format="{message} {extra}", level="TRACE"
    )
    yield caplog
    logger.remove(handler_id)
```

(Note that I changed it to take in caplog instead of _caplog otherwise it doesn't work using the import in conftest.py)

It would be great if the fixture were importable directly from a loguru module eg.
```python
from loguru.pytest import caplog
```

Even better would be if there was a pytest-loguru plugin on pypi which would simply need to be installed and hence no extra code would be needed in conftest.py.

**Comment by Delgan** [comment]
Hi @mcarans.

Actually, [the `caplog` snippet](https://loguru.readthedocs.io/en/stable/resources/migration.html#making-things-work-with-pytest-and-caplog) has been updated and no longer require sing the `PropagateHandler`:

```python
import pytest
from loguru import logger
from _pytest.logging import LogCaptureFixture

@pytest.fixture
def caplog(caplog: LogCaptureFixture):
    handler_id = logger.add(caplog.handler, format="{message}")
    yield caplog
    logger.remove(handler_id
```

I think it's simple enough and to be honest I would prefer adding sub-module to Loguru.

**Comment by mcarans** [comment]
@Delgan I've made a pytest plugin: https://github.com/mcarans/pytest-loguru. I tested it by adding git+git://github.com/mcarans/pytest-loguru.git#egg=pytest-loguru to my requirements.txt in another project that uses caplog. I was wondering if you'd like to take over the plugin?

**Comment by Delgan** [comment]
Oh, this is interesting, thanks for creating it!

I prefer not to become the official maintainer but if there is a need for my help or if I have ideas for improvement, I will try to contribute.

I'll also probably update the documentation to mention your package. :+1:

**Comment by mcarans** [comment]
Ok sure I will release it as a package on PyPI.

**Comment by mcarans** [comment]
Here is the link: https://pypi.org/project/pytest-loguru/0.1.0/

The coverage is actually 100% but the coverage tool seems to get confused by the pytest.fixture decorator.

**Comment by Delgan** [comment]
Confirmed working and docs updated, thanks for your time! :+1:

**Comment by mcarans** [comment]
@Delgan I don't see the documentation updates here: https://loguru.readthedocs.io/en/stable/resources/migration.html

**Comment by Delgan** [comment]
It's not yet on `stable` because I didn't make any release, but you can find it on the `latest` branch: https://loguru.readthedocs.io/en/latest/resources/migration.html#making-things-work-with-pytest-and-caplog
