### ISSUE TITLE
Log output is not coloured in GitHub Actions

### ISSUE THREAD

**Issue by mcarans** [Delgan/loguru#604]
I have found that log output is coloured when running locally but not when running through GitHub Actions. Is there something I need to do to get colour in GitHub Actions?

I noticed in a comment here: https://stackoverflow.com/questions/64111780/python-based-colored-logging-in-github-runner-with-ubuntu-latest that "humanfriendly.terminal.terminal_supports_colors actually returns False on the github runner (ubuntu-latest)". Could that be the problem?

GitHub Actions does support colour eg. from another logger:
https://github.com/OCHA-DAP/hdx-scraper-covid-viz/runs/5296688697?check_suite_focus=true

![screenshot-github com-2022 02 24-17_15_46](https://user-images.githubusercontent.com/3799212/155457038-65da3686-58c6-49ef-b418-265941876ac4.png)

**Comment by Delgan** [comment]
By default, Loguru tries to automatically detect whether or not the terminal supports colors. Maybe this is a false-negative case.

You can force colored output by adding you sink with `colorize=True`. Does it work better?

**Comment by mcarans** [comment]
@Delgan Thank you, that worked eg. see [this](https://github.com/OCHA-DAP/hdx-scraper-unhcr-microdata/runs/5352574985?check_suite_focus=true)

You could fix the false-negative case by detecting the environment variable:
`GITHUB_ACTIONS`  Always set to true when GitHub Actions is running the workflow. You can use this variable to differentiate when tests are being run locally or by GitHub Actions. (from [here](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables))

**Comment by Delgan** [comment]
Great, I will do that, thanks. :+1:

Why are some logs not colored in the Github Actions output you shared, though? Is it due to `InterceptHandler` or something?

**Comment by mcarans** [comment]
That script is using the standard logger and then imports another library of mine where the `InterceptHandler` is set up so I guess it is because of that.

**Comment by mcarans** [comment]
I guess it would go here: https://github.com/Delgan/loguru/blob/68616485f4f0decb5fced36a16040f5e05e2842f/loguru/_colorama.py#L10-L11

```python
        if any(x in os.environ for x in ("PYCHARM_HOSTED", "GITHUB_ACTIONS")):
            return True
```

**Comment by Delgan** [comment]
Fixed on `master` branch. :+1:
