### ISSUE TITLE
No fully descriptive exceptions output from pytest when using standard logging + InterceptHandler

### ISSUE THREAD

**Issue by mcarans** [Delgan/loguru#605]
I am unable to get fully descriptive exceptions when running a test through pytest that uses the standard logger with InterceptHandler. 

I do get fully descriptive exceptions for the loguru logger when using pytest. I do get fully descriptive exceptions for the standard logger with InterceptHandler when not running a pytest.

Also, if I create an errors.log file logger, it does not seem to be passed the errors that come from standard logging and only has the errors from loguru.

Here is how I have set up the loggers:
```python
def setup_logging(error_file: bool = False) -> None:
    """Setup logging configuration. intercepts standard logging and outputs errors to
    a file.

    Args:
        error_file (bool): Whether to output errors.log file. Defaults to False.

    Returns:
        None
    """
    logger.add(stdout, colorize=True, backtrace=True, diagnose=True)
    if error_file:
        logger.add(
            "errors.log",
            level="ERROR",
            mode="w",
            backtrace=True,
            diagnose=True,
        )

    class InterceptHandler(logging.Handler):
        def emit(self, record):
            # Get corresponding Loguru level if it exists
            try:
                level = logger.level(record.levelname).name
            except ValueError:
                level = record.levelno

            # Find caller from where originated the logged message
            frame, depth = logging.currentframe(), 2
            while frame.f_code.co_filename == logging.__file__:
                frame = frame.f_back
                depth += 1

            logger.opt(
                colors=True,
                record=True,
                depth=depth,
                exception=record.exc_info,
            ).log(level, record.getMessage())

    logging.basicConfig(handlers=[InterceptHandler()], level=logging.NOTSET)
```

Here is the test (which uses the pytest-loguru plugin I created and mentioned [here](https://github.com/Delgan/loguru/issues/602#issuecomment-1053668095)):
```python
"""Logging Tests"""
import logging

from loguru import logger

from hdx.utilities.easy_logging import setup_logging

standard_logger = logging.getLogger(__name__)


setup_logging(error_file=True)


class TestLogging:
    def test_setup_logging(self, caplog):
        with caplog.at_level(logging.ERROR):
            text = "This is an error!"
            standard_logger.error(text)
            assert text in caplog.text

            text = "Division by zero!"

            def divide(a, b):
                return a / b

            try:
                divide(1, 0)
            except ZeroDivisionError:
                standard_logger.exception(text)

            assert text in caplog.text

            text = "Another zero error!"
            try:
                divide(2, 0)
            except ZeroDivisionError:
                logger.exception(text)

            assert text in caplog.text
```

**Comment by mcarans** [comment]
@Delgan I'm not sure if this is feasible but I was wondering if loguru could more directly take over the logging from the standard logger? For example, the previous logger I used, colorlog, does it like this:
```python
    """Call ``logging.basicConfig`` and override the formatter it creates."""
    logging.basicConfig(**kwargs)
    logging._acquireLock()  # type: ignore
    try:
        handler = logging.root.handlers[0]
        handler.setFormatter(
            colorlog.formatter.ColoredFormatter(
                fmt=format,
                datefmt=datefmt,
                style=style,
                log_colors=log_colors,
                reset=reset,
                secondary_log_colors=secondary_log_colors,
                stream=kwargs.get("stream", None),
            )
        )
    finally:
        logging._releaseLock()  # type: ignore
```

(from https://github.com/borntyping/python-colorlog/blob/main/colorlog/wrappers.py#L54-L71)

**Comment by Delgan** [comment]
Hey @mcarans.

You're not seeing the messages from the standard logger because `pytest` adds its own handler thus [`logging.basicConfig()`](https://docs.python.org/3/library/logging.html#logging.basicConfig) won't add the `InterceptHandler`:

> This function does nothing if the root logger already has handlers configured, unless the keyword argument _force_ is set to `True`.

As explained in the `logging` documentation you may will surely get the desired result by using `force=True`. I may need to update the documentation to mention this caveat.

I'm not sure using a custom `Formatter` would help because in the end, we need to use `logger.log()` API so Loguru can handle the message consistently (formatting, filtering, thread safety, etc.). Using `Formatter` won't work if there is no standard handler registered and it would result in logs being duplicated by standard handler and Loguru one.

**Comment by mcarans** [comment]
Brilliant, thanks! `force=True` fixed it. I think it would be helpful to include that parameter in the InterceptHandler example in the docs.

**Comment by Delgan** [comment]
Docs updated.
