### ISSUE TITLE
Print log one process after another ( print log together in one process)

### ISSUE THREAD

**Issue by ahuan2616** [Delgan/loguru#606]
Hi @Delgan.
Thanks for great lib!
But I have a question.
We know that enqueue=True is for multiprocess-safe.   Is there a way to print log one process after another ? ( print log together in one process). Because a mixed log output in multiprocess is difficult to debug.
I have checked the document, but have no idea about this issue.

Thanks.

**Comment by Delgan** [comment]
Hi @ahuan2616.

If only one handler exists, logs shouldn't be mixed theoretically. Are you able maybe to share the logging configuration you're using?

**Comment by ahuan2616** [comment]
Hi @Delgan,
Thanks a lot for your suggestion, I will try it.
But synchronize the logs will be helpful if there is a large amount of logs in each process,

**Comment by Delgan** [comment]
You can maybe use one different file handler per process.

Synchronizing the logs the way you propose implies storing them temporarily which may saturate the computer memory.

Otherwise you'll have to implement your own sink implementation.

**Comment by Delgan** [comment]
I am closing this ticket as I think I have answered it. Feel free to re-open it otherwise.
