### ISSUE TITLE
duplicate logging records when using in muti-thread programmer

### ISSUE THREAD

**Issue by BL-Lac149597870** [Delgan/loguru#613]
import time
    import argparse
    import threading
    import numpy as np
    from easydict import EasyDict
    from loguru import logger

    class Ground:
        def __init__(self):
            self.QE = 9
            self.QMIN = self.QE
            self.QMAX = self.QE
            self.groundIndex = 0
            self.infoma = {}
        
        def reset(self):
            self.QMIN = self.QE
            self.QMAX = self.QE

        def add(self):
            self.groundIndex += 1

        @property
        def index(self):
            return self.groundIndex

    class Node:
        def __init__(self, ground, args):
            self.ground = ground
            self.index = self.ground.index
            self.ground.add()
            self.processID = args.processID
            self.threadID = args.threadID

        def log(self):
            logger.info('进程%s线程%s节点%s'%(self.processID,self.threadID,self.index))

    class myThread (threading.Thread):
        def __init__(self, args):
            threading.Thread.__init__(self)
            self.args = args
            self.threadID = args.threadID
            self.processID = args.processID
        def run(self):
            logger.add('./'+str(self.threadID)+ '.log', enqueue=True)
            logger.info ("开始进程:%s 线程:%s"%(self.processID, self.threadID))
            time.sleep(np.random.randint(5, size=1)[0])
            MCTSWrapper(self.args)
            logger.info ("退出进程:%s 线程:%s"%(self.processID, self.threadID))

    def MCTSWrapper(args):
        ground = Ground()
        pool = []
        for i in range(10):
            pool.append(Node(ground, args))
        
        for t in pool:
            t.log()

    if __name__ == '__main__':
        parser = argparse.ArgumentParser()
        parser.add_argument('-k', type=int, default=0)
        args = parser.parse_args()

        num_thread = 3
        num_GPUs = 2
        threadPool = []
        for i in range(num_thread):
            params = EasyDict({
                'k': args.k * num_thread + i,
                'device': str(args.k % num_GPUs),
                'source': 'new',
                'max': True,
                'st': 50,
                'threadID': i,
                'processID': args.k
            })
            threadPool.append(myThread(params))

        for t in threadPool:
            t.start()
        
        for t in threadPool:
            t.join()
[0.log](https://github.com/Delgan/loguru/files/8198073/0.log)
[2.log](https://github.com/Delgan/loguru/files/8198075/2.log)
[1.log](https://github.com/Delgan/loguru/files/8198076/1.log)

Why each log file contains different thread logging information?

**Comment by BL-Lac149597870** [comment]
> The handlers your added aren't filtering logs. They are added to the global `logger` object, which means they receive all logged message regardless of the thread. You have to implement a workaround using `bind()` and `filter` as described in the documentation: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers).
> 
> Later a `new()` method will be added to ease this process.

It works for me! Thank you!!!

**Comment by m986883511** [comment]
another way

```
from loguru import logger


def sink(message):
    ip = message.record["extra"]["ip"]
    with open(f'{ip}.log', 'a') as file:
        file.write(message)


logger.add(sink)
logger.add('ip.log')


class Worker:
    def __init__(self, ip):
        self.ip = ip
        self.log(ip)

    def log(self, msg):
        logger.bind(ip=self.ip).info(f'ping {msg}')


Worker('192.168.2.1')
Worker('192.168.2.2')
Worker('192.168.2.3')

```
