### ISSUE TITLE
Custom a filter, When the added field value is none or '', the whole log will not be printed

### ISSUE THREAD

**Issue by slowchen** [Delgan/loguru#615]
I customized a filter for loguru, named `correlation_id_filter`, In this filter, I added a field `correlation_id` on record, 
the value is `correlation_id.get()`, When the value is `None` or `''`, the whole log will not be printed

```python
import sys

from asgi_correlation_id.context import correlation_id
from loguru import logger


def correlation_id_filter(record):
    # record['correlation_id'] = correlation_id.get()
	record['correlation_id'] = None or ''
    return record['correlation_id']


def get_logger():
    logger.remove()
    fmt = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <light-cyan>[{correlation_id}]</light-cyan> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    logger.add(sys.stdout, level='DEBUG', format=fmt, filter=correlation_id_filter)

    return logger


log = get_logger()

print('===========log start===========')
log.info('test log')
print('===========log end===========')
```

When I execute the program, the output is as follows, no log output
```
/Users/slowchen/.virtualenvs/fastapi/bin/python /Users/slowchen/workspace/FastApi/tianya-fastapi/app/mainw.py
===========log start===========
===========log end===========

Process finished with exit code 0
```

when i  update `record['correlation_id'] = 'testesttest'` and execute the program,  the output is as follows
```python
def correlation_id_filter(record):
    # record['correlation_id'] = correlation_id.get()
    record['correlation_id'] = 'testesttest'
    return record['correlation_id']
```
```
/Users/slowchen/.virtualenvs/fastapi/bin/python /Users/slowchen/workspace/FastApi/tianya-fastapi/app/mainw.py
===========log start===========
2022-03-12 22:27:42.813 | [testesttest] | INFO     | __main__:<module>:29 - test log
===========log end===========

Process finished with exit code 0
``` 

After debugging, I found it in / site packages / loguru/_handler.py:105 return directly, Is this a bug or is it designed like this?
<img width="715" alt="image" src="https://user-images.githubusercontent.com/17584002/158022035-09669e66-7c25-4887-afef-00d53d6fdddd.png">

**Comment by Delgan** [comment]
Hi @slowchen.

I don't know exactly what you're trying to achieve, but any `filter` function is supposed to return `True` (if message is to be logged) or `False` (if message is to be discarded). The current implementation evalutes the returned value as ["truthy" or "falsy"](https://www.freecodecamp.org/news/truthy-and-falsy-values-in-python/) which explains the behavior you're observing when your `filter` function returns `None` or `""` (both being interpreted as `False`). This is the expected behavior. If you just need to modify the `record`, you can let your `filter` function to return `True` in all cases.

**Comment by slowchen** [comment]
Ok, thank you for your reply. I know what I should do. Have a nice weekend
