### ISSUE TITLE
How to test loguru logger with unittest?

### ISSUE THREAD

**Issue by fredrikaverpil** [Delgan/loguru#616]
I've got a project which is not using pytest. How can I successfully assert log statements made by loguru using unittests?

For example, I've got:

```python
# test_loguru.py

import contextlib
import io
from unittest import TestCase

from loguru import logger


class LoggerTest(TestCase):
    def test_logger_stderr(self):
        f = io.StringIO()
        with contextlib.redirect_stderr(f):
            logger.info("loguru log right here")

        self.assertEqual("loguru log right here\n", f.getvalue())

```

Running the test reveals I'm unsuccessful in capturing the loguru output:

```bash
$ python -m unittest test_loguru.py
2022-03-14 15:01:40.597 | INFO     | test_loguru:test_logger_stderr:12 - loguru log right here
F
======================================================================
FAIL: test_logger_stderr (test_loguru.LoggerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fredrik/code/repos/logger/test_loguru.py", line 14, in test_logger_stderr
    self.assertEqual("loguru log right here\n", f.getvalue())
AssertionError: 'loguru log right here\n' != ''
- loguru log right here


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
```

**Comment by fredrikaverpil** [comment]
You can see how this works fine:

```python
import contextlib
import io
import sys
from unittest import TestCase


class LoggerTest(TestCase):
    def test_logger_stderr(self):
        f = io.StringIO()
        with contextlib.redirect_stderr(f):
            print("printing here", file=sys.stderr)

        self.assertEqual("printing here\n", f.getvalue())

```

```bash
$ python -m unittest test_loguru.py -v
test_logger_stderr (test_loguru.LoggerTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

**Comment by fredrikaverpil** [comment]
So the issue here seems to be that the `unittest` runner replaces `sys.stdout`/`sys.stderr` before the testing starts.

I went with this approach, where I create a context manager heavily inspired by [this stackoverflow answer](https://stackoverflow.com/a/63678561/2448495):

```python
class CaptureLogger:
    """Context manager to capture log streams

    Args:
        logger: logger object

    Results:
        The captured output is available via `self.out`

    """

    def __init__(self, logger):
        self.logger = logger
        self.io = StringIO()
        self.sh = logging.StreamHandler(self.io)
        self.out = ""

    def __enter__(self):
        try:
            # try standard logging
            self.logger.add(self.sh)
        except AttributeError:
            # try loguru logging
            self.logger.add(self.sh)
        return self

    def __exit__(self, *exc):
        try:
            # try standard logging
            self.logger.removeHandler(self.sh)
        except AttributeError:
            # try loguru
            self.logger.remove()

        self.out = self.io.getvalue()

    def __repr__(self):
        return f"captured: {self.out}\n"
```

**Comment by fredrikaverpil** [comment]
Very nice, this is a lot cleaner! 😃 

I'm also thinking I'll add in an argument `format` (with some sane default), so I can decide what elements of the log I need to test. Most of the time I don't want to bother about the datetime string for example.

```python
from contextlib import contextmanager

@contextmanager
def capture_logs(format="{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} - {message}"):
    """Capture loguru-based logs."""
    output = []
    handler_id = logger.add(output.append, format=format)
    yield output
    logger.remove(handler_id)

```

Would be great to have this in the docs, yes! 😄

**Comment by Delgan** [comment]
Good point, I had forgotten that the format had to be adjusted as well!

I added the snippet to the documentation: [Replacing `assertLogs()` method from `unittest` library](https://loguru.readthedocs.io/en/latest/resources/migration.html#replacing-assertlogs-method-from-unittest-library).

Thanks for bringing this to my attention. :+1:

**Comment by dhdaines** [comment]
Could you please provide a *usage example* for the snippet above, for the following reasons:

1. It doesn't actually work like [`assertLogs`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertLogs).  Mostly, yes, but not exactly!
2. It isn't all that useful to just say "it returns a list of messages".  They are magical strings (or, actually, `loguru.handler._Message` objects, I guess?) with `record` attributes.  In most cases you probably just want to do `self.assertIn("some error", "".join(output))` for instance.  A link to https://loguru.readthedocs.io/en/latest/api/logger.html#message would be greatly appreciated in the FAQ.

I know this is obvious to you because you wrote `loguru` :) and it is easy once you get used to it, but it is not obvious to those of us who are used to the standard logging module and suddenly are confronted with someone's code using `loguru` which behaves mysteriously.

**Comment by Delgan** [comment]
@dhdaines Sorry for any confusion. I've considered your comment and made the following updates to the documentation:

* Included a new [Replacing `LogRecord` objects](https://loguru.readthedocs.io/en/latest/resources/migration.html#replacing-logrecord-objects) section to explain that the record is an attribute of the message.
* Added a usage example in the [Replacing `assertLogs()` method from `unittest` library](https://loguru.readthedocs.io/en/latest/resources/migration.html#replacing-assertlogs-method-from-unittest-library) section.

I hope this clears things up.

**Comment by Hadar933** [comment]
One comment on the suggested `capture_logs` - It is not a class method _on purpose_, namely, you cannot call it with `self.capture_logs(...)`, as the `level` variable will be assigned wrongly with `self`. To use `capture_logs` as a class method, is should be a static method. 
Concretely - 
```
    @staticmethod
    @contextmanager
    def capture_logs(level="INFO", format="{level}:{name}:{message}"):
        """Capture loguru-based logs."""
        output = []
        handler_id = logger.add(output.append, level=level, format=format)
        yield output
        logger.remove(handler_id)
```

**Comment by rjurney** [comment]
For `pytest` users, here's an equivalent:

```python
@pytest.fixture
def capture_logs():
    logger = MyCustomLogger.get_logger()
    output = []
    handler_id = logger.add(output.append)
    yield output
    logger.remove(handler_id)


def test_logger(capture_logs):
    logger = MyCustomLogger.get_logger()
    logger.error("Error happened :(")
    print(capture_logs)
```

And it prints your log messages.
