### ISSUE TITLE
MPI-compatible logger

### ISSUE THREAD

**Issue by x94carbone** [Delgan/loguru#618]
I've found the need for an MPI-compatible logger in my own projects. I've been using the standard `logging` module and at one point wrote a pretty crude wrapper for this, but I only just found this project and am very excited others had the idea to write an alternative to the `logging` module to make it more user friendly.

A quick search of the open and closed issues, and the documentation, for keyword "MPI" yielded nothing, hence my question. If this feature already exists I apologize for the inconvenience (but please point me to it)!

My proposal is simple: some API compatible with `mpi4py` that does something like this in e.g. someone's `__init__.py`:

```python
from loguru import logger
from mpi4py import MPI

logger.set_mpi_logger(MPI.COMM_WORLD)
logger.log_only_on_rank_0 = True
```

This is akin to what I've done in my own custom wrappers. Really helps to have this kind of compatibility. Obviously the user could customize whatever settings they wanted to.

Thoughts?

Also an aside: this library is _amazing_. Wonderful job.

**Comment by Delgan** [comment]
Hi @x94carbone, glad you like Loguru. :)

An MPI handler is too specific and complex to be added to Loguru as a built-in.

However, maybe can you achieve the desired effect with a custom sink?

```python
from mpi4py import MPI

comm = MPI.COMM_WORLD
def mpi_sink(message):

**Comment by Delgan** [comment]
Hi @x94carbone, glad you like Loguru. :)

An MPI handler is too specific and complex to be added to Loguru as a built-in.

However, maybe can you achieve the desired effect with a custom sink?

```python
from mpi4py import MPI
from loguru import logger

comm = MPI.COMM_WORLD

def mpi_sink(message):
    comm.send(message)

logger.add(mpi_sink)
```

Also, Loguru is compatible with standard [`logging.Handler`](https://docs.python.org/3/library/logging.html#handler-objects) so maybe you can re-use what you already developped:

```python
handler = MPIHandler()
logger.add(handler)
```

**Comment by x94carbone** [comment]
That's fair. I appreciate you considering the idea.

Before I close the issue, just to be clear, I only mean a way to ensure that the logger logs things at certain levels, at certain ranks. Your example above seems to imply loggers _communicating_ via the MPI protocol. That's not quite what I have in mind and I agree it's well outside the scope of Loguru. In my proposal, the only information Loguru would need from the communicator is the rank and world size.

- For example, in an MPI application, Loguru with default settings will run identically on every MPI rank. This is expected behavior, but will probably lead to a ton of unnecessary information being logged (e.g. identical copies of "initializing ClassXX at time YY").
- If a communicator is added, however, the user could then configure the logger so that, e.g, rank 0 outputs all logging levels, but ranks > 0 output only the debug level and to a different stream. The argument being that ranks > 0 are often used as "worker" processes and at the very least it makes sense to split up the streams.

If you feel it's still outside the scope of Loguru I accept that!

**Comment by Delgan** [comment]
To be honest I'm not familiar at all with the MPI protocol. Your suggestion sounds very abstract to me. But that's ok, that means I can surely learn some interesting new stuff. :)

I don't understand how you intend to use the logger other than as a tool to communicate the logs of your application. What would not be possible using a custom sink and possible `filter` function? Do you need both server and client handlers, similarly to using a socket: [Sending and receiving log messages across network or processes](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes)?

**Comment by x94carbone** [comment]
> To be honest I'm not familiar at all with the MPI protocol. Your suggestion sounds very abstract to me. But that's ok, that means I can surely learn some interesting new stuff. :)

No worries. I can try to give a very brief explanation. MPI is a communications protocol between different processes. When you do e.g. `python3 my_script.py` you're spawning a process, the script for which is contained in `my_script.py`. If you do something like mpiexec -n X python3 my_mpi_script.py`, you actually spawn `X` processes (dictated by the code under the hood of `mpiexec`). Each of these is identical instances of `my_mpi_script.py`, but each is assigned a unique _rank_. This rank differentiates the processes, and certain rules are put in place in the code to determine the behavior as a function of rank.

Take a very simple case, where you have a very long list and want to multiply every instance of that list by 2. I could have an MPI script in which each of e.g. 4 process reads the list from disk, but each of the processes only takes a portion of the list to multiply by 2. Then, the processes can communicate to assemble the list, and only process 0 will save the new list back to disk. This kind of parallelism can be achieved much more easily with the `multiprocessing` module, but it's just a simple case to demonstrate the idea.

One can imagine a world in which you wouldn't want each process logging the identical thing. Instead, only rank 0 needs to log information like "read list from disk". Even better, the logger can print the rank of the process after e.g. the traceback, for better-resolved debugging for MPI processes.

> I don't understand how you intend to use the logger other than as a tool to communicate the logs of your application. 

This is precisely how I would intend to utilize it, but not by sending messages between different processes via the MPI communicator. That's definitely not what I'm proposing.

> What would not be possible using a custom sink and possible filter function? Do you need both server and client handlers, similarly to using a socket: [Sending and receiving log messages across network or processes](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes)?

I'm not sure about using sockets or server/client handlers-- it's way simpler than that. What I'm proposing is actually quite concrete. You can think of it this way: it's like a filter, but the filter is not a function of the message, it's a function of some other variable called the MPI rank. 

This is already achievable with the infrastructure there already is, but this extra layer of abstraction will make it easier for the user, and more features could be added in a rigorous fashion. The simplest example I can think of is this, which could be easily added to the existing software there is in Loguru:

```python3
# In e.g. a package's __init__
from mpi4py import MPI
from loguru import logger

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

# Dumb example: ignore logging completely unless on rank 0
if rank != 0:
    logger.remove(0)
```

A better (hypothetical) example use case: configure Loguru's logger to actually output the MPI rank with every logged message:

```python3
from mpi4py import MPI
from loguru import logger

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

# Unsure if the functionality exists to use a prefix for every logged message,
# but let's pretend it does
logger.set_global_prefix(rank)
```

A very simple change which could make it much easier to configure loggers for MPI processes.

Please don't hesitate to ask any followup questions if you should have them!

**Comment by x94carbone** [comment]
@Delgan Any other thoughts on this? If you feel it's out of scope please feel free to either:
1. Close the issue
2. Close the issue, and let me know if you'd be open to a future pull request with the demonstrated feature

**Comment by Delgan** [comment]
Hi @x94carbone, sorry for the late answer.

Thank you for taking the time to write a detailed explanation about MPI. I understand better what this is about, especially the rank principle.

I prefer to rely on existing functionalities rather than adding new ones because Loguru must remain minimal and must not introduce in its core more dependencies like MPI. It is hopefully possible to design a utility class to facilitate the integration of this protocol with MPI that one will be able to re-use for MPI projects.

For example, the `set_global_prefix()` method you're suggesting echoes the `extra` attribute of the existing [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) method. We could also rely use the rank to set the logging level.

```python
import sys
from mpi4py import MPI
from loguru import logger

class LoggingHelperMPI:

    def __init__(self, rank):
        self._rank = rank

    def configure(self, output=sys.stderr):
        levels = {0: "TRACE", 1: "DEBUG", 2: "INFO"}
        format_ = "[{level}][{extra[rank]}] {message}\n{exception}"
        logger.configure(
            extra={"rank": rank},
            handlers=[{"sink": output, "format": format, "level": levels[rank]}],
        )

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
helper = LoggingHelperMPI(rank)
helper.configure()
```

We could certainly imagine other features based on a custom `filter` argument for example. I would rather do it this way. It can easily be published on PyPI to ease re-usability.  I am willing to support you if you need help with some of the features you had in mind.

**Comment by x94carbone** [comment]
@Delgan no worries, thanks for the response.

I agree in principle with everything you're saying, and I respect the design decision to not include core modules e.g. `mpi4py`. Indeed, everything I am suggesting can be accomplished with a combination of your code and mine.

Thanks for considering the suggestion!
