### ISSUE TITLE
[QUESTION] How does Loguru behave (sink-resolving) in a testing environment?

### ISSUE THREAD

**Issue by kaasbroek** [Delgan/loguru#619]
**Context:**
I'm working on logger-configuration in a private project that's intended to act like an SDK.  
This means configuration isn't something I can dead-set for all future users, I wish to allow them flexibility & catch mistakes early on.  

I'm quickly testing the implementation but seem to run into behaviour I can't quite explain and don't find mentioned in the docs.  
This ticket is meant to clarify whether it's an intentional Loguru thing or wheter I should look somewhere else.

**Versions:** 
Python 3.6
Loguru 0.5.3
Pytest 6.2.4

**Problem:**
Rather than pytest suppressing the output, loguru changes the sink to prevent logging output from leaking through.  
This makes it difficult to test whether my configuration-resolving is working or not.  

I would expect this to work out of the box
```python
# python -m pytest test_file.py

import sys
import json

from loguru import logger


def test_demo_purpose():
    # Default should be stderr -> https://loguru.readthedocs.io/en/stable/overview.html#ready-to-use-out-of-the-box-without-boilerplate
    default_sink = logger._core.handlers[0].__dict__["_sink"].__dict__["_stream"].name
    assert default_sink == "<stderr>"

    cfg = {
        "sink": sys.stdout,
    }
    logger.remove()
    logger.add(**cfg, format="Some formatting", level="DEBUG")
    custom_sink = logger._core.handlers[1].__dict__["_sink"].__dict__["_stream"].name
    assert custom_sink == "<stdout>"
```
Actual behaviour:
```
============================= test session starts ==============================
platform linux -- Python 3.6.13, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
plugins: celery-0.0.0a1
collected 2 items

../test_loguru.py F.                                                     [100%]

=================================== FAILURES ===================================
______________________________ test_demo_purpose _______________________________

    def test_demo_purpose():
        # Default should be stderr -> https://loguru.readthedocs.io/en/stable/overview.html#ready-to-use-out-of-the-box-without-boilerplate
        default_sink = logger._core.handlers[0].__dict__["_sink"].__dict__["_stream"].name
>       assert default_sink == "<stderr>"
E       AssertionError: assert '<_io.FileIO ...closefd=True>' == '<stderr>'
E         - <stderr>
E         + <_io.FileIO name=9 mode='rb+' closefd=True>

../test_loguru.py:10: AssertionError
=========================== short test summary info ============================
FAILED ../test_loguru.py::test_demo_purpose - AssertionError: assert '<_io.Fi...
========================= 1 failed, 1 passed in 0.09s ==========================
```

This works again when I run with `pytest -s` or when I interrupt the flow with a `pdb.set_trace()` statement.

Couldn't find the check for this in the codebase so I'm not entirely sure this is Loguru-specific.
Is this behaviour intentional? Can it be documented or mentioned somewhere?

**Comment by Delgan** [comment]
Hi @kaasbroek.

It is possible that `pytest` replaces `sys.stderr` with a `io.FileIO` in order to capture your program output. That would explain why you don't get the desired `"<stderr>"` display, although the added handler is `sys.stderr`.

Note that accessing fields like `logger._core` isn't part of the public API so I don't recommend basing tests on this.

**Comment by kaasbroek** [comment]
Hi @Delgan,

Thanks for the response. Didn't realize Pytest would redirect the logging for the Loguru module as well, would certainly explain why digging through the source code here doesn't show any clear leads.

I realize the `logger._core` isn't part of public library, but this seems to be the only way to test for the proper sinks being attached. 
Do you have a better way, because I'm not fond of this either 👍

**Comment by Delgan** [comment]
What about using [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html) to mock the `logger` and later check that `.add()` is called with `sys.stderr`?

It may require some changes to your code but it is the only reliable way to test this, I think.

**Comment by kaasbroek** [comment]
Thanks! This has been helpful as it assured the problem was not where I thought they were.
Wrt mock the logger, this is what I usually do but don't do here as it wouldn't be fair to the cases I'm testing.  

If the public API supports features that would allow me to check whether the custom formatter/sink work etc, I will definitely use that, but for now mocking isn't the way to go for me in these specific cases I'm dealing with.

Thanks again, I will close this as it's irrelevant :)
