### ISSUE TITLE
Question: Docs about provided sinks

### ISSUE THREAD

**Issue by fkromer** [Delgan/loguru#624]
It would be great to have an overview about available sinks like in the [serilog docs (provided sinks)](https://github.com/serilog/serilog/wiki/Provided-Sinks). What‘s in the docs right now is technically correct. But from an end user perspective one is looking for an overview list usually.

- [AsyncSink](https://github.com/Delgan/loguru/blob/master/loguru/_simple_sinks.py#L59)
- [CallableSink](https://github.com/Delgan/loguru/blob/master/loguru/_simple_sinks.py#L108)
- [FileSink](https://github.com/Delgan/loguru/blob/master/loguru/_file_sink.py#L138)
- [StandardSink](https://github.com/Delgan/loguru/blob/master/loguru/_simple_sinks.py#L29)
- [StreamSink](https://github.com/Delgan/loguru/blob/master/loguru/_simple_sinks.py#L8)

**Comment by Delgan** [comment]
Hi @fkromer.

The sinks you linked aren't actually meant to be public. Those are implementation details. The `sink` argument of the [`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) method accepts different types of objects (not `Sink` classes) which are listed [in the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#sink).
