### ISSUE TITLE
Feature request: Loguru Contrib

### ISSUE THREAD

**Issue by fkromer** [Delgan/loguru#625]
What do you think about introducing Loguru Contrib to share custom sinks... I mean an equivalent to [Serilog Contrib](https://github.com/serilog-contrib).

loguru sinks I‘ve came across so far:
- [gcloud_loguru](https://github.com/cedar101/gcloud_loguru)

**Comment by Delgan** [comment]
Hi.

To be honest I don't think Loguru is popular enough or that the sinks are complex enough to justify creating a Github Organization, especially since this implies having to guarantee their maintainability. :grimacing:

**Comment by fkromer** [comment]
> especially since this implies having to guarantee their maintainability. 😬

I get the point 😄
