### ISSUE TITLE
log length is limited in the console 

### ISSUE THREAD

**Issue by linpan** [Delgan/loguru#627]
<img width="1786" alt="WX20220329-164416@2x" src="https://user-images.githubusercontent.com/6077601/160571779-09d81d50-2bd5-4afa-9aad-cb5820069cfa.png">

as screenshot,  log text ( line start string : '2022-03-29 16:41:24.840 | INFO     | optimus.agents.aerospace.aero:get_large_glm:17')should  be  two lines, but only show one .  

IDE: pycharm terminal

**Comment by Delgan** [comment]
Loguru doesn't truncate lines (apart from traceback) so this is most likely an issue with your terminal.

**Comment by linpan** [comment]
as screenshot, print message is okay [two lines]

**Comment by Delgan** [comment]
Try maybe to add your handler with `colorize=False` in case ansi code are misinterpreted by your terminal.
