### ISSUE TITLE
Consolidated email notification

### ISSUE THREAD

**Issue by dclong** [Delgan/loguru#63]
The [Exhaustive Notifier](https://github.com/Delgan/loguru#exhaustive-notifier) gives a great example on how to get email notification on logging events. Are email notifications separate or consolidated? In another words, will each logging event for email sent in a separate email or in a single email? If sent by separate emails, is there any way to consolidate them into  one single email?

**Comment by Delgan** [comment]
Hi @dclong.

Using the `NotificationHandler` as a sink implies that at mail will be sent each time you log a message using the Loguru `logger` (if not filtered-out by `level` parameter).

If you prefer to send all the logs at once, I think you could use a file sink and make use of the `compression` parameter which will be triggered when your program terminates:

```python
def compression(filepath):
    params = {
        "attachments": [filepath],
        "username": "you@gmail.com",
        "password": "abc123",
        "to": "dest@gmail.com"
    }
    notifier.notify(message="Here are your logs", **params)

logger.add("file.log", compression=compression)

logger.info("This message does not trigger email sending immediately")
```

**Comment by Delgan** [comment]
@dclong Does the solution provided here satisfies your use case?

**Comment by dclong** [comment]
@Delgan Thank you for the solution! It works well. 

However, a related question comes to my mind suddenly. What if the program throws an error (not from loguru)? I haven't tried but I guess we won't receive an email? And I guess the trick is to use the `@logger.catch` annotation?

**Comment by Delgan** [comment]
If you program ends unexpectedly, you will stil receive the mail (the `compression` is triggered at program exit, no mater if an error was raised or not), but it won't contain the exception information.

As you have correctly guessed, the solution is to decorate your `main()` function with `@logger.catch(reraise=True)` (or using the context manager `with logger.catch(): ...`) so that exception is logged and hence appears in the log file.

**Comment by chwba** [comment]
I have a question about this one. I have an application, that will not terminate but rather sleep for an amount of time, do some work and then sleep again. Is there a way for me to use compression as explained here and somehow manually do something to loguru to have it trigger sending the log file?

**Comment by Delgan** [comment]
Hi @chwba.

The compression is triggered by the rotation. One possibility would be to attach the "request" using `.bind(compress=True)` and rotate the file adequately.

```python
def rotation(file, message):
    return message.record["extra"].get("compress", False)

def compression(filepath):
    params = {
        "attachments": [filepath],
        "username": "you@gmail.com",
        "password": "abc123",
        "to": "dest@gmail.com"
    }
    notifier = notifiers.get_notifier("gmail")
    notifier.notify(message="Here are your logs", **params)

logger.add("file.log", rotation=rotation, compression=compression)

logger.info("Basic message...")
logger.bind(compress=True).info("Sending logs by mail")
```

Alternatively, you could implement your own sink class to handle sending the logs in the specific way you prefer.

**Comment by chwba** [comment]
Sorry for the late reply, currently drowning in work. So like this on doing `logger.bind(compress=True).info("Sending logs by mail")` It would be sending the log via email, do I understand that correctly?

**Comment by Delgan** [comment]
@chwba Indeed, using the previous snippet this is what should happen.
