### ISSUE TITLE
What about supporting writing files asynchronously?

### ISSUE THREAD

**Issue by Rongronggg9** [Delgan/loguru#630]
I may open a PR implementing that.

**Comment by Delgan** [comment]
Using `enqueue=True` should write to file asynchronously already, right?

**Comment by Rongronggg9** [comment]
> Using `enqueue=True` should write to file asynchronously already, right?

`enqueue=True` writes files in another thread and is not a performance-best solution. There are some libs supporting **native** asynchronous file operations (e.g., [aiofile](https://github.com/mosquito/aiofile)) so implementing a native asynchronous file writer can potentially improve the performance of those asynchronous programs using `loguru`.

**Comment by Delgan** [comment]
Indeed. As Loguru supports `async` sink, what about the following:

```python
from loguru import logger
import asyncio
from aiofile import AIOFile


async def main():
    logger.remove()

    async with AIOFile("/tmp/file.log", 'w+') as afp:
        logger.add(afp.write)
        logger.info("Test message")
        await logger.complete()
        await afp.fsync()

        print(await afp.read())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

It seems to work pretty well. The downside is that it's not possible then to benefit from file features (rotation, compression, retention). Did you have something else in mind? Implementing "asynchornous file handler" natively in Loguru may require adding new dependencies, which I would prefer to avoid.

**Comment by Rongronggg9** [comment]
> The downside is that it's not possible then to benefit from file features (rotation, compression, retention). 

Unasynchronizable rotation and retention are not really a problem since they are intended to not occur often. As for compression, we could write a warning to the docs to tell them that it is unasynchronizable.

> Implementing "asynchronous file handler" natively in Loguru may require adding new dependencies, which I would prefer to avoid.

What about an `extra_require`?
That's OK if you are against adding new deps. If so, just close this issue. Anyway, thanks for your replies in time. ☺️
