### ISSUE TITLE
Any way to respect pytest caplog level?

### ISSUE THREAD

**Issue by mcarans** [Delgan/loguru#631]
pytest's caplog allows the setting of level eg. `caplog.set_level(logging.WARNING)`. Is there any way to set up the pytest fixture described [here](https://loguru.readthedocs.io/en/stable/resources/migration.html#making-things-work-with-pytest-and-caplog) to respect whatever level it is set to?

**Comment by Delgan** [comment]
What about explicitly adding the handler with `level="WARNING"`?

```python
@pytest.fixture
def caplog(caplog: LogCaptureFixture):
    handler_id = logger.add(caplog.handler, level="WARNING", format="{message}")
    yield caplog
    logger.remove(handler_id)
```

**Comment by mcarans** [comment]
Do you know if there any way to programatically retrieve the level X the user set with `caplog.set_level(X)` and pass that to the call?

```python
@pytest.fixture
def caplog(caplog: LogCaptureFixture):
    level = ...  # Programatically get level X the user set with caplog.set_level(X)
    handler_id = logger.add(caplog.handler, level=level, format="{message}")
    yield caplog
    logger.remove(handler_id)```

**Comment by Delgan** [comment]
According to the documentation, [`caplog.set_level()`](https://docs.pytest.org/en/6.2.x/reference.html?highlight=set_level#pytest.LogCaptureFixture.set_level) accepts an optional `Logger` object which defaults to the root logger.

Assuming the user didn't specify a `logger`, you can retrieve the default level with `logging.geLogger(None).level`.

**Comment by mcarans** [comment]
From what I can tell, the problem is the order of calls:
```python
    def test_setup_logging(self, caplog):  # noqa: F811
        with caplog.at_level(logging.ERROR):
```
The caplog fixture is set up and then yielded, and then afterwards (I think) the `at_level` call in the test function is executed. In other words the setting of the level happens after `handler_id = logger.add(caplog.handler, level=level, format="{message}")` has already been executed and hence the level passed at that stage is incorrect as it has not yet been set.

**Comment by Delgan** [comment]
Indeed, you're right. Maybe you can make use of a custom `filter` to retrieve the level dynamically?

```python
@pytest.fixture
def caplog(caplog: LogCaptureFixture):
    def filter_(record):
        return record["level"].no >= logging.getLogger(None).level
    handler_id = logger.add(caplog.handler, level=0, format="{message}", filter=filter_)
    yield caplog
    logger.remove(handler_id)
```

**Comment by mcarans** [comment]
Thanks, that put me on the right track. I think it should be:
```python
    def filter_(record):
        return record["level"].no >= caplog.handler.level

    handler_id = logger.add(caplog.handler, format="{message}", filter=filter_)
    yield caplog
    logger.remove(handler_id)
```

**Comment by Delgan** [comment]
@mcarans Looks great. I didn't realize we could access `handler.level` which is much better indeed.

I would just advise to use `level=0` while adding the handler otherwise users won't be able to test `"TRACE"` level for example.

I'll update the documentation as well, thanks for the improvement suggestion. :+1:

**Comment by mcarans** [comment]
Ok, so now the code is:
```python
@pytest.fixture
def caplog(caplog: LogCaptureFixture) -> None:
    def filter_(record):
        return record["level"].no >= caplog.handler.level

    handler_id = logger.add(caplog.handler, level=0, format="{message}", filter=filter_)
    yield caplog
    logger.remove(handler_id)
```

**Comment by mcarans** [comment]
@Delgan pytest-loguru 0.2.0 has been released with the above code.

**Comment by Delgan** [comment]
Thanks, I updated the recipe in Loguru documentation as well. :+1:
