### ISSUE TITLE
loguru and  mingw64

### ISSUE THREAD

**Issue by LinziWang** [Delgan/loguru#64]
Hi Sir,
When I use mingw64 to compile my code, the following  msg. :

C:\Users\Amber\Desktop\tsn-milestone2\module\lib\loguru\loguru.cpp:117:0: warning: "NOMINMAX" redefined
  #define NOMINMAX
In file included from C:/msys64/mingw64/include/c++/7.3.0/x86_64-w64-mingw32/bits/c++config.h:533:0,
                 from C:/msys64/mingw64/include/c++/7.3.0/utility:68,
                 from C:/msys64/mingw64/include/c++/7.3.0/algorithm:60,
                 from C:\Users\Amber\Desktop\tsn-milestone2\module\lib\loguru\loguru.cpp:29:
C:/msys64/mingw64/include/c++/7.3.0/x86_64-w64-mingw32/bits/os_defines.h:45:0: note: this is the location of the previous definition
 #define NOMINMAX 1

This is a warning msg., but I cannot ensure this will cause some error or not. Can I ignore this warning or what can i do??

Thank you.

**Comment by Delgan** [comment]
Hi @LinziWang.

I think you are on the issue tracker of the wrong library. 😛 

You are looking for the C++ `loguru` library which is located here: https://github.com/emilk/loguru

The repository here is a Python library which is not related to the C++ one, but just happens to share the same name.

**Comment by LinziWang** [comment]
Thank you for your reply. 😊

I have downloaded this library by that link, and followed the doc. to install this library.
After that, I write Loguru.cpp in cmakeList file and include Loguru.hpp in my cpp file.

I will check again,  thank you so much. ^^

**Comment by LinziWang** [comment]
Hi @Delgan

 I have checked again. I ensure the Loguru library is c++ version. Same warning occurred.
￼
![image](https://user-images.githubusercontent.com/18409593/54324882-81214700-463a-11e9-85e8-7b2eb37f1b3c.png)

and the color of log msg is opposite to your example, is that ok??
![image](https://user-images.githubusercontent.com/18409593/54324894-91392680-463a-11e9-8e09-8de235b6ddce.png)

Thank for your help ^^

**Comment by LinziWang** [comment]
Oh! Sorry I just realize I make a mistake.
Sorry about that, thank you for your help.

**Comment by Delgan** [comment]
@LinziWang No problem. 👍
