### ISSUE TITLE
How to create separate logs for each process

### ISSUE THREAD

**Issue by yhaokeen** [Delgan/loguru#643]
Hi
I need a separate log for each process, How can i do it?

**Comment by Delgan** [comment]
Hi.

You just need to [`add()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) an handler in each of your process. Make also sure that the child process does not inherit handlers from the parent process.

**Comment by yhaokeen** [comment]
tks
