### ISSUE TITLE
Hide Sensitive Information from Exception Traceback

### ISSUE THREAD

**Issue by DhavalShewale** [Delgan/loguru#651]
While there are ways to mask / scrub sensitive information from message as mentioned in https://github.com/Delgan/loguru/issues/17

There should also be ways to mask / scrub sensitive information in exception traceback.

**Comment by Delgan** [comment]
You can do so by implementing a custom exception formatting and/or disabling `diagnose` option: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).

**Comment by DhavalShewale** [comment]
So, we are saying that the only option is to set `diagose=False`?

Disabling `diagnose` would stop printing all the values, even the ones which were not sensitive and useful. 

It would be great if we can selectively disable some classes during diagnosis or configure a regex based replacement which is currently available for messages.

**Comment by Delgan** [comment]
There is currently no "regex based replacement" available for messages. One has to implement it's own filtering handler as described in the ticket you linked. I'm suggesting to do the same with a custom exception formatter. :+1:
