### ISSUE TITLE
Use custom JSONEncoder for serialization?

### ISSUE THREAD

**Issue by rmweiss** [Delgan/loguru#652]
Would it be possible to add the option to use a custom `JSONEncoder` when using `serialize=True`?

This would allow binding datatypes the json module currently doesn't know about into "extra" (without them getting converted to string) 

Here's an example how to use them to addi support for `dataclasses` to `json.dumps`:

```python
import dataclasses, json


class EnhancedJSONEncoder(json.JSONEncoder):
    def default(self, o):
        if dataclasses.is_dataclass(o):
            return dataclasses.asdict(o)
        return super().default(o)


@dataclasses.dataclass
class Point:
    X: int
    Y: int


result = json.dumps(Point(2, 4), cls=EnhancedJSONEncoder)
assert result == '{"X": 2, "Y": 4}'
```

**Comment by Delgan** [comment]
Hi @rmweiss.

Usually I suggest to implement a custom serializer as follow: [Serializing log messages using a custom function](https://loguru.readthedocs.io/en/stable/resources/recipes.html#serializing-log-messages-using-a-custom-function).

I prefer to recommend this method than to extend the existing functionality.

**Comment by rmweiss** [comment]
Hi @Delgan 

This seems to work for me.

Thanks!
