### ISSUE TITLE
No fully descriptive stack trace when using @logger.catch decorator

### ISSUE THREAD

**Issue by beyse** [Delgan/loguru#659]
#### Environment
I use Anaconda and python inside a conda environment.
Python version:  `Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32`
OS: `Windows 11`
Loguru version: `0.6.0`

#### Issue description
When using the `@logger.catch` decorator on a function I do not get the expected output with the entire stack trace and the values of variables.

#### Steps to reproduce the issue

1.  Create a conda env called `loguru` with

```console
conda create --name loguru python=3.8.12
```

2. Activate the new env using

```console
conda activate loguru
```

3. Install loguru using pip

```console
pip install loguru
```

4. Start a python interpreter right from the console using 

```console
python
```

5. Run this code (which I took from the [README](https://github.com/Delgan/loguru/blob/master/README.rst)):

```python
from loguru import logger
logger.add("out.log", backtrace=True, diagnose=True)
@logger.catch
def my_function(x, y, z):
    # An error? It's caught anyway!
    return 1 / (x + y + z)
my_function(0, 0, 0)
```

6. Observe the console output check if it is as expected.

#### What's the expected result?

- As described [in the documentation](https://github.com/Delgan/loguru#fully-descriptive-exceptions) I would expect to see a fully descriptive stack trace in the console, similar to:

```
2018-07-17 01:38:43.975 | ERROR    | __main__:nested:10 - What?!
Traceback (most recent call last):

  File "test.py", line 12, in <module>
    nested(0)
    └ <function nested at 0x7f5c755322f0>

> File "test.py", line 8, in nested
    func(5, c)
    │       └ 0
    └ <function func at 0x7f5c79fc2e18>

  File "test.py", line 4, in func
    return a / b
           │   └ 0
           └ 5

ZeroDivisionError: division by zero
```

#### What's the actual result?

- I get this:

```console
2022-05-23 00:11:02.830 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (12040), thread 'MainThread' (2052):
Traceback (most recent call last):

> File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in my_function

ZeroDivisionError: division by zero
```

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/5306790/169718284-1da80c83-6465-4964-b544-faf67891f5f9.png)

**Comment by beyse** [comment]
#### Additional Info

Also the log file `out.log` created by above code has:

```
2022-05-23 00:11:02.830 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (12040), thread 'MainThread' (2052):
Traceback (most recent call last):

> File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in my_function

ZeroDivisionError: division by zero

```

**Comment by Delgan** [comment]
Hi. Thanks for detailed report.

Stack trace context isn't available when Python is executed in an interactive shell. This is a Python technical limitation and unfortunately, there is nothing I can do to fix it.

**Comment by beyse** [comment]
I do not know if many people fall for this, but I suggest to note this behaviour in the readme as a hint or something. It could avoid confusion about this. 

Thanks for the quick response!

**Comment by Delgan** [comment]
Well, you're not alone: https://github.com/Delgan/loguru/issues/5

The `.gif` is indeed misleading, sorry for that. It would be better to change it or add a note underneath, but I can't do that without compromising the desired look of the Readme. I added a note under the "Fully descriptive exceptions" section. Hopefully it will reduce confusion a little.
