### ISSUE TITLE
How to configure logger in another module?

### ISSUE THREAD

**Issue by versatran01** [Delgan/loguru#66]
This might be a noob question, but suppose that in a module `mod.py` I import logger and do some logging.
Now how do I set the level of that logger (in mod.py) from my main.py?
Is this even the correct way to use the logger? If not then how should I use it?

**Comment by Delgan** [comment]
Hey @versatran01.

Basically, the `logger` object you import is the same in all of your modules, so, if you do `logger.add("file.log")` in `main.py`, then any message logged in `mod.py` will be propagated to the file.

If you want to log messages coming only from the `mod.py`, you can use a `filter`, for example to log "INFO" and higher messages: `logger.add("file.log", level="INFO", filter="mod")`.

Do these explanations help you?

**Comment by versatran01** [comment]
Thanks for your answer. Actually what I wanted is to disable log in `mod.py`. 
Is there a way to do this?

**Comment by Delgan** [comment]
@versatran01 You can either use `logger.disable("mod")` or filter-out the module while configuring your sinks: `logger.add("file.log", filter=lambda r: r['name'] != "mod")`.

**Comment by versatran01** [comment]
Thanks
