### ISSUE TITLE
How to log message with args like logger.warning('hello %s', 'world')

### ISSUE THREAD

**Issue by Littlecowherd** [Delgan/loguru#661]
This is a mini case
```python
import logging
logging.basicConfig(handlers=[logging.StreamHandler()])
logger = logging.getLogger('__name__')
logger.warning('hello %s', 'world')

from loguru import logger
logger.warning('hello %s', 'world')
```
Here is the output
```plain
WARNING:__name__:hello world
2022-05-23 19:44:00.547 | WARNING  | __main__:<module>:20 - hello %s
```
the logging works well, but loguru doesn't take the argument. Is there any way to let loguru work like logging?

**Comment by Delgan** [comment]
This is not (yet?) possible. Loguru favors more modern string formatting using curly braces.

```python
from loguru import logger
logger.warning('hello {}', 'world')
```

**Comment by Littlecowherd** [comment]
Got it, Thanks

**Comment by Littlecowherd** [comment]
Some Third-Party libraries like APScheduler accept a logger as an argument. Internally, they use %s to format strings, here is an example

```python
self._logger.info('Added job "%s" to job store "%s"', job.name, jobstore_alias)
```
So, if loguru could handle this case, it would be more compatible.

Anyway, thank you for the great work, I can't live without it. :-)

**Comment by Delgan** [comment]
I plan to give more control on how logs are formatted, yes (with even the possibility to disable formatting because this has been requested multiple times). Hopefully once implemented one will be able to use `"%"` formatting if desired. :+1:
