### ISSUE TITLE
[question] aggregating same log lines

### ISSUE THREAD

**Issue by delicb** [Delgan/loguru#664]
I have a situation where code is generating a lot of messages with same content. This block of code is well scoped. I am trying to figure out a way to record these messages and log them only once (with info in `extra` about number of occurrences). Ideally, it would look like something along the lines:
```python
with <some-context-manager>:
    for i in range(100):
        logger.warning("same message")
```
with `<some-context-manager>` doing something that would cause `"some message"` to be stored in a structure like `collections.Counter` and when context manager exists, it would log all unique messages once. Ideally, output of this snippet would be `<time> WARNING | some message - [count=100]` (where `count` is extracted from `extra`, of course, with proper formatter).

I do not know `loguru` well enough to write such context manager, so I am seeking advice. 

One idea I had was to inherit `Logger` class and override some methods (probably `_log`), but class does not seem to be designed to be inherited (it is not even importable from `loguru`), so I guess that is not the right path. Other idea I had was to create custom sink which could change behavior and implement this logic when context manager sends a signal to it, but sink provided via `add` is quite hidden and wrapped, so I guess it is not intended to be tweaked in runtime.

Is there something else that can solve this? I am open to any suggestions. 

Thanks.

**Comment by Delgan** [comment]
Hi @delicb.

The `Logger` class is indeed not intended to be inherited.

Other users have encountered similar needs, maybe this will help you.
Here is an example using a custom sink: https://github.com/Delgan/loguru/issues/516#issuecomment-932983777
And here is another solution using a wrapper instead of a subclass: https://github.com/Delgan/loguru/issues/383#issuecomment-869116088

Another possibility is to make use of `patch()` as follows:

```python
import sys

from loguru import logger
from contextlib import contextmanager
from collections import Counter

@contextmanager
def aggregate_logger():
    messages = Counter()

    def patch(record):
        nonlocal messages
        try:
            level = logger.level(record["level"].name).name
        except ValueError:  # Logger called with an integer level
            level = record["level"].no
        messages[(level, record["message"])] += 1
        record["extra"]["disabled"] = True

    yield logger.patch(patch)

    for (level, message), count in messages.items():
        logger.opt(depth=2).log(level, message + f" - [count={count}]")

logger.remove()
logger.add(sys.stderr, filter=lambda r: not r["extra"].get("disabled", False))

logger.info("Normal message")

with aggregate_logger() as alogger:
    for i in range(100):
        alogger.warning("Same message")
        alogger.info(f"Message {i % 10}")
        alogger.log(33, "Another message")
```

Another solution is to provide your own logging function like that:

```python
from loguru import logger
from collections import Counter
from contextlib import contextmanager


@contextmanager
def aggregate_logger():
    messages = Counter()

    def log(level, message):
        nonlocal messages
        messages[(level, message)] += 1

    yield log

    for (level, message), count in messages.items():
        logger.opt(depth=2).log(level, message + f" - [count={count}]")

logger.info("Normal message")

with aggregate_logger() as log:
    for i in range(100):
        log("WARNING", "Same message")
        log("INFO", f"Message {i % 10}")
        log(33, "Another message")
```

**Comment by delicb** [comment]
@Delgan thanks a lot for the response. 

Reading through these examples, I have created something. First, I have the following filter applied:
```python
aggregated_logs = {}

def log_filter(record: loguru.Record) -> bool:
    global aggregated_logs

    # my app specific filters
    filters = {
        "werkzeug": logger.level("WARNING").no,
        "sqlalchemy": logger.level("WARNING").no,
    }
    
    # filter_by_level is copied from loguru _filters.py
    if not filter_by_level(record, filters):
        return False

    # filters allow these, check if we have "once" in extra
    log_once = record["extra"].pop("once", False)
    if not log_once:
        return True

    key = f"{record['level'].name} - {record['message']}"
    if key in aggregated_logs:
        aggregated_logs[key]["count"] += 1
    else:
        aggregated_logs[key] = {
            "record": record,
            "count": 1
        }
    return False
```

Logging aggregated logs is done in 
```python
def flush_aggregated_logs(add_depth: int = 0):
    global aggregated_logs
    if not aggregated_logs:
        return
    for k, v in aggregated_logs.items():
        count = v["count"]
        record = v["record"]

        logger.opt(
            depth=1 + add_depth
        ).bind(
            **record["extra"]
        ).bind(
            count=count
        ).log(
            record["level"].name, record["message"]
        )
    aggregated_logs = {}  # reset aggregated logs
```

And context manager
```python
@contextmanager
def aggregate_logs():
    yield
    flush_aggregated_logs(add_depth=2)  # one for this func, one for contextlib
```

With this, I did not have to propagate logger instance that context manager would yield and I could just continue using `loguru.logger` as I already did. There was only a handful of places that produced bunch of same messages, so in those places I did `logger = logger.bind(once=True)`. 

I have some improvements in mind (e.g. I am not taking extra parameters in account when aggregating logs & I would probably want to flush aggregated logs  on exit, in case someone forgets context manager or program exists) so I will look into that. 

Leaving this here in case it helps someone with similar question and for comments on potential pitfalls I might have missed.
