### ISSUE TITLE
Log to terminal and file with enqueue (multiprocessing)

### ISSUE THREAD

**Issue by Didiervolk00** [Delgan/loguru#670]
Hi there, nothing multiprocess problem. Trying to log multiple processes to the terminal and a file at the same time. But it seems like using two enqueue's does not work.

```
@logger.catch
def initialize_logger():
    logger.remove()
    logger.add(
        sys.stderr,
        diagnose=True,
        colorize=True,
        enqueue=True
    )
    ## Open if not exists
    os.makedirs(r"/home/nvidia/SSD/Logfiles", exist_ok=True)
    logfile_path = "/home/nvidia/SSD/Logfiles/logfile.log"
    if not os.path.exists(logfile_path):
        txtfile = open(logfile_path, "w")
        txtfile.close()
    logger.add(
        logfile_path,
        diagnose=True,
        rotation="1 MB",
        retention="5 days",
        enqueue=True
    )
```
With both sinks using enqueue it only repeats once, and it should be repeating infinitely

Anyone familiar with this problem?

**Comment by Delgan** [comment]
Hi. What do you mean by "it should be repeating infinitely"?

**Comment by Didiervolk00** [comment]
It gives a log message once in the terminal and then it doesn't repeat itself. While he should return a value every second. But when I remove one of the enqueue's form the two sinks it works fine but just for one sink.

**Comment by Delgan** [comment]
@Didiervolk00 Can you provide a minimal reproducible example so I can try it out please?

The code you shared does not try to log any message from what I see.

**Comment by Didiervolk00** [comment]
```
from time import sleep
import multiprocessing
from loguru import logger
import sys

def initialize_logger():
    logger.remove()
    logger.add(
        sys.stderr,
        diagnose=True,
        colorize=True,
        enqueue=True
    )
    logger.add(
        "file.log" ,
        diagnose=True,
        rotation="1 MB",
        retention="5 days",
        enqueue=True
    )

def my_process():
    while True:
        logger.info("Executing function in child process")
        sleep(1)

if __name__ == "__main__":
    initialize_logger

    process = multiprocessing.Process(target=my_process)
    process.start()
    while True:
        logger.info("Done")
        sleep(0.5)

```

This something that can work? This does write to my terminal but not into a log file..

**Comment by Delgan** [comment]
@Didiervolk00 You're missing parentheses after the `initialize_logger` in your `if __name__ == "__main__"` branch. The function is not called, try `initialize_logger()` instead.

**Comment by Didiervolk00** [comment]
Well that is a rookie mistake, but this stil doesn't write into a file.

**Comment by Delgan** [comment]
@Didiervolk00 This works fine on my computer (Linux). Are you using Windows?

**Comment by Didiervolk00** [comment]
Working in a wsl (subsystem), let me grab a fully working linux system.

**Comment by Delgan** [comment]
Calling `multiprocessing.get_start_method()` must return `"fork"` otherwise `enqueue` won't work out of the box and you'll need to implement workaround [described in the documentation](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument) (basically, passing the `logger` to your sub-process).

**Comment by Didiervolk00** [comment]
It works, it sure has to do with something else in my code then. Thanks for your help!
