### ISSUE TITLE
Working example for datadog/json?

### ISSUE THREAD

**Issue by richstokes** [Delgan/loguru#672]
Do you have a working example for datadog?

It needs to output in JSON format, but not sure the best way to do this

**Comment by richstokes** [comment]
Ohhh, I think I need to add a `logger.remove()` in there first to remove the default and only log to json

**Comment by Delgan** [comment]
Indeed, the `logger` comes with a default handler logging to `stderr`. If you want a "datadog only" configuration, you have to remove it first. :+1:

**Comment by richstokes** [comment]
Thanks!

Awesome module btw!
