### ISSUE TITLE
Enable dependabots and security scans?

### ISSUE THREAD

**Issue by ckuethe** [Delgan/loguru#673]
I'm looking at using loguru for some personal projects and maybe stuff at work, and was wondering if you'd consider turning on dependabot and codeql for this repo? I quickly forked loguru to my account to enable these scans and it doesn't look like there will be a huge maintenance burden - so far dependabot just suggests bumping `freezegun`, `docutils`, and `sphinx`.

**Comment by Delgan** [comment]
Hi.

This is definitely something I planned to investigate but didn't have time to yet. :)

PR would be welcome. :+1:

**Comment by ckuethe** [comment]
PR sent.
