### ISSUE TITLE
Loguru update for Python 3.10 +?

### ISSUE THREAD

**Issue by MarkBruyneel** [Delgan/loguru#679]
Will you be creating a new version of the excellent Loguru module for more recent Python distributions? I am currently using Python 3.10.5 and, through Anaconda, Python 3.10.4 and in both cases cannot use it anymore. It either fails to install (Python import) or says that it is incompatible (Anaconda pip install).

**Comment by Delgan** [comment]
Hi @MarkBruyneel.

Loguru is already published and tested for Python 3.10, so I'm not sure which error you're facing.

Note that packages for Anaconda are created in a different repository (of which I'm not maintainer): https://github.com/conda-forge/loguru-feedstock

**Comment by MarkBruyneel** [comment]
Just tried it again this morning and now it seems to work fine. Maybe it was an issue with an update by IT on the computer. I will check the Anaconda thing using your link. I was not aware that this was maintained in a different repository. Thanks.

**Comment by Delgan** [comment]
Great. I'm closing this ticket then, but feel free to continue the discussion if needed. :+1:
