### ISSUE TITLE
Re-emitting log records received from another process

### ISSUE THREAD

**Issue by hashstat** [Delgan/loguru#68]
I wrote a multiprocessing-like module I use for creating worker processes. Worker processes add a callable sink that serializes logging records and sends them to the parent process via a pipe. Once records are received by the parent, it should deserialize them and forward them on to handlers for formatting and final logging, but I don't see any public methods for re-emitting records to handlers. So I'm currently using private attributes to re-emit the records.

Here is an incomplete example to provide a feel for what I am currently doing:

```python
# worker.py

import logging
from loguru import logger

def send_record(message):
    pipe.write(pickle.dumps(message))

logger.add(send_record, level=logging.DEBUG, format='')  # Final handlers will take care of formatting
```

```python
# parent.py

import logging
from loguru impor logger

def emit(message):
    record = message.record
    level = record['level']
    try:
        _, level_color, _ = logger._levels[level.name]
    except KeyError:
        level_color = ''
    for handler in logger._handlers.values():
        handler.emit(record, level_color, logger._ansi, logger._raw)

def recv_record():
    message = pickle.loads(pipe.read())
    emit(message)

logger.add(sys.stdout, level=logging.DEBUG)
```

Did I miss something in the loguru API? Are there public routines to handle this case? Is this a feature that could be added to loguru? I know the builtin logging libraries have similar support, but I would like to use loguru, if possible. Any help is appreciated.

Thanks!

**Comment by Delgan** [comment]
Hello @hashstat. 🙂 

You are right, this is a feature which is currently missing. There is no proper way to emit a record to the configured handlers.

This is something I had thought about and I planned to add for the `v0.3.0`.

Basically, the new method will be similar to `.bind()`, except it will accept a function which will be executed to modify the record dict prior to sending it to the handlers.

This will look like this:

```python
def recv_record():
    record = pickle.loads(pipe.read())
    level, message = record["level"], record["message"]
    logger.preprocess(lambda r: r.update(record)).log(level, message)
```

That's way, the user will be able to update the record dict dynamically.

**Comment by Delgan** [comment]
I added [a recipe in the documentation](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes) which explains how logs can be emitted across network or processes. This make use of the new [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) function. :+1:
