### ISSUE TITLE
Logger type import would crash at runtime

### ISSUE THREAD

**Issue by iyakushev** [Delgan/loguru#686]
# Summary
Static analyzers like `pyright` with `strict` mode are unhappy about the exported types in the `__init__.pyi`. Following the declarations, it would provide an import hint like `from loguru import Logger` which leads to problems.

# Problem
```py
from loguru import Logger  # crash at runtime
```
this would crash, since `__init__` exports it as `_Logger` but the stubs suggest otherwise (`Logger`). Importing from the `_logger` directly won't solve the issue either because definitions there are untyped. 

# Possible fix
Either export `Logger` as it is defined in the stubs, or add something like this:
```py
# __init__.py 
from typing import TypeAlias

Logger: TypeAlias = _Logger
```

**Comment by Delgan** [comment]
Hi, thanks for the detailed report.

Actually, as Loguru uses stub file for type hint, you should rely on postponed annotations or use string literals.

See this page on the documentation for more details and examples: [Type hints](https://loguru.readthedocs.io/en/stable/api/type_hints.html).

**Comment by iyakushev** [comment]
Got it. Thanks
