### ISSUE TITLE
Loguru with asyncio - [  await logger.complete()  ] - Question

### ISSUE THREAD

**Issue by Maxiviper117** [Delgan/loguru#688]
In the help docs, this example below is given for an async implementation via await logger.complete().

```python
async def sink(message):
    await asyncio.sleep(0.1)  # IO processing...
    print(message, end="")

async def work():
    logger.info("Start")
    logger.info("End")
    await logger.complete()

logger.add(sink)

asyncio.run(work())

```

My question is regarding the placement for the:
```python 
await logger.complete() 
```

Does this awaitable need to be placed after every async function? or after every logger or a group of loggers within the same indentation level?
Like the below?

```python

async def some_func():
    if x > 50:
        logger.info("x greater than 50")
        await logger.complete() # <----
        if x % 5 == 0:
            logger.info("x divisable by 5")
            await logger.complete() # <----


```

**Comment by Maxiviper117** [comment]
Currently, I have a trading bot that runs a few functions of code concurrently but its producing an error with the standard logging implementation as I have implemented it, where the logging from the multiple functions attempts to access the same file log simultaneously. 

There are ways to configure the standard logging library to work asynchronously, but I like Loguru's simplicity.

**Comment by Delgan** [comment]
Hi.

You don't need to `await` this method after every logging call. You only need to wait for `complete()` when you want to ensure all logged message so far has been processed by your asynchronous sink.

This is useful for example before leaving the event loop and your application.

**Comment by Maxiviper117** [comment]
@Delgan So, for my script for my bot there are two main functions that contain many processes along with the logs to log what is happening within them, they both run concurrently using asyncio, each running in their own While Loops.

So I should basically only need to use the ```complete()``` at the end of each of these functions, which is before a new loop iteration for each function.?

E.G.

```python
async func_1():
    while True:
        # do many things
        # log many things
        await logger.complete()
        asyncio.sleep(0.1)
async func_2():
    while True:
        # do many things
        # log many things
        await logger.complete()
        asyncio.sleep(0.1)

async def main():
    await asyncio.gather(func_1(), func_2())

if __name__ == '__main__':
    asyncio.run(main())

```

**Comment by Delgan** [comment]
You can put only one `await logger.complete()` at the end of the `main()` function, I guess.

**Comment by Maxiviper117** [comment]
Then how do we use the below method to write to a file?

```python
async def sink(message):
    await asyncio.sleep(0.1)  # IO processing...
    print(message, end="")

async def work():
    logger.info("Start")
    logger.info("End")
    await logger.complete()

logger.add(sink)

asyncio.run(work())

```

**Comment by Delgan** [comment]
I'm not sure to understand the question. If you want to log messages to a file, you need to add a file sink, like `logger.add("output.log")`.

**Comment by Maxiviper117** [comment]
```python

log_file =  "log.log"

# Some logger config here...etc

async def func_A():
    logger.info("log something")

async def func_B():
    logger.info("log something")

async def main():

    await asyncio.gather(
        func_A(),
        func_B(),
    )


asyncio.run(main())
```

If both func_A and func_B try log to "log.log" at the same time, it throws the error below.
I just need to ensure this doesnt happen, the process to fix this on the standard logging library is lengthy.
I'm looking how to avoid this error using Loguru

```yaml
Traceback (most recent call last):
  File "C:\Users\david\Anaconda3\lib\logging\handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "C:\Users\david\Anaconda3\lib\logging\handlers.py", line 195, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
OSError: [Errno 22] Invalid argument
```
