### ISSUE TITLE
How to properly configure logger to capture log messages from libraries which uses standart logging?

### ISSUE THREAD

**Issue by kiddick** [Delgan/loguru#69]
I've tried to use `InterceptHandler` for that purpose with asyncio lib. But I am only getting messages spawned from my script by `logger.info(..)`, but messages from libs are missing..
What is the proper way to capture underlying libraries log messages?
```python
config = {
    'handlers': [
        {
            'sink': sys.stdout,
            'level': 'DEBUG'
        },
    ],
}
logger.configure(**config)

class InterceptHandler(logging.Handler):
    def emit(self, record):
        logger_opt = logger.opt(exception=record.exc_info)
        logger_opt.log(record.levelname, record.getMessage())


logging.getLogger(None).addHandler(InterceptHandler())
logging.getLogger('asyncio').addHandler(InterceptHandler())
```

**Comment by Delgan** [comment]
Hi @kiddick.

I think you should try to configure the level of standard logger, something like: `logging.getLogger(None).setLevel(logging.DEBUG)`.

Tell me if this works for you. ;)

**Comment by kiddick** [comment]
Thank you. That solved my problem.
Another related question is it possible in InterceptHandler save original info about caller instead `emit` here `DEBUG    | myscript:emit:36` ?

**Comment by Delgan** [comment]
Yep, this is totally possible.

If you look at [the snippet in the README](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging), this is what `depth=6` is used for.

The `depth` option is used to query the information upward in the call stack. If you do `opt(depth=1).debug()`, it will use the information of the parent stack.

Using a depth of `6` for the `InterceptHandler` is some kind of "magic" number. It just happens that, between the built-in `logging.debug()` and the handling of log message inside `emit()`, there is 6 function calls. So, if you want the information of the stack where `logging.debug()` was called, you need `depth=6`. 😉

**Comment by kiddick** [comment]
Thank you again! Btw was confused about what magic number, so may be it is worth to mention about that in readme.

**Comment by Delgan** [comment]
Thanks for your suggestion, I added a few words about the `depth=6` option in the Readme. 👍
