### ISSUE TITLE
How to output the runtime of an interface or method?

### ISSUE THREAD

**Issue by jaxonister** [Delgan/loguru#691]
How to output the runtime of an interface or method?

**Comment by Delgan** [comment]
Please clarify your question.

**Comment by jaxonister** [comment]
I want to record the running time of each method and the processing time of the interface. Does loguru support it?

**Comment by jaxonister** [comment]
I want to check system response time, processing time by doing something like this

**Comment by Delgan** [comment]
This is not available out of the box, you'll need to implement a decorator like this one: [Logging entry and exit of functions with a decorator](https://loguru.readthedocs.io/en/stable/resources/recipes.html#logging-entry-and-exit-of-functions-with-a-decorator).
