### ISSUE TITLE
Permissions issue when creating or writing to log file

### ISSUE THREAD

**Issue by ExatechIT** [Delgan/loguru#696]
I'm having an issue when running a python script as a service. If I run it manually the logger works perfectly as expected, however if I try to run it as a service i get a permissions issue even though the service is being run as the local that python and loguru were installed with.

```
Aug 20 15:49:57 python3[24324]:   File "/home/pi/.local/lib/python3.9/site-packages/loguru/_logger.py", line 762, in add
Aug 20 15:49:57 python3[24324]:     wrapped_sink = FileSink(path, **kwargs)
Aug 20 15:49:57  python3[24324]:   File "/home/pi/.local/lib/python3.9/site-packages/loguru/_file_sink.py", line 167, in __init__
Aug 20 15:49:57  python3[24324]:     self._initialize_file()
Aug 20 15:49:57  python3[24324]:   File "/home/pi/.local/lib/python3.9/site-packages/loguru/_file_sink.py", line 187, in _initialize_file
Aug 20 15:49:57  python3[24324]:     self._file = open(path, **self._kwargs)
Aug 20 15:49:57  python3[24324]: PermissionError: [Errno 13] Permission denied: '/code.log'
Aug 20 15:49:57  systemd[1]: codeStart.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 15:49:57  systemd[1]: codeStart.service: Failed with result 'exit-code'.
Aug 20 15:49:57 systemd[1]: codeStart.service: Consumed 1.087s CPU time.
```

I have tried changing permission levels to 777 and changing ownership of folders and files to no avail.

Any help with this would be greatly appreciated

**Comment by Delgan** [comment]
Hi.

How are you configuring the `logger` and which file handlers are you adding?

It seems your script tries to create a file in the root folder (`/code.log`) which requires advanced permissions.

Maybe you need to specify the absolute path instead of a relative one, e.g `logger.add("/home/user/code.log")`. Alternatively, you can specify [the `WorkingDirectory` of your service](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=).

**Comment by ExatechIT** [comment]
I don't have any hadnlers configured, I am creating the log with the following line:

`logger.add('code.log', rotation='1 month')`

Again, this works and places the file in the working directory if i just run it from the command line. I have also tried 

`logger.add('./code.log', rotation='1 month')`

With the same issue. 

I'm honestly not sure why the error specifies /code.log becasue it is definitely not created in the root folder.

**Comment by Delgan** [comment]
> I don't have any hadnlers configured

While calling `logger.add()` you are actually added what we name an "handler", in this case, a "file handler" which handles logs of your application and write them to a file.

In both examples you're sharing, the path toward `code.log` is relative. This means the absolute path will be resolved with regards to the working directory from where your application is executed. As explained in the link I gave, a service is executed by default using the root folder as the working directory. This is why it's not working, although your script runs fine when started from the command line, when the working directory is likely not the root folder.

Please, try one of the two solutions I suggested.

**Comment by ExatechIT** [comment]
That did it. Thank you for your help and the detailed explaination!

**Comment by Delgan** [comment]
You're welcome. :+1:
