### ISSUE TITLE
'Pretty logging with colors' available for .log files?

### ISSUE THREAD

**Issue by deployment-ian** [Delgan/loguru#700]
I have been banging around with the ideolog plugin for pycharm and I have not had success for producing a usable format for the output log files that would mirror what is printed to console.

The following portion of the documentation produces marvelous results to the console:

![image](https://user-images.githubusercontent.com/50835503/188183075-a788f288-cc9c-4629-aaa6-3cd1632b35a9.png)

Would it be possible to have similar formatting on the output log files?

Here is what I see on the console vs what I see on the log file:
![image](https://user-images.githubusercontent.com/50835503/188185566-5f21950e-6a49-481d-a70d-e71aba46234a.png)

![image](https://user-images.githubusercontent.com/50835503/188186686-15c4672c-3622-4589-847b-bbdaa42def20.png)

**Comment by deployment-ian** [comment]
And I forgot to mention how much I love loguru... truly an awesome library.

**Comment by Delgan** [comment]
Hi @deployment-ian, glad you like Loguru. ;)

There is no colors in a `log` files. Displaying colors is a "feature" of terminal but files are not designed to contain colors.

You can still force the "color codes" (which work on terminal) to be displayed by specifying `colors=True` when adding your file sink, but it will likely not produce the output you expect.

**Comment by Delgan** [comment]
Closing as I answered your question but feel free to re-open it otherwise.
