### ISSUE TITLE
Support `captureWarnings`？

### ISSUE THREAD

**Issue by edsion1107** [Delgan/loguru#708]
https://stackoverflow.com/a/37979724/4144711
In loguru, is there another way?
I want to use `warnings.warn("message")`，but i don't know how to write logger.

**Comment by Delgan** [comment]
Hi, this is possible by replacing [`warning.showwarning`](https://docs.python.org/3/library/warnings.html#warnings.showwarning):

```python
import warnings
from loguru import logger

showwarning_ = warnings.showwarning

def showwarning(message, *args, **kwargs):
    logger.warning(message)
    showwarning_(message, *args, **kwargs)

warnings.showwarning = showwarning
```

Does that help you?

**Comment by Delgan** [comment]
Re-opening as I will add it to the documentation (assuming it worked for you).
