### ISSUE TITLE
Log to HTTP API?

### ISSUE THREAD

**Issue by cpach** [Delgan/loguru#709]
Can loguru be used to log (some) events to an HTTP API? E.g. Slack.

**Comment by Delgan** [comment]
Feel free to re-open this issue if you need more help or examples.

**Comment by cpach** [comment]
I must admit I couldn’t really figure out how to do this from the documentation. Could you please show some examples? That would be very useful.

**Comment by Delgan** [comment]
@cpach Sure:

```python
import requests
from loguru import logger

def send_request(message):
    data = {"message": message, "level": message.record["level"].name}
    requests.post("https://www.some-endpoint.com", json=data)

logger.add(send_request)

logger.info("Some message")  # It will generate a POST request.
```

Let me know what needs to be clarified.

**Comment by cpach** [comment]
Looks clear to me. Thank you @Delgan!
