### ISSUE TITLE
Many logs created with date in file name

### ISSUE THREAD

**Issue by AaronWaxson** [Delgan/loguru#710]
I use logger a lot  with same configuration, then I try to make a class for easy using logger like:
```python
from loguru import logger
from dataclasses import dataclass
from constants import LOG_DIR
import time


@dataclass
class LogConfig(object):
    log_name: str

    rotation: int = 100
    level: str = "DEBUG"
    fmt: str = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <y>{process}</y> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

    def __post_init__(self):
        logger.remove()

        time_str = time.strftime("%Y%m%d_%H%M%S", time.localtime(time.time()))
        log_name = f"{self.log_name}_{time_str}.log"
        log_path = LOG_DIR / log_name

        logger.add(
            log_path,
            rotation=self.rotation,
            level=self.level,
            enqueue=True,
            format=self.fmt,
        )

```
But when I use the class like:
```python
import LogConfig
LogConfig("rosbag_clipper")
logger.debug("something")
logger.debug("something else")
logger.debug("other things")
```
I got lots of log fiile with different name like:
![image](https://user-images.githubusercontent.com/37990023/191447720-e78bb9f7-f4b8-49cd-96fe-5df9eec7ca68.png)
And each log file only has one log info, Can help for that?
I only want output all log info to one file.

**Comment by Delgan** [comment]
This is because you add the file handler with `rotation=100` which means "rotate the file every time it contains more than 100 bytes".

Try to increase the treshold and it should fix your issue.

**Comment by AaronWaxson** [comment]
Thanks a lot, sry for that easy problem😓

**Comment by Delgan** [comment]
No problem let me close this issue then. :)
