### ISSUE TITLE
Loguru in flask with eventlet in thread started with eventlet tpool.execute fails

### ISSUE THREAD

**Issue by ebolam** [Delgan/loguru#711]
We're developing a new UI for KoboldAI (https://github.com/ebolam/KoboldAI) and have run into an issue when we added loguru.
For some reason when running a logger.debug(message) inside a tpool.execute function I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\ebolam\Desktop\Files\git\KoboldAI\miniconda3\lib\site-packages\eventlet\queue.py", line 118, in switch
    self.greenlet.switch(value)
greenlet.error: cannot switch to a different thread
```

**A bit more info:**
We use Flask as our UI with eventlet as the backend process. Eventlet monkey patching for threads will break other pieces of our code so it is currently off. On one specific function we have a long processing time without any sleeps so the UI will become unresponsive. To prevent that, we run that function on tpool.execute so that the UI continues to run OK. Any logger.debug() call within that tpool.execute run function will cause the above error. 

Any help would be appreciated.

**Comment by Delgan** [comment]
Please can you provide a minimal reproducible example?
Are you using `enqueue=True`?

**Comment by Delgan** [comment]
I think you need to [disable monkey patching]() of threads using:

```python
import eventlet
eventlet.monkey_patch(thread=False)
```

I remember similar issues with `gevent`.

In any case, if you can provide a fully reproducible example and need some help, feel free to re-open the issue.
