### ISSUE TITLE
Format elapsed?

### ISSUE THREAD

**Issue by jmrichardson** [Delgan/loguru#716]
Is it possible to remove the mircro seconds from timedelta?  I am using the following:

`logger.add(sys.stdout, level="INFO", format=lambda _: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> ({elapsed}, " + mem_gb() + "): {message}", colorize=True)`

Which displays:

`2022-09-30 13:51:31 (0:46:17.258451, 0.16gb): Message`

I would like to remove the ".258451" part.  Thanks for any help

**Comment by Delgan** [comment]
Hi.

The `elapsed` attribute used for formatting is of type [`datetime.timedelta`](https://docs.python.org/3/library/datetime.html#datetime.timedelta). You could [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) the logger with a new attribute from which microseconds are removed.

```python
import sys
from loguru import logger
from datetime import timedelta

def set_elapsed(record):
    seconds = int(record["elapsed"].total_seconds())
    record["extra"]["elapsed"] = timedelta(seconds=seconds)

logger.configure(patcher=set_elapsed)
logger.remove()
logger.add(sys.stdout, level="INFO", format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> ({extra[elapsed]}) {message}", colorize=True)

logger.info("Test")
```

I could probably add custom formatter to `elapsed` as a new feature, though.

**Comment by jmrichardson** [comment]
Hi @Delgan

Thank you and appreciate the great package!
