### ISSUE TITLE
Getting sink location in logger.bind.

### ISSUE THREAD

**Issue by nopnopwei** [Delgan/loguru#718]
Hello again,

In continuation of the previous issue that I posted about using logger with discord.py, I notice that setting up `.add` in my `/resgister` command is not an optimal solution as the sink is removed every time the bot is reset. 

So I thought of doing something like this whenever a command is called, but not sure if it's feasible or not.

```py
user_log = logger.bind(task=f"{ctx.author.id}")

if user_log.sink in ["<stderr>", None]:
    logger.add(
        f"logs/user/{ctx.author.id}.log",
        format="{time:YYYY-MM-DD at HH:mm:ss} {message}",
        filter=lambda record, task=ctx.author.id: record["extra"]["task"] == f"{task}",
    )
    user_log = logger.bind(task=f"{ctx.author.id}")

user_log.log(...)
```

Since `logger.sink` is not a thing, Maybe I could do string manipulation and check sink's location but I'm wondering is there an easier way in doing so, or do you have any suggestion on a better approach to this?

**Comment by Delgan** [comment]
Hi.

What do you mean by "the sink is removed every time the bot is reset"?
Are you calling `logger.remove()` or is the application started again?

Why not:
```python
registered_users = set()

if not ctx.author.id in registered_users:
    registered_users.add(ctx.author.id)
    logger.add(...)
```

**Comment by nopnopwei** [comment]
Hello @Delgan 

Apologies for not being clear. What I meant by reset is the bot restarting. What's happening is that whenever the bot restarts, the user will have to `/register` again as I believe the sink's cache is removed on application restart.

**Comment by Delgan** [comment]
Fine, I understand. :+1: 

What about the proposed solution of using a `set()` to know if a sink already exists for the user and add it if not?

**Comment by nopnopwei** [comment]
Hello @Delgan 

Your suggestion worked as intended and was much more clean. Thanks again :)
