### ISSUE TITLE
multi "opt" options, only the last work.

### ISSUE THREAD

**Issue by Yead** [Delgan/loguru#729]
Hi, thanks for the work in loguru. but I meet some problems here.

**my needs**
I want to format my logger with self-growing index in context, but I don't want to lose the correct line number, I found [`fmt` +` opt(depth=1)`] can give me my need, but custom formatting will lose colors, which I guess can be solved by   `opt(colors=True)`. So I combine them and wrote codes like this:

**my solution**
 
```python
import sys
from loguru import logger
name = "log"
context = {"user": "A",  "index": 0}
fmt = "[{level}] {extra[user]}_{extra[index]}  <{module}>{function}:{line}  {message}" 
logger.remove(handler_id=None)

logger.add(sys.stderr, format=fmt, level="DEBUG")
logger.add("test.log",  format = fmt, level = "DEBUG")

logger_event = logger.bind(name=name)

def log_info1(str_):
    logger_event.opt(depth=1).opt(colors=True).bind(**context).info(f"<red>{str_}</red>", extra=context)

def log_info2(str_):
    logger_event.opt(colors=True).opt(depth=1).bind(**context).info(f"<red>{str_}</red>", extra=context)

log_info1("test")
log_info2("test")

# output
# [INFO] A_0  <test_demo>log_info1:14  test
# [INFO] A_0  <test_demo><module>:20  <red>test</red>
```

I found only the latter 
 `.opt` took effect when  `.opt` apprear  twice in code, when I put depth behind the color, I will got logger with correct line without color, when I put color behind depth, I will got colorful logger with wrong number of line.

May I ask if I am using it correctly？

**Comment by Delgan** [comment]
Hi @Yead.

This is actually the intended behavior. The `.opt()` is not meant to be chained, you have to specify all modifiers at once, like `.opt(depth=1, colors=True).

I see `opt()` as a way to modify a messages specifically, it's not designed to modify the `logger` globally.

If you need the options to stack, you may need to use a wrapper. Let me know with a concrete example if you need help.

**Comment by Yead** [comment]
I am so sorry to miss the notification, thanks for your prompt reply and clear explanation!!
It's too stupid for me to use ‘opt()’  multi times instead of  passing two parameters(for I only saw one parameter in all example).
My problem have beed solved, thanyou again!
