### ISSUE TITLE
How  to set rotation filename formatter

### ISSUE THREAD

**Issue by imlison** [Delgan/loguru#733]
Currently, the history  log file name is  like 'app.2022-10-24_10-07-23_000000.log', but i want to make  it like 'app.log.2022-10-24'. Although using compress paramter can rename log file  but it is so inconvenient. Is  it  there anyway to implemente this?
thanks!

**Comment by Delgan** [comment]
You can set the date format in your file name like `logger.add("{app.log.{time:YYYY-MM-DD}")` but apart from that it's not possible to rename the file without using `compress`.

**Comment by imlison** [comment]
> You can set the date format in your file name like `logger.add("{app.log.{time:YYYY-MM-DD}")` but apart from that it's not possible to rename the file without using `compress`.

I think the best idea is pass a parameter named 'rename format' to `logger.add`, making `generate_rename_path` to generate a custom file name.

**Comment by Delgan** [comment]
Honestly I can understand you interest to such feature, but I don't feel like extending the existing `.add()` function to support this use case. I personally don't think the name of backup file is very important, and the `compress` workaround isn't that complicated in my opinion.

**Comment by imlison** [comment]
> the compress workaround isn't that complicated
Yes, it is not complicated and that's how I implemented it.

>  I personally don't think the name of backup file is very important
No, since loguru was introduced into our old projects, it's more important that adapting filename to existing toolchains.

Anyway, hope to see the offical implementation someday in the feature.
