### ISSUE TITLE
Traceback (most recent call last):   File "F:/data/yolox---/源码/YOLOX-main/tools/train.py", line 8, in <module>     from loguru import logger ImportError: cannot import name 'logger' from 'loguru' (unknown location)

### ISSUE THREAD

**Issue by haobingpeng** [Delgan/loguru#734]

**Comment by Delgan** [comment]
Please can you provided more information?

Did you install `loguru` correctly?

**Comment by haobingpeng** [comment]
The problem was solved by downloading loguru= version 0.6.0



At 2022-10-26 14:36:25, "Delgan" ***@***.***> wrote:

Please can you provided more information?

Did you install loguru correctly?

**Comment by Delgan** [comment]
Fine. :+1:
