### ISSUE TITLE
Please help with filter

### ISSUE THREAD

**Issue by Vladimir-v1** [Delgan/loguru#735]
Hello!

Can you please help me, I have read documentation many times and still have a problems

I need to split files using the filter but I think that I'm doing something wrong. I need to get all system messages in main.log and other provider specific info in separate log files

My example:

 ```python
import sys
from loguru import logger

PROVIDERS = ['x', 'y', "z"]

handlers = [dict(sink=sys.stdout, format="[{time}] - {extra} - {message}"),
            dict(sink="./logs/main.log", format="[{time}] - {extra} - {message}")]

for provider in PROVIDERS:
    handlers.append(
        dict(sink=f"./logs/{provider}.log", format="[{time}] - {extra} - {message}",
             filter=lambda record: record['extra'].get('name') == f"{provider}")
    )

logger.configure(
    handlers=handlers
)

d = {}

for item in PROVIDERS:
    d[item] = logger.bind(name=f"{item}")
    d[item].info(item)
    d[item].info(f"{item}-222")

logger.info('Test')
```

In main.log I have this info:

[2022-10-26T17:20:49.641614+0600] - {'name': 'x'} - x
[2022-10-26T17:20:49.642614+0600] - {'name': 'x'} - x-222
[2022-10-26T17:20:49.642614+0600] - {'name': 'y'} - y
[2022-10-26T17:20:49.642614+0600] - {'name': 'y'} - y-222
[2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z
[2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z-222
[2022-10-26T17:20:49.643614+0600] - {} - Test

I'm getting these same results in all files x.log, y.log, z.log:

x.log - [2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z
[2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z-222

y.log - [2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z
[2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z-222

z.log - [2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z
[2022-10-26T17:20:49.642614+0600] - {'name': 'z'} - z-222

Thank you so much in advance!

**Comment by Vladimir-v1** [comment]
Also I tried writing logs after all bindings as showed here https://buildmedia.readthedocs.org/media/pdf/loguru/latest/loguru.pdf - page 38

...
d = {}

for item in PROVIDERS:
    d[item] = logger.bind(name=f"{item}")    


for item in PROVIDERS:
    log = d[item]
    log.info(item)
    log.info(f"{item}-222")
    
logger.info('Test')

But I'm having the same results, in all x,y,z log files I have only these lines:

[2022-10-26T17:29:03.007427+0600] - {'name': 'z'} - z
[2022-10-26T17:29:03.008430+0600] - {'name': 'z'} - z-222

**Comment by Vladimir-v1** [comment]
I don't have a problems if I'm doing like this example (but this way isn't good for case)

...

handlers = [dict(sink=sys.stdout, format="[{time}] - {extra} - {message}"),
            dict(sink="./logs/main.log", format="[{time}] - {extra} - {message}")]

handlers.append(
    dict(sink=f"./logs/x.log", format="[{time}] - {extra} - {message}",
         filter=lambda record: f"x" in record['extra']))
handlers.append(
    dict(sink=f"./logs/y.log", format="[{time}] - {extra} - {message}",
         filter=lambda record: f"y" in record['extra']))

handlers.append(
    dict(sink=f"./logs/z.log", format="[{time}] - {extra} - {message}",
         filter=lambda record: f"z" in record['extra']))


d = {}

d['x'] = logger.bind(x=True)
d['y'] = logger.bind(y=True)
d['z'] = logger.bind(z=True)

for item in PROVIDERS:
    log = d[item]
    log.info(item)
    log.info(f"{item}-222")

results in x,y,z log files:

x.log - [2022-10-26T17:42:36.599489+0600] - {'x': True} - x
[2022-10-26T17:42:36.599489+0600] - {'x': True} - x-222

y.log - [2022-10-26T17:42:36.600491+0600] - {'y': True} - y
[2022-10-26T17:42:36.600491+0600] - {'y': True} - y-222

z.log - [2022-10-26T17:42:36.600491+0600] - {'z': True} - z
[2022-10-26T17:42:36.600491+0600] - {'z': True} - z-222

**Comment by Vladimir-v1** [comment]
I think I found solution, problem was in lambda function, it isn't capture value but used variable in runtime

the solution is to add specific function and set default value to capture it:

for provider in PROVIDERS:

    def specific_only(record, prov=provider):
        return prov in record["extra"]

    handlers.append(
        dict(sink=f"./logs/{provider}.log", format="[{time}] - {extra} - {message}",
             filter=specific_only))

logger.configure(
    handlers=handlers
)

d = {}

for provider in PROVIDERS:
    context = {provider: True}
    d[provider] = logger.bind(**context)

for item in PROVIDERS:
    log = d[item]
    log.info(item)
    log.info(f"{item}-222")


logger.info('Test')

**Comment by Delgan** [comment]
Hi @Vladimir-v1.

I don't see the problem with your code. When I run the following:

```python
import sys
from loguru import logger

PROVIDERS = ['x', 'y', "z"]

handlers = [dict(sink=sys.stdout, format="[{time}] - {extra} - {message}"),
           dict(sink="./logs/main.log", format="[{time}] - {extra} - {message}")]

for provider in PROVIDERS:
   def filt(record, prov=provider):
       return record["extra"].get("name") ==f"{prov}"

   handlers.append(
       dict(sink=f"./logs/{provider}.log", format="[{time}] - {extra} - {message}",
            filter=filt)
   )

logger.configure(
   handlers=handlers
)

d = {}

for item in PROVIDERS:
   d[item] = logger.bind(name=f"{item}")
   d[item].info(item)
   d[item].info(f"{item}-222")

logger.info('Test')
```

I get this in `main.log`:

```log
[2022-10-27T09:05:38.919139+0200] - {'name': 'x'} - x
[2022-10-27T09:05:38.919479+0200] - {'name': 'x'} - x-222
[2022-10-27T09:05:38.919733+0200] - {'name': 'y'} - y
[2022-10-27T09:05:38.920043+0200] - {'name': 'y'} - y-222
[2022-10-27T09:05:38.920292+0200] - {'name': 'z'} - z
[2022-10-27T09:05:38.920567+0200] - {'name': 'z'} - z-222
[2022-10-27T09:05:38.920892+0200] - {} - Test
```

This is the expected output, given you're calling:

```python
log.info(item)
log.info(f"{item}-222")
```

**Comment by Delgan** [comment]
@Vladimir-v1 You have to do it the same way: using a `filter` to exclude them.

For example:

```python
def main_filter(record):
    return record["extra"].get("name") not in PROVIDERS

main_handler = dict(sink="./logs/main.log", format="[{time}] - {extra} - {message}", filter=main_filter)
```

**Comment by Vladimir-v1** [comment]
Great, Thank you! )

Also, Thank you so much for your Great solution, Loguru!
