### ISSUE TITLE
Logger shows wrong function name inside decorator

### ISSUE THREAD

**Issue by MisterBianco** [Delgan/loguru#74]
I have the following code:

```
from functools import wraps

class base:
    @logdoc
    def __init__(self, head : bool):
        """docstring test""
        super(base).__init__(self)
        
def logdoc(func):
    @wraps(func)
    def wrapped(*args, **kwargs):
        logger.opt(depth=0).info(func.__doc__)
        return func(*args, **kwargs)
    return wrapped
```

What should happen is on execution of the __init__ method there should be a log output like:

```
19:33:09.462 | INFO     | my_file:__init__:16 - docstring test
```
but instead I get:
```
19:33:09.462 | INFO     | decorators:wrapped:16 - docstring test
```

If I set the depth to 1 then I get __main__:<module> Which is also not accurate.. Any suggestions?

**Comment by Delgan** [comment]
Hello @MisterBianco.

I did not realize that, but it seems the original name of the wrapped function is not reachable from a `frame` object. While [inspecting the stack](https://docs.python.org/3/library/inspect.html#types-and-members), the logger does not have access to the `function` object that `functools.wraps()` conveniently rename. Only the `__code__` object is avaiable, from which the `co_name` attribute is used to define the name of the function, but `functools.wraps()` does not modify it.

It annoys me, but there is no way to fix that as far as I know. 😕 

In the next `v0.3.0` release, there will be a workaround though. I plan to add a new method so one can update the `record` dict before it's sent to the handlers. That should look like this:

```python
def wrapped(*args, **kwargs):
    name, doc = func.__name__, func.__doc__
    logger.patch(lambda r: r["function"] = name).info(doc)
    return func(*args, **kwargs)
```

**Comment by MisterBianco** [comment]
That would be awesome :) thank you for looking into this 💯

**Comment by Delgan** [comment]
I just release `0.3.0` with the new [`.patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) method.

The code snippet previously provided should work fine now! :smile:
