### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by superlevure** [Delgan/loguru#740]
First of all, thanks for the great package 🙏 

I was wondering if a release was planned soon ? The latest `0.0.6` is [almost a year old](https://github.com/Delgan/loguru/releases/tag/0.6.0) and 79 commits behind `master`. 

I'm especially interested in this commit being released: https://github.com/Delgan/loguru/commit/0f0b698f91cfd9aadff10aa750bfc8abb4b6a18a

Cheers!

**Comment by Delgan** [comment]
Hi @superlevure. :)

You are right, it seems indeed time to publish a new release so that users can benefit from the latest improvements. I'll see if I can fit some additional bug fixes, and I'll release a new version during the next week.

**Comment by Oblynx** [comment]
Amazing! Came here to ask exactly the same, thanks. Need any help?

**Comment by Delgan** [comment]
Hey @Oblynx, thanks for offering your help. :+1: 

I don't think there is much to do, I'll finalize some fixes and try to make a release before the end of the week-end.

**Comment by Sefank** [comment]
95 commits to master since this release! It's quite a good time to draw a period to the amazing project for now, isn't it?

**Comment by Delgan** [comment]
Sorry, I was not able to deliver in time as I thought. I would love to finish fixing some bugs that are in the backlog before releasing a new version. I'm working on it right now, but I can't say how long it will take to finish.

In the meantime, you can benefit from the latest changes by installing a version from a hash commit:
```sh
pip install git+https://github.com/Delgan/loguru@16dbf79b861bc4b7930c2915ee38794c9d3d2b1d
```

**Comment by Delgan** [comment]
Sorry to keep you all waiting.
Next week I should be able to spend more time on Loguru.
I can't promise anything, but I would have in mind to publish a new version.

**Comment by Delgan** [comment]
Version [`0.7.0`](https://github.com/Delgan/loguru/releases/tag/0.7.0) has been published on Pypi: https://pypi.org/project/loguru/0.7.0/

Sorry this took so long, and thank you for your patience.

**Comment by mgorny** [comment]
Thank you!
