### ISSUE TITLE
a question with wrapping logutil.

### ISSUE THREAD

**Issue by CodingDjz** [Delgan/loguru#741]
Hi,
I wrapped a logutil with class,but I have a question:

log_service.py(not all code)
```
from loguru import logger as _logger

class Logger:
    __instance = None
    __init_flag = False
    format = '<b>{level} {extra[action_code]} {time:HH:mm:ss} **{module}.{function}{line}** </b>:{message}'

    def __new__(cls, *args, **kwargs):
        if cls.__instance is None:
            cls.__instance = super(Logger, cls).__new__(cls, *args, **kwargs)
        return cls.__instance

    def __init__(self) -> None:
        _logger.add("info_{time:YYYY-MM-DD}.log", colorize=True, format=self.format, rotation='00:00', level="INFO", compression="zip", backtrace=True,diagnose=True, retention='3 days',enqueue=True)
        self.logger = _logger.bind(action_code="0")
        other init code...

    def info(self, msg, *args, **kwargs):
        return self.logger.info(msg, *args, **kwargs)

    def reset_log_context(self, action_code):
        self.logger = self.logger.patch(
            lambda record: record["extra"].update(action_code=action_code))
        return self.logger
```

why I wrapping this calss:
I wrapping this class because action_code alaway change, I need bind or patch new value with logger.Wrapped this class I can update format with "reset_log_context" method  .

question:
when I call methon "info",is alaways print `INFO  00:27:45 **log_service.info** 42`,,is there any way to show the real code line **{module}.{function}{line}**  where I call Logger().info(msg)?

**Comment by imlison** [comment]
You  should deliver the `depth`  paratemer to `opt` method.
`return self.logger.opt(depth=1).info(msg, *args, **kwargs)`

**Comment by CodingDjz** [comment]
> You should deliver the `depth` paratemer to `opt` method. `return self.logger.opt(depth=1).info(msg, *args, **kwargs)`

thanks，its work well！I have to learn more about the lib。

**Comment by Delgan** [comment]
Thanks @imlison for helping @CodingDjz. :smiley:
