### ISSUE TITLE
pytest capsys fixture does not work with loguru

### ISSUE THREAD

**Issue by elisiariocouto** [Delgan/loguru#745]
Hello.

When using pytest's `capsys` fixture, the stdout and stderr are always empty.

Here's an example:
```python
from loguru import logger
import sys

# This works, printing directly to sys.stderr
def test_print(capsys):
    print("Some Error", file=sys.stderr)
    out, err = capsys.readouterr()
    assert "Some Error" in err


# This does not work even tough loguru's log is capture on pytest summary
def test_logger(capsys):
    logger.error("Some Error")
    out, err = capsys.readouterr()
    assert "Some Error" in err
```

When running this file with pytest, I get this output:
```
============================================ FAILURES =============================================
___________________________________________ test_logger ___________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x105daecb0>

    def test_logger(capsys):
        logger.error("Some Error")
        out, err = capsys.readouterr()
>       assert "Some Error" in err
E       AssertionError: assert 'Some Error' in ''

test.py:15: AssertionError
-------------------------------------- Captured stderr call ---------------------------------------
2022-11-08 23:42:01.267 | ERROR    | test:test_logger:13 - Some Error
===================================== short test summary info =====================================
FAILED test.py::test_logger - AssertionError: assert 'Some Error' in ''
```

I tried to use the workaround that is on the documentation but it doesn't work since with the `capsys` fixture.

Any workaround for this use case?

Thank you in advance

**Comment by Delgan** [comment]
Hello.

So the issue you're facing is indeed the same as #703.
It is a problem of execution order:

1. Loguru is imported which automatically adds a handler logging to `sys.stderr` object
2. Pytest start an unit test with `capsys` and thus replace `sys.stderr` with a custom object to capture `print()` calls
3. A message is sent by Loguru, it writes to the old `sys.stderr` and thus is not capture by Pytest

I don't know exactly how the logged message happens to be captured by Pytest outside of the `capsys` fixture, but basically to make sure logs are capture by `capsys` you need to call `.add()` from within the test (once Pytest has replaced `sys.stderr`):

```python
def test_logger(capsys):
    logger.add(sys.stderr)
    logger.error("Some Error")
    out, err = capsys.readouterr()
    assert "Some Error" in err
```

**Comment by elisiariocouto** [comment]
Hello @Delgan. Thank you for your quick answer. This indeed resolves the issue. Thank you
