### ISSUE TITLE
what is the different between patch() and bind()?

### ISSUE THREAD

**Issue by CodingDjz** [Delgan/loguru#748]
Hi，I see bind and patch descriped in doc is：

_bind_

> Bind attributes to the extra dict of each logged message record.

_patch(patcher)_

> Attach a function to modify the record dict created by each logging call.

I have a question：

If my log format is '<b><green>{time:HH:mm:ss} {level} {extra[action_no]} {module}.{function}.{line}</green>:</b>{message}'

action_no param always change，so what the different between use `logger.bind(action_no=action_no).info(msg)`  and  `logger.patch(lambda record: record["extra"].update(action_no=action_no).info(msg)` ?

**Comment by Delgan** [comment]
@CodingDjz In your case there is no difference, the two are equivalent. :)

The `patch()` is useful when the value is not static or depends on some attributes of the `record`.

**Comment by CodingDjz** [comment]
@Delgan thanks！I like loguru，its a excellent lib！
