### ISSUE TITLE
Add optional name to logger to avoid getframe

### ISSUE THREAD

**Issue by tds333** [Delgan/loguru#759]
Add the "name" to _options and use it when it is not None as the name for the logger. Avoid to call getframe in case.

Everytime when a logger logs something a frame object is used to get the callers module name and use it for the logger.
If you log in a loop calling log methods can be very expensive and time consuming because of this additions function calls.
Even more for Python 3.11 where the frame object is only constructed if needed. https://docs.python.org/3/whatsnew/3.11.html#cheaper-lazy-python-frames

For Python 3.11 if you use loguru every function the frame will be created and the performance improvement of 3.11 is negated.

This can be done optional and backward compatible.
If a new logger will be created with bind, patch or opt a new parameter "name" can be used to set the _option "name" and use it.

**Comment by Delgan** [comment]
The  `frame` object is not only used to know the name of the logger, it also gives other essential logging information like the line number, the function or the file. I don't think we can get away from it. Standard `logging` does need it as well: https://github.com/python/cpython/blob/ee6015650017ca145a48c345311a9c481949de71/Lib/logging/__init__.py#L1616

**Comment by tds333** [comment]
You are right. Looking deeper into it and also in the std Python logging implementation it is more needed to improve here than excpected. Python std logging has the ability with "_srcfile" to disable this. But it is rarely used. And you loose the function name and lineno info. Also loosing this info it is not worth it.

Thanks for responding so fast. I'll close it.
