### ISSUE TITLE
logger.add("something.log"...) - works, but it's also displaying the logs in output/stderr?

### ISSUE THREAD

**Issue by QuantumForced** [Delgan/loguru#761]
Apologies for my likely incorrect terminology (I'm new to programming)

`logger.add("handle_edited.log", format="{time:DD-MMM-YY HH:mm:ss} | {level: <8} | {function: ^18} | {line: >3} | {message}", retention="7 days", compression="zip")`

The above works perfectly for adding all `logger.info("something")` to the .log file. However, It's also displaying those same logs to my terminal/run window in pycharm (stderr I think is the right terminology?). Here's an example:

Code snippet from script:
`print("Initiating handle_edited.py script...")`
`logger.info("Initiating handle_edited.py script...")`

Respective line in handle_edited.log:
`04-Dec-22 16:19:27 | INFO     |      <module>      |  45 | Initiating handle_edited.py script...`

Output terminal/stderr:
`2022-12-04 16:17:44.058 | INFO     | __main__:<module>:45 - Initiating handle_edited.py script...`
`Initiating handle_edited.py script...`

How can I prevent this from happening?

Thanks!

**Comment by Delgan** [comment]
I guess you should call `logger.remove()` beforehand, the output you're seeing likely comes from the default handler logigng to `sys.stderr`.

**Comment by QuantumForced** [comment]
> I guess you should call `logger.remove()` beforehand, the output you're seeing likely comes from the default handler logigng to `sys.stderr`.

That fixed it, thank you!

**Comment by Delgan** [comment]
Closing the issue then. :+1:
