### ISSUE TITLE
contextlib.redirect_stderr does not work for loguru

### ISSUE THREAD

**Issue by shanehh** [Delgan/loguru#764]
My envinfo

- OS: macOS 12.5
- Python3: 3.7.12
- loguru==0.6.0

Source code, `test.py`:

```python
import contextlib
import os

from loguru import logger

with open(os.devnull, "w") as devnull:
    with contextlib.redirect_stderr(devnull), contextlib.redirect_stdout(devnull):
        logger.debug("This is a debug message")
        logger.info("This is an info message")
        logger.warning("This is a warning message")
        logger.error("This is an error message")
        logger.critical("This is a critical message")
```

Output:

```
❯ python test.py
2022-12-11 18:08:59.850 | DEBUG    | __main__:<module>:10 - This is a debug message
2022-12-11 18:08:59.851 | INFO     | __main__:<module>:11 - This is an info message
2022-12-11 18:08:59.851 | WARNING  | __main__:<module>:12 - This is a warning message
2022-12-11 18:08:59.851 | ERROR    | __main__:<module>:13 - This is an error message
2022-12-11 18:08:59.851 | CRITICAL | __main__:<module>:14 - This is a critical message
```

**Comment by Delgan** [comment]
This happens because the default handler of Loguru (logging to `stderr`) is added during `import`.
Consequently, when `redirect_stderr` is called, Loguru already own it's own reference of `sys.stderr` and logs won't be affected by the redirection.

As a workaround, you can replace the default handler with  a `lambda` to dynamically retrieve the `sys.stderr` object:

```python
import contextlib
import os

from loguru import logger

logger.remove()
logger.add(lambda m: sys.stderr.write(m), colorize=True)

with open(os.devnull, "w") as devnull:
    with contextlib.redirect_stderr(devnull), contextlib.redirect_stdout(devnull):
        logger.debug("This is a debug message")
        logger.info("This is an info message")
        logger.warning("This is a warning message")
        logger.error("This is an error message")
        logger.critical("This is a critical message")
```

**Comment by shanehh** [comment]
> This happens because the default handler of Loguru (logging to `stderr`) is added during `import`. Consequently, when `redirect_stderr` is called, Loguru already own it's own reference of `sys.stderr` and logs won't be affected by the redirection.
> 
> As a workaround, you can replace the default handler with a `lambda` to dynamically retrieve the `sys.stderr` object:
> 
> ```python
> import contextlib
> import os
> 
> from loguru import logger
> 
> logger.remove()
> logger.add(lambda m: sys.stderr.write(m), colorize=True)
> 
> with open(os.devnull, "w") as devnull:
>     with contextlib.redirect_stderr(devnull), contextlib.redirect_stdout(devnull):
>         logger.debug("This is a debug message")
>         logger.info("This is an info message")
>         logger.warning("This is a warning message")
>         logger.error("This is an error message")
>         logger.critical("This is a critical message")
> ```

Thank you!
