### ISSUE TITLE
According to VizTracer, there is a long wait on logging emit.

### ISSUE THREAD

**Issue by bill97385** [Delgan/loguru#768]
![image](https://user-images.githubusercontent.com/8643040/209931735-1ae80df5-6930-4856-ae64-6862b41c32d5.png)

A single line of log cost more than 100ms to complete. 

This seems unusual. Is there a reason for this? 

It appears that it is waiting for IO to be unlocked, but it seems to be taking a bit too long to wait. 

Here is the viztracer file.

[result1.zip](https://github.com/Delgan/loguru/files/10318630/result1.zip)

Any advice would be greatly appreciated.

**Comment by Delgan** [comment]
Hi @bill97385.

How many logging handlers are you using? Only the default one?

I see function call related to `colorama` in the screen you shared, you can maybe try to simplify your logging configuration to see if it helps:

```python
import sys
from loguru import logger

logger.remove()
logger.add(sys.stderr, colorize=False)  # Disable colorama
```

Additionally, I see you're using a `ThreadPoolExecutor`. As Loguru handlers are thread-safe, multiple threads can't log messages at the same time and need to acquire a lock first. That mean your thread might be blocked until others threads finish to log the message.

Do you have any minimal reproducible example to share I could investigate?
