### ISSUE TITLE
feature: limit printed traceback lines

### ISSUE THREAD

**Issue by Fak3** [Delgan/loguru#77]
If handler `backtrace` is True, the output traceback is very long. Especially for async functions - more than a hundred of lines come from the event loop, and clutter the output (example: https://gist.github.com/Fak3/81cf8554414e2d82cfcad93294f3e981)

It would be nice to have a way to limit number of backtrace lines printed, like `sys.tracebacklimit = 3` does.

**Comment by Delgan** [comment]
In the next `v0.3.0` release, you should be able to set `backtrace=False` to reduce the size of the traceback, a new parameter `diagnose` will allow to independently control whether or not the variable values should be displayed. 👍

**Comment by Delgan** [comment]
Starting from `v0.3.0`, the exception formatting will rely on the [`sys.tracebacklimit`](https://docs.python.org/3/library/sys.html#sys.tracebacklimit) variable to determine the depth of the stacktrace to display.

Also, note that adding an handler with `backtrace=False` should drastically reduce the number of frames displayed.
