### ISSUE TITLE
[Question] Is there an easy way to disable logging completely 

### ISSUE THREAD

**Issue by radugrosu** [Delgan/loguru#779]
Is there something like an environment variable that would disable all logging? Thanks

**Comment by Delgan** [comment]
It depends on how your logger and handlers are configured.

You could use [`logger.disable("")`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.disable) for example.

**Comment by radugrosu** [comment]
Thanks, I was trying to find out if the logger was behind the random hangs in my script (which uses forking multiprocessing) and an option to switch off logging completely entirely _and_ reliably would have been quite convenient.

**Comment by Delgan** [comment]
The most efficient way is to call `logger.remove()` which will remove all handlers, therefore disabling entirely the logging.
