### ISSUE TITLE
Logger.catch and logger.contextualize interaction

### ISSUE THREAD

**Issue by uditrana** [Delgan/loguru#783]
One of my use cases involve calling a data cleaning function over a set of data_ids using a mapstar multiprocessing pool. 

But I want to catch errors and include the _id of the passed in data to the logged output. Right now, I am using logger.contextualize.

```python
logger.add(
    Path("logs/Process JSONs {time:MM-DD at HH:mm}.log"),
    format="{time:YYYY-MM-DD at HH:mm} | {level} | {extra} | {message}",
    enqueue=True,
    backtrace=False,
    diagnose=True,
    level="ERROR",
    catch=True,
)

def clean(_id):
     play = json.load(f"{_id}.json")
     with logger.contextualize(_id=_id):
            # do stuff
            logger.error("Message")
            1/0
```

This is roughly the output I get logged:
```
2023-01-14 at 05:11 | ERROR | {'_id': '123123'} | Message
2023-01-14 at 05:11 | ERROR | {} | An error has been caught in function 'clean', ...
```

Basically, the key thing is that when an unexpected, runtime error is "caught"... it seems to lose the "extras" context. 

How can I make sure this _id information gets propagated and outputted to the log?

**Comment by Delgan** [comment]
The [`catch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch) decorator can be used as a context manager as well:

```python

def clean(_id):
     play = json.load(f"{_id}.json")
     with logger.contextualize(_id=_id):
            with logger.catch(message="Message"):
                1/0
```

**Comment by uditrana** [comment]
So is there any way you pass _id as an extra directly into the catch context manager?

Or do we have to stack context_managers like this for every function?

**Comment by Delgan** [comment]
Sorry, I'm not sure to understand your question. The "extra" attribute is filled with `logger.contextualize()`. The `logger.catch()` is just syntactic sugar for a `try / catch`, it does not modify the "extra" dict. However, the "extra" dict of message logged though `logger.catch()` will contain all the values assigned by the surrounding `contextualize()`.

If you're seeing error message logged without the `id_` attribute you are expecting, that means the exception was caught outside the scope of the `contextualize()` context manager.

I would need a fully reproducible example to help you further.

**Comment by uditrana** [comment]
Yea I think I get what you are saying, and to do what I want right now, I have to use nested context managers. 

I am wondering if it would make sense to have an option for the logger.catch decorator to automatically add input arguments into extras. But I should be able to create my own decorator for that now.

**Comment by Delgan** [comment]
In my opinion, it's better to separate different purposes in different methods.
The `contextualize()` method is there to feed logged messages with context values, and the `catch()` method is there to capture and log unexpected exceptions.
I don't think we should extend the `catch()` method with features from the `contextualize()` method, but I recommend you to create a small context manager if you find it more convenient for your personal use. :+1:
