### ISSUE TITLE
Add orange as default color for warning

### ISSUE THREAD

**Issue by mrx23dot** [Delgan/loguru#787]
Orange for 'warning' would make more sense, currently it's like mustard color, which is close to grey if you have small text/big monitor, 
or is it only my monitor?

<img width="138" alt="2023-01-20 10_14_14-cmd - python (Admin)" src="https://user-images.githubusercontent.com/4163396/213670896-adf8a3c7-a908-4dd3-acf7-6c9fad3d2838.png">

And it's fully the same if you have blue light filter on (built into win10).

I know it can be custom color,  but why not make it readable out of the box.
scientific way: https://webaim.org/resources/contrastchecker/

#C8C87F vs #C6C6C6
Contrast Ratio 1.02:1

orange:
#FF9500 vs #C6C6C6
Contrast Ratio 1.28:1

**Comment by Delgan** [comment]
Loguru uses special [ansi sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) to colorize the messages. Not all terminals support all possible sequences. Only 8 colors are available in [the most commonly supported sequence](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit), among which there is "yellow" but no "orange" code. 
For this reason, the default color of "WARNING" message is "yellow", to ensure maximum compatibility regardless of terminal used.

Color rendering may vary from one terminal to another. If the colors do not display well in your terminal, I suggest you set [the environment variable `"LOGURU_WARNING_COLOR"`](https://loguru.readthedocs.io/en/stable/api/logger.html#env) with [a tag containing an appropriate RGB value](https://loguru.readthedocs.io/en/stable/api/logger.html#color) (assuming your terminal supports it).
