### ISSUE TITLE
Optional %s in logger

### ISSUE THREAD

**Issue by ShivKJ** [Delgan/loguru#788]
Hi,

I find `loguru` simple and straightforward. Logging is an essential part of a project and it should be simple to use. Loguru is really a `logging for humans`.

I was going [through this link](https://github.com/Delgan/loguru#modern-string-formatting-using-braces-style). As someone who plans to use it may face some challenges. For example, existing projects can well be using python-logging with `%s` for injecting messages/information. In `loguru`, `{}` is used for the same.

Is there a way to enable `%s` instead of `{}` as this will attract fewer changes in the existing code base?

**Comment by Delgan** [comment]
Hi. :)

I plan to give more freedom to the user concerning the formatting of the messages, but for the moment there is unfortunately no existing solution.

I recommend using a regex to search the places in your codebase that need to be updated, or to progressively introduce `loguru` on a module-per-module basis to reduce risk of regression while still propagating logs to standard handlers (using a  `PropagateHandler`).
