### ISSUE TITLE
Question about intercepting standard logging from modules

### ISSUE THREAD

**Issue by rchardb** [Delgan/loguru#79]
When using stdlib logging module my script seems to get logging info from 3rd party modules (like selenium) for 'free'. I've added the recommended InterceptHandler class code at the beginning of my script and am not seeing expected logging info from other modules flow through.

I'm unsure how to proceed.  Perhaps I've misunderstood if this is possible or there's additional tasks required to complete the intercept.

Help!

**Comment by Delgan** [comment]
Hi @rchardb. Do you have some code snippet so I can more specifically address your problem?

I think your are maybe missing an `logger.setLevel()`. The standard root logger use a `WARNING` level by default, so you probably have to add `logger.getLogger(None).setLevel("DEBUG")` after adding the `InterceptHandler()`.

That made me realize that the example in the Readme is indeed incomplete, and could be actually even simpler by using `logging.basicConfig()`. I will update the code sample, I recommand you to use:

```python
logging.basicConfig(handlers=[InterceptHandler()], level=0)
```

Please, tell me if that solved your issue.

**Comment by rchardb** [comment]
That worked perfectly. Thank you so much!

**Comment by Delgan** [comment]
@rchardb Great! I'm closing this issue then. 👍
