### ISSUE TITLE
`@logger.catch` for async task and catch `__all__` from module.

### ISSUE THREAD

**Issue by PieceOfGood** [Delgan/loguru#801]
I would love to have comments on [this post](https://github.com/Delgan/loguru/issues/171#issuecomment-1418922275).

It is also interesting to know the following: if it is not possible to catch exceptions with the `@logger.catch` decorator for asynchronous functions used only as tasks, except by explicitly specifying this decorator above the declaration of each such function, then is there any possibility, say, to declare isolate a set of such functions in a separate module through `__all__ = []`, and then, when importing into `__init__.py`, loop through them and force them to be decorated? For example:
```python
# __init__.py
from loguru import logger
import module

for name in module.__all__:
    func = getattr(module, name)
    wrapped = logger.catch_wrapper(func)
    setattr(module, name, wrapped)

__all__ = [ "module" ]
```

**Comment by PieceOfGood** [comment]
Understood the last one.
```python
# __init__.py
from loguru import logger
import module

for name in module.__all__:
    func = getattr(module, name)
    wrapped = logger.catch()(func)
    setattr(module, name, wrapped)

__all__ = [ "module" ]
```

**Comment by Delgan** [comment]
Sorry for not answering sooner.

I would certainly not advise to blindly decorate all variables in `__all__`, but you can indeed use `logger.catch()` this way (like any other decorator in Python).
