### ISSUE TITLE
Report a bug, for multiprocess using loguru

### ISSUE THREAD

**Issue by AlreadyM** [Delgan/loguru#806]
The Python version :3.11.0
The Loguru version :0.6.0
Your operating system name and version : 
         Ubuntu 20.04.5 LTS
         Linux version 5.15.0-60-generic (buildd@lcy02-amd64-017) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023

Your development environment and local setup (IDE, Terminal, project context, any relevant information that could be useful)：

       VsCode, ssh remote to ubuntu server

Bug About --> Creating independent loggers with separate set of handlers[](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers)

Description:
     In main function , init loguru with sink='main_process.log'
            Init a child process with multiprocessing and ,init loguru with sink='server_connection.log'
also, configed the rotation limite with 5MB,
compress model =zip,
used the logger.remove() 
used the copy.depeth(logger)

Problem display with the file is full with 5MB,then it`ll raise a error like-->
FileNotFoundError: [Errno 2] No such file or directory: '/home/vsremote/Documents/Workspace/project_name/logs/2023-02-26/main_process.log'
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---

it may not  a hard error,after got the error ,thr process is still runing.maybe need catch the error and reflow the workflow for write in the file.

**Comment by AlreadyM** [comment]
Problem maybe caseby zip action. when it ziping,source file maybe not exist. but the writing function is calling the file,then create a new file the process going

**Comment by AlreadyM** [comment]
maybe it`s too fast,so that it can`t be work well. i split it with two process to log it,works well.
the time writing maybe 10 times per 1ms.
2023-02-26 20:37:48.014 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.123 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.124 | INFO
2023-02-26 20:37:48.125 | INFO

**Comment by ahmedmedo256** [comment]
> 

https://github.com/Delgan/loguru/issues/806#issuecomment-1445351277
