### ISSUE TITLE
Conditional & compact extra formatting

### ISSUE THREAD

**Issue by alexcannan** [Delgan/loguru#813]
I'm interested in using `{extra}` logging in production to firmly link lines with certain tasks. However, I'd like to format how the extras dict is printed, in order to minimize character usage.

Current behavior:
Empty: "`{}`"
Nonempty: "`{"key": "value", "foo": "bar"}`"

Desired behavior:
Empty: "` `"
Nonempty: "`key=value,foo=bar`"

It seems to me that extra formatting is done with `json.dumps`, which I imagine could be overridden to achieve my proposed formatting, but I have yet to trace where that formatting occurs. If anyone has working knowledge and could provide context that would be appreciated, otherwise I will update this issue with my progress.

**Comment by Delgan** [comment]
Hi.

You can use [a `patch` function](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) to transform the `extra` dict into your expected format, and use it while defining the `format` of your sink.

```python
import sys

from loguru import logger


def extra_formatter(record):
    compact = ",".join(f"{key}={value}" for key, value in record["extra"].items())
    record["extra"]["compact"] = compact


logger.configure(patcher=extra_formatter)

logger.remove()
logger.add(sys.stderr, format="{time} {level} {message} {extra[compact]}")

logger.bind(data="example").info("Some message")
# => '2023-03-03T17:31:37.413481+0100 INFO Some message data=example'
```

**Comment by alexcannan** [comment]
Works like a charm. Thanks!
