### ISSUE TITLE
How to change log level of an imported function?

### ISSUE THREAD

**Issue by drdarina** [Delgan/loguru#815]
I'm importing and using a function from a different project and it's spamming INFO logs that I don't need. What's the loguru version of `logging.getLogger('that_loggers_name').setLevel('ERROR')`?

**Comment by Delgan** [comment]
You can add a `filter` to your sink.

```python
logger.add(sys.stderr, filter={"that_loggers_name": "ERROR"})
```

**Comment by drdarina** [comment]
Thank you!
