### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by xalteropsx** [Delgan/loguru#817]
```py
        for log_line in log_file:

            log_record = logger.parse(log_line.strip(),
                                           log_pattern)

            if not log_record:
                continue  # Skip invalid log records
            logbeta = list(log_record) #and when i trying to list it throw this error 
            # Apply filtering criteria
            if start_date and logbeta["time"].date() < datetime.fromisoformat(start_date).date():
                continue
            if end_date and logbeta["time"].date() > datetime.fromisoformat(end_date).date():
                continue

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/223977459-ca186af1-c16d-4fb3-936d-89a7d6ffdcaf.png)
list error

**Comment by xalteropsx** [comment]
@Delgan  here bro 
![image](https://user-images.githubusercontent.com/103671642/223986526-971092ec-8498-471e-8458-776569742254.png)

**Comment by Delgan** [comment]
The [`logger.parse()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.parse) method returns an iterator of all matching logging line in the file.

You have to use is this way instead:

```python
for log_record in logger.parse('app.log', pattern=regex_pattern):
    print(log_record["level"])
    print(log_record["message"])
    print(log_record["name"])
    print(log_record["function"])
    print(log_record["line"])
    print(log_record["time"])
```

Also, the `pattern` must be a regular expression matching the logging format, it can't be the format itself.

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/224168877-a9303efb-3e23-4c67-ba59-d04d68d6befe.png)
tried nothing work here too

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/224169868-8b685cea-3ecd-4515-88ba-7909d1e4c0f9.png)

**Comment by Delgan** [comment]
Your regex is good, but as indicated in the documentation, it needs to contain [named groups](https://docs.python.org/3/howto/regex.html#non-capturing-and-named-groups).

Try this instead:

```python
pattern = r"(?P<date>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} (AM|PM)) \| (?P<level>[A-Z]+) \| (?P<message>.+)"
```

**Comment by xalteropsx** [comment]
@Delgan  amazing thank u very much i dont know regex can carry name as well

**Comment by Delgan** [comment]
I encourage you to practice and learn the regular expressions, it is very useful in programming. :+1: 

I'm closing this issue as it resolved now.
