### ISSUE TITLE
Loguru Multi-Sink Wrapper: Customizable Logging

### ISSUE THREAD

**Issue by agusticonesagago** [Delgan/loguru#819]
I would like the Loguru library to include the ability to **configure multiple sinks and specify the file to write to when logging**. To accomplish this, I have developed a solution that is available in this repository: https://github.com/agusticonesagago/loguru-multi-sink-logger. This implementation also provides a more user-friendly approach to initializing different sinks, and significantly speeds up initialization by allowing kwargs to be passed as arguments and consolidating everything in one place.

Although the current implementation is provided as a Loguru wrapper, I believe that it would be a valuable addition to the library to include a built-in feature that allows users to specify the file to write to when logging.

The code below is part of the solution, although the full implementation can be viewed more clearly in the linked repository with various examples.
```python
"""This module provides functionality to configure a logger with multiple file sinks, based on the given configurations.
The module includes a `_file_sink` function that returns a function that writes log messages to a file. The `configure_logger`
function uses the `_file_sink` function to create a new sink for each configuration in the configs parameter, and adds the
sink to the logger. The module also includes a main function that demonstrates the usage of the `configure_logger` function.
"""
from loguru import logger
from typing import Callable, List, Dict, Any

def _file_sink(file_path: str) -> Callable[[str], None]:
    """Returns a function that writes log messages to a file.
    :param file_path: The path to the file to write log messages to.
    :return: A function that takes a string argument and writes it to the specified file.
    """
    def _write_message(message: str) -> None:
        """Writes the specified message to the file specified by `file_path`.
        :param message: The message to write to the file.
        """
        with open(file_path, "a") as f:
            f.write(message + "\n")
    return _write_message


def configure_logger(configs: List[Dict[str, Any]]) -> None:
    """Configure a logger with multiple file sinks, based on the given configurations.
    Each configuration is represented as a dictionary with the following keys:
    - "file_path": The path to the file where the sink should write log messages.
    - "file_name": A short name to identify the sink in log records.
    - Additional key-value pairs can be provided as keyword arguments to be passed to `logger.add()`.
    The function removes the default sink (stdout) and adds a new sink for each configuration,
    using the `_file_sink` function to create the sink function.
    :param configs: A list of configurations, where each configuration is a dictionary that includes
    the necessary keys as well as any additional key-value pairs to be passed to `logger.add()`.
    """
    logger.remove()  # Remove the default sink (stdout)
    for config in configs:
        sink = _file_sink(config["file_path"])
        kwargs = {key: value for key, value in config.items() if key not in ["file_path", "file_name"]}
        logger.add(sink, filter=lambda record, name=config["file_name"]: record["extra"].get("file") == name, **kwargs)

if __name__ == "__main__":
    configs = [
        {
            "file_path": "my_log_file1.txt",
            "file_name": "file1",
            "level": "ERROR"
        },
        {
            "file_path": "my_log_file2.txt",
            "file_name": "file2",
            "format": "{time} - {level} - {message}"
        }
    ]
    configure_logger(configs)

    logger.info("This message will be written to my_log_file1.txt", file="file1")
    logger.info("This message will be written to my_log_file2.txt", file="file2")
    logger.error("This message will be written with ERROR to my_log_file1.txt", file="file1")
    
   ```

**Comment by Delgan** [comment]
Hey @agusticonesagago. 

Thanks for sharing this snippet.
However, I don't think multi-files sink is best and common practice, and I don't feel the existing solution is very cumbersome.
Consequently, I would prefer not extending the Loguru API with such built-in sink.

I'm not sure why you need the `_file_sink()` function, though. Can't we directly just use `config["file_path"]` as the sink?

**Comment by agusticonesagago** [comment]
Hi @Delgan ,

Thank you for your feedback on the snippet. It's true that I don't need the `_file_sink` function. Also, I usually use only one log file, but I have come across some corner cases where I use different internal packages and want to separate the logs into different files. I understand your point of view that it would overcomplicate the code base. However, the snippet is available for anyone to use if they require it. 

Thank you for your work on loguru 💯

**Comment by Delgan** [comment]
Yes, thanks again for sharing your work, I'll refer to your post if people ask for such feature. :+1: 

I'm closing this ticket consequently.
