### ISSUE TITLE
Integrate loguru into skywalking

### ISSUE THREAD

**Issue by Jedore** [Delgan/loguru#824]
I contributed logoru integration in [skywalking-python](https://sourcegraph.com/github.com/Jedore/skywalking-python@master/-/blob/skywalking/plugins/sw_loguru.py). 
But  there is a verbose process to generate the same log record as loguru [_log](https://sourcegraph.com/github.com/Delgan/loguru/-/blob/loguru/_logger.py?L1876:67&popover=pinned) method because of there is not a function can return a log record. 
So I think whether loguru can optimize this logic, that other library can easily integrate loguru and process loguru log record. `_log` method return log record and add a new method like `_handle`  to handle the log record specially:
```python
def _log(self, level, from_decorator, options, message, args, kwargs):
    ...
    return log_record

def _handle(self, log_record):
    for handler in self._core.handlers.values():
            handler.emit(log_record, level_id, from_decorator, raw, colored_message)
```

Then I can simplize 90% codes when integrating into skywalking.

Hope for your response...  😄

**Comment by Delgan** [comment]
Hey @Jedore. Thanks for working on integration with SkyWalking!

I'm not familiar with this framework. Could you please clarify what is required for logging integration?
For example, what prevent you to implement a custom sink which call ` agent.archive_log()` based on logged Loguru `record`?

**Comment by Jedore** [comment]
Appreciate for your response @Delgan 
Now Loguru 0.6.0 have been integreated into skywalking 1.0.0. Because of Loguru not like `logging` module, so loguru were integreated as a plugin.
The simplest integration logic is Skywalking get the Loguru `record` before Loguru emit ` record` to multi hanlders. Then Skywalking transfer Loguru `record` to a new format `LogData` and execute `agent.archive_log(LogData)`.
Now Loguru's `_log()` method contains two logic, generating Loguru `record` and emit `record` to handlers. So Skywalking can't get Loguru `record` elegantly before Loguru emit `record` to handlers. And have to copy the `_log()` code to generate the same `record` with sideeffect of duplicated codes.
 I think whether loguru can put the logic of generating `record` into a single method, the integration logic would not generate `record` again.

**Comment by Delgan** [comment]
Thanks for the explanation.
I would like to make integration with SkyWalking easier, but I still don't understand why not just use a custom sink.

Based on [`skywalking/plugins/sw_loguru.py`](https://github.com/apache/skywalking-python/blob/master/skywalking/plugins/sw_loguru.py), I understand that the integration is implemented through an `install()` function.

Why not using the `logger.add()` method instead of patching the `Logger._log` method?

For example (not tested so won't work, but you got the idea):

```python
def install():
    from loguru import logger

    def skywalking_sink(message):
        record = message.record  # Here you get the record generated by Loguru, hence no need to re-implement it.

        # loguru has only one logger. Use tags referring Python-Agent doc
        core_tags = [
            KeyStringValuePair(key='level', value=record['level'].name),
            KeyStringValuePair(key='logger', value='loguru'),
            KeyStringValuePair(key='thread', value=record['thread'].name),
        ]
        tags = LogTags()
        tags.data.extend(core_tags)

        exception = record['exception']
        if exception:
            stack_trace = ''.join(traceback.format_exception(exception.type, exception.value, exception.traceback,
                                                             limit=config.agent_cause_exception_depth))
            tags.data.append(KeyStringValuePair(key='exception',
                                                value=sw_filter(stack_trace)
                                                ))  # \n doesn't work in tags for UI

        context = get_context()

        active_span_id = -1
        primary_endpoint_name = ''

        try:
            # Try to extract active span, if user code/plugin code throws uncaught
            # exceptions before any span is even created, just ignore these fields and
            # avoid appending 'no active span' traceback that could be confusing.
            # Or simply the log is generated outside any span context.
            active_span_id = context.active_span.sid
            primary_endpoint_name = context.primary_endpoint.get_name()
        except IllegalStateError:
            pass

        log_data = LogData(
            timestamp=round(record['time'].timestamp() * 1000),
            service=config.agent_name,
            serviceInstance=config.agent_instance_name,
            body=LogDataBody(
                type='text',
                text=TextLog(
                    text=sw_filter(message)
                )
            ),
            tags=tags,
        )

        if active_span_id != -1:
            trace_context = TraceContext(
                traceId=str(context.segment.related_traces[0]),
                traceSegmentId=str(context.segment.segment_id),
                spanId=active_span_id
            )
            log_data.traceContext.CopyFrom(trace_context)

        if primary_endpoint_name:
            log_data.endpoint = primary_endpoint_name

        agent.archive_log(log_data)

    # Make sure any logged message is also sent to SkyWalking.
    logger.add(skywalking_sink)
```

**Comment by Jedore** [comment]
Seems this is a good idea too. I will try your idea. Thanks.

**Comment by Delgan** [comment]
Great. Keep me updated. :+1: 

The advantage is that you don't have to rely on Loguru internals. For example, `logger._log()` is not part of the public API and can change at any time, patching it is "risky".
