### ISSUE TITLE
How to add URL in the logger format?

### ISSUE THREAD

**Issue by BarryThrill** [Delgan/loguru#827]
Hello people and Delgan!

I hope you are all doing great and I need some help by setting a new format to the loguru if its even possible.

I have currently this code:

```py
import concurrent.futures
import random
import time
from loguru import logger
import requests


class WebScraper:
    def __init__(self):
        self.session = requests.Session()
        self.running = True

    def run(self, url: str):
        logger.bind(url=url)

        while self.running:
            logger.info(f'Scraping...')
            response = self.do_request(url)
            if response.status_code != 200:
                continue

            ...

            time.sleep(random.randint(1, 3))

    def do_request(self, url):
        response = self.session.get(url)
        return response



if __name__ == '__main__':
    URLS_TO_TEST = (
        "http://books.toscrape.com/catalogue/category/books/travel_2/index.html",
        "http://books.toscrape.com/catalogue/category/books/mystery_3/index.html",
        "http://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html",
        "http://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html",
        "http://books.toscrape.com/catalogue/category/books/classics_6/index.html",
    )

    with concurrent.futures.ThreadPoolExecutor() as executor:
        for url in URLS_TO_TEST:
            session = WebScraper()
            future = executor.submit(session.run, url)
```

and what I wonder if its possible to make it bind each thread by itself so it prints out something like this

```
2023-03-20 00:47:09.982 | INFO     | http://books.toscrape.com/catalogue/category/books/travel_2/index.html. | __main__:run:17 - Scraping...
2023-03-20 00:47:09.982 | INFO     | http://books.toscrape.com/catalogue/category/books/mystery_3/index.html | __main__:run:17 - Scraping...
2023-03-20 00:47:09.983 | INFO     | http://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html | __main__:run:17 - Scraping...
2023-03-20 00:47:09.984 | INFO     | http://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html | __main__:run:17 - Scraping...
```

Basically that the URL is inside the format I assume it is?

Would appreciate the help and wish you the best day!

**Comment by Delgan** [comment]
Hi @BarryThrill.

It seems you need to combine [`bind()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.bind) or [`contextualize()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.contextualize) with a custom `format`.

First, make sure to add a handler logging your custom `{extra[url]}` attribute:

```python
logger.remove()
logger.add(sys.stderr, format="{time} | {level} | {extra[url]} | {message}")
```

Secondly, because `logger.bind()` returns a new `logger` object, you need to store the result in a variable and then use it to log your messages.

```python
bound_logger = logger.bind(url=url)
bound_logger.info(f'Scraping...')
```

Then it should work fine.

**Comment by BarryThrill** [comment]
> ```python
> bound_logger = logger.bind(url=url)
> bound_logger.info(f'Scraping...')
> ```

Thank you for the beautiful answer and well described!

Just one more thing, is it possible to some colors into the format? to have it similar as default because currently its just all red:

![image](https://user-images.githubusercontent.com/15836342/226446117-3e109a67-891f-41a4-9ebe-c35b967ec67d.png)

**Comment by Delgan** [comment]
Sure, you have to use color tags in the `format`, [see documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#color).

For example:

```python
logger.add(sys.stderr, format="<green>{time}</> | <lvl>{level}</> | <blue>{extra[url]}</blue> | <lvl>{message}</lvl>")
```

**Comment by BarryThrill** [comment]
> Sure, you have to use color tags in the `format`, [see documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#color).
> 
> For example:
> 
> ```python
> logger.add(sys.stderr, format="<green>{time}</> | <lvl>{level}</> | <blue>{extra[url]}</blue> | <lvl>{message}</lvl>")
> ```

Thanks! Was looking at it but I forgot to add the </color> at the end :) 

I have 2 more question however, 

1. To change the format time to `2023-03-20 21:19:58.422` instead of `2023-03-20T21:19:58.420669+0100`? The default one has the format I wish but couldn't find anywhere on how to format it (I might be blind or searching incorrect in the docs)

2. Is it possible to make a if else statement, e.g. if I e.g. don't bind the url, is it possible to then "skip" without any exceptions e.g.

```
import loguru

logger.remove()
logger.add(sys.stdout, filter=lambda record: record["level"].name == "INFO")
logger.add(sys.stderr, format="<green>{time}</> | <lvl>{level}</> | <blue>{extra[url]}</blue> | <lvl>{message}</lvl>")

bound_logger = logger.bind(url=url)
bound_logger.info('scraping...')
logger.info('Just a random print') <--- Throws KeyError
```

**Comment by Delgan** [comment]
> To change the format time to `2023-03-20 21:19:58.422` instead of `2023-03-20T21:19:58.420669+0100`? The default one has the format I wish but couldn't find anywhere on how to format it (I might be blind or searching incorrect in the docs)

Yes, you can specify the desired date format, [see here](https://loguru.readthedocs.io/en/stable/api/logger.html#time).
You could use `{time:YYYY-MM-DD HH:mm:ss.SSS}` for example.

> Is it possible to make a if else statement, e.g. if I e.g. don't bind the url, is it possible to then "skip" without any exceptions

I suggest to use [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) to set a global default value.
For example, you could just call `logger.configure(extra={"url": ""})` in your main, and the `extra["url"]` value will be empty by default for all non-bound `logger`.
Alternatively, you can use a custom `format` function to adapt the format based on presence or absence of `url` attribute.

**Comment by BarryThrill** [comment]
> logger.configure(extra={"url": ""})

Thank you!

Would you say that this code is correctly made?

```
import concurrent.futures
import random
import sys
import time
from loguru import logger
import requests

logger.remove()
logger.add(sys.stderr, format="<green>{time}</> | <lvl>{level}</> | <blue>{extra[url]}</blue> | <lvl>{message}</lvl>")

class WebScraper:
    def __init__(self):
        self.session = requests.Session()
        self.running = True

    def run(self, url: str):
        bound_logger = logger.bind(url=url)

        while self.running:
            bound_logger.info(f'Scraping...')
            logger.info('Test print')
            response = self.do_request(url)
            if response.status_code != 200:
                continue

            ...

            time.sleep(random.randint(1, 3))

    def do_request(self, url):
        response = self.session.get(url)
        return response



if __name__ == '__main__':
    logger.configure(extra={"url": ""})
    URLS_TO_TEST = (
        "http://books.toscrape.com/catalogue/category/books/travel_2/index.html",
        "http://books.toscrape.com/catalogue/category/books/mystery_3/index.html",
        "http://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html",
        "http://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html",
        "http://books.toscrape.com/catalogue/category/books/classics_6/index.html",
    )

    with concurrent.futures.ThreadPoolExecutor() as executor:
        for url in URLS_TO_TEST:
            session = WebScraper()
            future = executor.submit(session.run, url)
```

and of course if it is, then we can close the question :)

**Comment by Delgan** [comment]
Looking good, yes. :smile: 

Feel free to re-open if you have any other question. :+1:
