### ISSUE TITLE
Seperate streams: warn/error/higher to stderr, rest to stdout

### ISSUE THREAD

**Issue by mrx23dot** [Delgan/loguru#828]
I'm looking for the simplest way doing this, without classes.
So when I do `w4twr.py > /dev/null  ` then only actionable text is remaining e.g. in a cron job.

I read the docs, and got so far:

```
from loguru import logger as log
from sys import stderr,stdout

# warn/error to stderr, rest to stdout
log.remove()
log.add(stdout, level='DEBUG')
log.add(stderr, level='WARNING')

log.info('hi')
log.warning('hi')
log.error('hi')
```

But it prints everything twice (stdout and stderr)
```
2023-03-20 21:19:30.711 | INFO     | __main__:<module>:8 - hi
2023-03-20 21:19:30.714 | WARNING  | __main__:<module>:9 - hi
2023-03-20 21:19:30.714 | WARNING  | __main__:<module>:9 - hi
2023-03-20 21:19:30.716 | ERROR    | __main__:<module>:10 - hi
2023-03-20 21:19:30.716 | ERROR    | __main__:<module>:10 - hi
```

Please consider adding the solution into documentation, I think it would be useful.
 
Also not sure why the name of the file (w4twr.py) isn't the default (instead of __main__) to make it easier to find source of log.

**Comment by Delgan** [comment]
You can use a simple `filter`.

```python
log.add(stdout, level='DEBUG', filter=lambda record: record["level"].no < 30)
log.add(stderr, level='WARNING')
```

Also the logger is named based on `__name__` Python variable, which equals to `__main__` for the entry module.
