### ISSUE TITLE
[Enhancement] Use ruff instead of flake8 for linting in pre-commit

### ISSUE THREAD

**Issue by baniasbaabe** [Delgan/loguru#830]
I guess using ruff instead of flake8 could be considered, especially for performance reasons of lining + additional features like import sorting (like isort) and removing unused code (like autoflake).

See here: https://github.com/charliermarsh/ruff

(There is also a performance comparison between common linters)

**Comment by Delgan** [comment]
Ruff has gained a lot of popularity lately. I recently considered migrating to Ruff, but I don't have the time to make the switch right now. PR welcome.
