### ISSUE TITLE
Access Available Levels

### ISSUE THREAD

**Issue by lasinludwig** [Delgan/loguru#844]
Hi there,

is there a different way to access the levels than `logger._core.levels`?

When creating a custom level, I'd like to make sure it doesn't already exist. Right now I do it like this:

```
if lvl not in logger._core.levels:
   logger.level(lvl, no=1)
```

...which is not great, because I'm accessing a protected member. Is there a better way to do this?

**Comment by Delgan** [comment]
Hi. ;)

The "idiomatic" way is to use a `try / except` block, a `ValueError` is raised if the level does not exist;

```python
try:
    logger.level(lvl)
except ValueError:
    pass
else:
    logger.level(lvl, no=1)
```

**Comment by lasinludwig** [comment]
Hi @Delgan ,

thank you so much! That looks much better. 🙂👍
