### ISSUE TITLE
logs are colorized, but stack traces are not

### ISSUE THREAD

**Issue by aviadr1** [Delgan/loguru#847]
tested both on windows and linux, it seems that the logs themselves are beautifully colorized as exected,
but the output of `logger.exception(e)` doesnt come out colorized, while better_exceptions README.md definitely shows that it is possible to be colorized very nicely.

ideally, stack traces should also be colorized

**Comment by Delgan** [comment]
Hi.

The argument passed to `logger.exception()` should be a message, just like others logging method. This is a convenient method that automatically retrieve the currently handled exception (if any) using [`sys.exc_info()`](https://docs.python.org/3/library/sys.html#sys.exc_info).

Loguru does not expect the message passed as argument to be the exception itself, that explains why the stack trace is not colored.

Maybe you're looking for `logger.opt(exception=e).error("Error message")`.

**Comment by aviadr1** [comment]
sorry, the issue is something else, I'll open a different ticket.
both logs and stack traces get colorized on windows.
