### ISSUE TITLE
Custom Serializer formater, use of included log formatter

### ISSUE THREAD

**Issue by ch0wm3in** [Delgan/loguru#855]
Hi,

Consider the following 

```python
def serialize(record):
    """Serialize the JSON log.
    """
    log = {}
    log["time"] = record["time"].timestamp()
    log["level"] = record["level"].name
    log["message"] = record["message"]
    log["func_string"] = f"{record['name']}:{record['function']}:{record['line']}"
    log["correlation_id"] = call_uuid
    log["total_runtime"] = record["elapsed"].seconds


    if record["exception"] is not None:
        error_data = {
            "error": {
                "stack": "".join(
                    traceback.format_exception(
                        record["exception"].type,
                        record["exception"].value,
                        record["exception"].traceback,
                    )
                ),
                "kind": getattr(record["exception"].type, "__name__", "None"),
                "message": str(record["exception"].value),
            },
        }
        log.update(error_data)
    
    return json.dumps(log, ensure_ascii=False)
```
How would i go about using the time format of "{time:YYYY-MM-DDTHH:mm:ss.SSSSSSSSSZ}" in a json serializer for the `log["time"]`? I see that `record["time"]` a datetime object, python datetime does not support nanoseconds afaik, but above works fine with stderr sink. Is there a way to set default time format globally across all sinks using the time formatter that's included in the libary?

**Comment by Delgan** [comment]
Hi.

Loguru does not support nanosecond neither.
When you use `"SSSSSSSSS"` in the format, it's certainly parsed as `"SSSSSS"` concatenated with `"SSS"`. Basically, microseconds joined with milliseconds, that give the impression of being nanoseconds.

Maybe should I detect this pattern and raise an exception?

Anyway, if you need nanoseconds in your JSON serializer, you can use a `patch` function:

```python
def add_nanoseconds(record):
    record["extra"]["nanoseconds"] = time.time_ns()

logger.configure(patcher=add_nanoseconds)
```

Then you can access `record["extra"]["nanoseconds"]` each time a message is logged.

**Comment by ch0wm3in** [comment]
Oh okay, yeah i would like an exception or at least a notion of that it's not actually nanoseconds 😁 

Thanks for the supplied, i ended up accepting using rfc3339micro instead of nano with pendulum doing the following in my serializer:

```python
import pendulum

def serialize(record):
    """Serialize the JSON log.
    """
    dt = pendulum.instance(record["time"])
    log = {}
    log["log_time"] = dt.format("YYYY-MM-DDTHH:mm:ss.SSSSSSZ")
    log["level"] = record["level"].name
    log["message"] = record["message"]
    log["func_string"] = f"{record['name']}:{record['function']}:{record['line']}"
    log["correlation_id"] = call_uuid
    log["total_runtime"] = record["elapsed"].seconds
    log["script_name"] = record["extra"].get("script_name", "")


    if record["exception"] is not None:
        error_data = {
            "error": {
                "stack": "".join(
                    traceback.format_exception(
                        record["exception"].type,
                        record["exception"].value,
                        record["exception"].traceback,
                    )
                ),
                "kind": getattr(record["exception"].type, "__name__", "None"),
                "message": str(record["exception"].value),
            },
        }
        log.update(error_data)
```

**Comment by Delgan** [comment]
Indeed, using `pendulum` would have been my suggestion, since Loguru implements the same formatting rules. :+1: 

I keep this ticket open and I'll try to detect pattern with more than 6 successive `"S"` and raise an exception in that case.
