### ISSUE TITLE
Avoid boilerplate code by accepting a list for sink in the add method

### ISSUE THREAD

**Issue by kmadridr** [Delgan/loguru#863]
Hello,
I am currently using loguru in a project. I needed to sink the logger output to the console as well to a log file. 

However, to accomplish this I had to have the following code:

`logger.remove(0)
logger.add("logs/connection-service-{time:YYYY-MM-DDThh-mm-ss!UTC}.log",
           format="<green>{time:YYYY-MM-DDThh:mm:ssZ!UTC}</green> |"
           " <level>{level}</level> | <level>{message}</level>", 
           level=os.environ['LOGURU_LEVEL'])
logger.add(sys.stderr,
           format="<green>{time:YYYY-MM-DDThh:mm:ssZ!UTC}</green> |"
           " <level>{level}</level> | <level>{message}</level>", 
           level=os.environ['LOGURU_LEVEL'])
`

As you will see the format and everything is exactly the same.

I went through the loguru base code and added a line to accomplish this:

`logger.add(["logs/connection-service-{time:YYYY-MM-DDThh-mm-ss!UTC}.log", sys.stderr],
           format="<green>{time:YYYY-MM-DDThh:mm:ssZ!UTC}</green> |"
           " <level>{level}</level> | <level>{message}</level>", 
           level=os.environ['LOGURU_LEVEL'])`

It works for me.

I have forked the project and added the unit testing as well ready for a PR.

**Comment by Delgan** [comment]
Hello @kmadridr. 

Thank you for your interest in contributing and improving the library. However, I don't think that changing `logger.add()\ to support multiple sinks is desirable. It adds complexity that I don't think is necessary. The same result can be achieved with a simple `for` loop, therefore Loguru does not need to re-implement this.

```python
for sink in ["logs/connection-service-{time:YYYY-MM-DDThh-mm-ss!UTC}.log", sys.stderr]:
    logger.add(sink, format="<green>{time:YYYY-MM-DDThh:mm:ssZ!UTC}</green> |" " <level>{level}</level> | <level>{message}</level>",  level=os.environ['LOGURU_LEVEL']))
```

What do you think?

**Comment by kmadridr** [comment]
Hi @Delgan,

Completely agree.

Thanks for taking the time to get back to me.
