### ISSUE TITLE
Color parsing error even though colorize=False

### ISSUE THREAD

**Issue by tiktuk** [Delgan/loguru#864]
Hi, I get the error `ValueError: Invalid format, color markups could not be parsed correctly` when adding the following handler, even though `colorize=False`. Is it supposed to be like that? The error goes away if I remove the `<pre>` tags but I would like those in this handler..

```
logger.add(
    telegram_handler,
    level="INFO",
    colorize=False,
    format="{time} {level} <pre>{message}</pre>"
)
```

**Comment by julian-goettingen** [comment]
you can escape the initial "<"-signs with a backslash to get your expected behaviour:

`format="{time} {level} \<pre>{message}\</pre>"`

will output sth like
2023-05-04 12:50:17.032 WARNING <pre>hello</pre>

**Comment by Delgan** [comment]
Thanks @julian-goettingen.

@tiktuk You need indeed to escape the tags which might be confused by Loguru as color markups.

This is displayed in the raised error:

```txt
Traceback (most recent call last):
  File "/home/delgan/loguru/loguru/_logger.py", line 937, in add
    formatter = Colorizer.prepare_format(format + terminator + "{exception}")
  File "/home/delgan/loguru/loguru/_colorizer.py", line 357, in prepare_format
    tokens, messages_color_tokens = Colorizer._parse_without_formatting(string)
  File "/home/delgan/loguru/loguru/_colorizer.py", line 449, in _parse_without_formatting
    parser.feed(literal_text, raw=recursive)
  File "/home/delgan/loguru/loguru/_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<pre>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/delgan/loguru/test.py", line 3, in <module>
    logger.add(
  File "/home/delgan/loguru/loguru/_logger.py", line 939, in add
    raise ValueError(
ValueError: Invalid format, color markups could not be parsed correctly
```

**Comment by tiktuk** [comment]
Ok, thanks, but why look for colour directives if `colorize=False`?

Anyways, I got it working now with the escaping :) .

**Comment by julian-goettingen** [comment]
because in colorize=false - mode, you still want to strip the color tags and that requires looking them up.

Lets say your format contains "<red>hello</red>", then you always want to write "hello", not "<red>hello</red>", no matter if that "hello" should be white or red.

It would also be very bad to have the validity of a log-format depend on another option - different fields of a configuration should ideally be orthogonal

**Comment by tiktuk** [comment]
Ok, makes sense :) .

**Comment by Delgan** [comment]
Thanks @julian-goettingen!

**Comment by quantumpacket** [comment]
> you can escape the initial "<"-signs with a backslash to get your expected behaviour:
> 
> `format="{time} {level} \\<pre\>{message}\\</pre\>"`

This should probably be in the documentation. Took me quite awhile to find this post while investigating why HTML tags in my email format string were causing errors. I too thought `colorize=False` would have disabled markup formatting :man_facepalming:.
