### ISSUE TITLE
Add/update context value when using `logger.contextualize`

### ISSUE THREAD

**Issue by Agontuk** [Delgan/loguru#869]
I've three middlewares in the order of `RequestIDMiddleware` -> `LoggingMiddleware` -> `AuthMiddleware`. As shown in below example, logging middleware initially calls `logger.contextualize` by passing `user=None`. When auth middleware finds current user I want to update the context value with current user data. How can I achieve this ? I don't want to put AuthMiddleware below LoggingMiddleware, as it'll stop printing logs when user is unauthenticated.

`main.py`
```python
app = FastAPI()

app.add_middleware(AuthMiddleware) # injects user into the request
app.add_middleware(LoggingMiddleware) # request.user not available here
app.add_middleware(RequestIDMiddleware)
```

`LoggingMiddleware.py`
```python
class LoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> Response:
        with logger.contextualize(request_id=request.state.request_id, user=None): # need to update it when request.user is available
            logger.info("Request Received")
            status_code = status.HTTP_200_OK

            try:
                response: Response = await call_next(request)
                status_code = response.status_code
            except Exception as e:
                status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
                raise
            finally:
                logger.info("Response Sent", response_code=status_code)

            return response
```

**Comment by Delgan** [comment]
That's not possible, do you think you can use [`starlette-context`](https://github.com/tomwojcik/starlette-context) for this? It seems quite appropriate to your use case.

**Comment by Agontuk** [comment]
> That's not possible, do you think you can use [`starlette-context`](https://github.com/tomwojcik/starlette-context) for this? It seems quite appropriate to your use case.

I tried using it, but then I have to import context in every file I want to log the user data. I'm trying to find a way to inject it into logger only once so it's available everywhere.

**Comment by Delgan** [comment]
> I tried using it, but then I have to import context in every file I want to log the user data.

Can't you use the `context` as part of Loguru `format` when adding the handlers? How were you planning to log the `user` value?

**Comment by Agontuk** [comment]
> > I tried using it, but then I have to import context in every file I want to log the user data.
> 
> Can't you use the `context` as part of Loguru `format` when adding the handlers? How were you planning to log the `user` value?

You mean to use `format` as callable and then use the context data to update record ? That makes sense, haven't tried it yet. I came up with a solution to use the `patcher` parameter to update the user info. Is this a valid approach ?

```python
from starlette_context import context

def patcher_func(record):
    user: Any = context.get("user")

    if user is not None:
        record["extra"].update(user=user["username"])


logger.configure(**log_config, patcher=patcher_func)

```

**Comment by Delgan** [comment]
Yes if you just want to add the value to the `extra` dictionary, using `patcher` is just as good. :+1:

**Comment by Agontuk** [comment]
Thanks for your quick feedback, closing the issue.
