### ISSUE TITLE
NotificationHandler is working okay?

### ISSUE THREAD

**Issue by YJinHai** [Delgan/loguru#87]
Hey, in this case:
```python
import notifiers

params = {
    "username": "you@gmail.com",
    "password": "abc123",
    "to": "dest@gmail.com"
}

# Send a single notification
notifier = notifiers.get_notifier("gmail")
notifier.notify(message="The application is running!", **params)

# Be alerted on each error message
from notifiers.logging import NotificationHandler

handler = NotificationHandler("gmail", defaults=params)
logger.add(handler, level="ERROR")
```
Using the NotificationHandler as a sink implies that at mail will be sent each time you log a message using the Loguru logger
but,
I noticed during the process that **notifier. notify** was able to send messages, while **NotificationHandler** did not see the sent message

**Comment by YJinHai** [comment]
I actually use email(SMTP)

**Comment by YJinHai** [comment]
I see, this needs to trigger an error to trigger

**Comment by Delgan** [comment]
Yes, `notifier.notify()` is unrelated to Loguru, buf if you add a `NotificationHandler` to the logger, then the logged messages need to pass the `level` threshold to trigger the sending of the mail. 😉
