### ISSUE TITLE
loguru completely disables huggingface logger

### ISSUE THREAD

**Issue by ashutoshbsathe** [Delgan/loguru#870]
Hi, I am trying to use `@logger.catch` from loguru with my HuggingFace training script but it seems that importing loguru completely disables HuggingFace logger. Any way to fix it ?

Here's my code structure roughly:
```
from loguru import logger
from transformers import Trainer, ....
....
@logger.catch
def main():
    ....
    trainer = Trainer(....)
    ....
    trainer.train() # <--- This should log a lot of information but doesn't when I import loguru
....
if __name__ == '__main__':
    main()
```

Example of what the `trainer.train()` typically logs -- https://github.com/huggingface/transformers/blob/cf11493dce0a1d22446efe0d6c4ade02fd928e50/src/transformers/trainer.py#L1778-L1786

I first thought it was because both HF and loguru refer to the same name `logger` so I changed the import to `from loguru import logger as lgr` and changed `@logger.catch` to `@lgr.catch` but it still did not work. Importing loguru before/after transformers also didn't make any difference

What am I doing wrong ?

**Comment by Delgan** [comment]
Hi. Are you configuring any particular handler? Any chance you could share a minimal reproducible example?

Loguru does not interfere with standard `logging` module, therefore I don't understand where the problem could come from. Based on your observations, is it related to `@logger.catch()`? You can try to use it as a context manager instead of a decorator and see if it improves things.

**Comment by ashutoshbsathe** [comment]
Somehow importing loguru messes with Transformer's default log level. I didn't notice that they had introduced a new  field in `TrainingArguments` that [explicitly controls the logging level](https://huggingface.co/docs/transformers/v4.29.1/en/main_classes/trainer#transformers.TrainingArguments.log_level). Setting `log_level` to `info` restores the HF logging correctly.

Closing the issue.
