### ISSUE TITLE
How to print out logger.debug after logger.remove

### ISSUE THREAD

**Issue by BarryThrill** [Delgan/loguru#871]
Hello beautiful Loguru!

I hope you are well. Im currently having some issues running loguru in Linux together with PM2. The code works exactly how I want when using logger.info however I do see when i'm trying to use logger.debug(...) it wont print anything at all which I believe is due to logger.remove. So I came up to do something like this:

```py
logger.remove()
logger.configure(extra={"url": "", "code": ""})
logger_format = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</> | <blue>{extra[url]}</blue> | <yellow>{extra[code]}</yellow> | <lvl>{message}</lvl>"

# Debug set to False
if not configuration.utils.debug:
    logger.add(sys.stdout, format=logger_format, filter=lambda record: record["level"].name == "INFO")
    logger.add(sys.stderr, format=logger_format, level="WARNING")
    logger.add(discord_sink, format=logger_format, filter=exception_only, enqueue=True)

# Debug set to True
else:
    logger.add(sys.stderr, format=logger_format, level="DEBUG")
    logger.add(lambda _: time.sleep(500), format=logger_format, filter=lambda record: record["level"].name == "DEBUG")
```

However the problem is that if I am now adding e.g.

```py
logger.add(sys.stderr, format=logger_format, level="DEBUG")
```

Then it will print out twice. I wonder how I can make it print out both for info and debug. Using pm2 the Info would be marked as green and debug as red. Here is old thread we spoke about the reason why I did it this way: https://github.com/Delgan/loguru/issues/356

**Comment by Delgan** [comment]
Hi. :)

The `time.sleep(500)` will cause your process to sleep for **500 seconds**, and because `enqueue=False` it will blocks the main thread. That might explains why you're not seeing any output, right?

**Comment by BarryThrill** [comment]
> Hi. :)
> 
> The `time.sleep(500)` will cause your process to sleep for **500 seconds**, and because `enqueue=False` it will blocks the main thread. That might explains why you're not seeing any output, right?

Ah the time.sleep(500) is whenever I have my debug set to True. But in my case it is set to False so it should use this part of code:

```py
    logger.add(sys.stdout, format=logger_format, filter=lambda record: record["level"].name == "INFO")
    logger.add(sys.stderr, format=logger_format, level="WARNING")
    logger.add(discord_sink, format=logger_format, filter=exception_only, enqueue=True)
```

**Comment by Delgan** [comment]
Ok, I understand. Then, where do you expect `"DEBUG"` messages to be logged? According to your configuration, `sys.stdout` will only receive `"INFO"` messages because of the `filter`, and `sys.stderr` will only receive `"WARNING"` messages and above because of the `level`. Therefore, when using `logger.debug()`, no message is printed.

**Comment by Delgan** [comment]
Actually you want to update the handler logging to `sys.stderr`, right?

There are a few workarounds explained here: [Changing the level of an existing handler](https://loguru.readthedocs.io/en/stable/resources/recipes.html#changing-the-level-of-an-existing-handler).

**Comment by BarryThrill** [comment]
> Ok, I understand. Then, where do you expect `"DEBUG"` messages to be logged? According to your configuration, `sys.stdout` will only receive `"INFO"` messages because of the `filter`, and `sys.stderr` will only receive `"WARNING"` messages and above because of the `level`. Therefore, when using `logger.debug()`, no message is printed.

To be honest I want both logger.info and debug to work. However according to https://github.com/Delgan/loguru/issues/356 - I want the debug to be printed as "red-mark" as you can see in this picture:

![image](https://github.com/Delgan/loguru/assets/15836342/bc2b90c0-d678-45bc-94c3-6d9080f8de15)


and whenever we use logger.info then it should be green. 

![image](https://github.com/Delgan/loguru/assets/15836342/3951670e-1140-4fbf-95f9-91110930935c)


The green part is already working fine but now we just need to get debug to work basically.

**Comment by BarryThrill** [comment]
> Actually you want to update the handler logging to `sys.stderr`, right?
> 
> There are a few workarounds explained here: [Changing the level of an existing handler](https://loguru.readthedocs.io/en/stable/resources/recipes.html#changing-the-level-of-an-existing-handler).

Hmmm.. Im not quite sure if I follow here. Im not quite sure if you get what I meant with the image, if that helps you in any ways?

**Comment by Delgan** [comment]
What about replacing:

```python
logger.add(sys.stderr, format=logger_format, level="WARNING")
```

with

```pyhon
logger.add(sys.stderr, filter=lambda record: record["level"].name != "INFO")
```
as suggested in the other ticket?

That means that every `"INFO"` message will be green, and everything else red, without duplication. Is that what you're trying to achieve?

**Comment by BarryThrill** [comment]
> ```python
> logger.add(sys.stderr, format=logger_format, filter=lambda record: record["level"].name != "INFO")
> ```

That was it... I knew it was something so easy yet I am over complicated it again. I wish you all the best and thank you very much. :)

**Comment by Delgan** [comment]
Thank you, I wish you the same. :)
