### ISSUE TITLE
Question: How to log client IP address to each log request

### ISSUE THREAD

**Issue by tuxpowered** [Delgan/loguru#872]
So using loguru has been wonderful, but I am looking to streamline repetitive tasks. One of which is logging the IP address of clients, specifically when using FastAPI.

I have used https://medium.com/1mgofficial/how-to-override-uvicorn-logger-in-fastapi-using-loguru-124133cdcd4e to configure uvicorn and fastapi logging and it works well. 

Looking at the loguru docs I know I could add an {extra[host]} to the format and use `.bind(host=None)` when configuring the logger. This would work if I updated every log request, to:

`logger.info("some information", host=requests.client.host)`

The issue is that no one really wants to go back and manaully add the `hosts=` portion to every single log statement. 

It would be better to beable to define an the logger to dynamically use FastAPI's Request to add it to each log statement. 
That is the part I can not figure out, as it seems that the only way to add something like this at the logger.level portion of creating the log. 

The following works,

`"format": "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | request_id: {extra[request_id]} - {extra[host]} - <cyan>{name}</cyan>:<cyan>{function}:{line}</cyan> - <level>{message}</level>"`

```
@app.middleware("http")
async def audit_log(request: Request, call_next):
    logger.info(f"{request.method} {request.url}", host=request.client.host)
    response = await call_next(request)
    return response
```
`2023-05-17 14:45:26.930 | INFO     | request_id: None - 127.0.0.1 - main:audit_log:90 - DELETE http://0.0.0.0:8000/router/21`

*BUT* I would like to do
```
logger.info("this is cool")
```
and get the result:
`2023-05-17 14:45:26.930 | INFO     | request_id: None - 127.0.0.1 - main:audit_log:90 - this is cool`
_note the IP address_ 

I modified the logger.bind to`logger.bind(request_id='app', host='localhost')` from the original medium post to makethe logs support the {extra[...]} field.

Any suggestions or tips?

**Comment by Delgan** [comment]
Hi @tuxpowered.

Your question seems similar to this recent ticket: https://github.com/Delgan/loguru/issues/869

Basically, I think you can use [`starlette-context`](https://github.com/tomwojcik/starlette-context) or combine a custom [`Middleware`](https://fastapi.tiangolo.com/tutorial/middleware/) with [`contextvars`](https://docs.python.org/3/library/contextvars.html) and [`logger.patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch):

```python
import sys

from loguru import logger
from fastapi import FastAPI, Request
from contextvars import ContextVar

host = ContextVar('host', default=None)

app = FastAPI()


@app.middleware("http")
async def request_middleware(request, call_next):
    host.set(request.client.host)
    response = await call_next(request)
    return response

@app.get("/")
async def root():
    logger.info("Hello world")
    return {"message": "Hello World"}

def add_host_to_logger(record):
    record["extra"]["host"] = host.get()

logger.configure(
    handlers=[{"sink": sys.stderr, "format":"[{time}][{extra[host]}] {message}"}],
    patcher=add_host_to_logger
)
```

**Comment by tuxpowered** [comment]
@Delgan Thank you. That works. Had to replace the logger.add() lines but that patcher= did just what I was hoping. This additionally gave me another solution for something I was wondering how to do as well. (Adding a unique ID to the log to track a session). Thank you again.

**Comment by Delgan** [comment]
Great! I'm closing the ticket then. :+1:
