### ISSUE TITLE
Implementation of Configuration File Based Adjustable Log Levels by Module & File Names 

### ISSUE THREAD

**Issue by fehimaltinisik** [Delgan/loguru#880]
First of all thanks for this great library.

### Proposal
I am opening this new issue in order to discuss an efficient way to implement adjustable log levels by module and file names. In short, I would like to manage log levels of different modules via a configuration file like the one Spring Boot [offers](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-levels).

For instance, with root level set to `**ERROR**` suppose that we have the following project structure and the logging configuration file:
```bash
src
│  
└───services
│   │   user.py
│   │   cleint.py
│   │   ...
│   └───store
│       │   virtual.py
│       │   retail.py
└───routers
└───db
```
```yml
level:
  src.services: WARNING
  src.services.user: DEBUG
  src.services.store: INFO
```
I would like to achieve the following behavior with the aforementioned setup:

- All modules (`routers`, `db` etc.) except the `src.services` should log at `**ERROR**` level.
- All modules and files under `src.services` except the ` src.services.store` module and ` src.services.user.py` file should log at `**WARNING**` level.
- All files under `src.services.store` should log at `**INFO**` level.
- `src.services.user.py` file should at `**DEBUG**` level.

### What I've Tried

I haven't been able to find an example on how to do it so far. So I've ended up with the following implementation in order to roughly achieve the behavior described above:
```Python
ROOT_LEVEL = logger.level('ERROR')

class LogFilterByModule:
    def _init_(self, log_level_by_module: Dict):
        self.log_level_by_name = {name: logger.level(level) for name, level in log_level_by_module.items()}

    def _call_(self, record):
        if record['level'].no < ROOT_LEVEL.no:
            return False

        log_level_by_module_name = self.find_first_log_level_matching_by_record_module_name(record['name'])

        if log_level_by_module_name:
            return record['level'].no >= log_level_by_module_name.no

        return True

    def find_first_log_level_matching_by_record_module_name(self, record_module_name: str) -> Optional[Any]:
        first_matching_module_name = next(filter(lambda module_name: module_name in record_module_name,
                                                 list(self.log_level_by_name.keys())), None)
        if not first_matching_module_name:
            return None

        return self.log_level_by_name.get(first_matching_module_name)


def read_log_level_config() -> Dict:
    with open(os.path.join('src', 'resources', 'log.yaml'), 'r') as file:
        log_level: Dict = load_yaml(file, Loader)
    log_level_by_module: Dict = log_level.get('level', {})

    return log_level_by_module


def configure_logger():
    logger.remove()

    log_level_by_module: Dict = read_log_level_config()
    filter_by_module = LogFilterByModule(log_level_by_module)
    logger.add(sys.stdout, format=formatter, filter=filter_by_module, level=LOG_LEVEL,
               colorize=False, backtrace=True, diagnose=False)

    for name, log_level in log_level_by_module.items():
        logger.info(f"Registered '{name}' module's log level registered at: {log_level}.")
```

### What's Next?
I wonder that if is there any built-in alternative to the implementation above. I have already used it across multiple projects already and more of them probably is on the way.

If there is no built-in way to achieve this functionality then I would like to work on a PR to ship this functionality.

### Appendix
I am aware that on Java side this functionality offered via Spring Boot the Web Framework rather than any logging framework (as far as I know). But I don't believe that this functionality should implemented in any web framework since the Python's web development tools are much less integrated. So I have opened discussion here. So please don't let the Spring Boot example above confuse you

**Comment by Delgan** [comment]
Hi @fehimaltinisik. :)

Loguru supports fine-grained filtering by passing a dictionary to the `filter` argument.

```python
from loguru import logger

module_levels = {
    "": "ERROR",
    "src.services": "WARNING",
    "src.services.user": "DEBUG",
    "src.services.store": "INFO",
}

logger.add(sys.stderr, filter=module_levels, level=0)
```

Does it match the functionality you're looking for?

**Comment by fehimaltinisik** [comment]
Hi @Delgan,

This is fascinating, the exact the functionality that I have been looking for.

However I am afraid I've couldn't found details of it in the documentation. Is this functionality shipped with loguru or standard logging module?

**Comment by Delgan** [comment]
This feature is only implemented in Loguru, not in the standard library.

This is briefly evoked in this section of the documentation: [The logged message](https://loguru.readthedocs.io/en/stable/api/logger.html#message).

> The `filter` attribute can be used to control which messages are effectively passed to the sink and which one are ignored. A function can be used, accepting the record as an argument, and returning `True` if the message should be logged, `False` otherwise. If a string is used, only the records with the same `name` and its children will be allowed. **One can also pass a `dict` mapping module names to minimum required level. In such case, each log record will search for it’s closest parent in the `dict` and use the associated level as the filter. The `dict` values can be `int` severity, `str` level name or `True` and `False` to respectively authorize and discard all module logs unconditionally. In order to set a default level, the `""` module name should be used as it is the parent of all modules (it does not suppress global `level` threshold, though).**

**Comment by fehimaltinisik** [comment]
Apparently I missed that part.

My final question is whether you see any value in file based configuration with environment variable substitution like in the following example:

```yaml
level:
  src.services: ${LOG_LEVEL_SRC_SERVICES}
  src.services.user: DEBUG
  src.services.store: ${LOG_LEVEL_SRC_SERVICES_STORE}
```
I am not sure whether it is overengineering or not since unlike Java in Python we can simply achieve same thing with the following snippet below:

```Python
import os

level {
  src.services: os.environ.get('LOG_LEVEL_SRC_SERVICES', '')
  src.services.user: 'DEBUG'
  src.services.store: os.environ.get('LOG_LEVEL_SRC_SERVICES_STORE', '')
}
```

**Comment by Delgan** [comment]
This is a common question in the Python ecosystem, whether providing configuration through a `.py' file is good practice or not. I don't have a strong opinion on either approach. Both solutions are acceptable and will depend on the intended use. 

Using a YAML file is probably safer and cleaner, but it will prove to be less versatile when it comes to implementing custom sink functions for example.

**Comment by fehimaltinisik** [comment]
I understand your point.

Your prior suggestion has been immensely helpful for my current use case. So I am closing this issue.

I greatly appreciate your efforts in providing such a great package 💎. Thank you for your assistance. Have a great one!

**Comment by Delgan** [comment]
Note that @erezinman just created a great package specifically dedicated to handle Loguru configuration from YAML files (among other formats): https://github.com/erezinman/loguru-config

You might be interested. :+1:
