### ISSUE TITLE
File not retried

### ISSUE THREAD

**Issue by mrx23dot** [Delgan/loguru#881]
I deleted the log file while the app was running, 
but then loguru never tried to recreate it in 24hrs, even though there were warnings to be stored.

debian
py3.9
loguru==0.6.0

**Comment by Delgan** [comment]
The file should not be deleted manually when the app is running. Loguru opens the file once on startup, and then uses the file handler to write the logs, without checking that the file still exists (for performance reasons). 

However, if you upgrade to Loguru v0.7.0, you could use the `watch` argument of `logger.add()`. When `watch=True`, the file will be monitored and re-created before writing a log message if it has been deleted.

**Comment by Delgan** [comment]
Writing to a file handler does not raise an exception even if the file is deleted.
