### ISSUE TITLE
How to print a colored formatted table using loguru?

### ISSUE THREAD

**Issue by Coinhexa** [Delgan/loguru#887]
![image](https://github.com/Delgan/loguru/assets/70217835/80ca3aa3-8134-4dc7-bc91-2cf3b99aa360)

How do you print a table on the terminal that lets you add colors using loguru?
- I have a list of urls loaded with status codes 200,400 etc
- I would like to print them neatly inside a table with 200 highlighted in green and 400 in red on the terminal
- Is there a way to log something like this using loguru?

**Comment by Coinhexa** [comment]
[Print the prettytable library output inside loguru](https://github.com/jazzband/prettytable/blob/main/tests/test_prettytable.py)

**Comment by Delgan** [comment]
Loguru isn't the appropriate tool for such formatting, `prettytable` or `rich` are indeed preferable. 
However, if you extract the table to a string, you can then log it as any other message.
