### ISSUE TITLE
Value of record.name has changed since Python 3.11

### ISSUE THREAD

**Issue by ggree1** [Delgan/loguru#889]
To differentiate the uvicorn access log, I added the following filter statement when using logger.add:
filter=lambda record: record["name"] == "uvicorn.protocols.http.httptools_impl"

However, after upgrading to Python 3.11, 
the value "logging" is being outputted in record["name"] 
instead of "uvicorn.protocols.http.httptools_impl", 
causing the filtering to not work correctly.

It seems that there is an issue with retrieving the frame in the InterceptHandler. 
How should I modify it?
Or How can I distinguish if the log message is from uvicorn.access ?

```python
class InterceptHandler(logging.Handler):
    def emit(self, record: logging.LogRecord) -> None:
        # Get corresponding Loguru level if it exists
        try:
            level: str = logger.level(record.levelname).name
        except ValueError:
            level: str = str(record.levelno)

        # Find caller from where originated the logged message
        frame, depth = logging.currentframe(), 2
        while frame.f_code.co_filename == logging.__file__:  # this should be changed?
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(
            level,
            record.getMessage(),
        )
```

**Comment by ggree1** [comment]
I just changed like below, and everything is well again.

```python
        frame, depth = logging.currentframe(), 0
        while frame.f_code.co_filename == logging.__file__ or frame.f_code.co_filename == __file__:
            frame = frame.f_back
            depth += 1
```

**Comment by Delgan** [comment]
There has indeed been a breaking change with Python 3.11. Note that the `InterceptHanler` in the README has been updated.

**Comment by ggree1** [comment]
> There has indeed been a breaking change with Python 3.11. Note that the `InterceptHanler` in the README has been updated.

I should have read README first before digging it. Thanks :)
