### ISSUE TITLE
The log file is abnormal when the log is rotating

### ISSUE THREAD

**Issue by jsonvot** [Delgan/loguru#894]
Hi, thank you so much for your project, it's really great. However, some problems have been found in the process of using it recently. Can you help to have a look?

I created a new file `logger.py`
```python
from loguru import logger

logger.remove()
logger.add(
    'logs/log.{time:YYYY-MM-DD}.log',
    level='INFO',
    rotation="00:00",
    retention='1 months',
    enqueue=True
)

logger.info('hello world')
logger.info('hello world')
```
I execute it on a time period of zero, for example at 00:10. Got two log files, but the other one is not what I expected. When I set the rotation parameter to 01:00, the normal result of executing the code will only generate the file `log.log`
`python logger.py`
<img width="378" alt="image" src="https://github.com/Delgan/loguru/assets/23091750/c4cd15b9-d9f6-4a87-8727-d94df736b8a6">

This should be a bug that must appear, and it will appear when it is executed at the same hour of the time set by the rotation parameter value.
@Delgan

**Comment by Delgan** [comment]
Hi @jsonvot.

Sorry but I'm not sure to fully understand the problem you're describing.

The `"log.2023-06-15_00-27_04_266726.log"` file is created when rotation occurs.  It's just the old file that's been renamed. After rotation, logs are wrote to `log.log` and the other one serves as a backup. If you want to limit the number of such files, you can use `retention=1`.

**Comment by jsonvot** [comment]
I changed the configuration of the code again, so it will look clearer. My idea should be easy to realize in your opinion, maybe it's just my improper use that leads to problems.
I hope the result is that the log can be stored by day and kept for one month. According to my configuration, when I execute the code at 0 o'clock, a file similar to log.2023-06-15 _ 00-27-04 _ 266726.log will be generated every time I run it, but I only need a file like log.2023-06-15.log.

**Comment by jsonvot** [comment]
Hi@Delgan, Do you have any good suggestions and/or demo for my question? I'll study.

**Comment by Delgan** [comment]
Hi @jsonvot, thanks for the clarification. I was able to reproduce the issue.

It was a good occasion to use `git bisect`. Running the following test scripts:

```python
from loguru import logger
logger.remove()
logger.add(
    'logs/log.{time:YYYY-MM-DD}.log',
    level='INFO',
    rotation="00:00",
    retention='1 months',
    enqueue=False
)

logger.info('hello world')
```
```bash
#!/usr/bin/env bash

rm -rf logs/*
sudo date --set="2023-06-15 23:59:55"
python script.py
sudo date --set="2023-06-16 00:00:05"
python script.py

file_count=$(find "logs" -maxdepth 1 -type f | wc -l)
if [[ "$file_count" -ne "2" ]]; then
  exit 1
fi
```

Led to the following faulty commit: https://github.com/Delgan/loguru/commit/20eb57f8728c64b95aa5fb1c5b34eedf1fb03024

In this commit, I added support for localized aware datetime used for `rotation` but it seems I introduced a regression.

As a workaround until I fix this bug, I think you can replace `rotation="00:00"` with a `datetime.time()` object configured with appropriate time and timezone: `rotation=datetime.time(hour=0, minute=0, tzinfo=datetime.timezone(datetime.timedelta(hours=2)))`. I'm not sure exactly which `tzinfo` you must use here... Maybe you need to actually specify UTC time (with `tzinfo=datetime.UTC`) of your local midnight time.
