### ISSUE TITLE
[self-tests] test_add_option_kwargs fails on ppc64le

### ISSUE THREAD

**Issue by stanislavlevin** [Delgan/loguru#896]
`test_add_option_kwargs` (loguru 0.7.0) fails on ppc64le machine with:
```
=================================== FAILURES =================================== 
_____________________________ test_file_buffering ______________________________ 
                                                                                 
tmp_path = PosixPath('/usr/src/tmp/pytest-of-builder/pytest-0/test_file_buffering0')
                                                                                 
>   ???                                                                          
E   AssertionError: assert '' != ''                                              
E    +  where '' = <bound method Path.read_text of PosixPath('/usr/src/tmp/pytest-of-builder/pytest-0/test_file_buffering0/test.log')>()                              
E    +    where <bound method Path.read_text of PosixPath('/usr/src/tmp/pytest-of-builder/pytest-0/test_file_buffering0/test.log')> = PosixPath('/usr/src/tmp/pytest-of-builder/pytest-0/test_file_buffering0/test.log').read_text
                                                                                 
file       = PosixPath('/usr/src/tmp/pytest-of-builder/pytest-0/test_file_buffering0/test.log')
tmp_path   = PosixPath('/usr/src/tmp/pytest-of-builder/pytest-0/test_file_buffering0')
                                                                                 
tests/test_add_option_kwargs.py:30: AssertionError
```

According to https://docs.python.org/3/library/functions.html#open:
> When no buffering argument is given, the default buffering policy works as follows:
> - Binary files are buffered in fixed-size chunks; the size of the buffer is chosen using a heuristic trying to determine the underlying device’s “block size” and falling back on io.DEFAULT_BUFFER_SIZE. On many systems, the buffer will typically be 4096 or 8192 bytes long.

On that machine:
```
(Pdb) file.stat().st_blksize
65536
(Pdb) io.DEFAULT_BUFFER_SIZE
8192
```

**Comment by Delgan** [comment]
Thanks for the report!

I can't remember why I wrote the test using `buffering=-1`. I'll update the test so that it's deterministic and not OS-dependent.

**Comment by Delgan** [comment]
Now I remember why I implemented the test in this way. A fixed-size buffer can only be used with files opened in binary mode, but Loguru doesn't support binary mode.

The test can't be made fully deterministic, therefore I added a check to skip the test on platforms where an unexpected buffer size is encountered.

Thanks again for the report. It has been fixed on `master` branch.
