### ISSUE TITLE
Include specical character in format string

### ISSUE THREAD

**Issue by af6140** [Delgan/loguru#9]
Cannot figure out how to include { or } literal character in format string.

**Comment by Delgan** [comment]
You can solve it the same way it is solved in `str.format()` (as Loguru uses it internally): by [doubling the braces](https://docs.python.org/3/library/string.html#formatstrings).

```python
logger.debug("{{ Hello }} {}", "world")
# => "{ Hello } world"
```

Also, note that if `*args` and `**kwargs` of your logged message are both empty, no formatting will occur, so you don't need to escape the braces.

```python
logger.debug("{ Hello } world")
# => "{ Hello } world"
```

**Comment by af6140** [comment]
cool, {{ has bo be followed by a space to get a single {.

**Comment by af6140** [comment]
Oh, forgot to mention, I was talking about generating { in format string.
