### ISSUE TITLE
How to redirect `print` and `logging` messages from third-party modules to `loguru`?

### ISSUE THREAD

**Issue by changchiyou** [Delgan/loguru#901]
I use `logging` directly instead of `loguru` before, and I have write some code to redirect `print` messages from third-party modules to `logging`:

```
import logging

class OutputLogger:
    """
    serves as a pseudo file-like stream object that redirects written content to a logger instance.
    It overrides the `write` method to append the written messages to an internal buffer
    (`linebuf`). When a message ends with a newline character, it logs the buffered messages
    as a log record.
    """

    def __init__(self, logger_name: str, logging_level: int = logging.INFO) -> None:
        self.logger = logging.getLogger(logger_name)
        self.logging_level = logging_level
        self.linebuf = ""

    def write(self, msg: str) -> None:
        r"""
        If redirected output end without `\n`, append it into `self.linebuf`,
        and log it out when the redirected output which end with `\n` comes.
        """
        self.linebuf += msg
        if msg.endswith("\n") is True:
            self.logger.log(
                self.logging_level,
                self.linebuf.rstrip(),
                stack_info=False,
                stacklevel=2,
            )
            self.linebuf = ""

    def flush(self) -> None:
        """
        Note that self.linebuf = '' is where the flush is being handled,
        rather than implementing a flush function.
        """
```

```
from contextlib import redirect_stderr

with redirect_stdout(OutputLogger(logging_level=logging.DEBUG)):  # type: ignore
    print("some message")
    third_party_moduel()
```

Is there any build-in feature works exactly same or even better?

### What have I tried

1. modify `OutputLogger` class above:

```diff
- self.logger = logging.getLogger(logger_name)
+ self.logger = loguru.logger
```

2. try to redirect `logging` messages to `loguru`:
```
with redirect_stderr(OutputLogger(logging_level=logging.DEBUG)):
    logging.debug("debug")
    logging.info("info")
```

but it didn't work, nothing printed on console and even no traceback error logs.

---

**Note.** My project used `Flask` to display, and `Flask` logs with `logging`(`"werkzeug"`). I want to record all the messages with `loguru` including messages which are generated with `logging` by third-party modules. This is the root reason why I want to redirect messages to `loguru`. If there exists any features which can solve my needs please ignore the question above 😃

**Comment by changchiyou** [comment]
I solve this problem via [ChatGPT](https://chat.openai.com/share/2389891a-9257-4db4-8d3b-354beae57cd1):

```
import logging
from flask import Flask
from loguru import logger

app = Flask(__name__)

# Werkzeug logger configuration
werkzeug_logger = logging.getLogger("werkzeug")
werkzeug_logger.addHandler(logging.StreamHandler())
werkzeug_logger.setLevel(logging.DEBUG)

def redirect_werkzeug_logs_to_loguru(record):
    log_level = logging.getLevelName(record.levelno)
    logger_opt = logger.opt(depth=6, exception=record.exc_info)
    logger_opt.log(log_level, record.getMessage())


werkzeug_logger.addFilter(redirect_werkzeug_logs_to_loguru)

@app.route('/')
def hello_world():
    return 'Hello, World!'

if __name__ == '__main__':
    app.run()

```

But I still wanna know whether exists better solution 👍

**Comment by changchiyou** [comment]
[The solution above](https://github.com/Delgan/loguru/issues/901#issuecomment-1606988163) has the problem about recording logs with color-syntax:

```
2023-06-26 20:36:11,012 INFO     [facepcs] serving.py - log_startup() : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
* Running on all addresses (0.0.0.0)
* Running on http://127.0.0.1:8000
* Running on http://192.168.1.110:8000
2023-06-26 20:36:11,012 INFO     [facepcs] serving.py - run_simple() : [33mPress CTRL+C to quit[0m`
```

**Comment by Delgan** [comment]
Hi.

To redirect messages from standard `logging` to Loguru, it is suggested to define and install a `InterceptHandler`: [Entirely compatible with standard logging](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging).

Regarding capture of messages emitted by `print()`, you can use `contextlib.redirect_stdout()`: [Capturing standard `stdout`, `stderr` and `warnings`](https://loguru.readthedocs.io/en/stable/resources/recipes.html#capturing-standard-stdout-stderr-and-warnings).

**Comment by changchiyou** [comment]
> To redirect messages from standard `logging` to Loguru, it is suggested to define and install a `InterceptHandler`: [Entirely compatible with standard logging](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging).

It perform like [the code above](https://github.com/Delgan/loguru/issues/901#issuecomment-1606988163) but it handle the `depth` and `level` with a better way. 

@Delgan Thanks for your reply, I guess that now I only have to combine the code with https://github.com/Delgan/loguru/issues/901#issuecomment-1607431982 then it would be perfect for me 😄 

> Solved via [ChatGPT](https://chat.openai.com/share/26ff7e69-5f1b-4a71-a8bd-613270a03ac1) again:
> 
> ```
> import re
> 
> ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
> 
> def redirect_werkzeug_logs_to_loguru(record):
>     log_level = logging.getLevelName(record.levelno)
>     log_message = ansi_escape.sub('', record.getMessage())
>     logger_opt = logger.opt(depth=6, exception=record.exc_info)
>     logger_opt.log(log_level, log_message)
> ```
