### ISSUE TITLE
Different level logs being shown even though handler is in place

### ISSUE THREAD

**Issue by mayurpande** [Delgan/loguru#904]
You have said in this [closed issue](https://github.com/Delgan/loguru/issues/54#issuecomment-461724397):

> As for clarification, doing from loguru import logger in each submodule will remember each added handler? As in no need to pass logger?

> Yes, exactly. The logger is just an object which dispatch your logs to all added handlers. Usually, you should .add() handlers in your main module while starting your application. Then in your sub-modules, from loguru import logger suffices, each future calls to logging functions (.debug(), .info(), etc.) will be propagated to the configured handlers.

However I have done this exact process, and INFO logs are still being shown in the console, and same if I change it around.

So for stderr I want it to only log "DEBUG" level logs (i.e. logger.debug("my debug log")).

For write to file I want it to only log "INFO" level logs (i.e. logger.info("my info log")).

So in my main app.py I have added the loggers as per the [docs](https://loguru.readthedocs.io/en/stable/overview.html#no-handler-no-formatter-no-filter-one-function-to-rule-them-all) like so:

```
import sys

from loguru import logger

from my_module import my_function

logger.add(sys.stderr, level="DEBUG")
logger.add("logs/file1.log", level="INFO")

results = my_function()

```

Then I have my_function() defined in my_module.py like so:

```
from loguru import logger


def my_function():

   logger.info("Start fn")
   # some sql query
   logger.debug("Debug message")
   logger.info("Finishes fn")
```

But as mentioned above it just prints them all out regardless of debug or info level.

**Comment by Delgan** [comment]
The `level` value is a minimum threshold. All messages from this level and above will be logged by the corresponding handler. If you want only `"DEBUG"`, you can use a `filter`:

```python
logger.add("sys.stderr, level="DEBUG", filter=lambda record: record["level"].name == "DEBUG")
```

**Comment by mayurpande** [comment]
Still seems to do it. I tried various variations as well.

I tried to say != INFO like so:

```
logger.add(sys.stderr, level="DEBUG", filter=lambda record: record["level"].name != "INFO")
```

I tried to put the add handler directly above the line where it logs like so:

```
logger.add(sys.stderr, level="DEBUG", filter=lambda record: record["level"].name == "DEBUG")
logger.info("Should not log to console")
```

I also did a print statement to see what level it was:
```
logger.add(sys.stderr, level="DEBUG", filter=lambda record: print(record["level"].name))
```

then in my next module

```
logger.info("Should not log to console")
```

```bash
> INFO
> 2023-06-28 09:56:04.846 | INFO     | __main__:<module>:15 - Should not log to console
```

I also tried in the main module itself:

```
logger.add(sys.stderr, level="DEBUG", filter=lambda record: record["level"].name == "DEBUG")
logger.info("Should not log to console")
```

then in my console

```
> 2023-06-28 09:56:04.846 | INFO     | __main__:<module>:15 - Should not log to console
```

**Comment by mayurpande** [comment]
![handler_loguru](https://github.com/Delgan/loguru/assets/6522456/f51f2199-192c-42ec-a514-d6b96968427e)
Now I am getting stranger behaviour with `stdout` not only it logs INFO level but it logs level DEBUG twice

**Comment by mayurpande** [comment]
Ah sorry, I removed default handler with:

`logger.remove()`

Before my add handler
