### ISSUE TITLE
Configure from file (JSON, YAML, etc.)

### ISSUE THREAD

**Issue by erezinman** [Delgan/loguru#914]
Hi,
Is there a way to configure non-file sinks using `logger.configure` straight from loaded configurations? For example, I want to configure  one of the sinks with `sys.stderr` straight from a `json.load`. Is there a way to do it?

Maybe I'm getting ahead of myself, but if there isn't such a way (as far as I see from the docs and code), I was thinking of implementing a configuration loader that mimics `python.logging`'s powerful configuration loader (and adds upon it). That is, it takes/loads a dictionary, and recursively parses its contents with the options below:

 *   `ext://package.module.member` (e.g. `ext://sys.stderr`) - imports `package.module` and gets `member` out of it.
 *   `cfg://path/to/file.json`  - loads a config part from the file path.
 *   User-defined objects - call a callable with the given values and use its return value instead of the callable specification. For example:
      
      ```yaml
      sink:
          (): my.package.load_sink
          bar: baz
          spam: 99.9
          answer: 42
      ```
  *  In addition, we could define "abbreviations" for common choices of sinks. For example, `sink: <stderr>`. 
  *  Another useful option would be to load values from environment variables. For example: `sink: "$://ENV_VAR"`.

This class can possibly be written without changing any code in `loguru`, and possibly as an external package, but it would be useful for anyone who wants to configure their logger (or parts of it) externally, so I could implement it and create a PR.

I would appreciate any thoughts on the matter.

Thanks!

**Comment by Delgan** [comment]
Hi @erezinman. ;)

No such feature exists within Loguru. It's a design choice that leaves users free to choose the configuration format they prefer and to avoid managing this complexity in the code base.

However, the implementation of a third-party library is very welcome and could be referenced in the documentation.

**Comment by erezinman** [comment]
Hi @Delgan,

Then you will hear from me soon. :)

Erez

**Comment by erezinman** [comment]
Hi, @Delgan 
I finished writing the [configurator](https://github.com/erezinman/loguru-config). Any comments before I release the first version?

Thanks

**Comment by Delgan** [comment]
Wow, I'm very impressed with the library you created. I always thought it would be too complicated to make something generic that could be kept simple but still handle all the special cases. Yet you've managed to make a feature-complete parser that's extremely easy to learn. I really like your attention to details (literals, user-defined functions, compatibility with `logging` handlers, recursion, extensibility, escaping, etc.) and I love how you extended the `logging.config` fields protocol to make it even more powerful and comprehensible.

Thank you very much for your work. That's definitely a big improvement for Loguru.

**Comment by erezinman** [comment]
@Delgan Thank you very much! It's a big compliment coming from you. So I'll publish it!

**Comment by erezinman** [comment]
@Delgan 
Now can be found at https://pypi.org/project/loguru-config/0.1.0/

**Comment by Delgan** [comment]
Great, thanks again! I updated the Readme and documentation to reference `loguru-config` library.
