### ISSUE TITLE
How to log with file name?

### ISSUE THREAD

**Issue by DeepDuke** [Delgan/loguru#915]
Usually the log looks like this, which doesn't show original filename but `__main__:<module>` 
`2023-07-04 15:30:44.302 | DEBUG    | __main__:<module>:13 - Hello World!`

How can we specify the configuration to show the original file name, e.g. `test.py`?

**Comment by DeepDuke** [comment]
Sorry, I didn't follow u. Does it mean that `logger.add(log_file_path, format=your-fmt-string)`? I have tried this, but it's not working...

**Comment by Chris-fullerton** [comment]
@DeepDuke remove `[<cyan>{extra[mark]}</cyan>]` from @changchiyou 's dormat string, then it should be work.

Or, set the `extra` info via `logger.configure(extra={"mark":"your_mark"})` and remain entire format string.

**Comment by DeepDuke** [comment]
@Chris-fullerton TKS！ It successfully printed the file name in log file. But I was curious about that the terminal output still missed the orignal file name.

This is sceenshot for log file. It showed the file name.
![image](https://github.com/Delgan/loguru/assets/15854511/d857acf6-16cb-482d-83d7-2baf3126af2c)

But for the terminal, it still printed `__main__:<module>`:
![image](https://github.com/Delgan/loguru/assets/15854511/4db385ab-bf8a-4208-a4dc-5cefe2e95025)

**Comment by Chris-fullerton** [comment]
@DeepDuke execute `logger.remove()` before your logger settings(multiple `logger.add()`) can solve your problem.

I **GUESS** that you have not remove the default handler which exists since you execute `from luguru import logger` at the first time, because the logger format in the first image you provided above

![](https://user-images.githubusercontent.com/15854511/250884710-d857acf6-16cb-482d-83d7-2baf3126af2c.png)

is same as the default handler.

**Comment by DeepDuke** [comment]
@Chris-fullerton But after adding `logger.remove()`,  the terminal will output nothing. How can I make the terminal print the same thing with the log file?

**Comment by Chris-fullerton** [comment]
@DeepDuke simply add another `logger.add()` to create a new handler for console

```
import sys
from loguru import logger

if __name__=="__main__":
  format = "<green>{time:YYYY-MM-DD HH:mm:ss,SSS}</green> <level>{level: <8}</level> <cyan>{file}</cyan> - <cyan>{function}</cyan>() : <level>{message}</level>"
  
  logger.remove()
  logger.add('record.log', format=format) # replace 'record.log' with your personal log object
  logger.add(sys.stderr, format=format)

  logger.debug("Hello World!")
  logger.info("This is normal info!")
```

**Comment by DeepDuke** [comment]
@Chris-fullerton @changchiyou Got it! Thanks for your kind help!

**Comment by Delgan** [comment]
Thanks @changchiyou  and @Chris-fullerton for the support. :+1:
