### ISSUE TITLE
logger format in console?

### ISSUE THREAD

**Issue by sheldygg** [Delgan/loguru#917]
when i set format like that
```python
logger.add(
    sink="log.log",
    format="[{time:MM-DD HH:mm:ss.SSS}] {level} | {name}: {message}"
)
```
this works only for log file, but not for console logs.
why?

**Comment by Delgan** [comment]
You need to `remove()` and re-`add()` a `sys.stderr` sink (to replace the one by default).

```python
logging_format = "[{time:MM-DD HH:mm:ss.SSS}] {level} | {name}: {message}"
logger.remove()
logger.add("log.log", format=logging_format)
logger.add(sys.stderr, format=logging_format)
```

**Comment by sheldygg** [comment]
works, but not colorized.
i try to pass colorize=True, but not help

**Comment by Delgan** [comment]
You need to add color markups to the `loging_format`, e.g.:

```python
logging_format = "<green>[{time:MM-DD HH:mm:ss.SSS}]</green> <level>{level} | {name}: {message}</level>"
```

See documentation here for details: [The color markups](https://loguru.readthedocs.io/en/stable/api/logger.html#color).

**Comment by sheldygg** [comment]
thanks.
