### ISSUE TITLE
Question: How can I obtain a value for {elapsed} separately

### ISSUE THREAD

**Issue by stevenhubhub** [Delgan/loguru#918]
logger.add(stdout, colorize=True, level='DEBUG',
                   format="{time:YYYY-MM-DD HH:mm:ss.SSS}|<level>{level}</level>|{message}|{elapsed}")

I want to elapsed the value of the parameter "elapsed" in the non-log code and I don't know how to do it.

Just like this:
print(f" {elapsed} ")

Thanks.

**Comment by changchiyou** [comment]
I don't think here exists an official way to get the `elapsed`'s value.

However, you can still learn how `elapsed` in `format` is replaced with the corresponding value and how to simulate similar results through the following reading order.

https://github.com/Delgan/loguru/blob/9fc929a54ae6ef92208c90ebafd449b8f9e3e34a/loguru/_handler.py#L253-L277

https://github.com/Delgan/loguru/blob/9fc929a54ae6ef92208c90ebafd449b8f9e3e34a/loguru/_logger.py#L2002

https://github.com/Delgan/loguru/blob/9fc929a54ae6ef92208c90ebafd449b8f9e3e34a/loguru/_logger.py#L1952-L1966

https://github.com/Delgan/loguru/blob/9fc929a54ae6ef92208c90ebafd449b8f9e3e34a/loguru/_logger.py#L1939

https://github.com/Delgan/loguru/blob/9fc929a54ae6ef92208c90ebafd449b8f9e3e34a/loguru/_logger.py#L110

https://github.com/Delgan/loguru/blob/9fc929a54ae6ef92208c90ebafd449b8f9e3e34a/loguru/_logger.py#L1932

https://github.com/Delgan/loguru/blob/9fc929a54ae6ef92208c90ebafd449b8f9e3e34a/loguru/_datetime.py#L81-L96

**Comment by Delgan** [comment]
This is not possible to access such value in "non-log code". If the business logic of your application requires to know the elapsed time, this should be implemented outside of the logging system.
