### ISSUE TITLE
about custom serializer

### ISSUE THREAD

**Issue by hanzhenbjm** [Delgan/loguru#919]
Hi

I use Loguru, how do I implement all the custom fields? For example, log_message replaces message and log_time replaces time. The log id of each request must be uniquely recorded in the traceId of the user-defined field. log files generated under the path are debug.log, warn. log, trace.log, error.log, and info.log. The logs are generated every day and reserved for 7 days. The log format is json, and only logs of the current log_level are written into the log file. For example, debug logs are only in the debug.log file, and error logs are only in the error.log file. The final effect is logger.debug("hello,world"), and in debug.log is {"log_message": "hello,world", "traceId": log_id, "log_time": "2023-07-12 10:08:35.088"}

thank you

**Comment by changchiyou** [comment]
- `test.py`:
```python 
from loguru import logger

def set_loguru_example(log_id):
    logger.configure(extra={"log_id": log_id})
    logger.remove()
    
    shared_parameters = {"rotation":"00:00", "retention":"1 week", "format":'{{log_message: "{message}", "traceId": {extra[log_id]}, "log_time": "{time:YYYY-MM-DD HH:mm:ss.SSS}"}}', "level": "TRACE"}

    logger.add("trace.log", filter=lambda record: "TRACE" == record["level"].name, **shared_parameters)
    logger.add("debug.log", filter=lambda record: "DEBUG" == record["level"].name, **shared_parameters)
    logger.add("info.log", filter=lambda record: "INFO" == record["level"].name, **shared_parameters)
    logger.add("warning.log", filter=lambda record: "WARNING" == record["level"].name, **shared_parameters)
    logger.add("error.log", filter=lambda record: "ERROR" == record["level"].name, **shared_parameters)

if __name__ == "__main__":
    set_loguru_example(log_id=1)
    logger.trace("trace_msg")
    logger.debug("debug_msg")
    logger.info("info_msg")
    logger.warning("warning_msg")
    logger.error("error_msg")

```

- `python test.py; find . -type f -name "*.log" -exec sh -c 'echo "==== {} ===="; cat {}' \;`

```
==== ./trace.log ====
{log_message: "trace_msg", "traceId": 1, "log_time": "2023-07-12 14:22:09.566"}
==== ./error.log ====
{log_message: "error_msg", "traceId": 1, "log_time": "2023-07-12 14:22:09.569"}
==== ./debug.log ====
{log_message: "debug_msg", "traceId": 1, "log_time": "2023-07-12 14:22:09.569"}
==== ./info.log ====
{log_message: "info_msg", "traceId": 1, "log_time": "2023-07-12 14:22:09.569"}
==== ./warning.log ====
{log_message: "warning_msg", "traceId": 1, "log_time": "2023-07-12 14:22:09.569"}
```

**Comment by Delgan** [comment]
Thanks @changchiyou for the example.

@hanzhenbjm Does that help?

**Comment by hanzhenbjm** [comment]
import os
import json
import uuid
from loguru import logger

path_ = "./"
name = "Python"


def loki_formatter(record):
    loki_dict = {"code_message": record["message"],
                 "log_time": record["time"].strftime('%Y-%m-%d %H:%M:%S.%f')[:-3],
                 "order_id": record["extra"]['extra']['orderId'],
                 "traceId": record["extra"]['extra']['traceId'],
                 "HOSTNAME": os.environ.get("HOSTNAME"),
                 "lineno": record['line'],
                 "module": record['module'],
                 "funcName": record['function'],
                 "level": record['level'].name,
                 "projectName": name
                 }
    serialized = json.dumps(loki_dict)
    record["extra"]["loki_dict"] = serialized
    return "{extra[loki_dict]}\n"


def set_loguru_example(path):
    logger.remove()

    shared_parameters = {"rotation": "00:00", "retention": "1 week"}
    logger.add(path + "trace.log", filter=lambda record: "TRACE" == record["level"].name, **shared_parameters,
               format=loki_formatter, level="TRACE")
    logger.add(path + "debug.log", filter=lambda record: "DEBUG" == record["level"].name, **shared_parameters,
               format=loki_formatter)
    logger.add(path + "info.log", filter=lambda record: "INFO" == record["level"].name, **shared_parameters,
               format=loki_formatter)
    logger.add(path + "warning.log", filter=lambda record: "WARNING" == record["level"].name, **shared_parameters,
               format=loki_formatter)
    logger.add(path + "error.log", filter=lambda record: "ERROR" == record["level"].name, **shared_parameters,
               format=loki_formatter)


if __name__ == '__main__':
    transaction_id = str(uuid.uuid4()).replace('-', '')
    set_loguru_example(path_)
    logger.trace("trace_msg", extra={"orderId": "123456", "traceId": transaction_id})
    logger.debug("debug_msg", extra={"orderId": "123456", "traceId": transaction_id})
    logger.info("info_msg", extra={"orderId": "123456", "traceId": transaction_id})
    logger.warning("warning_msg", extra={"orderId": "123456", "traceId": transaction_id})
    logger.error("error_msg", extra={"orderId": "123456", "traceId": transaction_id})

**Comment by changchiyou** [comment]
@Delgan You can simply insert your code into a pair of ```, for example:

````
```
your code
```
````

**Comment by hanzhenbjm** [comment]
thank you
If I want to change warning to a different format
Just change loki_formatter to my new format, right?
and Is there any risk in me writing this way

**Comment by hanzhenbjm** [comment]
```local.transaction_id = str(uuid.uuid4()).replace('-', '')```
```logger.debug("debug_msg", extra={"orderId": "123456", "traceId": getattr(local, 'transaction_id', None)})```
Is this necessary for high concurrency considerations?

**Comment by hanzhenbjm** [comment]
```  
 logger.add(path + "warn.log", filter=lambda record: "WARN" == record["level"].name, **shared_parameters,
               format=regular_formatter, level="WARN")
logger.warn("hello world", extra={"orderId": order_id, "traceId": getattr(local, 'transaction_id', None)})
```


ValueError: Level 'WARN' does not exist

**Comment by changchiyou** [comment]
> ```
>  logger.add(path + "warn.log", filter=lambda record: "WARN" == record["level"].name, **shared_parameters,
>                format=regular_formatter, level="WARN")
> logger.warn("hello world", extra={"orderId": order_id, "traceId": getattr(local, 'transaction_id', None)})
> ```
> 
> 
>     
>   
> 
> ValueError: Level 'WARN' does not exist

Please refer to [loguru.readthedocs.io - The severity levels](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger:~:text=used%20for%20formatting\).-,The%20severity%20levels,-Each%20logged%20message), here is not build-in level named `"WARN"`. 

I guess you have misspelled `"WARNING"` from my answer above:

> ```python
> logger.add("warning.log", filter=lambda record: "WARNING" == record["level"].name, **shared_parameters)
> ```

Or, if you want to have a costomize level with `loguru`, please refer to https://github.com/Delgan/loguru#customizable-levels  .

---

BTW, you can enhance your codeblock FVX with following markdown syntax:

````
```python

```
````

**Comment by hanzhenbjm** [comment]
I'm sorry I didn't make my meaning clear. I just wanted to customize log level, logger.warn("hello"), but an error was reported。
new_level = logger.level("SNAKY", no=38, color="<yellow>", icon="🐍")
Can logger.snaky("hello") be implemented?
Instead of logger.log("SNAKY", "Here we go!" )

**Comment by changchiyou** [comment]
@hanzhenbjm `loguru` doesn't support this currently. You can only costomize your logging level and log with 

```python
logger.log("WARN", "Here we go!")
```

In my opinion, it's possible to implement it, but extremely unsafe. For example, you may accidentally overwrite an existing method like `loguru.add` or `loguru.remove`, which could easily cause unexpect error.

If you really want to log via `logger.warn("Here we go!")` instead of `logger.log("WARN", "Here we go!")` with `loguru`. You can fork this repo and rewrite `loguru.Logger` by yourself 🤣 :
```python
class Logger:
  ...
  def __getattr__(self, ...):
    # do something here
    return getattr(...)
```

**Comment by hanzhenbjm** [comment]
thank you
