### ISSUE TITLE
How to reset the logging level?

### ISSUE THREAD

**Issue by jakane** [Delgan/loguru#92]
newbie to loguru here, but I like it so far.

I would like to know how to change the logging level for a particular handler after it has been initially configured.

For instance:

```
import sys
from loguru import logger

console_dict = {'sink': sys.stderr, 'level': 'INFO'}
file_dict = {'sink': 'file.log', 'level': 'INFO'}
console_handler, file_handler = logger.configure(handlers=[console_dict, file_dict])

if 'verbose' in **kwargs:
  logger.update_level(console_handler, level='DEBUG')
if 'verbose_log' in **kwargs:
  logger.update_level(file_handler, level='DEBUG')
```

This would allow one to begin your application with default logging level(s) and then, based on command line options, environment variables, or configuration file option, alter the logging level(s) to reflect your needs.

I have not been able to figure out how to do this without removing all of the loggers and then reinstantiating them with an updated `level={LEVEL}` in it's handler dict.

```
if 'verbose' in **kwargs:
  console_dict['level'] = 'DEBUG'
if 'verbose_log' in **kwargs:
  file_dict['level'] = 'TRACE'
console_handler, file_handler = logger.configure(handlers=[console_dict, file_dict])
```

That seems to be a bit **heavy** to me, and disruptive as well.

Am I messing something?

Thanks

**Comment by jakane** [comment]
I found: [Change level of default handler](https://github.com/Delgan/loguru/issues/51)
and [https://loguru.readthedocs.io/en/latest/resources/recipes.html#changing-the-level-of-an-existing-handler](Changing the level of an existing handler)

I missed the docs because the link I followed to the docs opened the **stable** branch and not the **latest** ... lots more documentation in **latest**.

I can live with the work around, I will move from `logger.config()` to:

```
logger.remove()
console_handler = logger.add(**console_dict)
file_handler = logger.add(**file_dict)

if 'verbose' in **kwargs:
  console_dict['level'] = 'DEBUG'
  logger.remove(console_handler)
  console_handler = logger.add(**console_dict)
if 'verbose_log' in **kwargs:
  file_dict['level'] = 'TRACE'
  logger.remove(file_handler)
  file_handler = logger.add(**file_dict)
```

This will accomplish what I need.

**Comment by Delgan** [comment]
> I missed the docs because the link I followed to the docs opened the **stable** branch and not the **latest** ... lots more documentation in **latest**.

Yep, sorry for that... A bunch of documentation has been added lately, but it did not make it to the `stable` branch yet. I have to update the links once the next version is released.

You can keep using `logger.configure()` if you prefer, although the solutions are equivalent:

```python
logger.remove()
console_handler = logger.add(**console_dict)
file_handler = logger.add(**file_dict)

if 'verbose' in **kwargs:
  console_dict['level'] = 'DEBUG'
if 'verbose_log' in **kwargs:
  file_dict['level'] = 'TRACE'

# ".configure()" remove the existing handlers anyway
logger.configure(handlers=[console_dict, file_dict])
```
