### ISSUE TITLE
file.path return relative path instead of full path

### ISSUE THREAD

**Issue by qsh-zh** [Delgan/loguru#922]
Thanks for the awesome `loguru`. It makes coding much easier for me. 

I notice that the current logger format,  `{file.path}` returns the full path. Is it possible to return the relative path?

**Comment by Delgan** [comment]
Hi.

Related to #649 actually.

To return a relative path, you'll need to [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) the logger (or use [`configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure)):

```python
def add_relative_path(record):
    start = os.getcwd()
    record["extra"]["relative_path"] = os.path.relpath(record["file"].path, start)

logger = logger.patch(add_relative_path)
logger.add(sys.stderr, format="{extra[relative_path]} {message}")
```

**Comment by qsh-zh** [comment]
@Delgan  Thanks for your response. It works!
