### ISSUE TITLE
Demo Code for worker processed application to log with loguru

### ISSUE THREAD

**Issue by jiaulislam** [Delgan/loguru#923]
hi, for past few days I was trying to troubleshoot a problem with builtin logging library as my application was using that. But I came across that its at the moment not possible to solve the issue. So the problem is as below.

I have an FastAPI application API running with hypercorn worker process around 5-8 worker processes. So each worker processess have it's own logging instance with `TimedRotatingFileHandler` independent file(code is as below). But What I want is on the rotation I want all the processes to rotate, not just a single process as this would be hard for me to track the log as in seperate cron job i need to parse the current date logs and consolidate those.

Can it be solved with this library or any demo can be provided how should I solve the issue. Or any other way to tackle the issue.

```python
import logging.config
import os


def get_configs(log_file_path: str) -> dict:
    return {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "normalFormatter": {
                "format": "%(asctime)s | loglevel=%(levelname)-6s | logger=%(name)s >>> %(message)s",
                "datefmt": "%Y-%m-%dT%H:%M:%SZ",
            },
            "detailedFormatter": {
                "format": "%(asctime)s | %(levelname)-7s | %(name)-5s |  funcName: %(funcName)-5s >>> %(message)s",
                "datefmt": "%Y-%m-%dT%H:%M:%SZ",
            },
            "colored": {
                "()": "colorlog.ColoredFormatter",
                "format": "%(log_color)s%(asctime)s | %(levelname)-7s | %(name)-5s |  funcName: %(funcName)-5s >>> %(message)s",
            },
        },
        "handlers": {
            "consoleHandler": {
                "class": "logging.StreamHandler",
                "level": "DEBUG",
                "formatter": "colored",
                "stream": "ext://sys.stdout",
            },
            "detailedConsoleHandler": {
                "class": "logging.StreamHandler",
                "level": "DEBUG",
                "formatter": "colored",
                "stream": "ext://sys.stdout",
            },
            "fileHandler": {
                "class": "logging.handlers.TimedRotatingFileHandler",
                "level": "INFO",
                "formatter": "detailedFormatter",
                "filename": log_file_path,
                "when": "midnight",
                "backupCount": 0,
                "encoding": "utf-8",
            },
        },
        "loggers": {
            "root": {
                "level": "WARNING",
                "handlers": ["detailedConsoleHandler", "fileHandler"],
            },
        },
    }


def init_logging():
    # log directories. log should be kept as folder structure as below
    # ProjectRoot > logs > fileName_pid(processId).log
    logs_directory = os.path.join(
        os.path.dirname(os.path.realpath(__file__)),
        os.pardir,
        os.pardir,
        "logs",
    )

    if not os.path.exists(logs_directory):
        os.makedirs(logs_directory, exist_ok=True)

    # log file name pattern for each of the hypercorn process otherwise with more than
    # one process all process will try to overwrite a single file.
    log_file_name = f"epay_pid{os.getpid()}.log"

    absolute_logfile_path = os.path.join(logs_directory, log_file_name)

    logging.config.dictConfig(get_configs(absolute_logfile_path))
```

**Comment by Delgan** [comment]
Hi.

It looks a bit complicated. Do you have a way of communicating between the different processes? As you said, each handler is independent, so synchronizing their rotation goes against your architecture.

An alternative would be to configure only one handler aggregating logs with inter-process communication: [Logging to a single file from multiple processes](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes).

**Comment by jiaulislam** [comment]
@Delgan , Hi thanks for your reply. It is very complicated. That's why I was searching for a library to use. So i found yours. I saw the documentation where it does support rotaiton but my issue is does it support the multiple workers using the same file to log and at the rotation time will all the workers will be in synced with updated rotated file ?

**Comment by Delgan** [comment]
Multiple handlers should not log to the same file, especially not from multiple processes.

It's possible, though, to have all processes logging to the same file using one unique handler, see: [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument).

However, I don't know if it's easily possible to send the `logger` instance from your main process to the FastAPI workers. I'm working on a way to improve this, but it's not yet available. If you want to keep it simple, I would advise to use one different file and rotation per worker for now (although I understand this is not what you're looking for unfortunately).

**Comment by jiaulislam** [comment]
> 

Thanks for your valuable suggestions. But even if I can't use it for what my purpose. I've decided to use your library for logging. Its much simpler than configuring builtin logger and much matured. Thanks for the hard work

**Comment by Delgan** [comment]
Thanks, I appreciate your feedback. :heart:
