### ISSUE TITLE
Async: Logging error in Loguru Handler #2

### ISSUE THREAD

**Issue by baderdean** [Delgan/loguru#927]
Here below the error in my code when I use AsyncAnnotator
```
--- Logging error in Loguru Handler #2 ---
Record was: None
Traceback (most recent call last):
  File "/home/bader/code/python3/lib/python3.11/site-packages/loguru-0.7.0-py3.11.egg/loguru/_handler.py", line 291, in _queued_writer
    message = queue.get()
              ^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AioRpcError.__init__() missing 3 required positional arguments: 'code', 'initial_metadata', and 'trailing_metadata'
--- End of logging error ---
```
Here below the code that trigger the error even if I use the logger in another context outside this function. If I don't call it, I don't have the error. 

```
async def find_pages_with_matching_images(
        image_url: str,
        max_results: Optional[int] = MAX_VISION_RESULTS,
        ) -> set[str]:
    """Find pages with matching images

    Args:
        image_url (str): image url

    Raises:
        Exception: Google Vision Error

    Returns:
        list[str]: list of urls
    """
    # search using google vision
    client = vision.ImageAnnotatorAsyncClient.from_service_account_file(
            settings.google_vision_credentials
            )

    response = await client.async_batch_annotate_images(
        requests=[vision.AnnotateImageRequest({
            'image': {'source': {'image_uri': image_url}},
            'features': [{
                'type_': vision.Feature.Type.WEB_DETECTION,
                'max_results': max_results,
                }]
    })])
    response = response.web_detection

    if hasattr(response, "error"):
        #log.error(f"Image: {image_url}. Error: {response.error.message}")
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))

    matching = [r for r in response.pages_with_matching_images if "full_matching_images" in r]
    #log.debug(f"Matching images found for {image_url}: {matching}")

    return matching
````

**Comment by Delgan** [comment]
Hi.

This is a problem due to `AioRpcError` not being de-serializable, see https://github.com/grpc/grpc/issues/33643.

In the meantime you can use one of the workaround described here: https://github.com/Delgan/loguru/issues/504#issuecomment-917365972

**Comment by baderdean** [comment]
@Delgan thanks, the hard part is to identify the faulty line of log because there is so much log lines in my code that uses to refer to this part of code while it was sync that now I'm lost especially because the error don't tell at all what file/line is faulty... Is there a way to identify the faulty file/line? I rather prefer that than monkey patching globally because it will requires me to change the import logic in every file and break the modularity of my code.

**Comment by Delgan** [comment]
Because the error occurs during de-serialization of a sink added with `enqueue=True`, it's not possible (for now) to identify the faulty line of code. At the time of de-serialization, the context about the logged message is encoded as `bytes` by `pickle`  protocol. Therefore, no information can be retrieved until the data is decoded... Which never happens.

To find the source of the problem, you can temporarily add the following sink. This is the same `SimpleQueue()` used internally by Loguru when `enqueue=True`, and this is were (de-)serialization occurs. Here, we set `enqueue=False` so that the de-serialization process takes place in the main thread, and thus the original non-serialized `record` is accessible and displayed in case of error. It will contain the file and the line of code where the faulty message was emitted.

```python
import multiprocessing

queue = multiprocessing.SimpleQueue()

def debug_sink(record):
    queue.put(record)
    queue.get()

logger.add(debug_sink, enqueue=False)
```

**Comment by Delgan** [comment]
Next release should include a mitigation for this.
