### ISSUE TITLE
True colors tags and some styles won't display on Windows 10 and above

### ISSUE THREAD

**Issue by tunaflsh** [Delgan/loguru#934]
### To Replicate

```python
from loguru import logger
import sys
logger.remove()
logger.add(sys.stdout, format="{message}")
logger.opt(colors=True).info("<fg 255,0,0>should be red</>")  # "should be red" is default color
logger.opt(colors=True).info("<u>should be underlined</>")  # "should be underlined" has default style
```

### Expected Output

```python
from colorama import just_fix_windows_console
just_fix_windows_console()
print("\033[38;2;255;0;0mthis is red\033[0m")  # "this is red" is red
print("\033[4mthis is underlined\033[0m")  # "this is underlined" is underlined
```

### Environment

- **Operating System**: Windows 11
- **Python Version**: 3.11.4
- **Terminals**: Windows Console, Windows Terminal
- **Shells**: `cmd`, `powershell`, `mingw64`

### Suggestion

On Windows 10 and above ANSI support can be enabled as in [colorama](https://github.com/tartley/colorama#initialisation).

[should_wrap()](https://github.com/Delgan/loguru/blob/master/loguru/_colorama.py#L40) and [wrap()](https://github.com/Delgan/loguru/blob/master/loguru/_colorama.py#L52) are redundant and can be replaced with [colorama.just_fix_windows_console()](https://github.com/tartley/colorama/blob/master/colorama/initialise.py#L72) or [colorama.init()](https://github.com/tartley/colorama/blob/master/colorama/initialise.py#L72)

**Comment by Delgan** [comment]
Fixed by #935.
