### ISSUE TITLE
[Feature] Some way to configure `level` by default - python import arguments

### ISSUE THREAD

**Issue by goyalyashpal** [Delgan/loguru#940]
* continued from: https://github.com/Delgan/loguru/issues/939

Hi! 

just fanatically thinking, does python supports supplying arguments while importing modules/packages like in latex lol?
that would be awesome.

'cz `from loguru import logging; logger.remove(0); logger.add( ... )` feels like hack

ohw wait, one genuine idea came to mind 

how about defining default configurations or defining a handler with default configuration
and require initialising it

this will keep the config requirement to minimal like now; will allow both costumisability (just add the things u want to override while first init); 

this will be a _massive_ breaking change 
but it likely won't break existing use in libraries etc which should be using custom `.add()`s already anyway as per the docs

or maybe something similar comes to someone minds which won't break stuff

**Comment by Delgan** [comment]
Hi.

Loguru supports [environment variable to configure the default handler](https://loguru.readthedocs.io/en/stable/api/logger.html#env), does it seem appropriate to your case?

For example, on Linux if you want the default handler to use `"INFO"` instead of `"DEBUG"` level by default:

```bash
export LOGURU_LEVEL="INFO"
```

**Comment by goyalyashpal** [comment]
hi!

thanks for sharing for levels. but other options like sink, format, etc still have to configured while `logger.add()` right?

**Comment by Delgan** [comment]
The default format is also modifiable through environment variable.
The sink itself is not, it will always log to `sys.stderr`.
Note that the default handler can also be disabled entirely with `LOGURU_AUTOINIT=0`.
