### ISSUE TITLE
.remove() removes all the formatting and colors

### ISSUE THREAD

**Issue by hwuiwon** [Delgan/loguru#942]
Hi, I used .remove() to remove getting double logs, but that would also remove the color and formatting, which is not I want.

How can I fix this?

Without remove
<img width="1222" alt="Screenshot 2023-08-12 at 12 52 36 PM" src="https://github.com/Delgan/loguru/assets/15950753/32b43461-4544-48ff-80c4-0fcc011af7b3">

```
logger.add(sys.stderr, format="{time} {level} {message}", level="INFO")
```

With remove
<img width="1219" alt="Screenshot 2023-08-12 at 12 54 14 PM" src="https://github.com/Delgan/loguru/assets/15950753/2cf2c2c3-707b-449f-b512-273690f7a0cf">
```
logger.remove(0) # same for logger.remove()
logger.add(sys.stderr, format="{time} {level} {message}", level="INFO")
```

**Comment by Delgan** [comment]
You need to add color tags to the format, example:

```python
logger.add(sys.stderr, format="<green>{time}</green> <level>{level} {message}</level>", level="INFO")
```

See more examples [in the documentation](https://loguru.readthedocs.io/en/stable/api/logger.html#color).
