### ISSUE TITLE
Removing Default Loguru Logger When Running Pytests

### ISSUE THREAD

**Issue by quantumpacket** [Delgan/loguru#946]
I'm using this:

```python
@pytest.fixture
def caplog(caplog: LogCaptureFixture):
    # logger.remove()
    handler_id = logger.add(
        caplog.handler,
        format="{message}",
        level=0,
        filter=lambda record: record["level"].no >= caplog.handler.level,
        enqueue=False,
    )
    yield caplog
    logger.remove(handler_id)
```

It works great, and I have no issues when running my Pytests from the commandline.

However, for some reason when I run my Pytests using PyCharm test runner the default logger outputs log entries to the test runner console. My tests still pass, but now my console is cluttered with an ever increasing output of red log entries as I add more tests. Uncommenting the  `logger.remove()` line stops that.

Is this the best way I can prevent this when running my tests, and afaik this would not work globally across all tests? Also, does anyone know why the PyCharm test runner is having this behavior when cli does not? 🤔

**Comment by Delgan** [comment]
I think both Pycharm and Pytest try to replace `sys.stderr` with their own wrapper in some circumstances. It can interfere with default handler of Loguru (which sends logs to `sys.stderr`). Depending on the order in which events are executed (`loguru` import vs. `sys.stderr` replacement), you can experience different behaviors.

If you want to `remove()` the default handler once and for all at the beginning of your tests, I think you can use  a function decorated with `@pytest.fixture(scope="session", autouse=True)` in your `conftest.py`.

**Comment by quantumpacket** [comment]
Thanks @Delgan!

So far this seems to work, time will tell as I add more tests :D

```python
# tests/conftest.py

@pytest.fixture(autouse=True, scope='session')
def remove_default_handler() -> None:
    logger.remove()
```

Closing for now.
