### ISSUE TITLE
Getting the caller class's name in output

### ISSUE THREAD

**Issue by AbhishekBose** [Delgan/loguru#947]
I am using loguru in my FastAPI application and I want users to be not be able to modify the log level by removing the handler.

Hence I have written a class which uses logger from Loguru indirectly.
I have made this class as a singleton and I am passing the message to explicitly defined methods like info, warning ,debug and eror which call logger.error, logger,info etc internally.

This class is LogFactory and instantiated inside a separate file.

I can import this singleton object and use it across the application as needed. The only issue being that , I am not able to get the name of the file in which this called. Instead using the following format

```
"{time} - {name} - {level} - {message}"
```

prints the name of the logger class instead of the caller class

**Comment by Delgan** [comment]
I think you might workaround this issue using `depth` argument of [`logger.opt()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt).

```python
# In your wrapper, use this:
logger.opt(depth=1).info(message)
```

**Comment by Delgan** [comment]
I'm closing this ticket assuming it's solved, then. ;)
