### ISSUE TITLE
Using Multiple Patches Globally

### ISSUE THREAD

**Issue by quantumpacket** [Delgan/loguru#950]
I have two functions which I am applying globally to all loggers, one is to sanitize the message to prevent log injection by escaping newlines, and the other will encrypt exception backtraces to prevent information leakage. Both functions return nothing, and modify the `record` in place by adding the `extra` fields.

However, I'm having an issue applying the functions as patches. The `loguru.logger.configure()` method only allows a single patcher:

**Works**
```python
loguru.logger.configure(patcher=_escape_message)
```
or
```python
loguru.logger.configure(patcher=_encrypt_exception)
```

**Not Supported**
```python
loguru.logger.configure(patcher=[_escape_message, _encrypt_exception])
```

So I then I tried to apply each patch individually like so:
```python
loguru.logger.patch(_escape_message)
loguru.logger.patch(_encrypt_exception)
```

> Note: this is done before I add any sinks, if that makes a difference.

But then neither patch works and I just get a `KeyError` for my now missing `extra` fields. I've looked over the documentation [here](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) and [here](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure), but not seeing what I am missing and why this is not working. I should be able to patch multiple times as least with the last solution?

**Comment by Delgan** [comment]
Hi.

You need to combine your two functions, like so for example:

```python
def global_patches(record):
    _escape_message(record)
    _encrypt_exception(record)

logger.configure(global_patches)
```

**Comment by quantumpacket** [comment]
> You need to combine your two functions, like so for example:

I had thought of doing that, but was hoping I would not have to create a wrapper function as it's just another function to unit test, but not the end of the world I guess.

Why exactly does the `loguru.logger.patch()` method above not work? From the docuementation it's said it can be called multiple times, and release 0.7 added support where it would also not override the previous patch.

**Comment by Delgan** [comment]
Because `logger.patch()` returns a new `logger`, it is intended for local patching.

**Comment by quantumpacket** [comment]
Ah ok, that makes sense why it wouldn't work. Thank you again for the help and quick responses, much appreciated!

**Comment by Delgan** [comment]
No problem. :+1:
