### ISSUE TITLE
Incorrect Logging File Name in Loguru when Using Custom Logger Class

### ISSUE THREAD

**Issue by miguelsmuller** [Delgan/loguru#952]
### Description:
I am currently using the Loguru logging library in my project, and I have encapsulated it within a custom logger class. However, I have encountered an issue where the log file name does not reflect the correct source file when logging from different modules. Instead, it always shows the file from the custom logger class.

### Steps to Reproduce:

1. Create a custom logger class encapsulating Loguru. (_Snippet - logger.py_)
2. Use the custom logger in different modules. (_Snippet - graph_connection.py_)
3. Log messages from those modules. 

### Expected Behavior:
The log file name should reflect the source file where the log message is generated. (_Snippet Log Message Expected_)

### Actual Behavior:
The log file name always reflects the custom logger class file. (_Snippet Log Message Wrong_)

### Additional Information:
This issue impacts the accuracy of log tracking in multi-module projects. It would be helpful to have a solution or workaround to ensure that the correct source file is reflected in the log file name.

### Snippet - logger.py
```
import sys
from loguru import logger as loguru_logger
from settings import settings

class Logger:
    def __init__(self, origin=None) -> None:
        self.logger = loguru_logger

        self._env = settings.options["app"]["env"]
        self._origin = origin
        self.logger.remove()
        self.logger.add(
            sys.stdout,
            level=settings.options["app"][self._env]["log_level"],
            enqueue=True,
        )

    def debug(self, mensagem):
        self.logger.debug(mensagem)

    def info(self, mensagem):
        self.logger.info(mensagem)

    def warning(self, mensagem):
        self.logger.warning(mensagem)

    def erro(self, mensagem):
        self.logger.error(mensagem)

    def critical(self, mensagem):
        self.logger.critical(mensagem)

```

### Snippet - graph_connection.py
```
import sys
from settings import settings
from logger import Logger

class GraphConnection:
   def __init__(self):
        try:
            self.logger = Logger()
            self._env = settings.options["app"]["env"]
            self._api_url = settings.options["brainiaks"][self._env]["url"]
        except Exception as err:
            self.logger.erro(
                f"Class `{self.__class__.__name__}` with erro in startup - Erro: {err}",
            )
            sys.exit(0)

    def get_classes_from_graph(self, graph_name):
        pass

    def get_properties_from_class(self, graph_name, klass_name):
        pass
```

### Snippet Log Message Wrong
`2023-08-25 14:33:05.500 | ERROR | logger:erro:35 - Class 'GraphConnection' with erro in startup - Erro: XPTO`

### Snippet Log Message Expected
`2023-08-25 14:33:05.500 | ERROR | graph_connection:__init__:11 - Class 'GraphConnection' with erro in startup - Erro: XPTO`

**Comment by AlTosterino** [comment]
Hey,

I think you should play around with `depth` argument in `opt` method (https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.opt). The reason you are getting `logger:erro:35` instead of `graph_connection:__init__:11` is because the real call to `loguru.error` is done inside your `class Logger`.

There is pretty good recipe for logging enter/exit of functions in loguru documentation (https://loguru.readthedocs.io/en/stable/resources/recipes.html#logging-entry-and-exit-of-functions-with-a-decorator), and it shows that using `depth=1` will correctly show from which file log message came.

Try this:
```python
class Logger:
    def __init__(self, origin=None) -> None:
        ...

    def debug(self, mensagem):
        self.logger.opt(depth=1).debug(mensagem)

    def info(self, mensagem):
        self.logger.opt(depth=1).info(mensagem)

    def warning(self, mensagem):
        self.logger.opt(depth=1).warning(mensagem)

    def erro(self, mensagem):
        self.logger.opt(depth=1).error(mensagem)

    def critical(self, mensagem):
        self.logger.opt(depth=1).critical(mensagem)
```

**Comment by miguelsmuller** [comment]
Thank you, @AlTosterino!

I really appreciate your quick response and helpful suggestion. It worked like a charm! You were absolutely right; adjusting the depth argument with self.logger.opt(depth=1) did the trick. My apologies for not diving deeper into the Loguru documentation before posting the issue. Your guidance was spot-on, and I'm grateful for your assistance.

Thanks again!

**Comment by Delgan** [comment]
Thanks @AlTosterino!
