### ISSUE TITLE
Log only debug

### ISSUE THREAD

**Issue by RohanRadia** [Delgan/loguru#96]
When using logger.debug it logs info and debug level logs to sink. Need it to just log debug level to the debug sink I don't want any logger.info outputs in there.

**Comment by Delgan** [comment]
@RohanRadia DId you find a solution?

I guess you can use something like `filter=lamdba record: record["level"].name == "DEBUG"` while adding a handler.

**Comment by jinfagang** [comment]
@Delgan  Would u provide any snippets to do this?

I have a huge project and sometimes I want debug some messages, but when the model is training, I want disable debug all, if comment out one by one, that's silly and waste time, any way to make it elgant in loguru?

**Comment by Delgan** [comment]
Hi @jinfagang. Maybe I misunderstood your question, but can't you just adjust the `level` of your sink? If your are debugging, use `logger.add(..., level="DEBUG")`. Once your program is ready to work, replace it with `logger.add(..., level="INFO")` to avoid being spammed with logs.
