### ISSUE TITLE
Issues with not being able to disable logger

### ISSUE THREAD

**Issue by hanzch** [Delgan/loguru#967]
filename:tmode.py

```python
from loguru import logger

logger.info("Allowed message by default")

logger.disable("tmode")
logger.info("While publishing a library, don't forget to disable logging")`
```

Return:

> 2023-09-02 15:27:08.452 | INFO     | __main__:<module>:7 - Allowed message by default
2023-09-02 15:27:08.452 | INFO     | __main__:<module>:10 - While publishing a library, don't forget to disable logging

python == 3.10.6
loguru == 0.7.0

What went wrong to disable it?

**Comment by Delgan** [comment]
In this example, your script is not executed as an external library, but as the main program.

The `logger.disable()` method is based on the value of `__name__`, which is `"__main__"` in your case. Therefore, logs are not filtered out.

**Comment by hanzch** [comment]
``

> In this example, your script is not executed as an external library, but as the main program.
> 
> The `logger.disable()` method is based on the value of `__name__`, which is `"__main__"` in your case. Therefore, logs are not filtered out.
> 
> If someone were to `import` your `tmode` mdule, then it would work.

Thank you very much for your help！
