### ISSUE TITLE
RuntimeError: context has already been set. When I use both Sanic and loguru

### ISSUE THREAD

**Issue by ChrisYP** [Delgan/loguru#974]
```python
from sanic import Sanic, text
from loguru import logger

app = Sanic(__name__)


@app.get('/')
async def run_shell(request):
    return text('Hello world!')


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=6666, debug=True, access_log=True, workers=2)
```
python version:3.8
Name: sanic
Version: 23.6.0
Name: loguru
Version: 0.7.1

The above code thorws an error:
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

**Comment by Delgan** [comment]
Thanks for the report and sorry for the inconvenience.

For `multiprocessing` purposes, Loguru v0.7.1 added a new `context` argument and uses [`multiprocessing.get_context()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context) by default. This is supposed to have the same effect as using `multiprocessing` directly, but makes it easier to switch from one context to another (eg. from `"fork"` to `"spawn"` on Linux).
Unfortunately, I didn't notice that calling `multiprocessing.get_context()` had the side effect of also **setting** the default context globally... And once a context is set, it can't be changed, hence the error you're getting.

I'll implement a fix as soon as possible. In the meantime, the only workaround I can think of is to disable the default handler of Loguru through `os.environ["LOGURU_AUTOINI"]` and re-add it with a context explicitly:

```python
import os
import sys

os.environ["LOGURU_AUTOINIT"] = "0"

from sanic import Sanic, text
from loguru import logger

logger.add(sys.stderr, context="spawn")  # Assuming Sanic tries to set the start method to "spawn".

app = Sanic(__name__)


@app.get("/")
async def run_shell(request):
    return text("Hello world!")


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=6666, debug=True, access_log=True, workers=2)
```
