### ISSUE TITLE
Better integration with standard logging library

### ISSUE THREAD

**Issue by trozen** [Delgan/loguru#975]
I have an application and bunch of libraries that I would like to migrate to loguru from standard python logging library. The script is already using loguru, but not the libraries.
There is a snippet in the docs how to do it using InterceptHandler. However, I feel there should be an easier way to achieve this, since it is a common case for larger projects. Hopefully this should be done by a single function call.
Copy-paste from the docs is not most convenient, but what's worse, if something changes in loguru (or the example) I need to remember to update that too.

**Comment by Delgan** [comment]
I agree. I plan to add a `logger.bridge(intercept=True, propagate=True)` method to replace the `InterceptHandler` and `PropagateHandler` from the documentation.

**Comment by Delgan** [comment]
Closing in favor or #633. :+1:
