### ISSUE TITLE
Passing bound logger's `extra` to `contextualize()`

### ISSUE THREAD

**Issue by HYBRID-BEING** [Delgan/loguru#986]
Maybe it's an XY problem, but it looked to me like `contextualize()` was a perfect solution to my little conundrum:
```python
def test():
    logger.info("This is logged to a main log.")

class RunnerA(BaseRunner):
    def run():
        self.logger.info("This is logged to a different log based on `extra` dict.")
        test()
        ...

class RunnerB(BaseRunner):
    def run():
        self.logger.info("This is logged to yet another log based on `extra` dict.")
        test()
        ...
```
When one of the Runner classes is instantiated, it's given a bound logger (`bind()`) that logs to a separate file. However outside functions called from inside the class obviously don't have access to bound logger and they log to the main log file.

Now, one obvious solution would be to just pass bound logger as an argument to extrernal function, but it feels somewhat clunky. However, `contextualize()` does in fact work, but the only way to get the `extra` dict from existing bound logger i found was this:
```python
with logger.contextualize(**self.logger._options[-1]):
    test()
```
Accessing an item in a private tuple is not exactly ideal, but it doesn't seem like there is any other way to access `extra` dict. Or is there?

**Comment by Delgan** [comment]
Why not instantiate your `Runner` classes with a `context` argument instead of passing a `logger` for example? Alternatively, maybe you could create them using the output of `logger.contextualize()` instead of `logger.bind()`.

**Comment by HYBRID-BEING** [comment]
Sorry for really late reply, but we actually did a step back and wrapped the call to `run()` methods in a `logger.contextualize()` context manager (also wrapped calls to callback methods returned by `run()` methods). That saves the hassle of instantiating `Runner` classes with bounded loggers and trying to access `extra` dict from them.
