### ISSUE TITLE
`Diagnose=False` somehow is omitted while using Sentry with `LoguruIntegration`

### ISSUE THREAD

**Issue by AlTosterino** [Delgan/loguru#987]
Hey!

(I don't 100% know if this issue should be posted here because I don't know where is the problem to be honest)

I'm experiencing strange issue while using loguru with Sentry. My logger is configured to serialize log messages and to not diagnose it `serialize=True, diagnose=False` but somehow `log.exception` is sending a whole traceback to Sentry with diagnose information.

Console log from loguru looks like this:
```
{"text": "Error processing request", "record": {"elapsed": {"repr": "0:00:57.233562", "seconds": 57.233562}, "exception": {"type": "NoStageFound", "value": "Cannot find stage with id: '6ed3247a-9ac6-4866-8a89-e39b2bb5cfd6'", "traceback": true}, "extra": {"request_method": "GET", "request_path": "/api/internal/...", "request_id": "3060498c-155a-4d37-b1b8-b74892e81293"}, "file": {"name": "api.py", "path": "/Users/Tosuto/PycharmProjects/..."}, "function": "on_exception", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 16, "message": "Error processing request", "module": "api", "name": "foo.bar", "process": {"id": 14602, "name": "SpawnProcess-24"}, "thread": {"id": 8518573568, "name": "MainThread"}, "time": {"repr": "2023-09-15 12:39:34.734965+00:00", "timestamp": 1694781574.734965}}}
```

But breadcrumb message or event message in Sentry looks like this:

For event message:

```
Message
2023-09-15 12:36:34.840 | ERROR | foo.bar:16 - Error processing request Traceback (most recent call last): File "<string>", line 1, in <module> File "/Users/Tosuto/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main exitcode = _main(fd, parent_sentinel) | | -> 4 | -> 7 -> <function _main at 0x10294e8e0> File "/Users/Tosuto/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/spawn.py", line 133, in _main return self._bootstrap(parent_sentinel) | | -> 4 | -> <function BaseProcess._bootstrap at 0x1028339c0> -> <SpawnProcess name='SpawnProcess-23' parent=14133 started> File "/Users/Tosuto/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap self.run() | -> <function BaseProcess.run at 0x102832f20> -> <SpawnProcess name='SpawnProcess-23' parent=14133 start...
```

For breadcrumb message:

```
2023-09-15 12:36:34.840 | ERROR    | foo.bar:16 - Error processing request
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Users/Tosuto/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               |     |   -> 4
               |     -> 7
               -> <function _main at 0x10294e8e0>
  File "/Users/Tosuto/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/spawn.py", line 133, in _main
    return self._bootstrap(parent_sentinel)
           |    |          -> 4
           |    -> <function BaseProcess._bootstrap at 0x1028339c0>
           -> <SpawnProcess name='SpawnProcess-23' parent=14133 started>
  File "/Users/Tosuto/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    |    -> <function BaseProcess.run at 0x102832f20>
    -> <SpawnProcess name='SpawnProcess-23' parent=14133 start...
```
    
I checked `BreadcrumbHandler` from `Sentry` and in this method:

```python
    def _breadcrumb_from_record(self, record):
        # type: (LogRecord) -> Dict[str, Any]
        return {
            "type": "log",
            "level": self._logging_to_event_level(record),
            "category": record.name,
            "message": record.message,
            "timestamp": datetime.datetime.utcfromtimestamp(record.created),
            "data": self._extra_from_record(record),
        }
```
`record.message` is a whole message and exception info as string.

Any ideas how to remove traceback from loguru message while doing `logger.exception` or at least remove diagnostics? I tried to put `event_format` and `breadcrumb_format` to `{message}` but it didn't help.

**Comment by Delgan** [comment]
Hi.

Sentry has built-in support for Loguru, are you using it?

According to the implementation [here](https://github.com/getsentry/sentry-python/blob/a7b4144d7450424b313ba58e1705c0a2e7f78fb6/sentry_sdk/integrations/loguru.py#L65-L79), `logger.add()` is called with the default value for `diagnose`, which may explain the output you're facing.

**Comment by AlTosterino** [comment]
Hey,

Yes I'm using `LoguruIntegration` for Sentry. Should I somehow patch LoguruBreadcrumbHandler and LoguruEventHandler and set them `diagnose=False`? Is that even possible?

**Comment by Delgan** [comment]
Not being a Sentry user, I can't give you a definitive answer. 

I guess you should rather re-implement `LoguruIntegration` and add `diagnose=False` to the `logger.add()` calls. I don't know how Sentry integration works. Maybe you just need to import `LoguruBreadcrumbHandler` and add it manually to Loguru's `logger`.

**Comment by AlTosterino** [comment]
I fixed it by passing callable formatter to `LoguruIntegration` like this:

```python
def sentry_log_format(record):
    return record["message"]
    
LoguruIntegration(event_format=sentry_log_format, breadcrumb_format=sentry_log_format),
```
It's only sending log message and `extra` dict, without traceback.

**Comment by Delgan** [comment]
Note that with such workaround you won't get any traceback at all.

**Comment by AlTosterino** [comment]
Yes, that's exactly what I want as traceback is correctly showing in Sentry, I need only log messages with extra dict.

Sorry for creating an issue without any real issue at all.

Thanks for your help!

**Comment by Delgan** [comment]
No problem. ;)
